### ISSUE TITLE
Block placing Issue with ViaBackwards and 1.13.2

### ISSUE THREAD

**Issue by ItsHoney** [ViaVersion/ViaBackwards#110]
### What is the output url of /viaversion dump?
> https://dump.viaversion.com/7af68b18ba5882d4fc05162f5400b95d72e1d048d931dd9183fbc2c46a0229b0

### How/when does this error happen? login?:
> With base server version of 1.13.2, clients who are connected from 1.12.2 or below are not able to place items obtained from the creative menu. Those items simply vanish as soon as taken from the creative menu. /give however can be used. This problem is only for people who are in creative mode ofcourse.

### Is there an error in the console? Use pastebin.com. Is there a kick message?:
> No kick, and no error, there were however several mapping issues that happen on server start.
https://pastebin.com/kzP96HJS

**Comment by Gerrygames** [comment]
This is fixed in the 1.14.c pull request.

**Comment by MylesIsCool** [comment]
^^
