### ISSUE TITLE
Startup error

### ISSUE THREAD

**Issue by Rukes** [ViaVersion/ViaBackwards#113]
### What is the output url of /viaversion dump?
> https://dump.viaversion.com/3dcac0d3796d383af79ef8083c1fecd77b653d75eee3bd6dca2472ea56b617c9

### How/when does this error happen? login?:
> When plugin is loading

### Is there an error in the console? Use pastebin.com. Is there a kick message?:
> https://pastebin.com/45RttBkp

**Comment by MylesIsCool** [comment]
Development builds are development builds.
