### ISSUE TITLE
Bungee Messaging Channel is broken for players using older versions

### ISSUE THREAD

**Issue by ColaIan** [ViaVersion/ViaBackwards#117]
### What is the output url of /viaversion dump?
> https://dump.viaversion.com/5c28c74d3eda79f5c106705bf02daec38f22648b052ab781ab8fd6ac597cbe92

### How/when does this error happen? login?:
> On bungeecord related plugins (bungee tablist [doesn't parse placeholders] / cross server portals [doesn't transfer players])
Which means that it is an issue with bungee plugin messaging channel

### Is there an error in the console? Use pastebin.com. Is there a kick message?:
> no, it doesn't even parse anything in the bungee plugin messaging channel

**Comment by ForceUpdate1** [comment]
Is no message displayed like "Could not find new channel for xyz" ?

**Comment by ColaIan** [comment]
I run viaversion, backwards and rewind on individual servers, and it doesnt even send the plugin messaging packet from the server to bungee, so it wasnt even trying to find the channel. I am certain that the problem is via plugins as it has no problem when I join with 1.14.3

**Comment by ForceUpdate1** [comment]
Do you have discord, then you can adden me then we can test something.
Foorcee#2831

**Comment by ForceUpdate1** [comment]
https://github.com/ViaVersion/ViaBackwards/blob/cba2566c217241e5ef8c91b8a304845075b39bf2/core/src/main/java/nl/matsv/viabackwards/protocol/protocol1_12_2to1_13/packets/PlayerPacket1_13.java#L437
