### ISSUE TITLE
Scoreboard Shrinked, Skull Offset

### ISSUE THREAD

**Issue by ColaIan** [ViaVersion/ViaBackwards#120]
### What is the output url of /viaversion dump?
> https://dump.viaversion.com/546cbf9f2fcbd60e845a70fc75ad539d306394a3b9b5a1938998318b1cca097b

### How/when does this error happen? login?:
> Gameplay

### Is there an error in the console? Use pastebin.com. Is there a kick message?:
> No, just a visual glitch

Older versions: (1.12.2 or older)
https://media.discordapp.net/attachments/601658698028548099/601677222700515348/unknown.png?width=702&height=421

Expected outcome: (1.13 - 1.14.3)
https://media.discordapp.net/attachments/601658698028548099/601677520219406347/unknown.png?width=704&height=421

**Comment by Maximvdw** [comment]
Download the latest legitimate version of FeatherBoard (https://www.spigotmc.org/resources/featherboard.2691/) will solve this issue

**Comment by MylesIsCool** [comment]
Ty Maxim

**Comment by ColaIan** [comment]
> Ty Maxim

that didn't solve the skull visual offset issue though

**Comment by MylesIsCool** [comment]
> > Ty Maxim
> 
> that didn't solve the skull visual offset issue though

I'd suggest making a new issue to keep it seperate

**Comment by ColaIan** [comment]
sure
