### ISSUE TITLE
Skull Offset Issue

### ISSUE THREAD

**Issue by ColaIan** [ViaVersion/ViaBackwards#121]
### What is the output url of /viaversion dump?
> https://dump.viaversion.com/546cbf9f2fcbd60e845a70fc75ad539d306394a3b9b5a1938998318b1cca097b

### How/when does this error happen? login?:
> Gameplay

### Is there an error in the console? Use pastebin.com. Is there a kick message?:
> No, just a visual glitch

Older versions: (1.12.2 or older)
https://media.discordapp.net/attachments/601658698028548099/601677222700515348/unknown.png?width=702&height=421

Expected outcome: (1.13 - 1.14.3)
https://media.discordapp.net/attachments/601658698028548099/601677520219406347/unknown.png?width=704&height=421

**Comment by KennyTV** [comment]
Fixed :)

**Comment by TNG-China** [comment]
Sorry, I have same issue but it's not fixed in 3.0.0 version,
How can I download the fixed version?

**Comment by KennyTV** [comment]
Download the "abstraction" build of VB (and VV) from https://ci.viaversion.com/view/ViaBackwards/job/ViaBackwards-Abstraction/
