### ISSUE TITLE
Titles don't show the correct message

### ISSUE THREAD

**Issue by TheCompieter** [ViaVersion/ViaBackwards#135]
### What is the output url of /viaversion dump?
> https://dump.viaversion.com/1464495b2257969bf8138234ccb4d6cbda0dfcd4fa54e826b8619679d9e7a7be

### How/when does this error happen? login?:
> When right clicking on a bed when on a older version and when its day you don't get the
correct title the tile shows: block.minecraft.bed.no_sleep.
Edit: This also happens with commands and other block that display's an title.

### Is there an error in the console? Use pastebin.com. Is there a kick message?:
> No

**Comment by KennyTV** [comment]
Fixed :)
