### ISSUE TITLE
Channel must contain : separator (attempted to use schematica)

### ISSUE THREAD

**Issue by Heliosard** [ViaVersion/ViaBackwards#138]
### What is the output url of /viaversion dump?
> https://dump.viaversion.com/daef6b650bb1bfb8fb4aafda0114bb7385f810b43db0a7f11bd302e0d4598308

### How/when does this error happen? login?:
> 1.12.2

### Is there an error in the console? Use pastebin.com. Is there a kick message?:
> https://gist.github.com/Heliosard/462e53c3a3ca04dabf64a14d145068c9

**Comment by LoXR** [comment]
This needs to be fixed ASAP!! Cant even use the latest dev releases due to this still popping up: https://pastebin.com/Lb8PwJCR
