### ISSUE TITLE
Elytra doesnt work less than 1.14

### ISSUE THREAD

**Issue by JHarris12345** [ViaVersion/ViaBackwards#141]
### What is the output url of /viaversion dump?
> https://dump.viaversion.com/70d48401434b4cbd5280d9bad38cf7baa87ac84e8d163dfff27dc049b89c926b

### How/when does this error happen? login?:
> Simply join in a 1.13.2 or lower client and try and fly with elytra

### Is there an error in the console? Use pastebin.com. Is there a kick message?:
> no

**Comment by KennyTV** [comment]
If you can't use the elytra with a 1.13.2 client on a 1.13.2 server, then it's an issue of one of your plugins

**Comment by JHarris12345** [comment]
Ill test

**Comment by KennyTV** [comment]
See above
