### ISSUE TITLE
Recipe book

### ISSUE THREAD

**Issue by TheCompieter** [ViaVersion/ViaBackwards#149]
### What is the output url of /viaversion dump?
> https://dump.viaversion.com/26c39363b2b5b6a0ae70e25753c5da1fb9fa75e4f0459b4f955f1c87bee8fd61

### How/when does this error happen? login?:
> When using an custom datapack that alters the recipes book they don't get  converted to older version's they will just show the default recipe's.

### Is there an error in the console? Use pastebin.com. Is there a kick message?:
> No

**Comment by KennyTV** [comment]
Put on the list in https://github.com/ViaVersion/ViaBackwards/issues/179, tho atm it doesn't seem feasible, since handling changed a *lot* and was even hardcoded at some point in the client - we'll see if some magic can help with that

**Comment by TheCompieter** [comment]
Thanks Kenny for your time i really appreciate it, yeh i thought it wasn't gonna work anyway cause if it would work it would be alot of work too implement right.
