### ISSUE TITLE
Sugercane

### ISSUE THREAD

**Issue by TheCompieter** [ViaVersion/ViaBackwards#150]
### What is the output url of /viaversion dump?
> https://dump.viaversion.com/59683e47fa6055f38eacf8f20488275f43b4fc4b6945c0efa2f92c09e9d3cedb

### How/when does this error happen? login?:
> When trying to walk through sugercane it glitches and wont let me trough.

### Is there an error in the console? Use pastebin.com. Is there a kick message?:
> No.

**Comment by Gerrygames** [comment]
Could it be the case that you are trying to walk through bamboo instead of sugarcane?

**Comment by TheCompieter** [comment]
It was bamboo sorry my fault
