### ISSUE TITLE
Falling sand/gravel

### ISSUE THREAD

**Issue by TheCompieter** [ViaVersion/ViaBackwards#151]
### What is the output url of /viaversion dump?
> https://dump.viaversion.com/59683e47fa6055f38eacf8f20488275f43b4fc4b6945c0efa2f92c09e9d3cedb

### How/when does this error happen? login?:
> When sand/gravel is falling it shows an falling podzol that's glitches.

### Is there an error in the console? Use pastebin.com. Is there a kick message?:
> No.

**Comment by ForceUpdate1** [comment]
Can you test it again with the latest version?

https://ci.viaversion.com/view/ViaBackwards/job/ViaBackwards-DEV/188/

It should be fixed

**Comment by TheCompieter** [comment]
Fixed
