### ISSUE TITLE
Walls & Fences

### ISSUE THREAD

**Issue by TheCompieter** [ViaVersion/ViaBackwards#152]
### What is the output url of /viaversion dump?
> https://dump.viaversion.com/59683e47fa6055f38eacf8f20488275f43b4fc4b6945c0efa2f92c09e9d3cedb

### How/when does this error happen? login?:
> When trying to walk onto an wall/fence from an shulkerbox/trapdoor/door it glitches.

### Is there an error in the console? Use pastebin.com. Is there a kick message?:
> No.

**Comment by KennyTV** [comment]
Fences now connect to blocks like opened trapdoors, this is not fixable as it is fully determined by the older client

**Comment by TheCompieter** [comment]
okay thanks
