### ISSUE TITLE
No versions below 1.14 can join

### ISSUE THREAD

**Issue by InfinityMage** [ViaVersion/ViaBackwards#154]
### What is the output url of /viaversion dump?
> https://dump.viaversion.com/32066464423e1845edef395a80ae85071079ae675b779e4244d3ed918e5aab07

### How/when does this error happen? login?:
> Every time you login with any version thats not 1.14.4 you get kicked

### Is there an error in the console? Use pastebin.com. Is there a kick message?:
> `Internal Exception: io.netty.handler.codec.EncoderException: java.lang.RuntimeException: An internal error occured.` is the only thing

**Comment by MylesIsCool** [comment]
Enable debug=true in server.properties and replicate to get the full error

**Comment by KennyTV** [comment]
Feel free to add new information when you have them, closing this until then
