### ISSUE TITLE
Question: Glowing effect

### ISSUE THREAD

**Issue by Likqez** [ViaVersion/ViaBackwards#171]
How does ViaBackwards handle the glowing effect which is available from 1.12+? What are Players below that versions? Nothing or a kind of replacement?

Thanks in Advance
Likqez

**Comment by KennyTV** [comment]
Glowing has been added to MC since 1.9, so all players will still be able to see them with VB

**Comment by Likqez** [comment]
I mean what do players below 1.9 see? If ViaRewind and Backwards is installed?

**Comment by KennyTV** [comment]
That's part of ViaRewind, tho iirc it's not displayed at all
