### ISSUE TITLE
9 by 3 chest gets renamed to "Barrel"

### ISSUE THREAD

**Issue by camdenorrb** [ViaVersion/ViaBackwards#175]
### What is the output url of /viaversion dump?
> 
https://dump.viaversion.com/ac31b93303d8be441fd907ff3cee025a7eb322ac045dacaf437be2525a93d2be

### How/when does this error happen? login?:
> 
Happens when you open a 9 by 3 chest

### Is there an error in the console? Use pastebin.com. Is there a kick message?:
> 
No

![image](https://user-images.githubusercontent.com/5360339/71443073-897cd700-26ce-11ea-92b5-98919dfa0bc8.png)
This appears to be the issue, I was gonna make a pull request but doing `mvn package` ended up with an error so I decided to just make an issue instead.

**Comment by KennyTV** [comment]
Thanks, I also addressed custom titles not being saved
