### ISSUE TITLE
Spam in console when online

### ISSUE THREAD

**Issue by TheCompieter** [ViaVersion/ViaBackwards#178]
### What is the output url of /viaversion dump?
>  https://dump.viaversion.com/691739a461e4fa40d7c2012975e3fc1ba4cfaacd53879c97cbb1c1a43a7385c2

### How/when does this error happen? login?:
> When i join.

### Is there an error in the console? Use pastebin.com. Is there a kick message?:
> no just an spamming warning  [ViaBackwards] Failed to get 1.12 item for 768

**Comment by KennyTV** [comment]
Did you have a debug stick in your inventory?

**Comment by TheCompieter** [comment]
yeh i think so is that the issue? i know a player was holding that in the world as an npc tho

**Comment by KennyTV** [comment]
Fixed in the latest abstraction build (tho using the stick won't send you the proper actionbar message, which is probably a "won't fix")

**Comment by TheCompieter** [comment]
Thanks Kenny i'll try it when i update my server.
