### ISSUE TITLE
io.netty.handler.codec.EncoderException: us.myles.ViaVersion.exception.InformativeException

### ISSUE THREAD

**Issue by OverBrave** [ViaVersion/ViaBackwards#180]
### What is the output url of /viaversion dump?
https://dump.viaversion.com/1440b2f6d621d1d4184c8a2e37a2402fc7b4004ad05868c98f2de543ab07762a

### Is there an error in the console? Use pastebin.com. Is there a kick message?:
https://hasteb.in/ozakubiy.kotlin
https://streamable.com/tq4ie
https://hasteb.in/kuyaseza.cs

![image](https://user-images.githubusercontent.com/47111280/72295078-e46b7380-3667-11ea-8c7b-e2a19cc5d5f9.png)

**Comment by OverBrave** [comment]
https://hasteb.in/noxuvizo.cs

**Comment by krusic22** [comment]
Issue resolved on Discord.
