### ISSUE TITLE
Metadata for entity id: xxxx in console (warn)

### ISSUE THREAD

**Issue by TheCompieter** [ViaVersion/ViaBackwards#181]
### What is the output url of /viaversion dump?
> https://dump.viaversion.com/48435e3068bd8456a4c43a2ba64d80e747c12c36b05ccbbad0e1c578c6eb2ae1

### How/when does this error happen? login?:
> i don't know i just see this in my console and maybe it needs an fix or something

### Is there an error in the console? Use pastebin.com. Is there a kick message?:
> https://pastebin.com/cMgsGTyE

**Comment by KennyTV** [comment]
Are you running Via on both Bungee and Spigot? If so, you shouldn't (and we'd need a dump from the platform ViaBackwards is on, because it's not listed on your proxy)

**Comment by TheCompieter** [comment]
yes it is on bungee & spigot idk why i left it in there. oof i just realised that it showed the proxy instead of the server itself sorry for that.. here's the dump from the right server https://dump.viaversion.com/6e88142b89d7dff1734e187638b53d3fc74d64d3b78b4076304750b8d27a8a7e

**Comment by KennyTV** [comment]
See if the warning still appears after removing VV from the proxy, and after that try removing some plugins (starting with TAB), to see if it might be related to that

**Comment by TheCompieter** [comment]
okay thanks

**Comment by KennyTV** [comment]
Any news on this?

**Comment by TheCompieter** [comment]
Yeah sorry i haven't see any new warnings so far thanks KennyTV
