### ISSUE TITLE
Items in Inventory get changed to random blocks

### ISSUE THREAD

**Issue by D3monw3st** [ViaVersion/ViaBackwards#182]
### What is the output url of /viaversion dump?
> https://dump.viaversion.com/56ff992d509c9068ddead2832d4451651f46a9e61543b20b4c4563049f460429

### How/when does this error happen? login?:
> Upon log in simply hovering over the item in your hand or having it in your inventory on an MC version that is <= 1.15. My jar is on 1.15.1. 

### Is there an error in the console? Use pastebin.com. Is there a kick message?:
> No error in console.

**Comment by D3monw3st** [comment]
Some errors were finally thrown: 
` [00:00:08] [Netty Epoll Server IO #1/WARN]: [ViaBackwards] Missing 1.14 item for 1.13.2 item 2271
> [00:00:08] [Netty Epoll Server IO #1/WARN]: [ViaBackwards] Missing 1.14 item for 1.13.2 item 2266
> [00:00:08] [Netty Epoll Server IO #1/WARN]: [ViaBackwards] Missing 1.14 item for 1.13.2 item 2271`

**Comment by KennyTV** [comment]
Are you running the latest/second build from yesterday?

**Comment by KennyTV** [comment]
Any news on this?

**Comment by Xernium** [comment]
Closed due to inactivity
