### ISSUE TITLE
Metadata spam

### ISSUE THREAD

**Issue by x1p** [ViaVersion/ViaBackwards#186]
### What is the output url of /viaversion dump?
> ttps://dump.viaversion.com/bcad7f05fed844d8d82e6d7d2d0dbbbc69a3c27903b4ef19cf11ca5f85e78546

### How/when does this error happen? login?:
> Probably a player joining with 1.14.4 playing on 1.15.2 server

### Is there an error in the console? Use pastebin.com. Is there a kick message?:
Continuous console spam of the following id's: 51, 72, 74, 79, 83, 88, 90
> https://pastebin.com/wEmE6gJ3

Viaversion 3.0.0 abstraction build 40
ViaBackwards 3.0.0 abstraction build 101

**Comment by Jo0001** [comment]
It looks like a plugin is sending invalid data. Set `suppress-metadata-errors` to true in viaversion config to hide the warnings.

**Comment by KennyTV** [comment]
Try removing plugins to see if it might be due to them, I suspect it could be tab or similar

**Comment by x1p** [comment]
I'm trying to replicate, but it's not that easy. No it's not tab.
I see some blocks are not visible too that should have been visible.
I'm going to revert to protocolsupport for now
