### ISSUE TITLE
Protocol Packet from 1.13 to 1.14

### ISSUE THREAD

**Issue by LoXR** [ViaVersion/ViaBackwards#188]
### What is the output url of /viaversion dump?
> https://dump.viaversion.com/c28ab03e3e6e66c9a92658976039e159385647efe6b0b9d655f9aa6b347e475f

### How/when does this error happen? login?:
> Havent seen it before, but possibly something that can be somewhat easy to sort.

### Is there an error in the console? Use pastebin.com. Is there a kick message?:
> https://paste.gg/p/anonymous/04fc91dbd5e54132b7f25ec37f1efeee

**Comment by KennyTV** [comment]
(Got another report of this, just dumping this here for reference https://paste.gg/p/anonymous/ab87ece9bd5c41ed92b92a8dbde80b77)
Unsure of how to reproduce or fix yet

**Comment by LoXR** [comment]
Another one: https://hastebin.com/huridodoyi.shell
Its when a player on 1.15.2 tried to join my 1.12.2 server.

**Comment by LoXR** [comment]
Unsure whats caused this one, but thought to add this since its for the lower versions: https://hastebin.com/asoponipaj.shell

**Comment by KennyTV** [comment]
Fixed that one, interesting that noone found it in 3 years 😛

**Comment by original-codematrix** [comment]
@KennyTV is this here still open? Or is it already fixed?

**Comment by LoXR** [comment]
I'll add this aswell: https://hastebin.com/cagixuhuce.shell

**Comment by KennyTV** [comment]
I added more debug info to that output with the latest build, so the next time the warning appears, it should help identify the problem a bit more.

**Comment by LoXR** [comment]
Id say this can be closed, havent seen any viabackwards errors anymore. Can re-open if I do find something.
