### ISSUE TITLE
Getting an Error On Joining

### ISSUE THREAD

**Issue by Skeec54** [ViaVersion/ViaBackwards#189]
### What is the output url of /viaversion dump?
> https://dump.viaversion.com/1aa7eb758cb2669d3f6669080b4383da03fcc24489dd5bf3ddb71daeaac44f05

### How/when does this error happen? login?:
> on joining the server

### Is there an error in the console? Use pastebin.com. Is there a kick message?:
> https://pastebin.com/A04rZdya

Server Version: 1.9
Client Version: 1.8.9 (with forge and mods (labymod and other things) )
Error i get on Joining: http://prntscr.com/rk60t1

**Comment by KennyTV** [comment]
You are not using ViaBackwards, and that error is likely due to something else

**Comment by Skeec54** [comment]
ok i got somehow on the wrong github page, sorry
