### ISSUE TITLE
The Server kicks when player teleport.

### ISSUE THREAD

**Issue by Obliviated** [ViaVersion/ViaBackwards#190]
**ViaVersion and ProtocolLib versions:**
![image](https://user-images.githubusercontent.com/36128276/77532561-286bc780-6ea6-11ea-8300-0c9811feba2c.png)

**Server Version**
This server is running CraftBukkit version git-Spigot-79a30d7-acbc348 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)

This is a final build for 1.12.2. Please see https://www.spigotmc.org/ for details about upgrading.

**Problem:**
When i teleport anywhere at another world.

**Informations**
Kicked message: Disconnected (yes only that.)
Error from Console`Mr_Obliviate lost connection: Internal Exception: io.netty.handler.codec.EncoderException: java.util.NoSuchElementException: us.myles.ViaVersion.protocols.protocol1_11to1_10.Protocol1_11To1_10`

Also, that happening while i'm on 1.8 not 1.12.2(the server's current version)

**Comment by KennyTV** [comment]
Your ViaBackwards build is outdated, use these 3 in combination
https://ci.viaversion.com/job/ViaVersion-Abstraction/
https://ci.viaversion.com/view/ViaBackwards/job/ViaBackwards-Abstraction/
https://ci.viaversion.com/view/ViaRewind/job/ViaRewind-DEV/
