### ISSUE TITLE
Error console:

### ISSUE THREAD

**Issue by colo13verdadeo** [ViaVersion/ViaBackwards#191]
### What is the output url of /viaversion dump?
> https://pastebin.com/cKJNHHim

28.03 23:17:10 [Server] WARN [ViaBackwards]: Metadata for entity id: 2382 not sent because the entity doesn't exist. MetaStorage{metaDataList=[us.myles.ViaVersion.api.minecraft.metadata.Metadata@16015621, us.myles.ViaVersion.api.minecraft.metadata.Metadata@1ffa6377, us.myles.ViaVersion.api.minecraft.metadata.Metadata@bcec9e2, us.myles.ViaVersion.api.minecraft.metadata.Metadata@d306f16, us.myles.ViaVersion.api.minecraft.metadata.Metadata@119c90cf, us.myles.ViaVersion.api.minecraft.metadata.Metadata@5d31b850, us.myles.ViaVersion.api.minecraft.metadata.Metadata@204dfbcd, us.myles.ViaVersion.api.minecraft.metadata.Metadata@2e0b680d, us.myles.ViaVersion.api.minecraft.metadata.Metadata@5b649feb, us.myles.ViaVersion.api.minecraft.metadata.Metadata@bc75fef, us.myles.ViaVersion.api.minecraft.metadata.Metadata@441b5ec9, us.myles.ViaVersion.api.minecraft.metadata.Metadata@31251d47, us.myles.ViaVersion.api.minecraft.metadata.Metadata@4ec1474f, us.myles.ViaVersion.api.minecraft.metadata.Metadata@7fc8515f, us.myles.ViaVersion.api.minecraft.metadata.Metadata@61bba579, us.myles.ViaVersion.api.minecraft.metadata.Metadata@786d532c, us.myles.ViaVersion.api.minecraft.metadata.Metadata@3cd28851]}
28.03 23:17:10 [Server] WARN [ViaBackwards]: Metadata for entity id: 2382 not sent because the entity doesn't exist. MetaStorage{metaDataList=[us.myles.ViaVersion.api.minecraft.metadata.Metadata@44da2471]}
On bungee

**Comment by KennyTV** [comment]
That's usually due to Hologram/NPC plugins or similar sending metadata for entities outside of the player's tracking range. You can disable the warnings with the 2 suppress-... options in the ViaVersion config
