### ISSUE TITLE
Enchantment Table Visual Glitch

### ISSUE THREAD

**Issue by SaltyPotata** [ViaVersion/ViaBackwards#192]
### What is the output url of /viaversion dump?
>https://dump.viaversion.com/8fd089f9fe028b36f6dba902826b3ccb413a663081c9eb3341965c801136889a

### How/when does this error happen? login?:
> Under 1.13.2 minecraft version

### Is there an error in the console? Use pastebin.com. Is there a kick message?:
> No

I am using viaback viarewind viaversion combo and when I login under 1.13.2 on my 1.13.2 paperspigot server the enchantment table is bugging. It shows fire aspect instead of unbreaking for some reason. No, it is not a client side problem. No mods installed, no datapack, no resourcepack. What do do now?
![unknown](https://user-images.githubusercontent.com/62210667/78051311-c87d9100-737d-11ea-9601-f2fc8a1e6eb6.png)

**Comment by Xernium** [comment]
@KennyTV at least reference the fix 👀 
Fixed in https://github.com/ViaVersion/ViaBackwards/commit/910f5d98dc0d7dbbcb2ddee01f6ae53b03c34eae
