### ISSUE TITLE
Bug? (20w16a)

### ISSUE THREAD

**Issue by andrew121410** [ViaVersion/ViaBackwards#198]
### What is the output url of /viaversion dump?
> https://dump.viaversion.com/d07008e16668682d455a23dc7a651e63d7f2ca8bc68f723d965a291b2f19add6

### How/when does this error happen? login?:
> Login

### Is there an error in the console? Use pastebin.com. Is there a kick message?:
> https://srcb.in/52b19f78e6

**Comment by KennyTV** [comment]
Most likely a plugin sending packet entities without properly regarding the tracking distance. But it's harmless, and can be suppressed by setting `suppress-metadata-errors: true` in the ViaVersion config

**Comment by andrew121410** [comment]
Well also https://sourceb.in/47c966930e
