### ISSUE TITLE
Enderchests

### ISSUE THREAD

**Issue by JRazek** [ViaVersion/ViaBackwards#200]
https://dump.viaversion.com/24cd9a8387e07a81a3bd89f3f7fcb24412ab69397ec0e29285cc9e9656bbe44d

How can i change the replacement items? It changes chests to enderchests.

**Comment by Xernium** [comment]
Invalid. You're using ProtocolSupport for old version support. You don't need to use Via to get your current functionality as it will do nothing being run on 1.15.2. If you want to change ProtocolSupports behaviour then there are plugins for that. I suggest you check out https://protocol.support

**Comment by MylesIsCool** [comment]
You're using ProtocolSupport, not ViaBackwards

https://www.spigotmc.org/resources/protocolsupportlegacychest.59314/
