### ISSUE TITLE
Error with ViaBackwards on 1.12.2

### ISSUE THREAD

**Issue by MateoNikolic** [ViaVersion/ViaBackwards#201]
### What is the output url of /viaversion dump?
> https://dump.viaversion.com/84a9ab4a139c4d35231615f394db6c0109d7ac460bd20410db1227e06c03d57f

### How/when does this error happen? login?:
> Whenever I use some GUI on some plugin. In some cases I can even take the item out of GUI that normally shouldn't happen

### Is there an error in the console? Use pastebin.com. Is there a kick message?:
>  [ViaBackwards] Metadata for entity id: 138 not sent because the entity doesn't exist. MetaStorage{metaDataList=[us.myles.ViaVersion.api.minecraft.metadata.Metadata@a1d69f1]}

**Comment by Xernium** [comment]
Those warnings are sent because a plugin isn’t using the proper way(s) to send data to the player. Most of the time this is harmless and the warning can be muted by enabling suppress warnings in the config.
