### ISSUE TITLE
Parrots cause stacktraces

### ISSUE THREAD

**Issue by Nubebuster** [ViaVersion/ViaBackwards#203]
### What is the output url of /viaversion dump?
> https://dump.viaversion.com/c84fc41425d7c2a64f7e155ea3a37f3d27430d5dc7b57c4580c1479632e9cc3a

### How/when does this error happen? login?:
> Players in 1.11 see parrots, then this error appears

### Is there an error in the console? Use pastebin.com. Is there a kick message?:
> https://pastebin.com/b1cnwuwD

**Comment by KennyTV** [comment]
Your VB is outdated, download the -abstraction builds from the ci.

**Comment by Nubebuster** [comment]
Where can I get the lastest ViaRewind? I am trying to update to the abstraction builds but ViaRewind seems to be incompatible

**Comment by BuzzTheGamer23** [comment]
[ViaVersion-Abstraction](https://ci.viaversion.com/job/ViaVersion-Abstraction/lastSuccessfulBuild/artifact/jar/target/ViaVersion-3.0.0-SNAPSHOT.jar)
[ViaBackwards-Abstraction](https://ci.viaversion.com/view/ViaBackwards/job/ViaBackwards-Abstraction/lastSuccessfulBuild/artifact/all/target/ViaBackwards-3.0.0-SNAPSHOT.jar) 
[ViaRewind-DEV](https://ci.viaversion.com/view/ViaRewind/job/ViaRewind-DEV/lastSuccessfulBuild/artifact/all/target/ViaRewind-1.5.0-SNAPSHOT.jar)
