### ISSUE TITLE
Custom Jumpads and ViaBackwards 1.15 > 1.12 intercompatibility issue

### ISSUE THREAD

**Issue by ThatMishakov** [ViaVersion/ViaBackwards#205]
### What is the output url of /viaversion dump?
> https://dump.viaversion.com/3b41dfe599f8acf48295bd4533991f0b443e479e96e153012a0a5e788e0deccf

### How/when does this error happen? login?:
> 
Players get kicked whenever they stand on a Jump Pad added by a **[Custom Jumpads](https://www.spigotmc.org/resources/custom-jumppads-1-8-1-15.44876/)** plugin. The issue only happens on 1.12 and does not happen when playing on native 1.15, nor on 1.13 and 1.14. 

### Is there an error in the console? Use pastebin.com. Is there a kick message?:
> 
https://pastebin.com/u2Wb3TEs
Screenshot of the kick message:
https://snipboard.io/Kxazsv.jpg

**Comment by Xernium** [comment]
Did you set the sound correctly? Try disabling the sound as I think that’s causing it

**Comment by KennyTV** [comment]
Update
