### ISSUE TITLE
outdated client! Please use 1.15.2

### ISSUE THREAD

**Issue by Imperialroma10** [ViaVersion/ViaBackwards#206]
### What is the output url of /viaversion dump?
>https://dump.viaversion.com/36aa8ec1054042cf6e4f8e30b1f35ccb08f488fe7deefbfabd51b77abe50f206

### How/when does this error happen? login?:
> When switching to another server

### Is there an error in the console? Use pastebin.com. Is there a kick message?:
> There is no error in the console only in the client, outdated client! Please use 1.15.2
![image](https://user-images.githubusercontent.com/57969768/83556250-3da14a00-a518-11ea-9b87-2938ee61b193.png)

**Comment by KennyTV** [comment]
Your ViaBackwards is outdated, download the abstraction builds from the ci.
