### ISSUE TITLE
Json error on 1.13 -> 1.12 when opening plugin inventory

### ISSUE THREAD

**Issue by lenis0012** [ViaVersion/ViaBackwards#207]
### What is the output url of /viaversion dump?
https://dump.viaversion.com/cfa47fb2f53d9d7ed50bbae2e321038a4b01a3644bbe2338386523708e840a0e

### How/when does this error happen? login?:
opening a plugin inventory (for instance, /hdb from HeadDatabase)

### Is there an error in the console? Use pastebin.com. Is there a kick message?:
https://pastebin.com/rREDExG6
Note: I am using a modified version that logs more verbose errors.

**Comment by LoXR** [comment]
Getting the same thing aswell on latest Jenkins build for ViaBackwards: https://pastebin.com/dEwShKqi
Having to go back a version.
