### ISSUE TITLE
Missing 1.13.2 block id for 1.14 block 669

### ISSUE THREAD

**Issue by Fiks75** [ViaVersion/ViaBackwards#209]
### What is the output url of /viaversion dump?
> https://dump.viaversion.com/8f480d23dcd950b3853353443d74ec27c60cd7cc6c96c2e26dcbcc22a6130268

### How/when does this error happen? login?:
> Often. Spam in console. paperSpigot 1.15.2

### Is there an error in the console? Use pastebin.com. Is there a kick message?:
> https://pastebin.com/BNJ5Dym1

**Comment by Jo0001** [comment]
You can ignore them.  Set `suppress-metadata-errors` to true in the Viaversion config.yml to suppress those messages

**Comment by KennyTV** [comment]
Harmless warning, will fix it when I can throw it on top of my local changes
