### ISSUE TITLE
[1.12.2] (URGENT) Entities not rendering properly / invisibility bug

### ISSUE THREAD

**Issue by ManO1234148** [ViaVersion/ViaBackwards#214]
Entities sometimes pop in and out of visibility without warning on the server. They are undetectable but still damageable, and they are not rendered but still exist. This issue is happening with and without a resource pack, with default entity-tracking in spigot. It affects all types of entities, hostile, non-hostile. The issue happens completely at random and is very game-breaking especially for a mob arena type gamemode. It **never occurs in vanilla, under any version**. Random Entities for texturepacks is disabled. Client renderdistance is 20+ and serverside is 10. Mob invisibility only seems to happen in certain areas although no specific area can be defined and replicated, so it is mostly at random.

https://gfycat.com/elatedobeseandalusianhorse

It also affects players

Bug was tested by both me and 2 other players, both also running optifine 1.12.2 HD U F5 and then tested using vanilla 1.12.2

## OptiFine Version
1.12.2 - HD U F5

**## Installation Method**
I used the standalone installer

**However it only happens on 1.12.2 optifine not 1.14.4**
SPIGOT version 1.14.4 non paper
BUNGEECORD version 1.15.2 with viaversion / backwards

## F3 Debug Screenshot
![image](https://user-images.githubusercontent.com/29739282/85973728-984b8b80-b988-11ea-9f26-39c8c98aaf08.png)
Invisible entities screenshot
![image](https://user-images.githubusercontent.com/29739282/85973862-e6608f00-b988-11ea-9555-6d12b959e904.png)

This issue does not happen in vanilla minecraft, with or without our resourcepack, on 1.12.2

https://dump.viaversion.com/6a13873ddb7cfbd0a28ede85c13c3c643d5e329c3543ed1fcbd89876a088d359

I expected mobs to (not) go invisible?

**Comment by KennyTV** [comment]
So you're saying this doesn't happen with a Vanilla 1.12.2 client, but with youe 1.12.2 OptiFine client?

**Comment by Xernium** [comment]
That sounds very heavily like it’s an issue we can’t fix because we don’t support mods interfering with vanilla in the first place. Let alone- where should we even start to debug this when it works in vanilla?

**Comment by ManO1234148** [comment]
I don't know where you should start but i know that it doesnt happen with optifine 1.14.4 which is the server base version

**Comment by KennyTV** [comment]
So you're saying this doesn't happen with a Vanilla 1.12.2 client, but with your 1.12.2 OptiFine client?

**Comment by OmegaByte** [comment]
This used to happen to me, I updated ViaVersion and ViaBackwards, I don't know if it was using optifine but for me was in versions under my main version 1.15.2, under 1.15.2, 1.12, 1.13, 1.14, were having this bug. I updated and now it doesn't happen, but now I have a bug were shulkers with special characters lag users and Time out them. It's #215

**Comment by ManO1234148** [comment]
Im on the latest viaversion and viabackwards

**Comment by KennyTV** [comment]
@ManO1234148 I can't help if you just ignore my question.

**Comment by KennyTV** [comment]
... Since you also opened an issue on the OF tracker, I'm just going to assume that's the case.

**Comment by ManO1234148** [comment]
So you're saying this doesn't happen with a Vanilla 1.12.2 client, but with your 1.12.2 OptiFine client?

This does not happen with vanilla but does with 1.12.2 optifine.
HOWEVER, the server version is 1.14.4, and if i use 1.14.4 optifine, it works just fine. This is probably something happening between both, so i'd appreciate if you look into it as well @KennyTV

**Comment by KennyTV** [comment]
This is obviously an OptiFine bug then, 1.12 and 1.14 OptiFine are 2 different versions 👀
