### ISSUE TITLE
Kick 1.9 with reason DecoderException Packet 0/34 found 3 bytes extra

### ISSUE THREAD

**Issue by lokha** [ViaVersion/ViaBackwards#218]
ViaBackwards version 2.4.0-SNAPSHOT
Core: paper spigot 1.12.2

this happens when the particle effect on my server is turned on. to repeat the problem, you can contact me, I will give you access to this effect

found only on 1.9 minecraft, but it is possible that on other versions there is no problem

![image](https://user-images.githubusercontent.com/32991511/86144878-e97d8b80-bafe-11ea-9e1e-b9627ab1abc1.png)

**Comment by KennyTV** [comment]
>2.4.0 🥶

**Comment by lokha** [comment]
thank
