### ISSUE TITLE
Modded clients can climb on air in survival mode

### ISSUE THREAD

**Issue by mihapain1** [ViaVersion/ViaBackwards#219]
**How can we reproduce it?**
1. Login on 1.16.1'
2. Click on space
3. Fly

**Screenshots**
![2020-06-28_09 30 44](https://user-images.githubusercontent.com/38764610/85939964-39532b80-b922-11ea-8fad-058e4c1e412c.png)

client: 1.15.2
mods: 
![image](https://user-images.githubusercontent.com/38764610/85940000-86370200-b922-11ea-89a9-d8b0569e10e4.png)

Server: vanila 1.16.1

**Comment by creeper123123321** [comment]
My hypothesis is: we are sending vanilla 1.16.1 invalid tags that fabric is interpreting as modded tags
