### ISSUE TITLE
BUG (1.12.2) Item lore (with crackshot, although probably other plugins as well) being messed up

### ISSUE THREAD

**Issue by ManO1234148** [ViaVersion/ViaBackwards#220]
**Describe the bug, provide any errors**
BUG - lore from crackshot weapons (and presumably other plugins) is displayed with strange {} tags attached to it

**How can we reproduce it?**
Load up crackshot, put lore on a gun
give yourself the gun

**Expected behaviour**
I expected the lore to be displayed as normal

**Screenshots**
![image](https://user-images.githubusercontent.com/29739282/86199048-e8a02600-bb0d-11ea-9e15-4e3476a3ecb4.png)

**ViaVersion Dump:**
https://dump.viaversion.com/368aabf639d521719659465777ecea735f4c0a76cb2d86a6f4df9b0210d0bc26

**Additional server info**
This is Viabackwards bungee, bungee is 1.15.2, server 1.14.4, and client 1.12.2.

**Comment by KennyTV** [comment]
You only have Via on your Bungee right, now on the other servers? Can you also please send me the weapon config for the mag-rail?

**Comment by KennyTV** [comment]
See https://github.com/ViaVersion/ViaBackwards/issues/223
