### ISSUE TITLE
1.16.1 SkinsRestorer & ViaBackwards incompatibility

### ISSUE THREAD

**Issue by xknat** [ViaVersion/ViaBackwards#221]
our refresher: [[link](https://github.com/SkinsRestorer/SkinsRestorerX/blob/master/src/main/java/skinsrestorer/bukkit/skinfactory/LegacySkinRefresher_v1_16_R1.java)] 
Refresher when they use paper: [[link](https://github.com/SkinsRestorer/SkinsRestorerX/blob/f53f5a8768521abe71f45c8e9d3bb5bf72b4da3c/src/main/java/skinsrestorer/bukkit/skinfactory/PaperSkinRefresher.java)]
Local git ticket: https://github.com/SkinsRestorer/SkinsRestorerX/issues/277

**Is your feature request related to a problem? Please describe.**
Incompatibility between the new world manager and previous versions are not working when using both ~~ViaVersion~~ViaBackwards & SkinsRestorer. 

**Describe the solution you'd like**
Our dev pointed out that This issue might be on ~~viaversion~~ViaBackwards side.
Therefor we created this issue and await your feedback.

**Describe alternatives you've considered**
N.A.

**Which versions is this for?**
when using 1.16.1 and ViaBackwards that does allow connections from 1.15.2 till 1.8.8
releases that support atleast 1.16.1
Server version = 1.16.1
client version = 1.15.2

**Comment by FormallyMyles** [comment]
Do you have any extra information on what is wrong / needs correcting?

**Comment by KennyTV** [comment]
Sorry, but this is not something we will add hacks to Via for; sending respawn packets while remaining in the same **world** is an absolute nono for older clients, and we can't support anyone doing that. After such a respawn, the client needs its full world data again.
You might want to look into https://github.com/ViaVersion/ViaVersion/issues/1860 as well btw, which is a reoccurrence of https://github.com/SkinsRestorer/SkinsRestorerX/issues/244.

**Comment by DoctorMacc** [comment]
Fixed with https://github.com/SkinsRestorer/SkinsRestorerX/pull/345.
