### ISSUE TITLE
Issues with lores using TokenEnchant (custom enchant plugin useful for prison)

### ISSUE THREAD

**Issue by LunglessYT** [ViaVersion/ViaBackwards#224]
**Describe the bug, provide any errors**
When enchanting my pickaxe with 'TokenEnchant' on a version lower than my main version (in my case the main version is 1.13.2 paper) it shows 2 lores instead of 1 lore, when using a version higher than 1.13.2 or 1.13.2 itself, it shows 1 lore which is correct. I have spoken to the maker of TokenEnchant and he confirms that this is an issue on Via*'s side.
I am getting no errors when enchanting my items.
startup log: https://pastebin.com/1KGnYVgb

**How can we reproduce it?**
1. Get TokenEnchant (this is a custom-enchant plugin that most people use for Prison servers)
2. Get Paper 1.13.2
3. Get the latest viaversion, backwards and rewind
4. use the command /te enchant Speed ( can be any enchant)
5. now you will see 2 lores instead of 1 lore, this only happens on any version under the server's main version, in my case my main version is 1.13.2 (paper), if I log on 1.8 or 1.9 for example, the enchant Speed will show 2 lores instead of one.
When I use 1.13.2 or any version higher than that, it will show 1 lore, which should be correct.

**Expected behaviour**
I expected to get 1 lore on my pickaxe, when enchanting it with TokenEnchant.

**Screenshots**
https://gyazo.com/5451ec97c6b035137d7e364e18164700

**ViaVersion Dump:**
https://dump.viaversion.com/23c89d60d8f3d04e825a69a6bcf524d9569afd054059d7139fb4adb1155f3ed7
note: I had the official released resources first, but a moderator asked me to get the latest dev builds*

**Additional server info**
I am using PaperMC 1.13.2
plugins: https://gyazo.com/b2096ae87a00a83f1adecb7f9221ada9
note: I have removed almost all plugins when testing TokenEnchant with viaversion,backwards and rewind, still seemed not to work.

**Comment by KennyTV** [comment]
Set `add-custom-enchants-into-lore` to false in the ViaBackwards config.
