### ISSUE TITLE
Items within chests, shulker boxes, do not render at all, and are uninteractable.

### ISSUE THREAD

**Issue by astronomic802** [ViaVersion/ViaBackwards#225]
**Describe the bug, provide any errors**
Some items do not even render on versions below 1.13. This issue was already created for **Shulker Preview Modifications**, but items will not even render in on vanilla versions below 1.13.
This is a problem with a server using ViaVersion. (problem with viaversion itself, not the server)
You are unable to interact with the items as well.

**How can we reproduce it?**
1. Get certain items (some enchanted, some with data values) on versions 1.13+
2. put them in a chest or shulker box, open then close it 2 times
**Expected behaviour**
On versions below 1.13, you should be able to access those items

**Screenshots**
What items should look like rendered in properly: https://imgur.com/fS0cncl
What they look like on versions below 1.13: https://imgur.com/hzcyZKc

**ViaVersion Dump:**
n/a

**Additional server info**
n/a

**Comment by KennyTV** [comment]
Can't reproduce this locally; So this happens with 1.12.2 and downwards? Was the shulker created through a mod/in creative/with nbt copying? And please append your ViaVersion dump info.
