### ISSUE TITLE
Particles: Block Crack on Air should be invisible.

### ISSUE THREAD

**Issue by MeFisto94** [ViaVersion/ViaBackwards#227]
**Describe the bug, provide any errors**
On a 1.15.2 server, we use `setParticle(Particle.BLOCK_CRACK, Material.AIR.createBlockData())` as the particles of an `AreaEffectCloud` to make it invisible.

When joining with 1.12.2 and ViaBackwards, those particles are rendered with the purple-black debug(?) checkerboard texture, see the screenshots

**How can we reproduce it?**
1. Create particles that simulate breaking are.
2. Join with 1.12.2 (probably also effects other versions)
3. see the particles.

**Expected behaviour**
The particles should be invisible, maybe the packets even dropped, 

**Screenshots**
![img](https://cdn.discordapp.com/attachments/555462289851940864/730772647746469888/unknown.png)

**ViaVersion Dump:**
https://dump.viaversion.com/4e5d6e5071c0e6ea1bb929649f1d004a29860a534accfca143c2c179e8214f8c

**Additional server info**
As seen in the dump, using Waterfall and a custom plugin to spawn such particles.

**Comment by KennyTV** [comment]
Does this also happen with 1.13 (or any higher version), or does it only start with 1.12.2?
