### ISSUE TITLE
Error when enabling plugin

### ISSUE THREAD

**Issue by Rubenicos** [ViaVersion/ViaBackwards#228]
**Describe the bug, provide any errors**
- Paper 1.12.2
- I use the lastest ViaVersion Build
- I use other things like ViaRewind, ViaRewindLegacySupport, ViaRewindPotions
- Here the error: https://hastebin.com/noxarevacu.js

**Comment by KennyTV** [comment]
Please follow the issue template. Be sure you actually have matching versions of ViaVersion and ViaBackwards.
