### ISSUE TITLE
StatusClient.getProtocolVersion incorrect

### ISSUE THREAD

**Issue by ShayBox** [ViaVersion/ViaBackwards#229]
**Describe the bug, provide any errors**
With this plugin installed, in the [PaperServerListPingEvent](https://papermc.io/javadocs/paper/1.13/com/destroystokyo/paper/event/server/PaperServerListPingEvent.html), [StatusClient](https://papermc.io/javadocs/paper/1.13/com/destroystokyo/paper/event/server/PaperServerListPingEvent.html#getClient--).getProtocolVersion() returns the servers protocol version, leading to in my case sending 1.16 hex color codes to pre-1.16 clients, this is not the case for similar plugin ProtocolSupport

**Expected behaviour**
Return the actual clients information despite the protocol layer

**Additional server info**
PaperMC 1.16.1 w/ ViaVersion, ViaRewind, and ViaBackwards

**Comment by FormallyMyles** [comment]
The ViaVersion API runs at a packet level meaning the server is not aware of this. You'd need to use ViaVersions API to determine real protocol version. There are libraries like adventure which can do this for chat based messages.

**Comment by ShayBox** [comment]
The server doesn't need to be aware of it, ViaVersion just has to not modify that data before it's sent to the server

**Comment by FormallyMyles** [comment]
That's not possible as then the client couldn't login.
