### ISSUE TITLE
Crash when connecting to 1.16.1 server from 1.15.2 client on Velocity

### ISSUE THREAD

**Issue by jackmawer** [ViaVersion/ViaBackwards#231]
**Describe the bug, provide any errors**
Connecting from a 1.15.2 client to a 1.16.1 Paper server using ViaVersion and ViaBackwards on a Velocity proxy causes the player to be disconnected, emitting the following error: https://pastie.io/mytvbk.java

1.16.1 users are able to connect normally to both 1.16.1 and 1.15.2 servers.

**How can we reproduce it?**
1. Setup a 1.16 Paper server behind a Velocity proxy with Via & ViaBackwards.
2. Connect using 1.15.2 client.
3. Lose connection when attempting to connect.
4. Observe error in Velocity console.

**Screenshots**
![Minecraft disconnection screen reads, "Your connection has encountered an error. Try again later."](https://user-images.githubusercontent.com/3983253/87699063-3793bf80-c78c-11ea-9b0d-519f9683aadf.png)

**ViaVersion Dump:**
https://dump.viaversion.com/29e3f4e77293833d095639e3192ead0232259a8e2255a8f32cff6b4dece3e29b

**Additional server info**
The error also occurs when using the stable build of Velocity 1.0.8, as well as the latest build `#229`

**Comment by KennyTV** [comment]
Fixed in the latest ViaVersion-Dev build
