### ISSUE TITLE
Warnings in console

### ISSUE THREAD

**Issue by Loonyy** [ViaVersion/ViaBackwards#234]
**Describe the bug, provide any errors**
My console gets spammed with warnings like these a lot. Are these a cause for concern // any way to disable them?
https://pastebin.com/bK7qTctP

**ViaVersion Dump:**
https://dump.viaversion.com/b63e1615920f8364e282cda7a0ef3841733d1344ca25e7b583050c81aaf2aafd

**Additional server info**
We're on Paper 1.15.2

**Comment by KennyTV** [comment]
Yes, enable `suppress-conversion-warnings` / `suppress-metadata-errors` in the ViaVersion config
