### ISSUE TITLE
[<= 1.12.2] Scoreboard Teams do not clear the color for the suffix

### ISSUE THREAD

**Issue by MeFisto94** [ViaVersion/ViaBackwards#236]
**Describe the bug, provide any errors**
So for our scoreboards we have the following setup: The Sidebar Entry has a name like `§a` and a score.
We then have a team which has `§a` as entry and a prefix and a suffix.
We use the prefix and suffix to display the actual information, so we don't have to predict the entry name.

Now the issue is that the suffix' color isn't reset to white, which means for our code, that the color of the suffix is bound to what we set as team entry. A simple workaround would be to include a `§r` as the prefix of the suffix, obviously.

This issue is present for every client below 1.13.2 (didn't check dot releases, but it's present on 1.12.2 and 1.8).
I guess this might need something similar to https://github.com/ViaVersion/ViaBackwards/blob/b98f208a985f1586d6cc985476ef81f4af29ef17/core/src/main/resources/assets/viabackwards/config.yml#L8

**How can we reproduce it?**
Create a team as outlined above

**Expected behaviour**
The Sidebar should look the same as on more recent versions, i.e. the suffix' color is reset to white.

**ViaVersion Dump:**
https://dump.viaversion.com/bf2fa3f0af3178923585229f632e8ee72e6e11c3b8e3d62269b2df0ce597f18d (but it's also present on the release versions (3.1.0) and bungeecord.

**Additional server info**
Bungeecord and Velocity both show this problem

**Comment by KennyTV** [comment]
It's not possible to predict how people use scoreboard teams for coloring, so things like splitting of prefix/suffix and resetting the color should be done in your own configuration/coloring

**Comment by MeFisto94** [comment]
On 1.15.2 and everything using the "new"? Teams API (presumably using JSON), no matter what the entry is, the suffix is printed as-is, basically as if it was it's own TextComponent so to speak.

At 1.12.2 and below, sideboard entry _and_ suffix seem to be joined, because the suffix has the last chat color that was present in the entry.

Speaking in Code, I would take https://github.com/ViaVersion/ViaBackwards/blob/650f89e1ce87dc6f539d9384e51f9df3ebcd7afe/core/src/main/java/nl/matsv/viabackwards/protocol/protocol1_12_2to1_13/packets/PlayerPacket1_13.java#L255-L257
copy and modify it to `clearTeamSuffixColorBefore1_12` or something and just add `suffix += "§r`.

Basically it seems that pre json clients just join the strings into one big, and thus the color is not reset. On JSON those are separate components that are rendered. When downgrading the version, the more-recent behavior should be adopted and not the other way around.

So to clarify, this is not because we'd like a different behavior more for our application, but a mismatch between the versions, see below:
1.15.2
![grafik](https://user-images.githubusercontent.com/12577813/88466090-3c155200-cec9-11ea-8a7f-0072ae5ab675.png)
1.12.2
![grafik](https://user-images.githubusercontent.com/12577813/88466103-5818f380-cec9-11ea-8373-f6a2028b56ab.png)

Actually by looking into our code, there seems to be something even more special going on by removeUnusedChatColor(?)

```java
Team account = sb.registerNewTeam("Account");
account.addEntry("§d");
sidebar.getScore("§d").setScore(12);
account .setPrefix("§8➟ §f");
account .setSuffix("§f" + p.getName());
```
So in fact we _do_ even define a suffix color, but we just don't see it, but the `§d` from the entry.
I don't know what 1.15.2 would do without that `§f`, maybe that's a missing piece of information here.

**Comment by KennyTV** [comment]
Thank you for the further investigation - can you try again with the latest dev build?

**Comment by MeFisto94** [comment]
Yep, that solves it, thanks!
