### ISSUE TITLE
Player kicked when given written book in 1.8

### ISSUE THREAD

**Issue by Stixil** [ViaVersion/ViaBackwards#237]
Describe the bug, provide any errors
When giving the player a custom written book (a server rules book in this case), the player is kicked from the game.
Stacktrace: https://mcpaste.io/97a9009187dd554d

How can we reproduce it?

Login on 1.8'
Use a command to give the player a custom written book.
The player is kicked from the game.
ViaVersion Dump:

https://dump.viaversion.com/6d6856217ed72c391f0c69f9d5006045467a3ffbbada147c8c5708b852894f3c
Additional server info
Waterfall-366
Paper 1.16.1 version 90
Running with ViaVersion, Rewind, and Backwards

**Comment by KennyTV** [comment]
Update to https://ci.viaversion.com/job/ViaVersion-DEV/ https://ci.viaversion.com/view/ViaBackwards/job/ViaBackwards-DEV/ https://ci.viaversion.com/view/ViaRewind/job/ViaRewind-DEV/ and try again / send the new error please

**Comment by Stixil** [comment]
Hi, I have just swapped to the DEV builds. Here is the new dump and stacktrace:

https://dump.viaversion.com/9111f45be6fb9e20ad99eb632111a316bb15e413a7157f04f4f2b01001b3ff33

https://mcpaste.io/18a243324c1f722f

Thanks!

**Comment by KennyTV** [comment]
The lore of your Help Book is invalid, it should be written as a proper component (or at least a simple one with quotations)
