### ISSUE TITLE
Incompatibility with AutoPickup

### ISSUE THREAD

**Issue by Rubenicos** [ViaVersion/ViaBackwards#238]
**Describe the bug, provide any errors**
I use AutoPickup plugin who cancel item drop when player mine blocks.
ViaBackwards spamming mesages when player break blocks.

**How can we reproduce it?**
1. Use [this plugin](https://www.spigotmc.org/resources/autopickup.7623/)
2. Enter with 1.9-1.11 in 1.12 server
3. Mine some blocks with shovel or pickaxe

**Screenshots**
![Captura de pantalla (255)](https://user-images.githubusercontent.com/44579213/88832193-b118ae00-d18d-11ea-918e-5df014703748.png)

**Comment by KennyTV** [comment]
Please follow the issue template.
