### ISSUE TITLE
Tab List Hex Compatibility

### ISSUE THREAD

**Issue by MrKorvic** [ViaVersion/ViaBackwards#239]
**Describe the bug, provide any errors**
Does not throw errors. When using Bungee color to create hex colors for player names on the tab list, ViaBackwards does not translate these colors to the old default colors. The colors themselves work on the same version & 1.16.2-pre1 (running on a 1.16.1 PaperMC server). Colors in chat change properly using the same source. Screenshot examples below.

**How can we reproduce it?**
1. Run Waterfall/PaperMC setup (latest 1.16.1)
2. Install ViaVer + ViaBack latest Dev builds on Waterfall, PaperMC, or Both.
3. Parse a Bungee Hex Color into a PlaceholderAPI placeholder.
4. With BungeeTabListPlus running on Waterfall, use the created placeholder to apply color to a username.
5. View tab list on a version that does not support hex color in text.
6. Observe that hex colors are seemingly replaced with 'reset' or 'white' colors.

**Expected behavior**
Should translate the hex color to the closest approximate old color.

**Screenshots**
Note; The tab list name is derived from the same method of color for the prefix in chat, and that the color is translated in chat, but not in the tab list.
Connecting on 1.16+; https://i.imgur.com/IaO62yt.png
Connecting on 1.15.2-; https://i.imgur.com/E8FR96G.png

**ViaVersion Dump:**
https://dump.viaversion.com/4ec6703b0ff6ea31760610ed60e091cdd50dc813d52918157f4c7cd203987bf3

**Additional server info**
The normal setup that is being used is Waterfall + PaperMC instances. Both have ViaVer + ViaBack on them. Have tested with ViaVer + ViaBack on only the Waterfall instance, and only on the PaperMC instance, but to no avail. The Waterfall instance is running BungeeTabListPlus 3.3.4, and the PaperMC instance is running BungeeTabListPlusBukkitBridge 3.3.4 to enable it to hook into PlaceholderAPI, also present on the PaperMC instance.

Tab List is managed by BungeeTabListPlus (consulted them in case they knew of the issue, but they haven't done anything explicit to make that not function, as per CodeCrafter47). Color is handled by a placeholder created with PlaceholderAPI. The placeholder itself is functional, it's simply the conversion of the hex color that seems to go awry on lower versions.

**Comment by KennyTV** [comment]
I fixed the approximation to be better at least, but it won't be perfect, you will have to live with potentially bad ones.

**Comment by MrKorvic** [comment]
Same issue with the new snapshot that was just pushed (217).

https://dump.viaversion.com/3f80f8cbbecdc45b84fe34cd4cc12d590ff104bed1a7a5a485cb3102c5a112ea

**Comment by KennyTV** [comment]
Ah you're right, thanks. It should be fixed with the next build.
