### ISSUE TITLE
Does not work - config Problem? (Paper)

### ISSUE THREAD

**Issue by UltraBlackLinux** [ViaVersion/ViaBackwards#241]
**Describe the bug, provide any errors**
My Friend cant connect to my 1.16.1 Paper server with mc 1.8, even though ViaBackwards is loaded with no problems.
I couldnt find any docs, and the IRC is down, so Im coming here with litterally no knowlage.

**Expected behaviour**
Let 1.8 join

**Screenshots**

**ViaVersion Dump:**
https://dump.viaversion.com/fd9b325f9a8a9a2791109e6783bd7d5cfcc3f650050f01131271920f9f7dcbde

**Additional server info**
Do you use a proxy (eg. BungeeCord)? What software do you use and what plugins?
None yet

**Comment by KennyTV** [comment]
You need ViaRewind.

**Comment by UltraBlackLinux** [comment]
thanks
