### ISSUE TITLE
Can't remap respawn anchors

### ISSUE THREAD

**Issue by 22s** [ViaVersion/ViaBackwards#242]
I can't remap respawn anchors from obsidian to end portal frames within the mapping-1.15to1.16.json file. 

i have tried using 
    "minecraft:respawn_anchor[charges=0]": "minecraft:end_portal_frame[eye=false,facing=north]",
    "minecraft:respawn_anchor[charges=1]": "minecraft:end_portal_frame[eye=true,facing=north]",
    "minecraft:respawn_anchor[charges=2]": "minecraft:end_portal_frame[eye=true,facing=north]",
    "minecraft:respawn_anchor[charges=3]": "minecraft:end_portal_frame[eye=true,facing=north]",
    "minecraft:respawn_anchor[charges=4]": "minecraft:end_portal_frame[eye=true,facing=north]",
i've also tried 
    "minecraft:respawn_anchor[charges=0]": "minecraft:end_portal_frame",
    "minecraft:respawn_anchor[charges=1]": "minecraft:end_portal_frame",
    "minecraft:respawn_anchor[charges=2]": "minecraft:end_portal_frame",
    "minecraft:respawn_anchor[charges=3]": "minecraft:end_portal_frame",
    "minecraft:respawn_anchor[charges=4]": "minecraft:end_portal_frame",
and 
    "minecraft:respawn_anchor[charges=0]": "minecraft:end_portal_frame[eye=false]",
    "minecraft:respawn_anchor[charges=1]": "minecraft:end_portal_frame[eye=true]",
    "minecraft:respawn_anchor[charges=2]": "minecraft:end_portal_frame[eye=true]",
    "minecraft:respawn_anchor[charges=3]": "minecraft:end_portal_frame[eye=true]",
    "minecraft:respawn_anchor[charges=4]": "minecraft:end_portal_frame[eye=true]",
and
    "minecraft:respawn_anchor[charges=0]": "minecraft:end_portal_frame[eye=false,facing=north]",
    "minecraft:respawn_anchor[charges=1]": "minecraft:end_portal_frame[eye=true,facing=north]",
    "minecraft:respawn_anchor[charges=2]": "minecraft:end_portal_frame[eye=true,facing=north]",
    "minecraft:respawn_anchor[charges=3]": "minecraft:end_portal_frame[eye=true,facing=north]",
    "minecraft:respawn_anchor[charges=4]": "minecraft:end_portal_frame[eye=true,facing=north]",

they've all returned 
No key for "minecraft:respawn_anchor[charges=0]" :(
No key for "minecraft:respawn_anchor[charges=1]" :(
No key for "minecraft:respawn_anchor[charges=2]" :(
No key for "minecraft:respawn_anchor[charges=3]" :(
No key for "minecraft:respawn_anchor[charges=4]" :(

**Comment by KennyTV** [comment]
`"minecraft:respawn_anchor[charges=0]": "minecraft:end_portal_frame[eye=false,facing=north]",`
