### ISSUE TITLE
issue with mining times, block traits, and durability 

### ISSUE THREAD

**Issue by 22s** [ViaVersion/ViaBackwards#243]
netherite tools being remapped to iron tools, the netherite tools then take the iron tool's mining speeds in lower versions, I would love to remap them to stone tools but then they take on the stone tools mining speed making them absolutely useless. also I have remapped respawn anchors from obsidian to end portals (with eyes in them when charged) but when mining them in lower versions where they are end portals they take the end portals durability. making them unmineable. netherite armor being remapped to diamond armor also makes them go into negative durability when lower than diamond armors durability, while it is  possible to set them higher than diamond armors durability so when they hit 0 durability theyll break instead being much more realistic and easily understandable than viewing an item with -100 durability and having no idea when it will break. it would be handy if viabackwards had some sort of way to fix these types of issues.

**Comment by 22s** [comment]
as for block breaking bugs id suggest giving viabackwards its own block break managing system to make the plugin break blocks for the server at the correct times,

**Comment by KennyTV** [comment]
Thanks for pointing out the dig speed issue - that's something we cannot influence in any way, so I remapped them to diamond tools now to at least work with blocks like obsidian/end portals. The durability issue will probably be a won't-fix.

We can't change block breaking without having it done 100% serverside with own ticking, counting in ping and setting break length for every block, which is a veery fat no no.
