### ISSUE TITLE
CONSOLE SPAM PROBLEM

### ISSUE THREAD

**Issue by MedetYldrk** [ViaVersion/ViaBackwards#247]
**Describe the bug, provide any errors**
A clear and concise description of what the bug is. Can you https://paste.gg/ the error?

**How can we reproduce it?**
1. Login on 1.12'
3. The '....' is displayed wrong

**Expected behaviour**

**Screenshots**

**ViaVersion Dump:**
- Type /viaversion dump, and put the link here.

**Additional server info**
Do you use a proxy (eg. BungeeCord)? What software do you use and what plugins?

**Checklist**
- [+] I have included a ViaVersion dump
- [+] If applicable, I have included a paste (not a screenshot) of the error
- [+] I have tried a build from https://ci.viaversion.com/ and the issue still persists

https://dump.viaversion.com/883d93a2fe715d485b7ec0918e83953778e92ce99c5c31c203f2e1d9319aab27
https://paste.gg/p/anonymous/535cdfaf42bd45c29c51d792008338c1

**Comment by KennyTV** [comment]
You have a plugin send data for untracked entities; Set `suppress-metadata-errors` to true in the ViaVersion config to suppress the warnings (while it technically is erroneous sending, it does not actually cause any harm).
