### ISSUE TITLE
ERROR IN Protocol1_13_2To1_14 IN REMAP OF ENTITY_EQUIPMENT (0x46) #222

### ISSUE THREAD

**Issue by xion87** [ViaVersion/ViaBackwards#248]
Describe the bug, provide any errors
I just upgraded my plotsquared world from 1.13.2 to 1.15.2 without doing the chunk upgrades.
Game seem to work fine for 1.15.2 and 1.16.1 clients. But for 1.8-1.12.2 clients they crash if they are tipped in certain places o visit certain plots.
https://gist.github.com/xion87/ff7276192c2a0d97007c915534427aca

How can we reproduce it?

Login on 1.12.2 on my server
Teleport to any random plots, some are good but most will crash you
That error will appaer
Expected behaviour
Should not crash

Screenshots
Not rilevant

ViaVersion Dump:
https://dump.viaversion.com/a585279154a6692892bc4ebea07c7e06fee50a78433fd19e9701aca2d8366495

Additional server info
I am using waterfall, the server is Paper version git-Paper-373 (MC: 1.15.2), Previous version: git-Paper-655 (MC: 1.13.2)

I tested with protocolsupport and  player don't crash

**Comment by KennyTV** [comment]
You're outdated, please update the plugins.
