### ISSUE TITLE
Old client getting disconected often on plotsquared world (1.13.2 --> 1.15.2)

### ISSUE THREAD

**Issue by xion87** [ViaVersion/ViaBackwards#249]
**Describe the bug, provide any errors**
People visitng plots on a converted world from 1.13.2 to 1.15.2, if they use a client old before 1.15.2 they will be kicked from the server with this error: https://gist.github.com/xion87/e945046cf947e80efc1df3ffe818297e

**How can we reproduce it?**
1. plot visit or visit certain chunk
2. people will crash

**Expected behaviour**
No crashing?

**ViaVersion Dump:**
https://dump.viaversion.com/3c4cbe0399c06b735f59d55b5076ff482f71a4697f7988a93e928371d15a67bf

**Additional server info**
Do you use a proxy (eg. BungeeCord)? What software do you use and what plugins?
Waterfall,

N.B. If i use Protocolsupport it work fine

**Checklist**
- [x] I have included a ViaVersion dump
- [x] If applicable, I have included a paste (not a screenshot) of the error
- [x] I have tried a build from https://ci.viaversion.com/ and the issue still persists

**Comment by KennyTV** [comment]
Please try without other plugins to see if it might be related to custom equipment sending.

**Comment by xion87** [comment]
i already using on skyblock, i don't have any issue here, it look something related with plotsquared maybe

**Comment by KennyTV** [comment]
Shouldn't occur with the current ci builds, but will reopen this if you do run into it again with them.

**Comment by xion87** [comment]
i tried  ViaRewind 1.5.1 and ViaBackwards 3.1.1
I upgraded my skyblock world too, and tada, every client crash when loading a chunk by using a teleport or something, (tp comand /spawn ecc)

**Comment by KennyTV** [comment]
Via doesn't modify protocol for 1.16.3 clients on a 1.16.3 server.

**Comment by xion87** [comment]
Tell me why removing viabackard and viarewind, i don't have the issue anymore so lol

**Comment by xion87** [comment]
somesone on viaversion support tell me to set max-chunk-sends-per-tick to 1 on paper.yml config

**Comment by Malachiel87** [comment]
still not fixed

**Comment by Malachiel87** [comment]
Bump, still a issue, was never fixed and i have to use protocolsupport....
