### ISSUE TITLE
Console Spam

### ISSUE THREAD

**Issue by Loonyy** [ViaVersion/ViaBackwards#250]
**Describe the bug, provide any errors**
https://pastebin.com/MgT6Mt9X
This gets spammed constantly in the console

**ViaVersion Dump:**
https://dump.viaversion.com/3a1e0e2422d748f4150819f8a298580c2525fc8530a06e41f41060964f17deff

**Additional server info**
Paper 1.15.2

**Comment by KennyTV** [comment]
You have a plugin send data for untracked entities; Set suppress-metadata-errors to true in the ViaVersion config to suppress the warnings (while it technically is erroneous sending, it does not actually cause any harm).

**Comment by Loonyy** [comment]
Alright thanks!
