### ISSUE TITLE
NoSuchFieldError whilst loading ViaBackwards mapping on Yatopia

### ISSUE THREAD

**Issue by ishland** [ViaVersion/ViaBackwards#252]
**Describe the bug, provide any errors**
NoSuchFieldError whilst loading ViaBackwards mapping on Yatopia
And players cannot join using 1.12.2
https://pastebin.com/eCV2S3gT

**How can we reproduce it?**
1. Start the server
2. See error

**Expected behaviour**
The mapping should be loaded just fine and players using 1.12.2 can join

**Screenshots**
Nope

**ViaVersion Dump:**
https://dump.viaversion.com/7daa16ad6f6c7fae8cda03b99da4c28dbdad0e97e45689fb6dec95f9c4e22fc5

**Additional server info**
Do you use a proxy (eg. BungeeCord)? What software do you use and what plugins?
Not using a proxy. 
Server software: Yatopia
Plugins: `Barrels, CS-CoreLib, JukeBox, MinecraftSP, MineTinker, Multiverse-Core, NoteBlockAPI, PlaceholderAPI, PluginManager*, ProtocolLib, QQMinecraft*, SandtoQuartz, ServerMSPT, Slimefun, spark, TitleManager*, Vault, ViaBackwards, ViaVersion, WorldEdit, XPConomy`

**Checklist**
- [x] I have included a ViaVersion dump
- [x] If applicable, I have included a paste (not a screenshot) of the error
- [ ] I have tried a build from https://ci.viaversion.com/ and the issue still persists

**Comment by KennyTV** [comment]
Update to the ci builds.
