### ISSUE TITLE
Lecterns not appearing on 1.13

### ISSUE THREAD

**Issue by cadeheinberg** [ViaVersion/ViaBackwards#254]
I have my server set to 1.13 - 1.16. I am using Via Backwards and Via Version.
Lecterns appear perfectly fine for 1.14 - 1.16, but they appears as bookshelfs on 1.13. I'm not sure why this is, is there anyway I can change it so that they can appear. I am pretty sure Lecterns were added in 1.10 unless that was just for bedrock edition.
I am a plugin dev so if its something like editing the source code I can probably figure that out.

Thanks for the great plugins!

**Comment by KennyTV** [comment]
Lecterns were added in 1.14.
