### ISSUE TITLE
Actionbars and inventory titles

### ISSUE THREAD

**Issue by Nick-kel** [ViaVersion/ViaBackwards#256]
(Bug exists in ViaBackwards and ViaRewind)

**Describe the bug, provide any errors**
Inventory titles with color codes (e.g. §a) are completely grey and actionbars with color codes are completely white

**How can we reproduce it?**
Login with 1.12.2 or another version on a 1.16.2 server. Open inventories with titles which contain color codes and look at a actionbar with colors.

**Expected behaviour**
Color codes will be displayed. No hex colors were used.

**Screenshots**

**Additional server info**
Do you use a proxy (eg. BungeeCord)? Yes

![image](https://user-images.githubusercontent.com/42046014/91639626-3820a680-ea18-11ea-8841-7b06f94ac22a.png)

**Comment by KennyTV** [comment]
Follow the issue template.
