### ISSUE TITLE
1.16.2 via rewind Problem

### ISSUE THREAD

**Issue by Finisu** [ViaVersion/ViaBackwards#258]
Ok, so, know that this is new so this is just to report a new bug. i used to use via-backwards a lot between 1.14 on my 1.15 server. i updated my server to 1.16.2 and got the brand new via-version, via-rewind and via-backwards. i have found a glitch where if i login to my 1.16.2 server on 1.15, when i first load in my game will make me floating in the air. It's not like not-loaded because my skin doesnt turn black and i can see my inbventory. i did some testing using my alt and i have found that in this state you cannot move and you are standing still, on the ground to other players. When you arein 1.15 you can still use commands, see particals and see other players. I have found that using multiverse core and swiching to any world (or getting /killed)

 will fix all of these issues. If you return to the spawn world, the issues will also be fixed. there is only 1 plugin i havethat is 1.16 only and that is GyserMC (a cross platform conbatibility plugin. Onemore thing, i have noticed that when you are loading into the server on 1.15, it will show everything while its loading, but then do this glitch straight after, even if there is no default texturepack for the server to force you to load.  Thank you soooo much for your help and it is much appreciated! :D :D :D

These are the immages of this glitch in action:     (PS. my server keeps crashing and this glitch might be the reason. Also, the first time i log in with any account, it will work and not do this glitch but will continuously teleport them back until they get kicked for "flying (or continuously teleporting)" and then have the glich happen to them whenever they login on 1.15 after that.)                                  

(The green guy/SpifeyOp is on 1.15 while the multicoulered guy/Skeppy_op is on 1.16.2) :

![Screenshot (18604)](https://user-images.githubusercontent.com/54497028/92552955-2b684200-f2a5-11ea-8c9d-45e49297ee53.png)
![Screenshot (18605)](https://user-images.githubusercontent.com/54497028/92552972-33c07d00-f2a5-11ea-8fc3-5f767cbd548a.png)
![Screenshot (18607)](https://user-images.githubusercontent.com/54497028/92553171-a7628a00-f2a5-11ea-9567-3f2ccc7da010.png)
![Screenshot (18608)](https://user-images.githubusercontent.com/54497028/92553001-489d1080-f2a5-11ea-993b-31e1eb9672b9.png)
![Screenshot (18615)](https://user-images.githubusercontent.com/54497028/92553247-c82adf80-f2a5-11ea-92d0-23de472f3136.png)

(PPS. : the whole "killedby:_error" is my custom kill message)

**Comment by KennyTV** [comment]
Please try without any other plugins and also add your ViaVersion dump (as asked for in the template)
