### ISSUE TITLE
Netherite armor turns back into diamond armor when switching out versions.

### ISSUE THREAD

**Issue by SpicyChickenMcNuggets** [ViaVersion/ViaBackwards#259]
When you login on a 1.16.2 server on an older minecraft version, netherite armor will turn back into diamond armor when you log back in with 1.16.2.
No errors.

**How can we reproduce it?**
1. Login on any minecraft version older than 1.16 on a 1.16+ server.'
2. Wear netherite armor.'
3. Log out
4. Log back in on 1.16+ client. Your armor is now diamond armor.

**Expected behaviour**
To have netherite armor and not diamond armor.

**Screenshots**
I don't have any screenshots.

**ViaVersion Dump:**
- Type /viaversion dump, and put the link here.
https://dump.viaversion.com/e54b3a3ee4c074fd89fb422e28fdfb9c7408fa96b60f5fb1363a2c79a026d44c

**Additional server info**
Do you use a proxy (eg. BungeeCord)? What software do you use and what plugins?
I use bungeecord and i dont have any plugins that conflict with armor and stuff. I run viaversion, viarewind and viabackwards for full crosscompatibility.

**Checklist**
- [✓ ] I have included a ViaVersion dump
- [X ] If applicable, I have included a paste (not a screenshot) of the error
- [ ✓] I have tried a build from https://ci.viaversion.com/ and the issue still persists

**Comment by KennyTV** [comment]
You're outdated.

**Comment by SpicyChickenMcNuggets** [comment]
Seriously? Im outdated by like one build and you close it in 5 seconds. I highly doubt its fixed

**Comment by KennyTV** [comment]
You are outdated by a month worth of commits, and yes, it is fixed.
