### ISSUE TITLE
Elytra not working for 1.10 clients on 1.11 server

### ISSUE THREAD

**Issue by MightyBoss** [ViaVersion/ViaBackwards#26]
### What is the output url of /viaversion dump?
>  https://gist.github.com/anonymous/381e90451bbe677c06d08aa3f000330f

### How/when does this error happen? login?:
> The issue happens when installing viabackwards on bungee side and trying to use elytra with a 1.10 client on a 1.11 server

### Is there an error in the console? Use pastebin.com. Is there a kick message?:
> No error, no kick msg

**Comment by ArtNRG** [comment]
Same problem on 1.12.1 server. Both viabackwards and viaversion are installed as bungee plugin. 1.11.1 clients can't use elytra, when i reinstall viabackwards and viaversion as spigot plugins all become ok.

**Comment by KennyTV** [comment]
See above - if it actually still happens, please tell us so :p
