### ISSUE TITLE
1.16.x

### ISSUE THREAD

**Issue by s7an1slaw** [ViaVersion/ViaBackwards#260]
Hello, I have a question, if the server is running on version 1.16.3, how can I do it so that people can enter only from 1.16 upwards without those in the old versions, I saw that there are ViaBackWards, but it also includes in the older versions and as I told me i only need from 1.16 to 1.16.3 (1.16.x)

**Comment by KennyTV** [comment]
You can use https://via.krusic22.com/ to generate the list for `block-protocols` in the ViaVersion config, this will allow you to whitelist / blacklist version.
