### ISSUE TITLE
I was asked to report an error (with 1.16.1 - 1.16.2)

### ISSUE THREAD

**Issue by Govindass** [ViaVersion/ViaBackwards#261]
**Describe the bug, provide any errors**
I was switching worlds with nether portal really fast then got kicked and was told to report this in github issues

errors: https://pastebin.com/raw/HeJAYTei

**How can we reproduce it?**
I don't really know, I was switching worlds with nether portal really fast

**Expected behaviour**
To not kick I guess

**Screenshots**

**ViaVersion Dump:**
https://dump.viaversion.com/528d4bf33d5beec0f4e60cdd5eea598adfc77631a122f3f60130fc6bdc69bdad

**Additional server info**
FlameCord & Purpur (1.16.3)

**Checklist**
- [x] I have included a ViaVersion dump
- [x] If applicable, I have included a paste (not a screenshot) of the error
- [x] I have tried a build from https://ci.viaversion.com/ and the issue still persists

I believe it is caused by NetherView plugin that I've just added.

**Comment by KennyTV** [comment]
Please update ViaVersion to the now latest ci build and send the new error (with slightly changed text).

**Comment by Govindass** [comment]
after updating ViaVersion I have failed to reproduce this bug
