### ISSUE TITLE
BungeeCord stuck at "Loading 1.16.2 -> 1.16.1 mappings...", BungeeCord and ViaVersion are both the latest It’s been stuck for almost an hour, and restarting is useless.

### ISSUE THREAD

**Issue by xiaowine** [ViaVersion/ViaBackwards#263]
BungeeCord stuck at "Loading 1.16.2 -> 1.16.1 mappings...", BungeeCord and ViaVersion are both the latest
It’s been stuck for almost an hour, and restarting is useless.
![捕获](https://user-images.githubusercontent.com/68009112/94107301-be8da400-fe6f-11ea-953c-21e78e9de789.PNG)

**Comment by KennyTV** [comment]
Follow the issue template.

**Comment by xiaowine** [comment]
> 按照问题模板操作（正确的日志和"最新"不明确）

ViaVersion and ViaBackwards is 3.3.1
BungeeCord  is 1536
