### ISSUE TITLE
BungeeCord stuck at "Loading 1.16.2 -> 1.16.1 mappings...",

### ISSUE THREAD

**Issue by xiaowine** [ViaVersion/ViaBackwards#265]
BungeeCord stuck at "Loading 1.16.2 -> 1.16.1 mappings...",
 ViaVersion and ViaBackwards is 3.3.1
BungeeCord is 1536
![94107301-be8da400-fe6f-11ea-953c-21e78e9de789](https://user-images.githubusercontent.com/68009112/94327108-77bcbd00-ffdb-11ea-8ab9-6ea8ee7d22ec.png)

**Comment by KennyTV** [comment]
It's not stuck, that's just the last debug we output.
