### ISSUE TITLE
I found two bugs

### ISSUE THREAD

**Issue by Koita0724** [ViaVersion/ViaBackwards#266]
versions
server version:paper.1.16.2
client version:1.14.4
viaversion,viabackwards version:3.1.1
First bug: actionbar text color is not painted.
second bug: netherite sword is change the diamond sword
[2020-09-27 22-16-46.zip](https://github.com/ViaVersion/ViaBackwards/files/5289925/2020-09-27.22-16-46.zip)
It is difficult to explain and shows it in a video
The video is in the zip file

https://dump.viaversion.com/877161a38181f8ae985fd657c0ab9060f133caea9dcab5707fd783de7a139aee

im not using bungee.

**Comment by KennyTV** [comment]
Sub 1.16 clients do not know about the existence of netherite swords, so they have to be temporarily remapped. As for the actionbar; It's a Minecraft bug, but technically, using the chat packet with system isn't the correct place for custom actionbars - you whatever plugin is sending them should send title packets with the actionbar type instead.
