### ISSUE TITLE
Error found, plugin still working

### ISSUE THREAD

**Issue by Bergfalk-Krieger** [ViaVersion/ViaBackwards#267]
I just found this error, the plugin still working good

https://paste.gg/p/anonymous/40cefa096ceb44e494bc6cbcc6b50434

**Expected behaviour**
Nothing because the plugin still working

**ViaVersion Dump:**
- https://dump.viaversion.com/bd9108bf7551ca2a06727c4622a3c1ddd73fd3370a6d4a11ff24d6fe55d00f7c

**Additional server info**
Do you use a proxy (eg. BungeeCord)?  Nope, I don't
What software do you use and what plugins?
Spigot
and the plugin:
![image](https://user-images.githubusercontent.com/65326502/94452917-77145a00-0186-11eb-93e1-a662864d483a.png)

**Checklist**
- [ +] I have included a ViaVersion dump
- [ +] If applicable, I have included a paste (not a screenshot) of the error
- [ +] I have tried a build from https://ci.viaversion.com/ and the issue still persists

**Comment by Jo0001** [comment]
Try it with this versions:
https://ci.viaversion.com/job/ViaVersion/lastSuccessfulBuild/artifact/jar/target/ViaVersion-3.2.0-SNAPSHOT.jar
https://ci.viaversion.com/view/ViaBackwards/job/ViaBackwards/lastSuccessfulBuild/artifact/all/target/ViaBackwards-3.2.0-SNAPSHOT.jar
