### ISSUE TITLE
1.16.3 colored inventory titles

### ISSUE THREAD

**Issue by Nick-kel** [ViaVersion/ViaBackwards#269]
**Describe the bug, provide any errors**
Colored inventory titles aren't colored in older versions than the server version. They are grey and not in the color they should be. The server version is 1.16.3, with the server version 1.15.2 it worked correctly

**How can we reproduce it?**
1. Login on 1.12.2 (or 1.8.9, ...)
2. Open an colored inventory (e.g. with the name "§cTest")
3. The displayed inventory isn't in the color it should be

**Expected behaviour**
That the inventory title is in the correct color

**ViaVersion Dump:**
- https://dump.viaversion.com/c6ec8c70664d1a9c699d4aa155c222dee78c0700f1313118c559266b70b5c0fd

**Additional server info**
BungeeCord

**Checklist**
- [x] I have included a ViaVersion dump
- [x] If applicable, I have included a paste (not a screenshot) of the error
- [x] I have tried a build from https://ci.viaversion.com/ and the issue still persists

**Comment by BredyAK** [comment]
When will this be fixed? It has been there for months.

**Comment by jakkeren** [comment]
Yeah, please. Seems like this bug's been here for months.
