### ISSUE TITLE
[Feature Request] Enable or disable versions in config

### ISSUE THREAD

**Issue by cwchristerw** [ViaVersion/ViaBackwards#272]
It would be nice to have a way to only enable specific old versions. I have currently 1.14.4 and planning to update it to latest. I have enabled ViaBackwards but it will enable also versions older than 1.14.4 and it will cause some weirdness when user is using 1.12. I want to disable every version older than 1.14.4

**Comment by DoctorMacc** [comment]
You can disable specific versions from joining by using https://via.krusic22.com/ which will generate a list that you can put in `block-protocols` in the ViaVersion config, which will also work for ViaBackwards.
