### ISSUE TITLE
Error in console

### ISSUE THREAD

**Issue by Volgeop** [ViaVersion/ViaBackwards#275]
**Describe the bug, provide any errors**
Hi from some reason I got this error in console and players were kicked from server, don't know exactly what happened.

**How can we reproduce it?**
1. Players were logged probably with multiple versions, but most of them were using 1.16.3 (server is also on 1.16.3).
2. Then there tried to join so many players on the server, because I restarted proxy before.
3. Then it kicked them back to Lobby with this error probably.

**Expected behaviour**
Normally joining server without error https://pastebin.com/Ku408cME

**ViaVersion Dump**
https://dump.viaversion.com/42623072eafefa01ac54afe2e848baf6a1a51573a6a11729c0c8851c831ba67e

**Additional server info**
Yes, I use bungeecord - waterfall, the newest version, and I don't use there via version plugins, these I use just on sub servers.

**Checklist**
- [x] I have included a Viaversion dump
- [x] If applicable, I have included a paste (not a screenshot) of the error
- [ ] I have tried a build from https://ci.viaversion.com/ and the issue still persists

**Comment by Volgeop** [comment]
https://github.com/ViaVersion/ViaVersion/issues/2154 copied from this

**Comment by KennyTV** [comment]
Use binary search to find what plugin is causing this please

**Comment by Volgeop** [comment]
I don't understand? This was caused by your plugin, or?

**Comment by BuzzTheGamer23** [comment]
Remove half of your plugins (move it to a different folder), then if it fixes it, the incompatible plugin is in the half you removed. If it didn’t, it is in the half you didn’t remove. Repeat with the half it is in. Do this until you find the incompatible plugin. Make sure to not remove the Via plugins when you do it.

**Comment by Volgeop** [comment]
but this happened only once when I restarted proxy and then multiple players tried to join.

**Comment by KennyTV** [comment]
As it stands it's probably caused by another plugin sending bad data, so unless you can somehow reproduce it on a clean server, that's all we can say.
