### ISSUE TITLE
Cannot Climbing Ladders

### ISSUE THREAD

**Issue by MoneyDrip** [ViaVersion/ViaBackwards#276]
I cannot climb ladders.

1.) Login on Minecraft 1.8x.
2.) Climb a ladder.
3.) You appear to be stuck from climbing the ladder and you don't gain any y velocity.

I really expected to reach the top of that ladder but it never works.

Animated GIF: https://media.giphy.com/media/sFPTGdVKy5kIJVNGJl/source.mov

Dump file. https://dump.viaversion.com/c7504d86cd9835c8c1e2bb109d13f11a0b5004bffe5ef1d7fefa643a615af320

The latest version of BungeeCord _(Wed. October 28th, 2020)_.

**Comment by Seanoo1** [comment]
You have to install viarewindlegacysupport

**Comment by MoneyDrip** [comment]
> You have to install viarewindlegacysupport

Thanks! All fixed.
