### ISSUE TITLE
Cannot Ride Horses

### ISSUE THREAD

**Issue by MoneyDrip** [ViaVersion/ViaBackwards#277]
I can mount my horse. Although, I cannot ride and control my tamed horse with a saddle on it.

1.) Login on Minecraft 1.8.x
2.) Find and tame a horse.
3.) Put a saddle on it and mount the horse.
4.) Attempt to start galloping.

I expected my horse to take off in high speeds.

Animated GIF: https://media.giphy.com/media/tnruy5TBYM8qwRQlgx/source.mov

Dump file: https://dump.viaversion.com/c47de9799fbaf98fb5dfe0ff5bd93f3738bcbe809d0d4e6c1a52387f8820a724

I use the latest version of BungeeCord. _(Wed. October 28th, 2020)_

**Comment by Seanoo1** [comment]
1. This is also viarewind issue(1.8- client issue is viarewind side)
2. Controlling vehicles(boat, cart, horse) is can't fix issue
3. About mounting, report on viarewind issue tracker.
