### ISSUE TITLE
ViaBackWards sound issues 

### ISSUE THREAD

**Issue by ZeyKoYT** [ViaVersion/ViaBackwards#279]
**Describe the bug, provide any errors**
A clear and concise description of what the bug is. Can you https://paste.gg/ the error?

Hi !  I got multiples bugs , first bug is with ViaBackWards i think , like when you go into lava and take damages , it dont play damage sound (1.9.4 client - 1.12.2 server version).
The other bug is when i install Viaversion , ViabackWards and viarewind , and when i join the server with 1.8.8 client on my 1.12.2 server it kick me instantly for [Proxy] Lost connection to the server (screen : https://prnt.sc/vaofn6) 

I use Travetive for proxy , i try to change it and use normal bungeecord , flamecord ect but same issue.
And server version i use Paper 1.12.2.

I got 0 plugins on my bungeecord.
I got Only ViaVersion , ViaRewind and ViaBackWards my spigot server.

**How can we reproduce it?**
To reproduce the lava sound  issue , 
1 - just setup a bungeecord 
2 - setup a 1.12.2 paper server
3-  install viaversion , viarewind and viabackwards on it (spigot side)
4 - take lava damages.

To reproduce the player kick issue , 
1 - just setup a bungeecord 
2 - setup a 1.12.2 paper server
3-  install viaversion , viarewind and viabackwards on it  (spigot side)
4 - Join with a <= 1.8.9  client 

**Expected behaviour**
- I expect it to be fixed

**Screenshots**
If applicable, add screenshots to help explain your problem.*
- With the lava issue i cant , screen that because it's a sound issue, no console errors or anything.
- With the kick issue on <= 1.8.9 client i got just 2 screens 1 minecraft side and on bungeecord side 
- Minecraft Side: https://prnt.sc/vaoixp
- Bungeecord Side (Console) : https://prnt.sc/vaoj6l
- No console errors proxy / spigot side.

**ViaVersion Dump:**
- Type /viaversion dump, and put the link here.
- https://dump.viaversion.com/dd77e09a3d415f490c96cf64f49d830ebc59c17a6d7a646b3553ce3e1feae461

**Additional server info**
Do you use a proxy (eg. BungeeCord)? What software do you use and what plugins?
i use Travetine lasted for this test , but alredy tryed to use FlameCord or a normal Bungeecord. i dont have plugins proxy side.

**Checklist**
- [x] I have included a ViaVersion dump
- [x] If applicable, I have included a paste (not a screenshot) of the error
- [x] I have tried a build from https://ci.viaversion.com/ and the issue still persists

- I install lasted version of all the plugins 

 Good luck for fixing it. and Srry for my english i'm french

**Comment by KennyTV** [comment]
Does this also happen with a 1.9-1.11 client?

**Comment by KennyTV** [comment]
The kick for 1.8 is related to ViaRewind, so you should open an extra issue on its repository for that. I will look at the sound issue soon

**Comment by ZeyKoYT** [comment]
Yeah it happen with 1.9 and 1.11 to , ok will create an other report for ViaRewind.

**Comment by ZeyKoYT** [comment]
So fire & lava sound not played , exp bottle interact make a succeful hit sound

**Comment by ZeyKoYT** [comment]
and suffocation sound to

**Comment by Seanoo1** [comment]
I think we have to close this issue. lava/fire damage sound does not exist on 1.11.2. Suffocation sound too.

**Comment by Seanoo1** [comment]
Or maybe we can translate similar sound. Like block.fire.extinguish

**Comment by ZeyKoYT** [comment]
I made test to and in 1.12.2 there are lava , fire and suffocation sounds , the xp bottle sound is an issue of the developper but tere are sounds in 1.12.2 ( server and 1.12.2 client) or just in 1.12.2 singleplayer world it need to be fixed ! and not closed

**Comment by ZeyKoYT** [comment]
and why closing an issue without resolving it ?
