### ISSUE TITLE
Featherboard lines cut in half on 1.8-1.12

### ISSUE THREAD

**Issue by ColorbombDev** [ViaVersion/ViaBackwards#280]
**Describe the bug, provide any errors**
No errors. I have a scoreboard that is made by featherboard, and if a line on it is long enough (not past limit), it slices the end off. This only happens client-side on 1.8-1.12. I have been informed multiple times by the author of featherboard that this is not an issue on his end but on yours. Is there a way to fix this? Scoreboard will be very important on my server and if I can get a solution to this it would be very much appreciated.

**How can we reproduce it?**
1. Login on 1.8-1.12
2. Look at a featherboard that has a long enough line
3. The line should be cut off at the end

**Expected behaviour**
The line isn't supposed to be cut off, it should show the entire thing.

**Screenshots**
1.8-1.12 [ERROR]: ![Screenshot_1](https://user-images.githubusercontent.com/43486893/97794980-b04d4900-1bce-11eb-90d9-6801b5df1e1d.png)
1.13+ [EXPECTED]: ![Screenshot_2](https://user-images.githubusercontent.com/43486893/97794984-bd6a3800-1bce-11eb-8746-ba4bf5b10105.png)

**ViaVersion Dump:**
https://dump.viaversion.com/a2db09c74836c9f4573008179b41619263f706a571be5838ab7f47d029d40a31

**Additional server info**
Server runs 1.16 Paper. Proxy runs Waterfall.

**Checklist**
- [x] I have included a ViaVersion dump
- [x] If applicable, I have included a paste (not a screenshot) of the error
- [x] I have tried a build from https://ci.viaversion.com/ and the issue still persists

**Comment by KennyTV** [comment]
Legacy clients have a characters limit in team prefix and suffix.

**Comment by ColorbombDev** [comment]
So is this a problem I can fix myself? Or is it an issue with ViaBackwards/Featherboard?

**Comment by Blocksnmore** [comment]
This isn't fixable, this is mojang limitations. 1.8 has a shorter character thing which causes issues

**Comment by ColorbombDev** [comment]
> This isn't fixable, this is mojang limitations. 1.8 has a shorter character thing which causes issues
If you look at his original message, he said there is a workaround.
