### ISSUE TITLE
Plugin won't start in paper 1.13.2

### ISSUE THREAD

**Issue by EarlyGamer45** [ViaVersion/ViaBackwards#284]
**Describe the bug, provide any errors**
A clear and concise description of what the bug is. Can you https://paste.gg/ the error?
https://paste.gg/p/anonymous/321a681a639d487f850ea8f8533732fc When he loads the plugin gives this error and shut down.
**How can we reproduce it?**
1. Use 1.13.2 paper
2. Start the server.
3. In console he displays an error and the plugin shut's down

**ViaVersion Dump:**

- Type /viaversion dump, and put the link here.

https://dump.viaversion.com/7ca1cc42824b49b64c2b3ddfcedb1775654c39aff869aea293f5d80ef15cb416 

**Additional server info**
Do you use a proxy (eg. BungeeCord)? What software do you use and what plugins? 

I use viaversion (last update 1.16.4) and viarewind.

**Checklist**
- [ x] I have included a ViaVersion dump
- [ x] If applicable, I have included a paste (not a screenshot) of the error
- [ ] I have tried a build from https://ci.viaversion.com/ and the issue still persists

**Comment by FormallyMyles** [comment]
Use the latest from the ci
