### ISSUE TITLE
A bug with command blocks

### ISSUE THREAD

**Issue by XReioX** [ViaVersion/ViaBackwards#287]
**Describe the issue**
So, when your server is in the newer version (mine is 1.14.4) and your client is in the older version (mine is 1.8.9) then you get a bug with command blocks. When you update the command in the command block it doesnt work, and sends a message to the console:
[ViaBackwards] Client send MC|AdvCmd custom payload to update command block, weird!
It works when my client is in newer versions, so probably command blocks changed in newer versions?

**ViaVersion Dump**
https://dump.viaversion.com/64411d5fc4311b45d9809f59f4608aa0eb3d2a3ee8c02c9abafa9050d0ade312

**How to reproduce**
I basically explained it in the issue, you just gotta make your server newer and client older, and then try to update a command block.

**Screenshots**
https://prnt.sc/vepo4x

**Any other information?**
Well i tried to get help in discord, but they just said to update to the latest version. what i did but it still didnt work.
Thanks.

**Comment by KennyTV** [comment]
ViaBackwards is only for 1.9+, so it doesn't account for 1.8 specialties

**Comment by XReioX** [comment]
So i should make it to viarewind's issue tracker?
The error says [ViaBackwards] tho.

**Comment by KennyTV** [comment]
It's basically a mixture of the two, but there will likely not be any further legacy (1.9-1.12) fixes for VB anymore, especially not for 1.8 client specific content.
