### ISSUE TITLE
ERROR IN Protocol1_11_1To1_12 IN REMAP OF CHUNK_DATA

### ISSUE THREAD

**Issue by sgdc3** [ViaVersion/ViaBackwards#288]
**Describe the bug, provide any errors**
https://paste.gg/p/anonymous/2eafa60862534588a4313009eacc7883

**ViaVersion Dump:**
https://dump.viaversion.com/4b8aba7e6d51121a07c80bade027b5340d5e961c56951ae26a9885e5a6e0206f

**Additional server info**
Using Waterfall and Paper 1.12.2

**Checklist**
- [x] I have included a ViaVersion dump
- [x] If applicable, I have included a paste (not a screenshot) of the error
- [x] I have tried a build from https://ci.viaversion.com/ and the issue still persists

**Comment by KennyTV** [comment]
I'm going to assume you have corrupted chunks/used corrupt builds of FAWE at some point, since that's what all of these reports came down to in the past. If you somehow still encounter this on cleanly built worlds, we will reopen this.
