### ISSUE TITLE
Remapped items become the actual remapped item

### ISSUE THREAD

**Issue by TheBlackEntity** [ViaVersion/ViaBackwards#289]
Hey,

For example:
A 1.16.4 player has a netherite sword.
The player drops it to a 1.13 player. This player sees it as a diamond sword.

Everything seems to work prefectly normal first, but as soon as the 1.13 player opens any inventory, the netherite sword becoms an actual diamond sword.

This completely breaks my server. I don't want players to be able to downgrade their gear or turn warped leaves to blue wool...

This issue is already in this plugin for a very long time, I really don't know how this problem isn't fixed neither reported yet...

**Comment by KennyTV** [comment]
Follow the issue template.
