### ISSUE TITLE
No textures when join 1.15.2 on serwer 1.16.4

### ISSUE THREAD

**Issue by krfcm** [ViaVersion/ViaBackwards#292]
When player joins to my server 1.16.4 on version 1.15.2 they dont have textures when instaled is skinrestorer
![image](https://user-images.githubusercontent.com/14114364/99573995-18759a80-29d7-11eb-8415-2c9e045f5850.png)

**How can we reproduce it?**
Use lase version of paperspigot and last version viaver and visbackwards and install skinrestorer last version

**ViaVersion Dump:**
- https://dump.viaversion.com/98b5c194cd572bcea6cf60fecb343824f880063715761cdfd34a3cb25246b94a

**Comment by KennyTV** [comment]
Won't fix, has to be fixed on their side with version dependent checks
