### ISSUE TITLE
Crash on 1.8.x client

### ISSUE THREAD

**Issue by lorenzoalinovi** [ViaVersion/ViaBackwards#293]
**Describe the bug, provide any errors**
I'm using a BedWars pluging and when a 1.8.x player tries to play a BedWars, it crashes and gives this: https://prnt.sc/vn453z

**How can we reproduce it?**
1. Login to a 1.8.x version
2. Start a bedwars with https://www.spigotmc.org/resources/screamingbedwars-1-9-1-16.63714/
3. When the match starts, 1.8.x player crashes.

**Expected behaviour**
The match starts.

**Screenshots**
https://prnt.sc/vn453z

**ViaVersion Dump:**
https://dump.viaversion.com/2b48759f8b90b09b2858c0a2cad2036aaaa045948c13230c838b39fdc2956334

**Additional server info**
https://prnt.sc/vn45wi (plugins)
Using 1.16.4 Spigot

**Comment by lorenzoalinovi** [comment]
(The Dump is old, I removed SkinsRestorer: https://dump.viaversion.com/9b4c88625c981233285a53e9af1ad8f2e821d5def9732e5dac5aef49d83d1016)

**Comment by KennyTV** [comment]
We need the full error from your console.

**Comment by lorenzoalinovi** [comment]
https://hastebin.com/doyedefodo.lua

Here it is

**Comment by KennyTV** [comment]
Please download the latest build from https://ci.viaversion.com/job/ViaVersion/ and resend the error with the new error message.
