### ISSUE TITLE
Players getting kicked repeatedly from the server due to AbstractChannel error

### ISSUE THREAD

**Issue by angeluscaligo** [ViaVersion/ViaBackwards#297]
One of our players got kicked from the server, repeatedly, within a second of logging in. As far as we know, they were playing on a 1.15.2 Minecraft cliënt & the issue resolved when they updated to 1.16.3. Still, we tought it prudent to log this error here nonetheless.

[Mon, 23. Nov 2020 15:12:11 CST WARN] at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738) [Mon, 23. Nov 2020 15:12:11 CST WARN] at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730) [Mon, 23. Nov 2020 15:12:11 CST WARN] at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:816) [Mon, 23. Nov 2020 15:12:11 CST WARN] at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:723) [Mon, 23. Nov 2020 15:12:11 CST WARN] at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:111) [Mon, 23. Nov 2020 15:12:11 CST WARN] at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738) [Mon, 23. Nov 2020 15:12:11 CST WARN] at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:801) [Mon, 23. Nov 2020 15:12:11 CST WARN] at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:814) [Mon, 23. Nov 2020 15:12:11 CST WARN] at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:794) [Mon, 23. Nov 2020 15:12:11 CST WARN] at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:831) [Mon, 23. Nov 2020 15:12:11 CST WARN] at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1071) [Mon, 23. Nov 2020 15:12:11 CST WARN] at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:300) [Mon, 23. Nov 2020 15:12:11 CST WARN] at com.comphenix.protocol.injector.netty.ChannelProxy.writeAndFlush(ChannelProxy.java:327) [Mon, 23. Nov 2020 15:12:11 CST WARN] at net.minecraft.server.v1_16_R2.NetworkManager.lambda$b$6(NetworkManager.java:300)
[10:19 PM]
[Mon, 23. Nov 2020 15:12:11 CST WARN] at com.comphenix.protocol.injector.netty.ChannelInjector$3.lambda$onMessageScheduled$1(ChannelInjector.java:325) [Mon, 23. Nov 2020 15:12:11 CST WARN] at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) [Mon, 23. Nov 2020 15:12:11 CST WARN] at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404) [Mon, 23. Nov 2020 15:12:11 CST WARN] at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:313) [Mon, 23. Nov 2020 15:12:11 CST WARN] at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884) [Mon, 23. Nov 2020 15:12:11 CST WARN] at java.base/java.lang.Thread.run(Thread.java:834) [Mon, 23. Nov 2020 15:12:11 CST WARN] Caused by: us.myles.ViaVersion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues [Mon, 23. Nov 2020 15:12:11 CST WARN] {Source 0: nl.matsv.viabackwards.protocol.protocol1_15_2to1_16.packets.BlockItemPackets1_16$2 (Anonymous)} [Mon, 23. Nov 2020 15:12:11 CST WARN] Actual Error: [Mon, 23. Nov 2020 15:12:11 CST WARN] Caused by: java.lang.NullPointerException [Mon, 23. Nov 2020 15:12:11 CST WARN] at nl.matsv.viabackwards.api.rewriters.EnchantmentRewriter.rewriteEnchantmentsToClient(EnchantmentRewriter.java:66) [Mon, 23. Nov 2020 15:12:11 CST WARN] at nl.matsv.viabackwards.api.rewriters.EnchantmentRewriter.handleToClient(EnchantmentRewriter.java:41) [Mon, 23. Nov 2020 15:12:11 CST WARN] at nl.matsv.viabackwards.protocol.protocol1_15_2to1_16.packets.BlockItemPackets1_16.handleItemToClient(BlockItemPackets1_16.java:320) [Mon, 23. Nov 2020 15:12:11 CST WARN] at nl.matsv.viabackwards.protocol.protocol1_15_2to1_16.packets.BlockItemPackets1_16$2.lambda$registerMap$0(BlockItemPackets1_16.java:100) [Mon, 23. Nov 2020 15:12:11 CST WARN] at us.myles.ViaVersion.api.remapper.PacketHandler.write(PacketHandler.java:19)

**Additional server info**
We use a Paper Server, utilizing Spigot, running Minecraft 1.16.2

**Comment by KennyTV** [comment]
Follow the issue template.
