### ISSUE TITLE
Players not being rendered

### ISSUE THREAD

**Issue by SprigWave** [ViaVersion/ViaBackwards#298]
So when a player joins the server, a player can see them. But let's say player 1 dies. Player 1 cannot see player 2 but player 2 can see player 1. Player 2 can interact with player 1 but player 1 cannot interact with player 2. I will a ViaVersion dump which includes the plugins as well.
https://dump.viaversion.com/69558e3b143b6290149e5714861c8afe025c0438b44235a32e79da29c4603ac8

**Comment by KennyTV** [comment]
Properly follow the issue template.
