### ISSUE TITLE
ViaBackwards / ViaVersion

### ISSUE THREAD

**Issue by iskrentsbg** [ViaVersion/ViaBackwards#299]
**Describe the bug, provide any errors**
In console there is no error, but in 1.8 client chunks need like 30 minutes to load. 

**How can we reproduce it?**
1. Login on 1.8'
2. Chunks don't load..

**Expected behaviour**
I want to know how to fix this error if possible

**Screenshots**
screenshot: https://prnt.sc/vqifzj

**ViaVersion Dump:**
- https://dump.viaversion.com/fd40321cbe4fd6a4531af1143435253113af2deba4abfc8441a42d36389b86b9

**Additional server info**
I have BungeeCord, but plugins are only in lobby and survival, because I need the ViaRewind-legacyFix for my server

**Comment by KennyTV** [comment]
Remove SkinsRestorer, it is not compatible with older clients.
