### ISSUE TITLE
ViaBackwards preventing Forge Client to join Forge servers

### ISSUE THREAD

**Issue by Pobetore** [ViaVersion/ViaBackwards#300]
**Describe the bug, provide any errors**
If you are playing on a Waterfall network with some 1.16.4 servers and some Forge 1.12.2 servers, if you try to connect with a modded client to the forge server starting from a 1.16.4 server you are kicked

**How can we reproduce it?**
1. Set up a waterfall network with 1 1.16.4 server and a 1.12.2 server
2. Connect to the waterfall ip and join the 1.16.4 server
3. Do /server name_of_forge_server
4. Enjoy being prevented from joining the server 

**Expected behaviour**
Joining the server

**Screenshots**
Nop, this isn't the case

**ViaVersion Dump:**
The dump itself isn't interesting, basically the problem is created because VB traslate both REGISTER and FML|HS to minecraft:register and fml:hs and this basically stops the Client to communicate with Forge correctly and the handshake just times out. 

**Additional server info**
Now I created a workig fix for Vb but it works only with VV 3.4.0 so something changed in the API that breaks it. My guess is that something changed in how VV translate the ID of the the PluginPacket (the serverbound one) in fact while with VV3.4.0 it was sent as a 0x09 packets now with the same code it is traslated to 0x0a (so modern id) and this breaks everything.
Also from my testing this change happens sometime after that this method https://github.com/ViaVersion/ViaBackwards/blob/0f631eb1d94a95da451fd94d379bd680bd3c0a32/core/src/main/java/nl/matsv/viabackwards/protocol/protocol1_12_2to1_13/packets/PlayerPacket1_13.java#L363 runs.

If you have any idea of how to correct this we should be able to complitelly fix this forge related error

**Comment by KennyTV** [comment]
We do not provide any further support for legacy/modded clients.
