### ISSUE TITLE
What is wrong with this plugin? This is the second year I’ve had this problem, the via version and via backwards compatible versions are loaded but yet it still says I’m using an outdated client??? 

### ISSUE THREAD

**Issue by JavaLava3** [ViaVersion/ViaBackwards#302]
**Describe the bug, provide any errors**
A clear and concise description of what the bug is. Can you https://paste.gg/ the error?

**How can we reproduce it?**
1. Login on 1.12'
3. The '....' is displayed wrong

**Expected behaviour**

**Screenshots**

**ViaVersion Dump:**
- Type /viaversion dump, and put the link here.

**Additional server info**
Do you use a proxy (eg. BungeeCord)? What software do you use and what plugins?

**Checklist**
- [ ] I have included a ViaVersion dump
- [ ] If applicable, I have included a paste (not a screenshot) of the error
- [ ] I have tried a build from https://ci.viaversion.com/ and the issue still persists

**Comment by DoctorMacc** [comment]
Could you provide a ViaVersion dump, and fill in the checklist? The information you've provided if of absolutely no help for the ViaVersion developers.
