### ISSUE TITLE
spam warnings on 1.16.4

### ISSUE THREAD

**Issue by steveq7** [ViaVersion/ViaBackwards#304]
on server minecraft on 1.16.4  I still have warnings spam
[Netty Epoll Server IO #4/WARN]: [ViaBackwards] Metadata for entity id: 7462 not sent because the entity doesn't exist. MetaStorage{metaDataList=[Metadata{id=0, metaType=Byte, value=0}, Metadata{id=2, metaType=OptChat, value=null}, Metadata{id=6, metaType=Pose, value=0}, Metadata{id=4, metaType=Boolean, value=false}, Metadata{id=15, metaType=Boolean, value=false}, Metadata{id=14, metaType=Byte, value=0}, Metadata{id=12, metaType=VarInt, value=0}, Metadata{id=13, metaType=OptPosition, value=null}, Metadata{id=8, metaType=Float, value=20.0}, Metadata{id=9, metaType=VarInt, value=0}, Metadata{id=11, metaType=VarInt, value=0}, Metadata{id=10, metaType=Boolean, value=false}, Metadata{id=1, metaType=VarInt, value=300}, Metadata{id=3, metaType=Boolean, value=false}, Metadata{id=7, metaType=Byte, value=0}, Metadata{id=5, metaType=Boolean, value=false}, Metadata{id=16, metaType=VarInt, value=0}, Metadata{id=17, metaType=Boolean, value=false}]}

**Comment by KennyTV** [comment]
Enable `suppress-metadata-warnings` in the ViaVersion config.
