### ISSUE TITLE
20w51a

### ISSUE THREAD

**Issue by LordCandyAndy** [ViaVersion/ViaBackwards#307]
Immediate crash upon join
https://mclo.gs/GrH7QQo

USED:
Fabric server 20w51a 0.10.8
-ViaVersion-3.3.0-20w51a
-ViaFabric-0.2.16-SNAPSHOT+build-630.1-mc-1.16
-ViaBackwards-3.3.0-20w49a (build #241)
-fabric-api-0.28.2+1.17
-cotton-client-commands-1.0.1+1.16-rc1

**Comment by KennyTV** [comment]
Follow the issue template, don't use versions not matching each other.

**Comment by Xernium** [comment]
Might I add, ViaFabric isn't updated for 1.17 snapshots yet, so even if you report this, your platform is currently unsupported and any other reports you post will be also closed until that is no longer the case.

**Comment by LordCandyAndy** [comment]
Sorry I did not know that, viafabric worked for me on 20w49a so I just assumed viafabric is 1.16**+**. My bad
