### ISSUE TITLE
Mushroom blocks are not replaceable on older versions + Kick 1.8.9

### ISSUE THREAD

**Issue by DarkyCat** [ViaVersion/ViaBackwards#310]
**Describe the bug, provide any errors**
A clear and concise description of what the bug is. Can you https://paste.gg/ the error?
https://paste.gg/p/anonymous/f9d43edba15140fd86fa34586674e1d5

**How can we reproduce it?**
If I log in from version 1.16.4, then there are mushroom blocks, but if I log in from 1.8.9 instead of mushroom blocks, there will be empty space. 
If the plugin is not installed on BungeeCord and if you log in with 1.8.9 it will be kicked with an error:  https://youtu.be/Z9mJQ1OsCoo

**Expected behaviour**

**Screenshots**
1.16.4 What mushroom blocks look like
![изображение](https://user-images.githubusercontent.com/50515714/103233981-519f1400-4960-11eb-94ca-ce6bdaddf20b.png)

1.8.9 What mushroom blocks look like
![изображение](https://user-images.githubusercontent.com/50515714/103234114-a5116200-4960-11eb-9221-f1660c5412e7.png)

**ViaVersion Dump:**
https://dump.viaversion.com/954d7c2fe17e29c7c3a8a3754b5f2ad7b8ab3d5a471f818389c3af2e8c805f34

**Additional server info**
Do you use a proxy (eg. BungeeCord)? What software do you use and what plugins?
I have tested and if the plugin is on BungeeCord there is no bug on 1.8.9.

**Checklist** (mark with [X] to check)
- [] I have included a ViaVersion dump
- [] If applicable, I have included a paste (not a screenshot) of the error
- [] I have tried a build from https://ci.viaversion.com/ and the issue still persists
- [] I have looked at https://www.spigotmc.org/resources/viarewind-legacy-support.52924/ and it does not offer a fix for my problem

**IMPORTANT: Follow the Checklist or we can't reproduce your issue and your issue will be close**

**Comment by KennyTV** [comment]
Duplicate.
