### ISSUE TITLE
Entity 99 Not Found, and Lightning Not showing

### ISSUE THREAD

**Issue by Pulsih** [ViaVersion/ViaBackwards#312]
In the console when i summon a lightning, He spamm this:
 
![image](https://user-images.githubusercontent.com/74119488/102087505-f3c7e380-3e19-11eb-9229-33e8fe617d05.png)

And he doesn't show the Lightning Effect... 

Server is: Paper 1.16.4

I don't know what can i do for fix this, i search on google and i don't find anything, thanks to who will help me. :D

**Comment by KennyTV** [comment]
Open a new issue and follow the template.
