### ISSUE TITLE
[ViaBackwards] Metadata for entity id: ------- not sent because the entity doesn't exist. 

### ISSUE THREAD

**Issue by EuanM199** [ViaVersion/ViaBackwards#314]
**Describe the bug, provide any errors**
A warning in console that is consistently spammed [Paste.gg](https://paste.gg/p/anonymous/2eb427c531e14999b23530989d20237f)

**How can we reproduce it?**
N/A

**ViaVersion Dump:**
https://dump.viaversion.com/3fe8b6f5075772062e58c0080505c568a42a97fcec80bf42e4cd795ec8578287

**Additional server info**
I use Velocity, here is my plugins list too
[plugins list](https://cdn.discordapp.com/attachments/716405933105872938/796845005997998110/unknown.png)

**Comment by Camotoy** [comment]
From the ViaVersion Discord:

> To fix console spam, use `suppress-conversion-warnings: true` and `suppress-metadata-errors: true` in the ViaVersion config.yml. The errors will still happen but you won't be spammed with them and the issues will be ignored.

**Comment by EuanM199** [comment]
thank you :)
