### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by SimplyTex** [ViaVersion/ViaBackwards#317]
e{metaDataList=[Metadata{id=0, metaType=Byte, value=0}, Metadata{id=2, metaType=OptChat, value={"extra":[{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"aqua","text":""},{"color":"aqua","translate":"entity.minecraft.bat"},{"color":"white","extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"green","text":"6.0"},{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"white","text":"/6.0"}],"text":": "}],"text":""}],"text":""}}, Metadata{id=6, metaType=Pose, value=0}, Metadata{id=4, metaType=Boolean, value=false}, Metadata{id=15, metaType=Byte, value=1}, Metadata{id=14, metaType=Byte, value=0}, Metadata{id=12, metaType=VarInt, value=0}, Metadata{id=13, metaType=OptPosition, value=null}, Metadata{id=8, metaType=Float, value=6.0}, Metadata{id=9, metaType=VarInt, value=0}, Metadata{id=11, metaType=VarInt, value=0}, Metadata{id=10, metaType=Boolean, value=false}, Metadata{id=1, metaType=VarInt, value=300}, Metadata{id=3, metaType=Boolean, value=true}, Metadata{id=7, metaType=Byte, value=0}, Metadata{id=5, metaType=Boolean, value=false}]}

**Comment by KennyTV** [comment]
You didn't even copy the full warning (not error) 🥶
Set suppress-metadata-errors to true in the ViaVersion config.
