### ISSUE TITLE
No key/old entry/item mapping for various blocks.

### ISSUE THREAD

**Issue by mibby** [ViaVersion/ViaBackwards#321]
Paper dev 457 (Spigot 1.16.5)
ViaVersion-DEV dev 414
ViaBackwards-DEV dev 250
ViaReind-DEV dev 187
ViaRewind Legacy Support dev 8

Latest ViaVersion dev build has new mappings that spam ``No key``, ``No old entry``, & ``No item mapping`` warnings.
https://paste.gg/p/anonymous/6be3a7926dd040d89a5e937cdc41130d/files/e5e89040a4264466b36e9bf536c4a940/raw

**Comment by KennyTV** [comment]
Support for 21w05a is not out yet.
