### ISSUE TITLE
Long array tag disconnect

### ISSUE THREAD

**Issue by Semisol** [ViaVersion/ViaBackwards#322]
**Describe the bug, provide any errors**
You will get disconnected if you encounted a long array NBT tag, such as in an item.

**How can we reproduce it?**
1. Login on <1.12
2. Receive any packet with a long array tag (Mostly inventory (prevents player from logging in), maybe item, and containers)
3. Client disconnect

**Expected behaviour**
No disconnects

**Screenshots**

**ViaVersion Dump:**
https://dump.viaversion.com/f0bb2b33ef9dd6494d4591066d0965228e406b46a4d82b1e170da3c5b445f699

**Additional server info**
Bungeecord, other plugins are not relevant.

**Checklist** (mark with [X] to check)
- [x] I have included a ViaVersion dump
- [x] If applicable, I have included a paste (not a screenshot) of the error
- [x] I have tried a build from https://ci.viaversion.com/ and the issue still persists
- [x] I have looked at https://www.spigotmc.org/resources/viarewind-legacy-support.52924/ and it does not offer a fix for my problem

**IMPORTANT: Follow the Checklist or we can't reproduce your issue and your issue will be close**

**Comment by KennyTV** [comment]
Errors?

**Comment by Semisol** [comment]
Client side kick.

**Comment by Semisol** [comment]
@KennyTV Do this command on a 1.16 server with ViaBackwards
`give @s egg{testArray:[L;0,0]}`

**Comment by KennyTV** [comment]
Ah I see, thanks, 1.12 added long array nbt tags.

**Comment by Semisol** [comment]
> Ah I see, thanks, 1.12 added long array nbt tags.

Was talking about that. And yeah, because of that.
I have two solutions:
1. rewrite to an int array with double the size (requires just changing the size and type, can be done without modifying the packet size)
2. remove the tag (slowest implementation as it requires a packet resize imo)

**Comment by Semisol** [comment]
Thank you.
