### ISSUE TITLE
Error Unknown named sound

### ISSUE THREAD

**Issue by SrStronus** [ViaVersion/ViaBackwards#323]
Hello, I put custom sounds in the texture pack, but when they sound, I get that on the console and my minecraft crashes

WARN [ViaBackwards] Unknown named sound in 1.13->1.12 protocol: minecraft:block.portal.travel

That error comes up with almost all the sounds when I play them, it is not the texture pack because it served me before, but now that that sound sounds or another that I have put, the minecraft crashes

**ViaVersion Dump:**

https://dump.viaversion.com/4b92cbcea55a72a2a1324139584f895129a509c162156871ab4d77a4456d0729

Thanks...

**Comment by KennyTV** [comment]
Update to dev builds.
