### ISSUE TITLE
[Bug Report] Error produced on 1.12.2 clients when lightning strikes

### ISSUE THREAD

**Issue by Arrowheads844** [ViaVersion/ViaBackwards#324]
**Describe the bug, provide any errors**
https://paste.gg/p/anonymous/aab343a1e9e842b78cb1e43623188acb

**ViaVersion Dump:**
https://dump.viaversion.com/751d98dc16eee172eee8453f53cdc92f693594a8188615e185cc2d0816c768ce

**Additional server info**
Using Waterfall (1.16.5) and Paper (1.12.2)

**How can we reproduce it? Steps to reproduce the behavior:**
1. Login on 1.12.2 (or lower)
2. Type /Smite <player> or /Lightning or /Summon minecraft:lightning_bolt
3. Error is displayed in bungee console

**Checklist** 
- [x] I have included a ViaVersion dump
- [x]  If applicable, I have included a paste (not a screenshot) of the error
- [x]  I have tried a build from https://ci.viaversion.com/ and the issue still persists

**Comment by KennyTV** [comment]
Update to dev builds.

**Comment by Arrowheads844** [comment]
> Update to dev builds.

Where can I find the Dev builds?

**Comment by Arrowheads844** [comment]
> Update to dev builds.

When updating to Dev builds, ViaRewind will not enable.

**Comment by KennyTV** [comment]
Update ViaRewind to its dev builds. 😛
