### ISSUE TITLE
shows unavailable commands in tab-complete

### ISSUE THREAD

**Issue by lokha** [ViaVersion/ViaBackwards#328]
**Describe the bug, provide any errors**
my server is 1.16.5 paperspigot, ViaVersion-3.2.1, ViaBackwards-3.2.0

if I enter a command on client version 1.16.5, everything works as tab-complete should, the commands are only offered to which the player has rights.  
but if you go to the server on client version 1.12.2, then it will offer all server commands, including those for which the player has no rights

**How can we reproduce it?**
1. Login on 1.12.2
2. write `/` and press TAB
3.  you will see commands that you do not have permission to.

**Expected behaviour**
I expect not to display commands in the tab-complete output that the player does not have permission to.

**Screenshots**
![image](https://user-images.githubusercontent.com/32991511/107874323-6bb99500-6ec1-11eb-8245-d3273745f4e4.png)

**ViaVersion Dump:**
https://dump.viaversion.com/8b60192fff5e03d58fe09519496532ead17c68184892d9bf18c8b70229a2a29f

**Additional server info**
none, only Via  
no bungeecord

**Checklist**
- [x] I have included a ViaVersion dump
- [ ] If applicable, I have included a paste (not a screenshot) of the error
- [ ] I have tried a build from https://ci.viaversion.com/ and the issue still persists

**Comment by lokha** [comment]
I solved the problem for myself like this  
however, this will only work on paperspigot due to the use of AsyncPlayerSendSuggestionsEvent  
but it would be nice if such a fix would be built into viabackwards

```java
import com.destroystokyo.paper.event.brigadier.AsyncPlayerSendSuggestionsEvent;
import org.apache.commons.lang.StringUtils;
import org.bukkit.Bukkit;
import org.bukkit.command.Command;
import org.bukkit.event.EventHandler;
import org.bukkit.event.Listener;

public class Events implements Listener {
    @EventHandler
    public void on(AsyncPlayerSendSuggestionsEvent event) {
        String buffer = event.getBuffer();
        if (buffer.startsWith("/") && !buffer.contains(" ")) {
            event.getSuggestions().getList().removeIf(suggestion -> {
                String commandString = suggestion.getText();
                commandString = StringUtils.removeStart(commandString, "/");

                Command command = Bukkit.getCommandMap().getCommand(commandString);
                if (command == null) {
                    return false;
                }

                String tabPerm = command.getPermission();
                if (tabPerm == null) {
                    return false;
                }

                return !event.getPlayer().hasPermission(tabPerm);
            });
        }
    }
}
```

**Comment by KennyTV** [comment]
The problem is that we have no (easy/direct) means of doing permissions checks since we mostly work on a plain networking level, so a fix would likely be a Paper specific one as well with what you sent (tho I think Spigot should have a tab complete event as well, albeit sync?)

**Comment by lokha** [comment]
don't know if there is an alternative in spigot

**Comment by polonytzer** [comment]
> 
> 
> I solved the problem for myself like this
> however, this will only work on paperspigot due to the use of AsyncPlayerSendSuggestionsEvent
> but it would be nice if such a fix would be built into viabackwards
> 
> ```java
> import com.destroystokyo.paper.event.brigadier.AsyncPlayerSendSuggestionsEvent;
> import org.apache.commons.lang.StringUtils;
> import org.bukkit.Bukkit;
> import org.bukkit.command.Command;
> import org.bukkit.event.EventHandler;
> import org.bukkit.event.Listener;
> 
> public class Events implements Listener {
>     @EventHandler
>     public void on(AsyncPlayerSendSuggestionsEvent event) {
>         String buffer = event.getBuffer();
>         if (buffer.startsWith("/") && !buffer.contains(" ")) {
>             event.getSuggestions().getList().removeIf(suggestion -> {
>                 String commandString = suggestion.getText();
>                 commandString = StringUtils.removeStart(commandString, "/");
> 
>                 Command command = Bukkit.getCommandMap().getCommand(commandString);
>                 if (command == null) {
>                     return false;
>                 }
> 
>                 String tabPerm = command.getPermission();
>                 if (tabPerm == null) {
>                     return false;
>                 }
> 
>                 return !event.getPlayer().hasPermission(tabPerm);
>             });
>         }
>     }
> }
> ```

Since I have no knowledge in Java, would you mind to share the compiled JAR with the solution?

**Comment by lokha** [comment]
@polonytzer 

but keep in mind, it only works on the core of paperspigot

[plugins.zip](https://github.com/ViaVersion/ViaBackwards/files/6284886/plugins.zip)

**Comment by polonytzer** [comment]
> 
> 
> @polonytzer
> 
> but keep in mind, it only works on the core of paperspigot
> 
> [plugins.zip](https://github.com/ViaVersion/ViaBackwards/files/6284886/plugins.zip)

Thank you, I appreciate.
