### ISSUE TITLE
[Forge] [Suggestion] Store ignored Forge plugin message channels on none Forge servers

### ISSUE THREAD

**Issue by xXSchrandXx** [ViaVersion/ViaBackwards#329]
Hey,

is it possible to save the forge plugin message channels to a database so bungeecord doesn't have to check them everytime for none forge servers?

With great wishes

xXSchrandXx

**Comment by Xernium** [comment]
That’s outside the scope of Via*. This kind of register would be inconsistent and it doesn’t serve much of a purpose.
