### ISSUE TITLE
1.12.2 server gets console warning spam from ViaBackwards

### ISSUE THREAD

**Issue by AMDBartek** [ViaVersion/ViaBackwards#332]
**Describe the bug, provide any errors**
When running a development build of ViaBackwards on a 1.12.2 server the plugin spams the console with warnings.
https://paste.gg/p/anonymous/9d3bea987d0343f4ae1506d9de769877

**How can we reproduce it?**
1. Start a 1.12.2 server with ViaBackwards and required plugins
2. Check console

**Expected behaviour**
The server to start without any warnings.

**Screenshots**
![image](https://user-images.githubusercontent.com/46637209/108639572-34cd1b80-748d-11eb-8ba5-6f3700a300f7.png)

**ViaVersion Dump:**
https://dump.viaversion.com/b18e4ff66e8d276ec7d113613a61838abfaf3addf8b2f010d53b89cd385cc95f

**Additional server info**
No proxy
Server version: 1.12.2-R0.1-SNAPSHOT git-Paper-1618 (MC: 1.12.2)

**Checklist**
- [X] I have included a ViaVersion dump
- [X] If applicable, I have included a paste (not a screenshot) of the error
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists

**Comment by KennyTV** [comment]
ViaBackwards hasn't been updated to the latest snapshot (which the VV dev version already has mappings for).

**Comment by AMDBartek** [comment]
@KennyTV will this spam be removed when viabackwards updates?

**Comment by KennyTV** [comment]
Yes. For the meantime, you can just usean older ViaVersion dev version matching the ViaBackwards version
