### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by birthdates** [ViaVersion/ViaBackwards#335]
**Describe the bug, provide any errors**
A clear and concise description of what the bug is. Can you https://paste.gg/ the error?
There is no error. Just very bad GC
**How can we reproduce it?**

1. Start a 1.16.5 PaperSpigot server
2. Log on ~20 people on 1.8

**Expected behavior**
TPS stays stable and GC remains at normal times.

**Screenshots**
https://prnt.sc/109qgrx - GC
Memory analyzation:
https://prnt.sc/109qide
https://prnt.sc/109qh1d
https://spark.lucko.me/#qU6iF5wV60 - Spark heap summary
**ViaVersion Dump:**
- Type /viaversion dump, and put the link here.
https://dump.viaversion.com/b893c9aacbafa43a4af81a2d052b1b42251fd8efe0aa0af2df54654a8297410e
**Additional server info**
Do you use a proxy (eg. BungeeCord)? What software do you use and what plugins?
No proxy is being used.
**Checklist**
- [ X] I have included a ViaVersion dump
- [X ] If applicable, I have included a paste (not a screenshot) of the error
- [ X] I have tried a build from https://ci.viaversion.com/ and the issue still persists

**Comment by birthdates** [comment]
Update: has nothing to do with the world or any mishap on Minecraft's end

**Comment by KennyTV** [comment]
Hmm looking at client code, I can't find any code clearing stored chunks other than the chunk remove and respawn (+login), the only thing I could think of where those wouldn't be sent after also sending light data would be for neighbouring chunks at the very corners? So eh yeah, not sure how I would have to tackle this.

Not sure what tool you are using, what do the two numbers in the memory analyzation window stand for exactly / with units?

**Comment by birthdates** [comment]
> Hmm looking at client code, I can't find any code clearing stored chunks other than the chunk remove and respawn (+login), the only thing I could think of where those wouldn't be sent after also sending light data would be for neighbouring chunks at the very corners? So eh yeah, not sure how I would have to tackle this.
> 
> Not sure what tool you are using, what do the two numbers in the memory analyzation window stand for exactly / with units?

I believe those numbers are bytes. There are 10 of these huge heap users.
![image](https://user-images.githubusercontent.com/28874107/109438298-5717e980-79f7-11eb-83db-1a10c3a1597d.png)

**Comment by KennyTV** [comment]
Well uh that looks about right tbh; 10mb per player is exactly what a player on a server with a viewdistance of around 6-10 would have (depending on how many chunks with blocks there actually are), and since we have to cache *all* lighting for all currently loaded chunks in order for old clients to see any lighting at all due to major changes in how it was handled, it's not something we can do anything about - tho it doesn't look like it's all that much data anyways.

**Comment by birthdates** [comment]
> exactly

Ok well, if it thats the case, it isn't bytes. In the spark heap summary it says its taking ~800MB. From further digging
![image](https://user-images.githubusercontent.com/28874107/109438496-49169880-79f8-11eb-8d7b-14277a4ed436.png)
Is all skyLight is (2k entries of that)

**Comment by KennyTV** [comment]
Where does it say 800mb? In the spark I only see an entry with 900kb

**Comment by birthdates** [comment]
![image](https://user-images.githubusercontent.com/28874107/109438587-a6aae500-79f8-11eb-905d-68cd461a2248.png)
![image](https://user-images.githubusercontent.com/28874107/109438594-af9bb680-79f8-11eb-87c6-ba67099ad192.png)
Ok, I believe those are bytes but however, 100 players taking 1GB of ram is not right. (and it just goes up then garbage collections ~2GB)

**Comment by birthdates** [comment]
![image](https://user-images.githubusercontent.com/28874107/109438633-d659ed00-79f8-11eb-8d64-6413fe6f9958.png)
I've connected this byte[] to ViaVersion

**Comment by birthdates** [comment]
![image](https://user-images.githubusercontent.com/28874107/109438744-35b7fd00-79f9-11eb-8fd5-e7796e9130d9.png)
Also, 100 players taking ~1GB is 100MB per player.

**Comment by KennyTV** [comment]
A billion bytes (1GB)/100 is 10mb, tho not all players' UserConnections actually hold any data, but the ones that do also have more than just those light caches, coming to that 10mb average. Allowing clients that were made up to half a decade ago does come with its costs, that's unfortunately nothing we can do anything about 👀

**Comment by birthdates** [comment]
> A billion bytes (1GB)/100 is 10mb, tho not all players' UserConnections actually hold any data, but the ones that do also have more than just those light caches, coming to that 10mb average. Allowing clients that were made up to half a decade ago does come with its costs, that's unfortunately nothing we can do anything about 👀

Okay, that explains that. But what explains the insane GC?
![image](https://user-images.githubusercontent.com/28874107/109439016-b1ff1000-79fa-11eb-9e66-10db8127b9e5.png)

**Comment by KennyTV** [comment]
Likely because of all the chunk related data that has to be stored over the versions combined with a lot of players constantly loading new chunks / unloading old, and we have to store all of that individually per player. I *think* ProtocolSupport shouldn't suffer from this problem given it has a single transformers from the latest version to an other given version, instead of a pipeline from version to version like we do + it directly depends on Bukkit and can thus directly use its already present world data.

... so in a nutshell, that's just the disadvantage Via has that we accept in favor of the advantages, but PS might suit you better in your case.

**Comment by birthdates** [comment]
> Likely because of all the chunk related data that has to be stored over the versions combined with a lot of players constantly loading new chunks / unloading old, and we have to store all of that individually per player. I _think_ ProtocolSupport shouldn't suffer from this problem given it has a single transformers from the latest version to an other given version, instead of a pipeline from version to version like we do + it directly depends on Bukkit and can thus directly use its already present world data.
> 
> ... so in a nutshell, that's just the disadvantage Via has that we accept in favor of the advantages, but PS might suit you better in your case.

So would this occur if all chunks are preloaded?

**Comment by KennyTV** [comment]
No, it's based on what the server sends the client in their surroundings/view distance, not what chunks are actually loaded on the server in total.

**Comment by birthdates** [comment]
> No, it's based on what the server sends the client in their surroundings/view distance, not what chunks are actually loaded on the server in total.

Ok so, each player has ~10MB of data, and all that data is lighting?
