### ISSUE TITLE
Login crash with 1.9.4 version to 1.16.5 server !

### ISSUE THREAD

**Issue by Divalo** [ViaVersion/ViaBackwards#336]
**Describe the bug, provide any errors**
Crash while connecting to the server, or some time later. https://paste.helpch.at/ayabozamay.md

**How can we reproduce it?**
1. Login on 1.9.4

**Expected behaviour**
Crash while connecting to the server, or some time later.

**ViaVersion Dump**
https://dump.viaversion.com/2026ccedb06fd1d3e71013a15e5915a5b10fcfc8701d3e1449d86210409a952f

**Additional server info**
Velocity with BotSentry (ViaVersion and ViaBackwards are installed in spigot server (I'm using Tuinity so 1.16.5 version).

**Checklist**
Yes

**Comment by KennyTV** [comment]
Fixed in the latest dev build (once it's built).

**Comment by Divalo** [comment]
> Fixed in the latest dev build (once it's built).

Last Build on ViaVersion or ViaVersion-DEV in Jenkins ?

**Comment by KennyTV** [comment]
ViaBackwards, but you need both in order for them to work with each other.

**Comment by Divalo** [comment]
> ViaBackwards, but you need both in order for them to work with each other.

Yes but ViaBackwards or ViaBackwards-DEV in Jenkins ?

**Comment by KennyTV** [comment]
Dev
