### ISSUE TITLE
ViaBackwards Not Working

### ISSUE THREAD

**Issue by SeanAlkemade** [ViaVersion/ViaBackwards#337]
Hello there,

Im new to minecraft servers, I've just put in viaversion and it worked! But my viabackwards isn't working. It still says outdated client. The viabackwards client is up to date so I don't know what to do. I asked my host and they said nothings wrong so ask support.

Any info you may need?: 
Version: 1.12.2
Trying to play on: 1.8.9 Labymod (doesn't work with other versions to but idK)

**Comment by KennyTV** [comment]
Follow the issue template.

**Comment by SeanAlkemade** [comment]
What do you mean?

**Comment by Jo0001** [comment]
Create a new issue https://github.com/ViaVersion/ViaBackwards/issues/new?assignees=&labels=&template=bug_report.md and **fill it out instead of deleting the original content **
