### ISSUE TITLE
ViaBackwards not Working

### ISSUE THREAD

**Issue by SeanAlkemade** [ViaVersion/ViaBackwards#339]
**Describe the bug, provide any errors**
Im sorry if this is hard to understand I'm new. 
I want to be able to have ViaBackwardsPlugin, I have put it in my plugin folder with ViaVersion also (Viaversion works perfect).
I have asked my host (pebblehost) they found nothing wrong and told me to go to support. There are no errors in the console.

**How can we reproduce it?**
1. Look at viaversion dump?
2.  look for errors?
3.  idk I'm sorry.

**Expected behaviour**
I expected to have viabackwards work, by putting viaversion and viabackwards in the plugins folder and the fact that viaversion worked.

**Screenshots**
![maybe](https://user-images.githubusercontent.com/79937512/109704254-aea08b80-7b96-11eb-959a-21ce13bd9f2b.PNG)
Paste of the screenshot

**ViaVersion Dump:**
- Type /viaversion dump, and put the link here.
- https://dump.viaversion.com/80c5ebaaa57b16b7d09f8dc2aceb0ea892a86905d9bd80f3850e2c115254a82d
a paste of something that may help.
02.03 20:32:09 [Server] INFO Loading libraries, please wait...
02.03 20:32:15 [Server] INFO Starting minecraft server version 1.12.2
02.03 20:32:15 [Server] INFO Loading properties
02.03 20:32:15 [Server] INFO Default game type: SURVIVAL
02.03 20:32:15 [Server] INFO This server is running CraftBukkit version git-Spigot-79a30d7-acbc348 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
02.03 20:32:16 [Server] INFO Using 4 threads for Netty based IO
02.03 20:32:16 [Server] INFO Server Ping Player Sample Count: 12
02.03 20:32:16 [Server] INFO Debug logging is disabled
02.03 20:32:16 [Server] INFO Generating keypair
02.03 20:32:16 [Server] INFO Starting Minecraft server on 164.132.219.131:25586
02.03 20:32:16 [Server] INFO Using epoll channel type
02.03 20:32:17 [Server] INFO Set PluginClassLoader as parallel capable
02.03 20:32:17 [Server] INFO [WorldEdit] Loading WorldEdit v6.1.9;caf0ad9
02.03 20:32:17 [Server] INFO [ViaVersion] Loading ViaVersion v3.2.1
02.03 20:32:17 [Server] INFO [ViaVersion] ViaVersion 3.2.1 is now loaded, injecting!
02.03 20:32:18 [Server] INFO [ViaVersion] Loading 1.12 -> 1.13 mappings...
02.03 20:32:18 [Server] INFO [ViaVersion] Loading 1.13 -> 1.13.2 mappings...
02.03 20:32:18 [Server] INFO [ViaVersion] Loading 1.13.2 -> 1.14 mappings...
02.03 20:32:18 [Server] INFO [ViaVersion] Loading 1.14 -> 1.15 mappings...
02.03 20:32:18 [Server] INFO [ViaVersion] Loading 1.15 -> 1.16 mappings...
02.03 20:32:18 [Server] INFO [ViaVersion] Loading 1.16 -> 1.16.2 mappings...
02.03 20:32:18 [Server] INFO [ViaVersion] Loading block connection mappings ...
02.03 20:32:18 [Server] INFO [ViaBackwards] Loading ViaBackwards v3.2.0
02.03 20:32:18 [Server] INFO [Multiverse-Core] Loading Multiverse-Core v2.5.0-b727
02.03 20:32:18 [Server] INFO [WorldGuard] Loading WorldGuard v6.2.2-SNAPSHOT;8eeab68
02.03 20:32:18 [Server] INFO [LuckPerms] Loading LuckPerms v5.2.76
02.03 20:32:19 [Server] INFO [Essentials] Loading Essentials v2.18.2.0
02.03 20:32:19 [Server] INFO [EssentialsSpawn] Loading EssentialsSpawn v2.18.2.0
02.03 20:32:19 [Server] INFO [EssentialsChat] Loading EssentialsChat v2.18.2.0
02.03 20:32:19 [Server] INFO [Prison] Loading Prison v3.2.3
02.03 20:32:19 [Server] INFO [ViaBackwards] Enabling ViaBackwards v3.2.0
02.03 20:32:19 [Server] INFO [ViaBackwards] Loading translations...
02.03 20:32:19 [Server] INFO [ViaBackwards] Registering protocols...
02.03 20:32:20 [Server] INFO [ViaVersion] Loading 1.13 -> 1.12 mappings...
02.03 20:32:20 [Server] INFO [ViaVersion] Loading 1.13.2 -> 1.13 mappings...
02.03 20:32:20 [Server] INFO [ViaVersion] Loading 1.14 -> 1.13.2 mappings...
02.03 20:32:20 [Server] INFO [ViaVersion] Loading 1.15 -> 1.14 mappings...
02.03 20:32:20 [Server] INFO [ViaVersion] Loading 1.16 -> 1.15 mappings...
02.03 20:32:20 [Server] INFO [ViaVersion] Loading 1.16.2 -> 1.16 mappings...
02.03 20:32:20 [Server] INFO [LuckPerms] Enabling LuckPerms v5.2.76
02.03 20:32:20 [Server] INFO __    

**Additional server info**
I have a Spigot 1.12.2 server. Hosted by PebbleHost 5gm ram. I use the following plugins:
Worldedit, Viaversion, ViaBackwards, Multiverse-Core, Wolrdgaurd, Luckperms, Essentials, EssentailsSpawn, EssentailsChat, Prison

**Checklist**
- [x] I have included a ViaVersion dump
- [ sort of ] If applicable, I have included a paste (not a screenshot) of the error
- [ ] I have tried a build from https://ci.viaversion.com/ and the issue still persists

**Comment by KennyTV** [comment]
Download ViaRewind (from the ci or Spigot), it will allow 1.8 players to join your server - ViaBackwards alone only goes down to 1.9.

**Comment by SeanAlkemade** [comment]
OK ty
