### ISSUE TITLE
Invalid Entity ID

### ISSUE THREAD

**Issue by skw359** [ViaVersion/ViaBackwards#340]
**Describe the bug, provide any errors**
Whenever someone logs in through Velocity, this error occurs: https://pastebin.com/vAMWAKfS
Please note that the person does not need to be on a legacy MC client and that this affects Velocity's proxy only. 

**How can we reproduce it?**
1. Login on any MC client version (in this case, I was using 1.16.5 Optifine)
2. Watch the Velocity proxy
3. The errors happen. 

**Expected behaviour**
No errors

**Screenshots**
None applicable

**ViaVersion Dump:**
- Type /viaversion dump, and put the link here.
https://dump.viaversion.com/91705d279a4dfcf716b3c1d92e7d396163c105d241d802c0b243951a3d090398
I'm not sure if this is the Proxy or the actual server. 
**Additional server info**
I use Velocity (latest version) 
Plugins: buycraft, luckperms, nuvotifier, tcpshield, velocitystaffchat, viaversion, viabackwards, viarewind. 

**Checklist**
- [ ] I have included a ViaVersion dump
- [ ] If applicable, I have included a paste (not a screenshot) of the error
- [ ] I have tried a build from https://ci.viaversion.com/ and the issue still persists
- [ ] I hope I'm not dumb and missed something simple xd

**Comment by KennyTV** [comment]
Set `suppress-metadata-errors` to true in the ViaVersion config.yml, otherwise it also sounds like you have Via on both proxy and backend - it should only be on either one.

**Comment by skw359** [comment]
Alrighty, yeah I have via installed on both the proxy and backend - should I just have it installed on the proxy then?

**Comment by KennyTV** [comment]
Preferably on the the backend servers, but either one is fine.

**Comment by skw359** [comment]
Alrighty thank you very much for your time and efforts!
