### ISSUE TITLE
Hologram for  1.12.2 and lower doesn't have correct text

### ISSUE THREAD

**Issue by tomikcz987** [ViaVersion/ViaBackwards#341]
**Describe the bug, provide any errors**
Hologram from Gholo doesn't have correct text on 1.12.2 and lower
**How can we reproduce it?**
1. Login on 1.16.5 server with 1.12.2 and lower
2. look at hologram from Gholo plugin
3. text will 'Armor stand' or another (it depends on language of game )
![obrazek](https://user-images.githubusercontent.com/78663470/111034041-1e730980-8414-11eb-8dc5-a8c344390544.png)

**Expected behaviour**
This text
![obrazek](https://user-images.githubusercontent.com/78663470/111034053-292d9e80-8414-11eb-806c-d265b1ed4b92.png)

**ViaVersion Dump:**
https://dump.viaversion.com/c1de9b5a6a6e5233f51fe321a853e49348fed4bcc17f49402cffd68f545b53f9

**Additional server info**
Latest Yatopia behind bungee

**Checklist**
- [X] I have included a ViaVersion dump
- [ ] If applicable, I have included a paste (not a screenshot) of the error
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists

**Comment by KennyTV** [comment]
Try reproducing this on Paper without any other plugins (except for Via and the hologram plugin) please.

**Comment by tomikcz987** [comment]
I tried it on paper 1.16.5 (without bungee) and still
![obrazek](https://user-images.githubusercontent.com/78663470/111034908-0ef5bf80-8418-11eb-9d91-1e58cb0608bc.png)

**Comment by tomikcz987** [comment]
This bug is on ViaBackwards-dev build 272+ on build 271 hologram is normal
https://ci.viaversion.com/view/ViaBackwards/job/ViaBackwards-DEV/272/

**Comment by KennyTV** [comment]
Thank you for narrowing down the issue, I will try to see what can be done about it when I have time

**Comment by KennyTV** [comment]
Updating to the next ViaVersion (not VB) dev build will fix it, tho the hologram plugin has some *extremely* strange code. What caused this was it putting its text into translatable components instead of... text components, and that conversion had a little flaw.
