### ISSUE TITLE
cannot connect to server with 1.15 and 1.12

### ISSUE THREAD

**Issue by ROTOMEGA** [ViaVersion/ViaBackwards#342]
**Describe the bug, provide any errors**
when connecting to the server through bungeecord it gives me an  error

**How can we reproduce it?**
1. Login on 1.12'
2. error

**Expected behaviour**
I login into the server

**Screenshots**
![ViaBackwards error](https://user-images.githubusercontent.com/64898343/111069857-b5ed6080-84d7-11eb-8ebd-cfbbfbe63901.png)
https://paste.gg/p/anonymous/40588f40652d408e9f88afa274f85993

**ViaVersion Dump:**
https://dump.viaversion.com/4072f312a3a2d5c3a0460253ac56e52103fabb08e2ecffd4ce1ad6549098d40c

**Additional server info**
connected to bungeecord running both viaversion and viarewind, I can connect to the lobby with no errors, If I set my bungeecord to offline it works

**Checklist**
- [*] I have included a ViaVersion dump
- [*] If applicable, I have included a paste (not a screenshot) of the error
- [*] I have tried a build from https://ci.viaversion.com/ and the issue still persists

**Comment by KennyTV** [comment]
Try the ci dev builds, otherwise send the full error please.

**Comment by KennyTV** [comment]
Don't use Via on both proxy and backend, only one of them.

**Comment by ROTOMEGA** [comment]
> Don't use Via on both proxy and backend, only one of them.
I have it only on my proxy, the issue persists

> Try the ci dev builds, otherwise send the full error please.
where can I get them? (or, you mean the one from Jenkins?)

**Comment by KennyTV** [comment]
Yes, https://ci.viaversion.com/job/ViaVersion-DEV/ and https://ci.viaversion.com/view/ViaBackwards/job/ViaBackwards-DEV/

**Comment by ROTOMEGA** [comment]
after I installed these its loading terrain infinitely

**Comment by KennyTV** [comment]
Any errors with the dev builds (and did you make sure to use both ViaVersion and ViaBackwards -dev builds)? Also, it might be worth trying to put the Via plugins on your backend servers instead of the proxy then.

**Comment by KennyTV** [comment]
The infinite loading is now fixed with the latest -dev builds.
