### ISSUE TITLE
1.8 Clients crash with `readAddress(..) failed: Connection reset by peer`

### ISSUE THREAD

**Issue by Maroon28** [ViaVersion/ViaBackwards#352]
### '/viaversion dump' Output

https://dump.viaversion.com/d17063ca8152390937dd74ece97707b0ac06ab82441c0665ae88cf8e7d827340

### Console Error

```
NativeIoException: readAddress(..) failed: Connection reset by peer

That's literally all. 
```

### Bug Description

So, I've set up Viaversion, ViaBackwards, and ViaRewind on my 1.16.5 spigot server. Once I try connecting with 1.8.8 to that server, it gets weird from there. So the plugin works fine on my Lobby server, and I can connect to it normally, however, when I join the other server, the client is kicked displaying no errors at all. The only error I could find was on the bungeecord (waterfall) server, which is the one in the above field. I tried with ProtocolSupport, and it worked fine. 

### Steps to Reproduce

1. Install ViaVersion, Backwards, And Rewind on a 1.16.5 Paper server.
2. Connect to the server using a legacy version (1.8)
3. ???
4. Player crashes and sends an error in the bungeecord. 

I can't exactly give good steps, since I'm not too sure what's causing it myself. 

### Expected Behavior

The legacy players should be able to connect to the server without crashing.

### Additional Server Info

I use waterfall, with this list of plugins: Plugins (15): AntiBot, AntiVPN, BungeeHub, BuycraftX, CommandWhitelistBungee, DBVerifier, LuckPerms, NuVotifier, Parties, PartyAndFriends, RedirectPlus, ServerListPlus, ServerUtils, UltraStaffChat and nLogin

### Checklist

Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
I have included a ViaVersion dump.
If applicable, I have included a paste (**not a screenshot**) of the error.
I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by KennyTV** [comment]
Try -dev builds from the ci, otherwise open an issue on the ViaRewind issue tracker.

**Comment by Maroon28** [comment]
Oh, yeah. Good point xD I confused the plugins a bit, sorry about that! Opened the issue there instead!
