### ISSUE TITLE
Scoreboard issue

### ISSUE THREAD

**Issue by AggerTV** [ViaVersion/ViaBackwards#354]
### '/viaversion dump' Output

https://dump.viaversion.com/aa04e4cc3e4ae6a88d40058d97c0be4034ad70db9724e78c0f667aefd96dc763

### Console Error

```
none
```

### Bug Description

Scoreboards do not work on older versions of minecraft.
My server is on 1.16.5

What it looks like on 1.13.*-1.16.*:
https://gyazo.com/989a4b2fba22dc64735ad5aeb515e28f

What it looks like on 1.8.*-1.12.2
https://gyazo.com/b0210fb1cbdf3bb0f9e0d0bded71f7ae

### Steps to Reproduce

I'm not sure, I use featherboard for scoreboards, but the developer said this is an issue with all scoreboards

### Expected Behavior

The scoreboard should look the same on all versions, and the scoreboard should not cut off in the specified versions.

### Additional Server Info

I did try and install the latests successful dev builds of viaversion, viarewind and viabackwards, but the issue still persists.

### Checklist

Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
I have included a ViaVersion dump.
If applicable, I have included a paste (**not a screenshot**) of the error.
I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by KennyTV** [comment]
Old clients have strict length limitations, only way of displaying full/proper lines is for the scoreboard plugin itself to split their team names into prefix and suffix, since we would have to make possibly faulty assumptions.

**Comment by AggerTV** [comment]
Does that mean you can't fix the issue, or is it because you are unwilling to?

**Comment by KennyTV** [comment]
We could *work around it*, but that would result in creating other issues

**Comment by AggerTV** [comment]
Well, you also can't say this state of it know is acceptable? Isn't starting to fix it the best thing to do, even though you create new problems? I mean, how is the issue ever going to be fixed if you are unwilling to begin?

Also, I don't mean to be rude, I'm just really looking for a fix for this, as my server is planned to open within a month or so :)

**Comment by KennyTV** [comment]
If we work around (not fix, but *work around*) the all omnipresent client restriction of 16 characters in prefix and suffix, we would immediately have people complaining about the issues we just created, possibly even you yourself would be affected by bad tablist names. If there is a middle-ground way of doing it, we aren't aware of it. The gist of it is; if you want to use new features, use new versions (and unlimited team affixes simply aren't a thing with old clients).

**Comment by AggerTV** [comment]
I can inform you that I switched to using ProtocolSupport, and they have a fix for the issue, so something can be done that you don't know of. I just thought I would inform you that there is a fix (or workaround, whatever).

**Comment by KennyTV** [comment]
I'm aware of that, but as I said, while it fixes *your* issue, it will create an issue for others, so there's no workaround that works for everyone.

**Comment by IWolfZZ** [comment]
Please fix this issue, protocol support is old and buggy
