### ISSUE TITLE
can't load ViaBackwards

### ISSUE THREAD

**Issue by Dreeam-qwq** [ViaVersion/ViaBackwards#355]
### '/viaversion dump' Output

https://dump.viaversion.com/0dd0776a578d3e25c0f94445050a3c68462d4e051662cdef3ad463c736c67061

### Console Error

https://paste.gg/p/anonymous/ad18d258051d4a918c3d7ec9a09d6c5b

### Bug Description

can't load the Viabackwards dev build

### Steps to Reproduce

1. use the dev builds of the Viaversion, Viarewind and Viabackwards.
2. run server
3. see this error.

### Expected Behavior

just can't load this plugin and see the error.
when player use 1.8 to enter the server, proxy console shows 

```
[16:05:58 INFO]: [xxx|/ip:58240] <-> ServerConnector [lobby] has connected
[16:05:58 INFO]: [xxx|/ip:58240] <-> ServerConnector [lobby] has disconnected
[16:06:28 WARN]: [/ip:58240|xxx] -> UpstreamBridge - read timed out
[16:06:28 INFO]: [xxx] disconnected with: ReadTimeoutException : null
[16:06:28 INFO]: [/ip:58240|xxx] -> UpstreamBridge has disconnected
```

### Additional Server Info
proxy: waterfall
backend： paper 1.12.2 (have Via)

### Checklist

Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
I have included a ViaVersion dump.
If applicable, I have included a paste (**not a screenshot**) of the error.
I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by KennyTV** [comment]
Can't reproduce. Do you have a custom Paper version and does this also happen without other plugins?

**Comment by Dreeam-qwq** [comment]
so strange, after I reset the spigot.yml, this error will not happen

**Comment by Dreeam-qwq** [comment]
> Can't reproduce. Do you have a custom Paper version and does this also happen without other plugins?

I set `late bind: true` in the `spigot.yml`, then the error happen, I don't know why.
