### ISSUE TITLE
Bungeecord ViaBackwards Warning spam

### ISSUE THREAD

**Issue by Whqcky** [ViaVersion/ViaBackwards#360]
### '/viaversion dump' Output

https://dump.viaversion.com/419ba4b239a2b7cb178c17fed6641ae89f2397130d07dff461e233e3df1ed078

### Console Error

```
https://paste.gg/p/anonymous/b113d15b43e74657b0d54920d61abaa9
```

### Bug Description

This problem started after i restarted my server i didn't noticed it until i tried to /gamemode creative when i open the inventory it just disconnected me from the server without reason. 

### Steps to Reproduce

1. Login with 1.16.5
2. gamemode creative
3. Kicked without reason from the server

### Expected Behavior

Spam in the console and when i go gmc it just kick me out

### Additional Server Info

I use this plugin on my Bungeecord and the problem is only on my Survival server 

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by KennyTV** [comment]
We can't help you if you don't provide full logs (that log message has nothing to do with a kick). In any case, update to -dev builds on the ci before opening a new issue.
