### ISSUE TITLE
Wont let 1.9 - 1.16 clients join

### ISSUE THREAD

**Issue by Russhvith** [ViaVersion/ViaBackwards#361]
### '/viaversion dump' Output

https://dump.viaversion.com/b7ad34f5cbb78bce8bdeaa8a18edcec140443e762992f5b69e6c56c8a92762ad

### Console Error

Matty_candlin lost connection: Internal Exception: java.io.IOException: Error while write(...): Broken pipe

### Bug Description

Idk what is this bug but it wont work properly when we try to join with 1.16 - 1.9 it gives this error screen 
![image](https://user-images.githubusercontent.com/62888270/120059314-6518ed00-c06e-11eb-81b2-e02e4953e97b.png)

### Steps to Reproduce

1. Join the server on a 1.16 client with this plugins
2. It gives this error

### Expected Behavior

Server wont allow 1.16.x - 1.9.x clients to join only 1.8 cause server is running on that.

### Additional Server Info

Nope.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by KennyTV** [comment]
Update to -DEV builds on the ci.
