### ISSUE TITLE
Console spam

### ISSUE THREAD

**Issue by RealisticThreat** [ViaVersion/ViaBackwards#363]
### '/viaversion dump' Output

https://dump.viaversion.com/13e511e9dfafe6ae8a82fd39ab9ae934eebeefd1eb3124480c94ac2340bac06d

### Console Error

https://pastebin.com/xnygsZQj

### Bug Description

My console is being flooded with these ViaRewind WARN.

### Steps to Reproduce

It only happen on my server.

### Expected Behavior

Players could not see the server resource pack if joined under the ViaRewind versions.

### Additional Server Info

I use Tuinity 1.16.5, Java 11

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by creeper123123321** [comment]
Try -DEV builds
