### ISSUE TITLE
Errors with Spigot 1.17

### ISSUE THREAD

**Issue by x9nico** [ViaVersion/ViaBackwards#369]
### '/viaversion dump' Output

https://dump.viaversion.com/832d93e3715321972c28f55cf58bc524cedccc8f15c6ccb13226607e6f7e6818

### Console Error

```
Put the paste.gg link or text here.
```
https://pastebin.com/r7eSW8eu

### Bug Description

When I'm loading ViaBackwards on Spigot 1.17, it provides the errors.

### Steps to Reproduce

1. Upload ViaBackwards on 1.17
2. Start your server
3. And then, you have the errors

### Expected Behavior

The plugin should load correctly

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by KennyTV** [comment]
Please don't report plugin issues on an alpha build of Paper.
