### ISSUE TITLE
Error getting spammed in console - [ViaVersion] An error occurred in metadata handler EntityPackets1_13 for untracked entity type: Metadata{id=18, metaType=VillagerData, value=com.viaversion.viaversion.api.minecraft.VillagerData@61e2801}

### ISSUE THREAD

**Issue by AlecMcQuarrie** [ViaVersion/ViaBackwards#370]
### '/viaversion dump' Output

https://dump.viaversion.com/f763e44ea9ca66fb87a6a7eac92a2871032e481ec0b031eae1a5e561f5fb6bb4

### Console Error

[11:11:44 WARN]: [ViaBackwards] New 1.14 metadata was not handled: Metadata{id=18, metaType=VillagerData, value=com.viaversion.viaversion.api.minecraft.VillagerData@61e2801} entity: null
[11:11:44 ERROR]: [ViaVersion] An error occurred in metadata handler EntityPackets1_13 for untracked entity type: Metadata{id=18, metaType=VillagerData, value=com.viaversion.viaversion.api.minecraft.VillagerData@61e2801}
[11:11:44 ERROR]: [ViaVersion] Full metadata: Metadata{id=0, metaType=Byte, value=0}

### Bug Description

Error getting spammed in console starting with ViaBackwards having a problem with some villagerdata

### Steps to Reproduce

Not entirely sure how to reproduce it, but I assume someone on the server is behind a couple of versions and is using a villager.

### Expected Behavior

There shouldn't be an error like this getting spammed in my console. My server has also been crashing a lot recently, and it has been because of ViaBackwards. I have used a new dev version of viabackwards to try to fix things, but i am still crashing and getting errors.

### Additional Server Info

I am using Purpur

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by AlecMcQuarrie** [comment]
![Screen Shot 2021-06-16 at 11 19 16 AM](https://user-images.githubusercontent.com/42359278/122246642-b7427680-ce94-11eb-9008-b7e62ebd4276.png)

**Comment by KennyTV** [comment]
Likely your npc plugin being bad. Removed the first warning, for the second we need the full error to do anything about.
