### ISSUE TITLE
ViaBackwards fails to start on Velocity

### ISSUE THREAD

**Issue by benfoster04** [ViaVersion/ViaBackwards#371]
### '/viaversion dump' Output

https://dump.viaversion.com/e0169d119ab8869fe29405ef3b74f3d6e1d7556b2d72a5992bdd1be08e9850d6

### Console Error

```
https://paste.gg/p/anonymous/282793337a6b4400ae4996db180210f4
```

### Bug Description

Starting the Velocity proxy server with all Via* up-to-date on stable (4.0.1, 2.0.1) causes a stacktrace to appear with ViaBackwards failing to load. Evidenced by the ViaBackwards plugin config folder not being created. This is also evidenced by clients sub 1.13 being unable to join.

### Steps to Reproduce

1. Install all stable builds on an up-to-date Velocity server
2. Attempt to join on a sub 1.13 client (eg. 1.12.2)
3. Observe disconnect message:
Failed to connect to the server
This server is only compatible with 1.13 and above.

### Expected Behavior

Clients on versions sub 1.13 should be able to join, along with no error in console.

### Additional Server Info

I'm running Velocity 1.1.8 Stable, with the following plugins:

- Anvil for Velocity 0.3.0
- BuyCraftX for Velocity 12.0.7
- Catalyst for Velocity 0.3.2
- LuckPerms 5.3.30
- NuVotifier 2.7.2
- Private Proxy Plugin that does not do any packet modification
- ViaBackwards 4.0.1-SNAPSHOT
- ViaRewind 2.0.1-SNAPSHOT
- ViaVersion 4.0.1-SNAPSHOT

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by FormallyMyles** [comment]
I'd suggest moving ViaVersion to your backend servers, the new ViaVersion Velocity injector is designed for velocity 3.0.0 which you could use builds for but i'd recommend just using Via on backend services.

**Comment by benfoster04** [comment]
Apologies, I understand the significant stability improvements as a result of moving Via* to backend over the proxy, but it is required to remain on the proxy so that secure player information forwarding can be upheld between the nodes without the need for additional plugins which prevent unauthorised access to backend servers. If your recommendation is to update Velocity to v3, then I will try that?

**Comment by benfoster04** [comment]
@FormallyMyles Apologies for the bump for this, but I need this to work in the configuration it's set up as.

**Comment by FormallyMyles** [comment]
If you were still stuck on this then Velocity 3.0.0 would be the option to take.
