### ISSUE TITLE
[ViaBackwards]: Unknown named sound in 1.13->1.12 protocol: block.anvil.hit

### ISSUE THREAD

**Issue by craciu25yt** [ViaVersion/ViaBackwards#373]
### '/viaversion dump' Output

https://dump.viaversion.com/816d86bfcf4555c134ce3c905fcc99babac762a4c83c5ee37a93f57a2e92b110

### Console Error

```
Put the paste.gg link or text here.
```
[ViaBackwards]: Unknown named sound in 1.13->1.12 protocol: block.anvil.hit

### Bug Description

[ViaBackwards]: Unknown named sound in 1.13->1.12 protocol: block.anvil.hit

### Steps to Reproduce

[ViaBackwards]: Unknown named sound in 1.13->1.12 protocol: block.anvil.hit

### Expected Behavior

[ViaBackwards]: Unknown named sound in 1.13->1.12 protocol: block.anvil.hit

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by KennyTV** [comment]
#326

**Comment by craciu25yt** [comment]
uncofirmed for what?
