### ISSUE TITLE
ViaBackwards creates a second folder under config's name.

### ISSUE THREAD

**Issue by Kichura** [ViaVersion/ViaBackwards#374]
### '/viaversion dump' Output

Fabric's dump: https://dump.viaversion.com/ab147bca6bdc0726b4ed42de46a0836460222ee6cc5fb60fe17f9cb208dde16a

Spigot's dump: https://dump.viaversion.com/b03f3d97afa759af9114a5a3ef623793b8d429e1cee16d333011bf11d5f20a71

### Console Error

(No errors were created on both server-sides)

### Bug Description

When using ViaFabric and ViaBackwards on the fabric server, Viewing the ViaBackwards shows a second folder under the config's name; Inside that folder contains the same config's name which isn't present in the bukkit variant.

Fabric:
![fabric](https://user-images.githubusercontent.com/68134602/122642963-57a2d000-d10d-11eb-9d2e-5b4655a1d32c.PNG)

Bukkit:
![bukkit](https://user-images.githubusercontent.com/68134602/122642974-65f0ec00-d10d-11eb-904b-719250aab9d2.PNG)

### Steps to Reproduce

1. Obtain both a copy of bukkit and fabric respectively as server software,
2. Add both viaversion/viafabric and viabackwards to each server,
3. Run both servers,
4. Check the viabackwards folder, it should end up causing a difference.

### Expected Behavior

When using ViaFabric and ViaBackwards on the fabric server, it is normally expected that the config.yml will appear in the respective folder such as ViaBackwards\config.yml.

### Additional Server Info

The bukkit server is a 1.16.5 spigot dummy server used for testing (Mainly aternos), Meanwhile the fabric server is running on a fabric dummy server (0.11.6).

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [x] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by KennyTV** [comment]
https://github.com/ViaVersion/ViaBackwards/commit/7013ed8acfb08d739fd46e212127290524d4b0cc

**Comment by Kichura** [comment]
Update on this issue: Seems to persist in velocity aswell. (Not sure if it applies to Bungeecord/Waterfall though)
