### ISSUE TITLE
When I join 1.17 server with 1.16.5 My chunks would not load

### ISSUE THREAD

**Issue by Dibya07** [ViaVersion/ViaBackwards#379]
### '/viaversion dump' Output

https://dump.viaversion.com/6fe59c517ea1eedd688d5ae7ba83a0da45b9ff16cb63708f10e5d0ac155ff5c8

### Console Error

```
Put the paste.gg link or text here.
```

### Bug Description

**When I login in a 1.17 paper/bukkit server with my 1.16.5 (optifine) the chunks would not load till I place or break one block in each of the chunks but it also disappears in few minutes. However, I can still hear the sound of entities (like footsteps, villager sounds, zombie groans etc.) and interact with the entities and other player of the server.**

### Steps to Reproduce

1) Make a 1.17 paper/bukkit server with viaversion&viabackwards 4.0
2) Login in the server with your 1.16.5 version(I used optifine).
3) you will be able to login and can see the problem occurring

### Expected Behavior

Chunks and blocks should be loaded like it happens in any 1.16.5 server.

### Additional Server Info

I dont use any proxy. I use paer/bukkit 1.17 with viaversion-viabackwards 4.0

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by KennyTV** [comment]
Try with a Vanilla client/without OptiFine please.

**Comment by Dibya07** [comment]
> Try with a Vanilla client/without OptiFine please. Also note that Paper 1.17 itself also still has some chunk loading issues.

Thanks It worked !
