### ISSUE TITLE
"Unknown Named Sound" check false-positives on custom sounds

### ISSUE THREAD

**Issue by NathanWolf** [ViaVersion/ViaBackwards#380]
### '/viaversion dump' Output

https://dump.viaversion.com/c303b0b3819b85502586c3a02d2752d2e14a160969c5400a71fbeebbc1f33cde

### Console Error

```
[13:11:02 WARN]: [ViaBackwards] Unknown named sound in 1.13->1.12 protocol: minecraft:magic.zap
```

### Bug Description

Plugins that play custom sounds from resource packs will spam the console with warnings about the sound being unrecognized. 

Is there a way to disable this check via configs?

### Steps to Reproduce

Use any plugin that uses custom sounds. My plugin (Magic) was reported to be console-spamming, any time a spell is cast that plays a custom sound.

https://www.spigotmc.org/resources/magic.1056/

### Expected Behavior

I understand this check is nice to have for development purposes, but I imagine there are many plugins out there that use custom sounds. This should not cause such log spam.

Perhaps the check should be off by default, but if not then I think server owners should get an option to turn it off, if such an option does not exist already.

### Additional Server Info

The Magic plugin from here: https://www.spigotmc.org/resources/magic.1056/

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by kennytv** [comment]
You can enable `suppress-conversion-warnings` in the ViaVersion config to hide those warnings.

**Comment by NathanWolf** [comment]
Whoops, thank you, sorry for wasting your time!

**Comment by kennytv** [comment]
No worries. We know this obviously causes "wrong" warnings for custom sounds, but is necessary for us to identify missing/wrong mappings for existing sounds.
