### ISSUE TITLE
Entities disappear after respawning

### ISSUE THREAD

**Issue by Valtn** [ViaVersion/ViaBackwards#381]
### '/viaversion dump' Output

https://dump.viaversion.com/044d30621dc1a56c3d575544f2e111b31e9ecd0b4d01bb65e4df03e664da7b0a

### Console Error

No console errors.

### Bug Description

Entities disappear after respawning.

### Steps to Reproduce

1. Join a `1.16.5` (latest) server with client version `1.12.2` or `1.9.4`.
![image](https://user-images.githubusercontent.com/19395782/124199045-6e034100-daa8-11eb-87be-bbed864894c9.png)

1. Die (`/kill <yourself>` can do the trick if you have no-one to kill you).
![image](https://user-images.githubusercontent.com/19395782/124198995-5330cc80-daa8-11eb-8966-ce6ca379a1fb.png)

1. Respawn and all entities (including players) disappear after less than 1 second.
![image](https://user-images.githubusercontent.com/19395782/124199102-8d9a6980-daa8-11eb-8064-a18b6c6b6490.png)

### Expected Behavior

After respawn entities should not disappear.

### Additional Server Info

Works fine with spigotmc.org releases:
```
ViaVersion-3.2.1.jar
ViaBackwards-3.2.0.jar
```

Breaks with any version >=4.0.0, I've tried:
```
ViaVersion 4.0.0 (spigotmc.org release)
ViaBackwards 4.0.0 (spigotmc.org release)

ViaVersion-4.0.1-SNAPSHOT.jar #529
ViaBackwards-4.0.1-SNAPSHOT.jar #220

ViaVersion-4.0.1-1.17.1-rc1-SNAPSHOT.jar #575
ViaBackwards-4.0.1-1.17.1-rc1-SNAPSHOT.jar #334
```

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by kennytv** [comment]
Are you using client mods (like OptiFine)?

**Comment by Valtn** [comment]
@kennytv Same issue while not using client mods. Entities (including players) disappear until you rejoin the server.

**Comment by kennytv** [comment]
Fixed in -dev builds... A bit of a dirty fix for now, but it works:tm:

**Comment by Valtn** [comment]
It works! And I just noticed that it also respects the `doImmediateRespawn` gamerule now. Thank you!

Tested with MC versions 1.9.4 and 1.12.2 the following builds:
- ViaVersion-DEV `#575`
- ViaBackwards-DEV `#336`
