### ISSUE TITLE
Particles (and possibly armor stands) cause players to time out randomly

### ISSUE THREAD

**Issue by xph11** [ViaVersion/ViaBackwards#383]
### '/viaversion dump' Output

https://dump.viaversion.com/6953d3b7434b267121dcfa9c6335acda97118f7dd6b42356bb6dd6f2fdea5138

### Console Error

No error, simply says 'player disconnected'. For players it shows 'timed out'.

### Bug Description

Whenever players are in proximity of particles (and possibly armor stands, gotta double check that), the time out.

### Steps to Reproduce

Just be in proximity of particles.

### Expected Behavior

Not time out.

### Additional Server Info

Happens on all server versions, also tried without plugins at all, both on spigot side and proxy side. tried 3 different machines.

### Checklist

- [x] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by kennytv** [comment]
Not a Via issue.
