### ISSUE TITLE
1.17.1 -> 1.17 Outdated error

### ISSUE THREAD

**Issue by DillWhipper** [ViaVersion/ViaBackwards#384]
### '/viaversion dump' Output

https://dump.viaversion.com/eb068a00a7cc9c2e62943f85dd00c7adf58664cc2441b652206915a832a3b82a

### Console Error

```
Put the paste.gg link or text here.
```
N/A

### Bug Description

I try to join a 1.17.1 server on 1.17  and it says outdated.

### Steps to Reproduce

Play a 1.17.1 server with viarewind and viaversion on 1.17 Optifine - get error message.

### Expected Behavior

I expected it to let me play.

### Additional Server Info

Viaversion and Viarewind were working fine until i updated them for 1.17.1.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by TDMidkwhatisxd** [comment]
I get same too, why closed unconfirmed -.-

**Comment by kennytv** [comment]
Because that's an issue on your side (bad setup, outdated plugins, or outdated Bunge)

**Comment by TDMidkwhatisxd** [comment]
everything is latest, and i get same issue too

**Comment by kennytv** [comment]
Definitely not; as said, you can join our Discord for more help with setup issues.
