### ISSUE TITLE
1.13 -> 1.12 teleport messages

### ISSUE THREAD

**Issue by JustLonelyy** [ViaVersion/ViaBackwards#385]
### '/viaversion dump' Output

https://dump.viaversion.com/ec55b47bdad0e476f8f7a59d249c65c7f4b464bf812ef00878177674d19e9356

### Console Error

...

### Bug Description

When i wanted to teleport to a location with cords i got this weird message instead of teleported to that location
![image](https://user-images.githubusercontent.com/85992155/124957054-e54b4e80-e02d-11eb-90ce-d39e86c0faae.png)

### Steps to Reproduce

...

### Expected Behavior

...

### Additional Server Info

Server Version 1.13.2 paper

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by kennytv** [comment]
Related to https://github.com/ViaVersion/ViaBackwards/issues/375
