### ISSUE TITLE
1.16.1 wrong metadata translation

### ISSUE THREAD

**Issue by RaphiMC** [ViaVersion/ViaBackwards#388]
### '/viaversion dump' Output

https://dump.viaversion.com/153df901793b41ee5a4d0d3d6379e456aea97ab10f43765e1463b90f1c35201c

### Bug Description

When dropping oak leaves they appear as sandstone. Also happens with many other blocks.
Client: Fabric 1.14.4
Server: Spigot 1.16.1

### Steps to Reproduce

See bug descrpition

### Expected Behavior

Dropped items should be translated correctly

### Additional Server Info

No plugins on the testserver

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by kennytv** [comment]
You're outdated.
