### ISSUE TITLE
Inventory desync issues

### ISSUE THREAD

**Issue by compieter-gh** [ViaVersion/ViaBackwards#389]
### '/viaversion dump' Output

https://dump.viaversion.com/2292498dbe3a81ee107fbab916325e9fabc4c32ea5a4a83a225489db115cf432

### Console Error

```
None
```

### Bug Description

When moving items in inventory's it duplicates sometimes (ghost items). And it's quite annoying if i need to provide anything more to fix this say so.

### Steps to Reproduce

Login with a client lower than 1.17 (as stated in the readme)
move items in ur inventory 
and it will sometimes duplicate.

### Expected Behavior

No ghost items.

### Additional Server Info

https://www.youtube.com/watch?v=t9EdKSdPJgc
https://streamable.com/i6ijtd

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by AMDBartek** [comment]
Also having a similar issue.

**Comment by JHarris12345** [comment]
I too have this issue. It is when an inventory cancels the inventory move event, it appears to duplicate on the 2nd click. The "duplicated" ghost item can be moved around, placed in containers and used / interacted with until a relog where it will then dissapear. Here is a gif below. Notice the first click of the diamond sword is cancelled, the 2nd one is where the glitch occurs:

https://gyazo.com/960aa6a37f19f81a2873b9534c442492

**Comment by BredyAK** [comment]
same issue, fix this please, please...

**Comment by ComPieter-1** [comment]
Bump, Is this an easy thing to fix or is this gonna be an complicated issue that needs a lot off debugging?

**Comment by JHarris12345** [comment]
I believe this only happens if you have ViaVersion installed on your bungee. Try deleting that

**Comment by etayl221** [comment]
> 
> 
> I believe this only happens if you have ViaVersion installed on your bungee. Try deleting that

Nope, i do not have it installed on bungee and it's happening to me on versions below 1.16.5 (server version 1.17)

**Comment by nolberh2** [comment]
Hello, how long will it take to solve this problem? 
It is currently unplayable

**Comment by JHarris12345** [comment]
Delete via version from bungee @nolberh2 OR update your bungee

**Comment by nolberh2** [comment]
> Elimina a través de la versión de bungee @ nolberh2 O actualiza tu bungee

I don't have viaversion on my bungee and it is up to date :/

**Comment by JHarris12345** [comment]
What via versions are you using and what spigot

**Comment by nolberh2** [comment]
4.1.2 and purpur

**Comment by JHarris12345** [comment]
What version of purpur

**Comment by JHarris12345** [comment]
And what version of bungee / fork?

**Comment by nolberh2** [comment]
> And what version of bungee / fork?

waterfall #471

**Comment by JHarris12345** [comment]
What client do you use / version

**Comment by nolberh2** [comment]
> What client do you use / version

Vanilla 1.16.5 (server with viabackwards)

**Comment by buzzcoding** [comment]
Here is another video ([From jakasNazwa#8472](https://discord.com/channels/316206679014244363/316208160232701955/921185366017454111)):
[https://media.discordapp.net/attachments/783431038625382510/921185125230866532/edxvfd.mp4](https://media.discordapp.net/attachments/783431038625382510/921185125230866532/edxvfd.mp4)

**Comment by ComPieter-1** [comment]
Is there gonna be a fix for this?
Or is there more info needed?

**Comment by Firosee** [comment]
It lets people actually duplicate items aswell, check out this video as an example: https://gyazo.com/a71c5e04786387c2ce4b0baab19f151d

Here i am showcasing the inventory glitch, moving the item in my inventory where i can then sell the item on an auction house, where people can buy those items which should not be accessable. - thus rendering these effected versions unusable. 

This really needs to be fixed soon.

**Comment by kennytv** [comment]
No it doesn't; creative clients have full control over their inventory and the server accepts whatever the client says it has.

**Comment by Firosee** [comment]
Okay so i tried out of creative and i couldnt replicate it, so i suppose thats somewhat good news. Apologies for the potential gas lighting there.

**Comment by Firosee** [comment]
Do we have any idea on when a fix will be made though, or is it something thats not going to be fixed anytime soon and we/i should look into switching to a version which isnt 1.17?

**Comment by mercury55554** [comment]
> Okay so i tried out of creative and i couldnt replicate it, so i suppose thats somewhat good news. Apologies for the potential gas lighting there.

so did you find the problem and fix it? when is the update?

**Comment by Firosee** [comment]
> > Okay so i tried out of creative and i couldnt replicate it, so i suppose thats somewhat good news. Apologies for the potential gas lighting there.
> 
> so did you find the problem and fix it? when is the update?

It’s not an issue our end it’s an issue with the developers, they said that it will be fixed *eventually* but this has been an issue since august 2021, so I wouldn’t keep your hopes high.

**Comment by LaivyTLife** [comment]
sorry for the bumping... The devs will notice us here when fix it? in that case, i will subscribe the issue to receive notifications to be alert

**Comment by kennytv** [comment]
Yes, this issue will be closed when it's fixed.

**Comment by Firosee** [comment]
Has anyone found any temporary or permanent fixes for this in the meantime?

**Comment by Firosee** [comment]
Has any other progress been made on this?

**Comment by kennytv** [comment]
I tried fixing it on a packet level/without copy pasting a whole bunch of Vanilla code and failed miserably 눈_눈

**Comment by compieter-gh** [comment]
Wish i knew java ;-;

**Comment by Firosee** [comment]
> I tried fixing it on a packet level/without copy pasting a whole bunch of Vanilla code and failed miserably 눈_눈

Does this mean its unlikely it will ever be fixed, atleast sometime soon?

**Comment by PZSleezi** [comment]
> Has anyone found any temporary or permanent fixes for this in the meantime?

I download the latest Jenkins build of ProtocolSupport and I'm using it w/ ViaVersion and the problem went away for me

**Comment by compieter-gh** [comment]
> > Has anyone found any temporary or permanent fixes for this in the meantime?
> 
> I download the latest Jenkins build of ProtocolSupport and I'm using it w/ ViaVersion and the problem went away for me

Won't work on proxy side though and by doing this ur also throwing the options out the window of customization like version selection without adding more plugins.

And there more downsides too this option i find than just using viaversion plugins like the chests are enderchest and more i probably didnt mention.

If ur using this for a hub server it probably would be just fine but if for Survival, Anarchy or any other gamemode i kinda find that deal breaking.

**Comment by Firosee** [comment]
I am too currently using viaversion with protocolsupport as there is literally no other option (other than downgrading but having just updated all my custom plugins over to 1.17, i dont want to have to revert). Has anyone had any success using viaversion and its addons on the proxy instead of the main servers, does this work? No offence to the protocolsupport developer but it just isnt as good as viaversion to me.

**Comment by buzzcoding** [comment]
For the chests changing to ender chests with ProtocolSupport, use ProtocolSupportLegacyChest: [https://www.spigotmc.org/resources/unofficial-protocolsupportlegacychest.81307/](https://www.spigotmc.org/resources/unofficial-protocolsupportlegacychest.81307/)

**Comment by HowardZHY** [comment]
ghost item is very common when using ViaForge 1.8.9/1.12.2 on 1.13+ servers

**Comment by luapascoal** [comment]
@kennytv in 1.8 this error persists.

**Comment by LBoomsky** [comment]
issue still is issue 🥺
