### ISSUE TITLE
Make block/item remappings configurable

### ISSUE THREAD

**Issue by Roadhog360** [ViaVersion/ViaBackwards#39]
Hey. I love ViaBackwards, and I have a request. Could there be a feature to remove the version number for backported blocks? I'm sure my players know concrete is from 1.12, and Observers are from 1.11, and so on.
It looks weird to me, so either a rename config or an overall option to turn it off would work. Please consider. Thank you.

Could you please also change Magma Block from Hardened Clay to Red Sandstone? Red Sandstone is almost identical to Magma Block as far as mine time goes.

Another suggestion would be an /advancements command on a 1.12 server, so older clients can view their advancements. (The achievement menu is completely broken on a 1.12 server if running 1.11 or below)

**Comment by KennyTV** [comment]
Better late than never 🐋
