### ISSUE TITLE
Crash on 1.8.9

### ISSUE THREAD

**Issue by bpx573** [ViaVersion/ViaBackwards#390]
### '/viaversion dump' Output

https://pastebin.com/Eq7kekPu

### Console Error

```
Put the paste.gg link or text here.
```
03.08 12:09:03 [Server] INFO Debug: Login: BarryMcLarry (21049489-10ed-4eda-8a79-a3be85747689)
03.08 12:09:03 [Disconnect] User BarryMcLarry has disconnected, reason: Disconnected
03.08 12:09:03 [Server] INFO Debug: Logout: BarryMcLarry (21049489-10ed-4eda-8a79-a3be85747689)

I got limited on pastes sorry. I tried this with only the required plugins.

### Bug Description

I crash as soon as I enter the server only on version 1.8.9

PC crash log.

https://pastebin.com/sbqSYge1

### Steps to Reproduce

1: Log in with client version 1.8.9 only that version not other 1.8.x versions.

### Expected Behavior

I should just be able to log in.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by kennytv** [comment]
We don't support Yatopia. Nice try tho.

**Comment by kennytv** [comment]
Stop re-pasting dump contents and use the correct issue tracker at https://github.com/ViaVersion/ViaRewind/issues
