### ISSUE TITLE
Invisible players on Paper 1.16.5

### ISSUE THREAD

**Issue by CatCoderr** [ViaVersion/ViaBackwards#393]
### '/viaversion dump' Output

https://dump.viaversion.com/3ca83c345b7984daa9e1013c96bfd43e71c5bf8bb290d839aed1365f331697ce

### Bug Description

Players who play from Minecraft 1.12.2 version periodically encounter a visual bug - they cannot see other players. The problem is solved by the combination F3 + A.
In the rest of the players who play on version 1.16.5, everything works fine.

Detailed video: https://www.dropbox.com/s/ccx8jkpkadbj5uv/%D0%97%D0%B0%D0%BF%D0%B8%D1%81%D1%8C%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202021-08-15%20%D0%B2%2013.58.47.mov?dl=0

### Steps to Reproduce

This bug occurs due to circumstances completely incomprehensible to me, by accident. Therefore, I do not know how exactly it can be reproduced.

UPD: Perhaps the bug happens precisely when teleporting players to a long distance.
UPD: Possible related bug https://www.spigotmc.org/threads/i-need-help.513339/

### Expected Behavior

Players must see each other.

### Additional Server Info

I am using waterfall as a proxy, no plugins that affect the protocol in any way.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by Jo0001** [comment]
Can you test it with just the latest Via (from  https://ci.viaversion.com/ )installed?

**Comment by CatCoderr** [comment]
> Can you test it with just the latest Via (from https://ci.viaversion.com/ )installed?

Installed the latest Via builds. So far, no issues have been detected.

**Comment by kennytv** [comment]
If you encounter them again, let us know, so we reopen the issue.
