### ISSUE TITLE
Inventory Dupe Issue

### ISSUE THREAD

**Issue by JHarris12345** [ViaVersion/ViaBackwards#394]
### '/viaversion dump' Output

https://dump.viaversion.com/923dd79577d64bc2dfe91abd9414304eab397f202c8d47c5a10da181b1026802

### Console Error

```
Put the paste.gg link or text here.
```

### Bug Description

This occurs on 1.17 servers if you log in with a 1.16.5 or lower client

When the InventoryClickEvent is cancelled, it only cancels for the first click. The second click allows you to grab the item and move it. If you then try to click around after that, it will glitch it, however, the item can be duped by not clicking after and just closing your inventory.

Here is a gif where you can see the first click on the diamond sword is cancelled, but after that it is not

https://gyazo.com/960aa6a37f19f81a2873b9534c442492

### Steps to Reproduce

1. Login with a 1.16.5 or lower client to a 1.17 server
2. Enter a GUI where the inventory click event is cancelled
3. Click an item twice and you will be able to move / dupe it

### Expected Behavior

The click event should always be cancelled

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by JHarris12345** [comment]
I can currently do this on every 1.17 server I join so if a patch is done quickly that would be massively appreciated

**Comment by kennytv** [comment]
Via operates on a packet level and has nothing to do with actually changing items on the server, so that'll be a fault of your plugin (but potentially made easy through Via by changing userinput).

**Comment by JHarris12345** [comment]
@kennytv When you say "thatll be a fault of creative mode or your plugin", this occurs on every GUI from any plugin. And it occurs in survival mode. I've successfully duped items on nearly every random 1.17 server I've joined

**Comment by kennytv** [comment]
https://github.com/ViaVersion/ViaBackwards/issues/389

**Comment by JHarris12345** [comment]
@kennytv That thread doesn't provide any solution. How would I go about stopping this glitch from occuring

**Comment by kennytv** [comment]
It's an open issue.

**Comment by JHarris12345** [comment]
I mean, whatever the visual glitch is, it's caused by Via and never has happened until the 1.17 updates so why could it not be fixed like all previous versions. Having these sorts of glitches is very annoying

**Comment by JHarris12345** [comment]
> It's an open issue.

Ah ok
