### ISSUE TITLE
Does not generate YML's or Configs for Minecraft 1.17.1

### ISSUE THREAD

**Issue by InfiltraitorPH** [ViaVersion/ViaBackwards#395]
### '/viaversion dump' Output

No Dump

### Console Error

```
Put the paste.gg link or text here.
```

### Bug Description

Starting a 1.17.1 server with ViaBackwards does not generate a config or yml.

### Steps to Reproduce

1. Create ne 1.17.1 Server with ViaBackwards jar.
2. Start server.
3. Check Plugins folder
4. Does not show any Folder or Config for ViaBackwards.
5. /plugins does not show the plugin as active

### Expected Behavior

Typing /plugins on the console of on OP player does not show that the plugin is active.

### Additional Server Info

BungeeCord and 1.17.1

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by Camotoy** [comment]
You probably forgot to install ViaVersion alongside ViaBackwards; please install this plugin as well. If the problem persists, please open a new issue with a complete log from your server so we can diagnose the issue. Thanks!
