### ISSUE TITLE
Powder snow bug

### ISSUE THREAD

**Issue by FeAr5v** [ViaVersion/ViaBackwards#397]
### '/viaversion dump' Output

https://dump.viaversion.com/4956121bf9e7fd5022dbd9428e26e189e50fb7d7fdf24cef574c849742699744

### Console Error

No Console Error

### Bug Description

when u are on 1.16 on a 1.17 server the powder snow bucket works perfectly in creative mode but when u are in survival mode right when u use it to place the snow you get back the snow in ur bucket and the powder snow block breaks

### Steps to Reproduce

Log in to a 1.17.1 server on 1.16.5 client
Go in survival mode
Try placing powder snow bucket

### Expected Behavior

The snow shouldn't disappear unless you press right click again with ur bucket

### Additional Server Info

i used no other plugin than via backwards and via version

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: 3211-Spigot-18c71bf-2cdc6b1 (MC: 1.17.1)](https://img.shields.io/badge/Platform-3211--Spigot--18c71bf--2cdc6b1%20%28MC%3A%201.17.1%29-3498db?style=flat-square) <br />![ViaVersion (4.0.1): 23 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.0.1)-23%20commit(s)%20behind%20master-yellow?style=flat-square)<br />![ViaBackwards(4.0.1): 11 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.0.1)-11%20commit(s)%20behind%20master-yellow?style=flat-square)

**Comment by kennytv** [comment]
As said in the Discord, that's an easy fix by changing mappings
