### ISSUE TITLE
Inventory item for 1.16

### ISSUE THREAD

**Issue by DiamondXP** [ViaVersion/ViaBackwards#398]
### '/viaversion dump' Output

https://dump.viaversion.com/3a3d156646eff41a8ce6ee66d352a0e2db3944eda2d852b27fce09f1ac1386e8

### Console Error

```
Put the paste.gg link or text here.
```

### Bug Description

Inventory items don't disappear from your hand when you put them down
When crafting, when you place 4 boards, you still have 64 boards in your hand
Inventory items don't disappear from your hand when you put them down

### Steps to Reproduce

1) You take four boards
2) Place 4 boards on the craft workbench
3) They are already in the crafting area of the inventory, but there are also 4 boards in your hand

### Expected Behavior

The blocks should disappear from the hand

### Additional Server Info

I am using the PaperSpigot 1.17.1 kernel, but have also tested on Purpur 1.17.1, the error persists

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git-Paper-259 (MC: 1.17.1)](https://img.shields.io/badge/Platform-git--Paper--259%20%28MC%3A%201.17.1%29-3498db?style=flat-square) <br />![ViaVersion (4.0.1): 23 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.0.1)-23%20commit(s)%20behind%20master-yellow?style=flat-square)<br />![ViaBackwards(4.0.1): 12 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.0.1)-12%20commit(s)%20behind%20master-yellow?style=flat-square)

**Comment by kennytv** [comment]
https://github.com/ViaVersion/ViaBackwards/issues/389
