### ISSUE TITLE
ViaBackwards warn log

### ISSUE THREAD

**Issue by kh0mka** [ViaVersion/ViaBackwards#400]
### '/viaversion dump' Output

https://dump.viaversion.com/5d116ab62c7a8f91331366daf208372c901b7040d36b31196b3b6fdb8e2d1b79

### Console Error

26.09 15:53:51 [Server] Netty Epoll Server IO #1/WARN [ViaBackwards] Unknown named sound in 1.13->1.12 protocol: minecraft:cs.weapons.pistolshot
26.09 15:53:51 [Server] Netty Epoll Server IO #0/WARN [ViaBackwards] Unknown named sound in 1.13->1.12 protocol: minecraft:cs.weapons.pistolshot
26.09 15:53:51 [Server] Netty Epoll Server IO #2/WARN [ViaBackwards] Unknown named sound in 1.13->1.12 protocol: minecraft:cs.weapons.pistolshot
26.09 15:53:51 [Server] Netty Epoll Server IO #3/WARN [ViaBackwards] Unknown named sound in 1.13->1.12 protocol: minecraft:cs.weapons.pistolshot
26.09 15:53:51 [Server] Netty Epoll Server IO #0/WARN [ViaBackwards] Unknown named sound in 1.13->1.12 protocol: minecraft:cs.weapons.pistolshot
26.09 15:53:51 [Server] Netty Epoll Server IO #2/WARN [ViaBackwards] Unknown named sound in 1.13->1.12 protocol: minecraft:cs.weapons.pistolshot
26.09 15:53:51 [Server] Netty Epoll Server IO #3/WARN [ViaBackwards] Unknown named sound in 1.13->1.12 protocol: minecraft:cs.weapons.pistolshot
26.09 15:53:52 [Server] Netty Epoll Server IO #3/WARN [ViaBackwards] Unknown named sound in 1.13->1.12 protocol: minecraft:cs.shop.shopcantbuy

### Bug Description

I am using a plugin on CounterStrike and resourcepack. ViaBackwards writes to me about an unknown sound in the resource pack when the plugin is running. It's not a mistake. This is the question: how to disable the clogging of console logs? How can I turn off the display of messages about this?

### Steps to Reproduce

I am using a plugin on CounterStrike and resourcepack. ViaBackwards writes to me about an unknown sound in the resource pack when the plugin is running. It's not a mistake. This is the question: how to disable the clogging of console logs? How can I turn off the display of messages about this?

### Expected Behavior

Disable message in console about WARNS plugin ViaBackwards

### Additional Server Info

BungeeCord
Spigot 1.16.4 (compiled by BuildTools a week ago)
ViaVersion 4.0.1 + ViaBackwards (latest update)

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git-Spigot-a93cbb1-7a6c3c9 (MC: 1.16.4)](https://img.shields.io/badge/Platform-git--Spigot--a93cbb1--7a6c3c9%20%28MC%3A%201.16.4%29-3498db?style=flat-square) <br />![ViaVersion (4.0.1): 32 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.0.1)-32%20commit(s)%20behind%20master-yellow?style=flat-square)<br />![ViaBackwards(4.0.1): 13 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.0.1)-13%20commit(s)%20behind%20master-yellow?style=flat-square)

**Comment by FormallyMyles** [comment]
suppress-conversion-warnings: true in the ViaVersion config will disable these.

**Comment by kh0mka** [comment]
> suppress-conversion-warnings: true in the ViaVersion config will disable these.

IIt already stands as "true" and it doesn't help

**Comment by kennytv** [comment]
The dump you sent states otherwise: `"suppress-conversion-warnings": false,`

**Comment by kh0mka** [comment]
Sorry, thanks for the help. It turns out that the config is out of order. Thank you so much everyone and apologize for the duplicate perhaps.
