### ISSUE TITLE
Not using translatable names for new entities

### ISSUE THREAD

**Issue by BredyAK** [ViaVersion/ViaBackwards#405]
### '/viaversion dump' Output

https://dump.viaversion.com/2b00637ca2ca8ff785e147d7b630b78deba1976bb60484bcf10f32630d7f1c3f

### Console Error

No errors.

### Bug Description

My server version is 1.16.5 and player's client version is 1.12.2.

I've set entity's name in `translation-mappings.json`, but player can't see correct entity name, what he saw is just entity's original english name. For example, I've set `entity.minecraft.salmon` to `鲑鱼` (Chinese words) in `translation-mappings.json`, but the entity will show `Salmon` to player. (Even if I've restart my server.)

![wrong entity name](https://i.imgur.com/io1UKrx.jpg)

### Steps to Reproduce

See "Bug Description".

### Expected Behavior

Fix the wrong name bug, display right names to players.

### Additional Server Info

Java Version:
```
java version "16.0.2" 2021-07-20
Java(TM) SE Runtime Environment (build 16.0.2+7-67)
Java HotSpot(TM) 64-Bit Server VM (build 16.0.2+7-67, mixed mode, sharing)
```
Bukkit Version: `git-Paper-790 (MC: 1.16.5)`
Proxy Version: `BungeeCord-b1607`

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by kennytv** [comment]
https://github.com/ViaVersion/ViaBackwards/commit/becba6498e4cc066204b69ec4a9dd312d6ae9e0f
