### ISSUE TITLE
TabCompleteEvent doesnt get called using viabackwards with 1.12.2 client on 1.17.1 server

### ISSUE THREAD

**Issue by Bullish53** [ViaVersion/ViaBackwards#407]
### '/viaversion dump' Output

.

### Console Error

No console

### Bug Description

So when running a 1.17.1 server and joining it with 1.12.2 client u can use tab to complete the command or get the list of commands / players. And TabCompleteEvent event will not get called for any plugin. That way the user can bypass the event and get a list of every command in the server which is not good. But joining with 1.17.1 client gets the event called normally.

### Steps to Reproduce

Run 1.17.1 paper server using viabackwards
Log into server with 1.12.2 client and use tab to get the list of commands / players
TabCompleteEvent will not get called but the player will still get a list of all the commands or players.

### Expected Behavior

The TabCompleteEvent should be called no matter what version the player is joining with.

### Additional Server Info

The server is running paper 1.17.1

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Error: Invalid or missing dump](https://img.shields.io/badge/Error-Invalid/missing%20dump-red?style=flat-square) </br>

**Comment by kennytv** [comment]
That's not for Via to handle, any regular client can theoretically do that. See https://github.com/PaperMC/Paper/pull/6592
