### ISSUE TITLE
Inventory Title Isn't Translated as Defniend in `translation-mappings.json`

### ISSUE THREAD

**Issue by BredyAK** [ViaVersion/ViaBackwards#410]
### '/viaversion dump' Output

https://dump.viaversion.com/9bf9dd12a6e467d26b9bc2227c3c9df8c3508feca2013f1931c500586014cebc

### Console Error

No errors.

### Bug Description

Inventory's title isn't translated as it's set in `translation-mappings.json`.

### Steps to Reproduce

For example, set "1.13"."container.chest" to `箱子`(two chinese words) in `/ViaBackwards/translation-mappings.json`, then start BungeeCord and server, then prepare a 1.12.2 version client and join. Open a chest, you'll find it's title is the default translation `Chest`, not `箱子`.

### Expected Behavior

Fix the translation issue.

### Additional Server Info

There are some other messages not translated as I set:

![1](https://user-images.githubusercontent.com/33515294/143054198-057596a9-5c6a-4f73-9e80-7cfff8a2b873.jpg)
![2](https://user-images.githubusercontent.com/33515294/143054208-c00451cb-9067-423e-aa89-550ee337e322.png)

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git%3ABungeeCord--Bootstrap%3A1.18--R0.1--SNAPSHOT%3Abee99be%3A1611](https://img.shields.io/badge/Platform-git%3ABungeeCord--Bootstrap%3A1.18--R0.1--SNAPSHOT%3Abee99be%3A1611-3498db?style=flat-square) </br>![ViaVersion (4.1.0-1.18-pre6-SNAPSHOT): Even with dev](https://img.shields.io/badge/ViaVersion%20(4.1.0--1.18--pre6--SNAPSHOT)-Even%20withdev-brightgreen?style=flat-square) </br>![ViaBackwards(4.1.0-1.18-pre5-SNAPSHOT): Even with dev](https://img.shields.io/badge/ViaBackwards%20(4.1.0--1.18--pre5--SNAPSHOT)-Even%20with%20dev-brightgreen?style=flat-square) </br>
