### ISSUE TITLE
1.17.1 client shown red X with 1.18-rc3 server

### ISSUE THREAD

**Issue by Bobcat00** [ViaVersion/ViaBackwards#411]
### '/viaversion dump' Output

https://dump.viaversion.com/2fe0110a0ea8cea6c5a08bf9a071b3e3947bb0637effc698657185a96c3e24a5

### Console Error

```
Put the paste.gg link or text here.
```

### Bug Description

Running Spigot 1.18-rc3 server, a 1.17.1 client is shown a red X on the server list screen.

### Steps to Reproduce

Spigot 1.18-rc3 server
1.17.1 client
ViaBackwards 4.1.0-1.18-pre5-SNAPSHOT
ViaRewind 2.0.2-SNAPSHOT
ViaVersion 4.1.0-1.18-rc3-SNAPSHOT
Look at the server list screen, screenshot below.

### Expected Behavior

Should show the player count, etc., indicating the client can join the server.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: 3317--Spigot--b7a4222--c98abfb%20%28MC%3A%201.18%20Release%20Candidate%203%29](https://img.shields.io/badge/Platform-3317--Spigot--b7a4222--c98abfb%20%28MC%3A%201.18%20Release%20Candidate%203%29-3498db?style=flat-square) </br>![ViaVersion (4.1.0-1.18-rc3-SNAPSHOT): Even with dev](https://img.shields.io/badge/ViaVersion%20(4.1.0--1.18--rc3--SNAPSHOT)-Even%20withdev-brightgreen?style=flat-square) </br>![ViaRewind(2.0.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaRewind%20(2.0.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(4.1.0-1.18-pre5-SNAPSHOT): Even with dev](https://img.shields.io/badge/ViaBackwards%20(4.1.0--1.18--pre5--SNAPSHOT)-Even%20with%20dev-brightgreen?style=flat-square) </br>

**Comment by Bobcat00** [comment]
![Via_bug](https://user-images.githubusercontent.com/3617206/143662687-343ab16e-bf83-449a-9c7a-c3604fcb9e5a.png)

Second server is the 1.18-rc3 server. Client is 1.17.1
