### ISSUE TITLE
ERROR IN Protocol1_13_1To1_13_2 IN REMAP OF ENTITY_METADATA (0x3F)

### ISSUE THREAD

**Issue by Dreeam-qwq** [ViaVersion/ViaBackwards#412]
### `/viaversion dump` Output

https://dump.viaversion.com/6124bec360db91ef236304fe67476beda871c3553824cde1c3bd1f00a3ced190

### Console Error

```
https://paste.gg/p/anonymous/74f1c00f865548a3a450d3925d7a8108
```

### Bug Description

disconnect from 1.16.5 server when enter nether in 1.8.9 client.

### Steps to Reproduce

1. login with 1.8.9 client
2. join 1.16.5 server
3. tp to nether 0,0 location
4. disconnect from server and see error in console

### Expected Behavior

player can enter nether normally.

### Additional Server Info

Purpur-1.16.5-1171

### Checklist

- [x] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Purpur--1171%20%28MC%3A%201.16.5%29](https://img.shields.io/badge/Platform-git--Purpur--1171%20%28MC%3A%201.16.5%29-3498db?style=flat-square) </br>![ViaVersion (4.1.1-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.1.1--SNAPSHOT)-Even%20withmaster-brightgreen?style=flat-square) </br>![ViaRewind(2.0.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaRewind%20(2.0.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(4.1.1-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.1.1--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by Deeptanil** [comment]
Is this known? Maybe the issue?
02.12 08:53:04 [Server] WARN [ViaVersion] You are running an outdated Java version, please consider updating it to at least Java 17 (your version is 16.0.1). At some point in the future, ViaVersion will no longer be compatible with this version of Java.

**Comment by Deeptanil** [comment]
![Screenshot_20211202-144942_Chrome](https://user-images.githubusercontent.com/86883566/144393406-e5e2ad3a-1616-4e33-a451-cd35b74d561b.png)
![Screenshot_20211202-145005_Chrome](https://user-images.githubusercontent.com/86883566/144393420-d302d659-7679-4558-a271-5aee6c9cf745.png)

This is interesting... Never mentioned the versions that are malfunctioning!

**Comment by Deeptanil** [comment]
Nvm didn't work.

**Comment by kennytv** [comment]
Still fairly certain this is another plugin sending bad metadata. A change in 4.1.0 just meant an error was thrown instead of ignoring it; the new build on https://ci.viaversion.com/view/ViaBackwards/job/ViaBackwards/ will give a more informative error and will also prevent you from being kicked, so please update to that build and send the new, full error message.

**Comment by Deeptanil** [comment]
https://mcpaste.io/76cd9316e85ae8f2

**Comment by kennytv** [comment]
We don't need startup logs, we need logs of the error

**Comment by Deeptanil** [comment]
https://mcpaste.io/54c876a698f08648

**Comment by kennytv** [comment]
And a new dump please. Same for anyone else pasting the new error here

**Comment by Deeptanil** [comment]
https://dump.viaversion.com/74acf91b30a8f7a149d351d4d0f4cfe42563233843b79d2759ff404aedbb3d2b

**Comment by Barvalg** [comment]
![Platform: git--Paper--386%20%28MC%3A%201.17.1%29](https://img.shields.io/badge/Platform-git--Paper--386%20%28MC%3A%201.17.1%29-3498db?style=flat-square) </br>![ViaVersion (4.1.0): 5 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.1.0)-5%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(4.1.1-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.1.1--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by Dreeam-qwq** [comment]
error: https://paste.gg/p/anonymous/e621daabb0734ed2b22b688d0732ea70
dump: https://dump.viaversion.com/3c8b189824374c86c18d69be29898c2c9c6fe6d780ff9628adc3de98bd11cb32

warn on loading viaversion: https://paste.gg/p/anonymous/a722127a62ae4d74bb6b96490a9c71ea (maybe helpful?)

**Comment by Barvalg** [comment]
![Platform: git--Purpur--1171%20%28MC%3A%201.16.5%29](https://img.shields.io/badge/Platform-git--Purpur--1171%20%28MC%3A%201.16.5%29-3498db?style=flat-square) </br>![ViaVersion (4.1.1-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.1.1--SNAPSHOT)-Even%20withmaster-brightgreen?style=flat-square) </br>![ViaRewind(2.0.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaRewind%20(2.0.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(4.1.1-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.1.1--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by kennytv** [comment]
Something really strange is going on, I think I'd need to reproduce this myself to be able to fix it. Can you to binary plugin search (removing half until it works again, readd until you know which causes it) to figure out with what plugin/setup I could reproduce this locally?

**Comment by Deeptanil** [comment]
I've 52 plugins and can't do that since my players would get kicked...

**Comment by Dreeam-qwq** [comment]
For my server,, I test it on Paper1.17.1.
1. launch Paper-1.17.1-391 with plugins:
Plugins (5): [InteractionVisualizer](https://ci.loohpjames.com/job/InteractionVisualizer/1/), [ProtocolLib](https://ci.dmulloy2.net/job/ProtocolLib/536/), ViaBackwards, ViaRewind, ViaVersion
2. Enter server with 1.8.9/1.12.2 client, both get kicked.

Viaver dump: https://dump.viaversion.com/46dff5e948452fa87ed3e9f6c7943d545b96f7df5339253ace81b65c0851ad65

**Comment by Barvalg** [comment]
![Platform: git--Paper--391%20%28MC%3A%201.17.1%29](https://img.shields.io/badge/Platform-git--Paper--391%20%28MC%3A%201.17.1%29-3498db?style=flat-square) </br>![ViaVersion (4.1.1-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.1.1--SNAPSHOT)-Even%20withmaster-brightgreen?style=flat-square) </br>![ViaRewind(2.0.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaRewind%20(2.0.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(4.1.1-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.1.1--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by Deeptanil** [comment]
> > Something really strange is going on, I think I'd need to reproduce this myself to be able to fix it. Can you to binary plugin search (removing half until it works again, readd until you know which causes it) to figure out with what plugin/setup I could reproduce this locally?
> 
> For my server,, I test it on Paper1.17.1.
> 
> 1. launch Paper-1.17.1-391 with plugins:
>    Plugins (5): [InteractionVisualizer](https://ci.loohpjames.com/job/InteractionVisualizer/1/), [ProtocolLib](https://ci.dmulloy2.net/job/ProtocolLib/536/), ViaBackwards, ViaRewind, ViaVersion
> 2. Enter server with 1.8.9/1.12.2 client, both get kicked.
> 
> Viaver dump: https://dump.viaversion.com/46dff5e948452fa87ed3e9f6c7943d545b96f7df5339253ace81b65c0851ad65

Among those plugins I've protocollib as a common.

**Comment by Barvalg** [comment]
![Platform: git--Paper--391%20%28MC%3A%201.17.1%29](https://img.shields.io/badge/Platform-git--Paper--391%20%28MC%3A%201.17.1%29-3498db?style=flat-square) </br>![ViaVersion (4.1.1-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.1.1--SNAPSHOT)-Even%20withmaster-brightgreen?style=flat-square) </br>![ViaRewind(2.0.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaRewind%20(2.0.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(4.1.1-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.1.1--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by kennytv** [comment]
> For my server,, I test it on Paper1.17.1.
> 
> 1. launch Paper-1.17.1-391 with plugins:
>    Plugins (5): [InteractionVisualizer](https://ci.loohpjames.com/job/InteractionVisualizer/1/), [ProtocolLib](https://ci.dmulloy2.net/job/ProtocolLib/536/), ViaBackwards, ViaRewind, ViaVersion
> 2. Enter server with 1.8.9/1.12.2 client, both get kicked.

Thank you very much, I was able to find the issue and fixed it. The root cause is other plugins sending virtual entities and sending metadata for entities that no longer exist. But since clients ignore those, so does VB again.

**Comment by Deeptanil** [comment]
Where can we find the fix?

**Comment by kennytv** [comment]
https://ci.viaversion.com/view/ViaBackwards/job/ViaBackwards/ in about 5-10 minutes.

**Comment by Deeptanil** [comment]
Did it come yet?
