### ISSUE TITLE
1.18 advancements are not translated.

### ISSUE THREAD

**Issue by Kichura** [ViaVersion/ViaBackwards#415]
### '/viaversion dump' Output

https://dump.viaversion.com/2ea15620a73ca91d71a39d36a5b0e6ac81341b10a0c5315f7faa216ded33b7ff

### Console Error

(No console errors were available for me to share in this section!)

### Bug Description

When viewing or gaining any advancements on a 1.18 server while using 1.17/1.17.1 as client, the names including descriptions for them are not translated and instead use the code strings instead.

![broken_advancements](https://user-images.githubusercontent.com/68134602/144712589-289267f3-74d2-4174-9bc8-8b759c503724.png)

### Steps to Reproduce

1. Have a 1.17/1.17.1 client with both viafabric and viabackwards installed,
2. Join a 1.18 server,
3. View the advancements page,
4. The 1.18 advancements should be displayed in a non-friendly language.

### Expected Behavior

All advancements are properly translated and have their details displayed correctly.

### Additional Server Info

1. The 1.18 server itself is running on a pure vanilla while the 1.17.1 client has viafabric + viabackwards installed,
2. This issue was originally in viafabric issues but creeper requested me to move this here instead,
3. So far, only the otherside music disc is translated but rest of assets were not.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: 0.4.5+250--main](https://img.shields.io/badge/Platform-0.4.5+250--main-3498db?style=flat-square) </br>![ViaVersion (4.1.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.1.2--SNAPSHOT)-Even%20withmaster-brightgreen?style=flat-square) </br>![ViaBackwards(4.1.1-SNAPSHOT): 3 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.1.1--SNAPSHOT)-3%20commit(s)%20behind%20master-yellow?style=flat-square) </br>
