### ISSUE TITLE
Chest textures invisible from 1.8 - 1.13 <- 1.16.5

### ISSUE THREAD

**Issue by InAJiff** [ViaVersion/ViaBackwards#419]
### '/viaversion dump' Output

https://dump.viaversion.com/6423c036b798a3e8511283af1df38cef53106b5a533e9bd5d28b3e549e647ebb

### Console Error

No console errors.

### Bug Description

Textures for chests that are placed directly next to each other will become invisible on clients below 1.13. Clients 1.13 and above will show these textures correctly.

### Steps to Reproduce

1. Place double chests directly next to each other on a client above 1.8 - 1.12.
2. Login to a client under 1.13.
3. Some chest textures are now completely invisible.

### Expected Behavior

Chests should display the correct texture and not become invisible, no matter how they're placed.

### Additional Server Info

Server Version: git-Paper-791 (MC: 1.16.5)

The first screenshot is taken on a 1.8 client. The second screenshot is taken on a 1.18 client. (Issue persists from 1.8 - 1.12)

![vv-bug-chesttexture-1 8](https://user-images.githubusercontent.com/96176028/146654710-f2b9cedd-efe8-4df9-b5ff-da9d1059dc1c.png)
![vv-bug-chesttexture-1 18](https://user-images.githubusercontent.com/96176028/146654711-f56ec1b5-259f-4ad3-bcbb-30272306ed8c.png)

### Checklist

- [x] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [x] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [x] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--790%20%28MC%3A%201.16.5%29](https://img.shields.io/badge/Platform-git--Paper--790%20%28MC%3A%201.16.5%29-3498db?style=flat-square) </br>![ViaVersion (4.1.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.1.2--SNAPSHOT)-Even%20withmaster-brightgreen?style=flat-square) </br>![ViaRewind(2.0.3-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaRewind%20(2.0.3--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(4.1.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.1.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by kennytv** [comment]
Not possible to fix, sorry
