### ISSUE TITLE
So i am getting a error of 1.18 server 

### ISSUE THREAD

**Issue by Ninja9090** [ViaVersion/ViaBackwards#420]
### '/viaversion dump' Output

nothing

### Console Error

```
Put the paste.gg link or text here.
```
Bo

### Bug Description

in 1.18 server when i joined from 1.16.5 version i cant go below 0 y level please fix that 

### Steps to Reproduce

dig below 0 level 

### Expected Behavior

there was like empty void and nothing loading 

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Error: Invalid or missing dump](https://img.shields.io/badge/Error-Invalid/missing%20dump-red?style=flat-square) </br>

**Comment by Camotoy** [comment]
Yes, this is a known limitation, as described in the README of this repository and when someone joins the server on 1.16.5. This currently has no known workaround.
