### ISSUE TITLE
Can I & How to translate this wonderful plugin？

### ISSUE THREAD

**Issue by HamsterYDS** [ViaVersion/ViaBackwards#421]
### Problem Description

I wanna translate ur plugin to the other language
Could you tell me what should I do?
I have tried to adapt the "translation-mappings.json" file in the jar:

    "block.minecraft.ancient_debris": "Ancient Debris",
    "block.minecraft.crying_obsidian": "Crying Obisidian",
↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓
    "block.minecraft.ancient_debris": "远古残骸",
    "block.minecraft.crying_obsidian": "哭唧唧的黑曜石",

but when I got the ancient debris item in 1.12. It still was displayed as "1.16 Ancient Debris"

Sorry for my bad English :D

### Solution Description

Instructions to translate
Or just add this useful function.

Your plugin is really cool!

**Comment by Barvalg** [comment]
![Error: Invalid or missing dump](https://img.shields.io/badge/Error-Invalid/missing%20dump-red?style=flat-square) </br>

**Comment by kennytv** [comment]
Move the `mapping-1.15to1.16.json` file into your plugin directory and search for `"name": "1.16 Ancient Debris"` to change that (same file for the crying obsidian)
