### ISSUE TITLE
Wrong biome mappings (1.18.1 -> 1.12.2)

### ISSUE THREAD

**Issue by Dymeth** [ViaVersion/ViaBackwards#422]
### '/viaversion dump' Output

https://dump.viaversion.com/24548c36a061658d4787f4dfd9288d9edd15e03f4d12a27b06ed1489ea76bb02

### Bug Description

Most biomes are not mapped correctly. Feels like it's randomly:

**1.18.1 -> 1.12.2**
OCEAN -> The End
PLAINS -> Plains
DESERT -> Taiga
WINDSWEPT_HILLS -> Forest Hills
FOREST -> River
TAIGA -> Mushroom Island
SWAMP -> Swampland
RIVER -> Extreme Hills+
NETHER_WASTES -> Plains
THE_END -> Plains
FROZEN_OCEAN -> Ocean
FROZEN_RIVER -> Savanna
SNOWY_PLAINS -> Extreme Hills
MUSHROOM_FIELDS -> Deep Ocean
BEACH -> Savanna Plateau
JUNGLE -> Jungle Hills
SPARSE_JUNGLE -> Jungle Edge
DEEP_OCEAN -> The End
STONY_SHORE -> Mesa Plateau F
SNOWY_BEACH -> Mesa
BIRCH_FOREST -> The End
DARK_FOREST -> Frozen Ocean
SNOWY_TAIGA -> Mushroom Island Shore
OLD_GROWTH_PINE_TAIGA -> Ice Plains
WINDSWEPT_FOREST -> Extreme Hills Edge
SAVANNA -> Beach
SAVANNA_PLATEAU -> Desert Hills
BADLANDS -> Stone Beach
WOODED_BADLANDS -> Birch Forest
SMALL_END_ISLANDS -> Plains
END_MIDLANDS -> Plains
END_HIGHLANDS -> Plains
END_BARRENS -> Plains
WARM_OCEAN -> Mesa Plateau
LUKEWARM_OCEAN -> The End
COLD_OCEAN -> Ocean
DEEP_LUKEWARM_OCEAN -> The End
DEEP_COLD_OCEAN -> Ocean
DEEP_FROZEN_OCEAN -> Deep Ocean
THE_VOID -> Ocean
SUNFLOWER_PLAINS -> Desert
WINDSWEPT_GRAVELLY_HILLS -> Taiga Hills
FLOWER_FOREST -> Hell
ICE_SPIKES -> Forest
OLD_GROWTH_BIRCH_FOREST -> Frozen River
OLD_GROWTH_SPRUCE_TAIGA -> Ice Mountains
WINDSWEPT_SAVANNA -> Jungle
ERODED_BADLANDS ->Cold Beach
BAMBOO_JUNGLE -> Deep Ocean
SOUL_SAND_VALLEY -> Plains
CRIMSON_FOREST -> Plains
WARPED_FOREST -> Plains
BASALT_DELTAS -> Plains
DRIPSTONE_CAVES -> Deep Ocean
LUSH_CAVES -> Frozen Ocean
MEADOW -> Birch Forest Hills
GROVE -> Roofed Forest
SNOWY_SLOPES -> Cold Taiga
FROZEN_PEAKS -> Cold Taiga Hills
JAGGED_PEAKS -> Mega Taiga
STONY_PEAKS -> Mega Taiga Hills

### Steps to Reproduce

1. Install WorldEdit
2. Select 4x4x256 area (or from min work height to max world height)
3. Change biome with //setbiome <name>
4. Rejoin server to see differences

### Expected Behavior

Biomes should be mapped correctly 

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--103%20%28MC%3A%201.18.1%29](https://img.shields.io/badge/Platform-git--Paper--103%20%28MC%3A%201.18.1%29-3498db?style=flat-square) </br>![ViaVersion (4.1.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.1.2--SNAPSHOT)-Even%20withmaster-brightgreen?style=flat-square) </br>![ViaBackwards(4.1.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.1.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>
