### ISSUE TITLE
Custom Height Error in console

### ISSUE THREAD

**Issue by rishabhk571** [ViaVersion/ViaBackwards#423]
### '/viaversion dump' Output

https://dump.viaversion.com/ccbc59f72f08e2ead1c5fcf41046c10d121fcba535f92a860797bf3eae9ea5ec

### Console Error

```
[11:14:24 ERROR]: [ViaBackwards] Custom worlds heights are NOT SUPPORTED for 1.16 players and older and may lead to errors!
[11:14:24 ERROR]: [ViaBackwards] You have min/max set to -64/384
```

### Bug Description

Players in 1.16 are getting this error, i dont know reason behind it and how to fix

### Steps to Reproduce

[11:14:24 ERROR]: [ViaBackwards] Custom worlds heights are NOT SUPPORTED for 1.16 players and older and may lead to errors!
[11:14:24 ERROR]: [ViaBackwards] You have min/max set to -64/384

### Expected Behavior

No error

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--77%20%28MC%3A%201.18.1%29](https://img.shields.io/badge/Platform-git--Paper--77%20%28MC%3A%201.18.1%29-3498db?style=flat-square) </br>![ViaVersion (4.1.1): 8 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.1.1)-8%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaRewind(2.0.2): 4 commits behind master](https://img.shields.io/badge/ViaRewind%20(2.0.2)-4%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(4.1.1): 5 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.1.1)-5%20commit(s)%20behind%20master-yellow?style=flat-square) </br>

**Comment by kennytv** [comment]
It's a warning, not an error. 1.18 worlds are higher and deeper and old clients simply don't support that, no sane way around it

**Comment by Bobcat00** [comment]
> It's a warning, not an error. 1.18 worlds are higher and deeper and old clients simply don't support that, no sane way around it

Looks like a **SEVERE error** to me, not a warning.
https://github.com/ViaVersion/ViaBackwards/blob/7a19cb8d040129f970865571504208b7cbaad77e/common/src/main/java/com/viaversion/viabackwards/protocol/protocol1_16_4to1_17/packets/EntityPackets1_17.java#L221

The levels in descending order are:
- SEVERE (highest value)
- WARNING
- INFO
- CONFIG
- FINE
- FINER
- FINEST (lowest value)

**Comment by LaivyTLife** [comment]
how can i solve that?
