### ISSUE TITLE
Just a question (CustomModelData)

### ISSUE THREAD

**Issue by LaivyTLife** [ViaVersion/ViaBackwards#425]
### Problem Description

CustomModelData (Spigot 1.14+) works fine with ViaBackwards??

Whats de limitations? thanks and sorry for the issue open!

### Solution Description

CustomModelData has been inserted into spigot 1.14+ and allow users to change items texture based on client texture, but i dont know if an 1.18 server with custom model data will apply the same texture in 1.12 clients

### Alternatives

.

### Additional Info

.

**Comment by Barvalg** [comment]
![Error: Invalid or missing dump](https://img.shields.io/badge/Error-Invalid/missing%20dump-red?style=flat-square) </br>

**Comment by kennytv** [comment]
Probably not, no. we don't add new features to old clients
