### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by LaivyTLife** [ViaVersion/ViaBackwards#426]
### '/viaversion dump' Output

https://dump.viaversion.com/1950e8d9ebf40234b0b01c463ddb6fddc0e3289fa53106f4031c0f76cfed3e60

### Console Error

https://paste.gg/p/anonymous/ca20222612534e87a3257cfc5a60c8f8

### Bug Description

![image](https://user-images.githubusercontent.com/87931201/148672317-167c62dd-a170-454c-ac13-bd6fa872046a.png)

i didnt know

### Steps to Reproduce

i dont know :CCC

i just tried to join the server, and this happend

### Expected Behavior

Join into the server

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--134%20%28MC%3A%201.18.1%29](https://img.shields.io/badge/Platform-git--Paper--134%20%28MC%3A%201.18.1%29-3498db?style=flat-square) </br>![ViaVersion (4.1.1): 9 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.1.1)-9%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(4.1.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.1.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by kennytv** [comment]
You have a corrupted jar file
