### ISSUE TITLE
No emerald ore generated in chunks using an older client

### ISSUE THREAD

**Issue by ACoolerName** [ViaVersion/ViaBackwards#429]
### '/viaversion dump' Output

https://dump.viaversion.com/218c7f117f29a53f78d566574d0ed5bf290465d178122f78b006ea316bbfc0a6

### Console Error

```
Put the paste.gg link or text here.
```

### Bug Description

1.17.1 client loading new chunks on a 1.18.1 paper server does not spawn emerald_ore or deepslate_emerald_ore

### Steps to Reproduce

1. Login to a 1.18.1 Paper Server using 1.17.1 client (I used optifine client)
2. Load new chunks
3. use worldedit or xray or another method to try find emerald ore in these chunks

### Expected Behavior

Emerald ore and deepslate emerald ore are meant to generate in the new chunks

### Additional Server Info

Paper server, running Essentials, EssentialsChat, EssentialsDiscord, EssentialsSpawn, FastAsyncWorldEdit (WorldEdit), Vault, ViaBackwards, ViaVersion

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--129%20%28MC%3A%201.18.1%29](https://img.shields.io/badge/Platform-git--Paper--129%20%28MC%3A%201.18.1%29-3498db?style=flat-square) </br>![ViaVersion (4.1.1): 14 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.1.1)-14%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(4.1.1): 9 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.1.1)-9%20commit(s)%20behind%20master-yellow?style=flat-square) </br>

**Comment by ACoolerName** [comment]
![image](https://user-images.githubusercontent.com/95275227/150623494-e74011f0-fbdd-44ae-a7a8-37814151ed9e.png)
screenshot of newly loaded chunks, no emerald ore

**Comment by Camotoy** [comment]
ViaVersion doesn't modify the server whatsoever. (You're not on the latest versions anyway)
