### ISSUE TITLE
1.18 custom heights on older versions

### ISSUE THREAD

**Issue by kahveciderin** [ViaVersion/ViaBackwards#430]
### Problem Description

i want people using older clients to be able to interact with the blocks below 0 and over 256

### Solution Description

clients older than 1.17 could be "teleported" to 64 when they go below 0, and the server will map and translate every action from 0 to -64 to 64 to 0 for these clients. the coordinates shown on the f3 screen will be wrong, but at least they will be able to interact with the blocks there. same for blocks over 256, the player will be teleported to 192 and actions will be mapped from 256 to 320 to 192 to 256. note that this place they are teleported to is a virtual one, so 1.17+ clients will just see these clients as normal. (just to summarize, their actual position stored in the server and their position which is sent to them will be different)

**Comment by Barvalg** [comment]
![Error: Invalid or missing dump](https://img.shields.io/badge/Error-Invalid/missing%20dump-red?style=flat-square) </br>

**Comment by kennytv** [comment]
Due to the effort involved in storing the entire world and everything within it as well as the mapping process of basically every change and interaction that happens in a world, that's most likely not going to happen.

**Comment by kahveciderin** [comment]
how processor intensive would this operation be? i'd be happy to work on this and send a pr if this is even feasible as i have a server and i have friends whose computer only runs 1.12 and below

**Comment by kennytv** [comment]
Probably very, plus *extremely* ram intensive on the server, as well as just very large in scope
