### ISSUE TITLE
blocks mapping bug

### ISSUE THREAD

**Issue by shadichy** [ViaVersion/ViaBackwards#431]
### '/viaversion dump' Output

https://dump.viaversion.com/a9dacd2b284160e3014a49b09db4f83379fff941222e376439dfd723751981f0

### Console Error

```
Put the paste.gg link or text here.
```

### Bug Description

What the hell is this freaking blocks mapping?
![hmm](https://imgur.com/pvU2ysm.jpg)

### Steps to Reproduce

1. open a fabric 1.18 server (with terralith & viafabric)
2. launch a 1.12 client, then connect

### Expected Behavior

blocks mapping should be normal 
fences and Grass Paths

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: 0.4.5+244--main](https://img.shields.io/badge/Platform-0.4.5+244--main-3498db?style=flat-square) </br>![ViaVersion: Outdated](https://img.shields.io/badge/ViaVersion-Outdated!-red?style=flat-square) </br>![ViaBackwards(4.1.1): 11 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.1.1)-11%20commit(s)%20behind%20master-yellow?style=flat-square) </br>

**Comment by shadichy** [comment]
Tried ci build, same result
