### ISSUE TITLE
Crashing with OptiFine (1.18.1 -> 1.16.3)

### ISSUE THREAD

**Issue by VidTu** [ViaVersion/ViaBackwards#433]
### '/viaversion dump' Output

https://dump.viaversion.com/67528c645dcd444a1e2a7d032f97b220ae003b829888586f22a155ebb468acbe

### Console Error

No console errors aside from the "Custom world heights" warning.

### Bug Description

Joining a 1.18.1 Paper server with **OptiFine** 1.16.3 crashes the game.

### Steps to Reproduce

1. Install the latest 1.18.1 PaperMC Server.
2. Install the OptiFine HD U G5 for the 1.16.3 version.
3. Join the server.
4. Crash.

### Expected Behavior

Joining the server without crashes

### Additional Server Info

Original crash report (OptiFine only): https://paste.gg/p/anonymous/166e8cd7a8664c1b8fb89df1afcba805

Deobfuscated (FabricLoader+OptiFine+OptiFabric+[NotEnoughCrashes](https://www.curseforge.com/minecraft/mc-mods/not-enough-crashes)): https://gist.github.com/VidTu/8a17434eba78cd8c4fa24b9054aef159

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--175%20%28MC%3A%201.18.1%29](https://img.shields.io/badge/Platform-git--Paper--175%20%28MC%3A%201.18.1%29-3498db?style=flat-square) </br>![ViaVersion (4.2.0-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.2.0--SNAPSHOT)-Even%20withmaster-brightgreen?style=flat-square) </br>![ViaBackwards(4.2.0-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.2.0--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by Xernium** [comment]
If this doesn’t happen on an unmodified/unmoderated (vanilla) client then this issue is invalid. We don’t support mods for this reason. Please reproduce it with an unmodified client and then open a new bug report.
