### ISSUE TITLE
add an option to enable/disable the warning message `Custom worlds heights are NOT SUPPORTED for 1.16 players and older and may lead to errors!`

### ISSUE THREAD

**Issue by BredyAK** [ViaVersion/ViaBackwards#434]
### Problem Description

my server is using map generated on 1.18.1 server, but there are some players using version 1.16(or less) client, the BungeeCord will duplicating the same warning message: `[SEVERE] [ViaBackwards] Custom worlds heights are NOT SUPPORTED for 1.16 players and older and may lead to errors!`, they are so annoying. please add an option to disable this message.

### Solution Description

add an option to disable the warning message: `[SEVERE] [ViaBackwards] Custom worlds heights are NOT SUPPORTED for 1.16 players and older and may lead to errors!`

**Comment by Barvalg** [comment]
![Error: Invalid or missing dump](https://img.shields.io/badge/Error-Invalid/missing%20dump-red?style=flat-square) </br>

**Comment by kennytv** [comment]
Use ci builds
