### ISSUE TITLE
New version -> Old version mapping

### ISSUE THREAD

**Issue by INotSleep** [ViaVersion/ViaBackwards#435]
### Problem Description

When I/my friends play on my/other server from older version, we encounter a problem that it is not convenient to quickly understand what kind of item.

### Solution Description

Create a recoure pack based on optifine's name/tag based textures.

**Comment by Barvalg** [comment]
![Error: Invalid or missing dump](https://img.shields.io/badge/Error-Invalid/missing%20dump-red?style=flat-square) </br>

**Comment by INotSleep** [comment]
Sorry for my stupid english :3

**Comment by kennytv** [comment]
Not feasible as we would have to do multiple packs for multiple resource pack formats, which would just become unmaintainable
