### ISSUE TITLE
Bug with armor stands on ViaBackAwards and Vehicles

### ISSUE THREAD

**Issue by DextralityNetwork** [ViaVersion/ViaBackwards#436]
### '/viaversion dump' Output

https://dump.viaversion.com/96392e4b391af779bc090cfefe85fdbcad992db5146814dd4adc5ab74260aec5

### Bug Description

When I use the viabackawards and vehicles plugins and try to use a car in a version prior to the native version of the server, it does not let me drive it but it does in later versions.

### Steps to Reproduce

1) install viabackawards
2) install vehicles
3) use /getCAR to get a vehicle
4) if you are server version or later the bug does not work.
if you are a minor version (when using viabackwards) the car doesn't move.

### Expected Behavior

Driving

### Additional Server Info

Yes I'm using a fork of bungeecord called XCord with plugins like liteannouncer litebans luckpermsbungee

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Pufferfish--20%20%28MC%3A%201.17.1%29](https://img.shields.io/badge/Platform-git--Pufferfish--20%20%28MC%3A%201.17.1%29-3498db?style=flat-square) </br>![ViaVersion (4.1.1): 15 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.1.1)-15%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(4.1.1): 11 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.1.1)-11%20commit(s)%20behind%20master-yellow?style=flat-square) </br>

**Comment by Camotoy** [comment]
> I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

Please re-try with the latest version from the CI and if it still persists please reopen the issue with a new dump. Thank you!

**Comment by kennytv** [comment]
Please also include the actual client version and test with a standard Bungee/Waterfall instance / try moving Via to your backend servers.
