### ISSUE TITLE
Height problems at <1.16

### ISSUE THREAD

**Issue by Sun8ox** [ViaVersion/ViaBackwards#440]
### '/viaversion dump' Output

https://dump.viaversion.com/08ca50b2c71ca234168b0c58b1b3bf2a306de15560cd7b7111028b007e87ca78

### Console Error

None

### Bug Description

The server is running on the latest Purple 1.18.1 and when I connect to a server with version 1.18 or 1.17 everything is OK but when I'm at 1.16 and below I miss a fairly large part of the terrain and half of my lobby.

### Steps to Reproduce

Join with version lower than 1.17

### Expected Behavior

The terrain will not be missing and everything will be as it should be :)

### Additional Server Info

ViaVersion - Latest
ViaBackwards - Latest
Server version: Latest Purpur
Server type: Standalone

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Purpur--1565%20%28MC%3A%201.18.1%29](https://img.shields.io/badge/Platform-git--Purpur--1565%20%28MC%3A%201.18.1%29-3498db?style=flat-square) </br>![ViaVersion (4.2.1): Even with master](https://img.shields.io/badge/ViaVersion%20(4.2.1)-Even%20withmaster-brightgreen?style=flat-square) </br>![ViaBackwards(4.2.0): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.2.0)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by kennytv** [comment]
See the console warning, that's a won't-fix, sadly.

**Comment by Sun8ox** [comment]
oh. Sorry. Im blind :D
