### ISSUE TITLE
bug... map 

### ISSUE THREAD

**Issue by ddman1211** [ViaVersion/ViaBackwards#441]
### '/viaversion dump' Output

https://dump.viaversion.com/ad8bdce52419fe43ee7b47b420f520962a34a87fca97d2f0fe2a1efebf5cc020

### Console Error

```
null
```

### Bug Description

you can't see the level under the -1 layer etc. etc. caves other things.

### Steps to Reproduce

put the latest version of the plugin and scroll down and you will see that nothing is visible

![unknown (3)](https://user-images.githubusercontent.com/100175933/156096743-32396c47-afd9-4b91-bf01-7e26a2750899.png)
.

### Expected Behavior

to look like the 1.17.1 caves but with another type of block, e.g. something to replace the deep mine material.

### Additional Server Info

spigot, 

Plugins (38): AlonsoLevels, AlonsoTags, AnimatedScoreboard, AuthMe, BotSentry, ChatManager, Citizens, CommandDefender, ConditionalEvents, CustomCrafting, DeluxeCombat, DungeonSystem, EnchantmentForge, Essentials, EssentialsSpawn, ExecutableItems, FastAsyncWorldEdit (WorldEdit), Interactions, InventorySaver, Limbo*, LuckPerms, MMOItems, Multiverse-Core, MythicLib, NBTAPI, OreRegenerator, PlaceholderAPI, PlayerKits, ProtocolLib, SCore, TAB, Vault, ViaBackwards, ViaRewind, ViaVersion, WolfyUtilities, WorldEdit, WorldGuard, Oraxen.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Purpur--1445%20%28MC%3A%201.18.1%29](https://img.shields.io/badge/Platform-git--Purpur--1445%20%28MC%3A%201.18.1%29-3498db?style=flat-square) </br>![ViaVersion (4.2.1): Even with master](https://img.shields.io/badge/ViaVersion%20(4.2.1)-Even%20withmaster-brightgreen?style=flat-square) </br>![ViaBackwards(4.2.0): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.2.0)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by Camotoy** [comment]
See the console warning; that's a won't-fix, sadly.
