### ISSUE TITLE
TabCompleteEvent/DeclareCommandEvent not being called or respected for pre-brigadier clients

### ISSUE THREAD

**Issue by TauCubed** [ViaVersion/ViaBackwards#442]
### '/viaversion dump' Output

https://dump.viaversion.com/23f5c1e997afcc9b42e0fffd4a887caa802649fa8fa57142c5571632be6df797

### Bug Description

When a client joins a 1.18 server on a pre-brigadier client (<1.13) and runs `/<tab>` they are presented with a list of commands the server has without TabCompleteEvent being called. This is a nonissue for brigadier clients as this can be resolved by listening on PlayerCommandSendEvent.

This leads to incompatibility with plugins that may wish to edit/remove commands from being sent to the client.

### Steps to Reproduce

1) Create a simple plugin listening  on `TabCompleteEvent` on a 1.18 server
2) Login with a 1.8 or 1.12.2 client
3) type `/<tab>`

Example code:
```
@EventHandler
public void onTab(TabCompleteEvent e) {
    System.out.println(e.getBuffer());
}
```

### Expected Behavior

That `TabCompleteEvent` is called or changes to `DeclareCommandsEvent` are respected.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--216%20%28MC%3A%201.18.1%29](https://img.shields.io/badge/Platform-git--Paper--216%20%28MC%3A%201.18.1%29-3498db?style=flat-square) </br>![ViaVersion (4.2.1): Even with master](https://img.shields.io/badge/ViaVersion%20(4.2.1)-Even%20withmaster-brightgreen?style=flat-square) </br>![ViaBackwards(4.2.0): 3 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.2.0)-3%20commit(s)%20behind%20master-yellow?style=flat-square) </br>

**Comment by Camotoy** [comment]
I won't close this, but this may be a can't-fix. https://github.com/ViaVersion/ViaBackwards/issues/407

**Comment by TauCubed** [comment]
Hmm you may be right. I'll have to investigate that.

**Comment by TauCubed** [comment]
Indeed, the PR related to the paper issue does not call TabCompleteEvent.
Thank you.

**Comment by TauCubed** [comment]
So just to confirm, this is a bukkit bug?

So from my understanding of it the client can send a TAB_COMPLETE whenever it wants? Is that correct?
And in this event the server is responding to it as it would without ViaVersion?

More information from protocollib if it's useful:

```
> protocollib:packet add play server 17 true
[20:23:49 INFO]: Added listener ListeningWhitelist[priority=MONITOR, packets=[TAB_COMPLETE[class=PacketPlayOutTabComplete, id=17]], gamephase=BOTH, options=[]]
> protocollib:packet add play client 6 true
[20:24:09 INFO]: Added listener Sending: ListeningWhitelist[priority=MONITOR, packets=[TAB_COMPLETE[class=PacketPlayOutTabComplete, id=17]], gamephase=BOTH, options=[]], Receiving: ListeningWhitelist[priority=MONITOR, packets=[TAB_COMPLETE[class=PacketPlayInTabComplete, id=6]], gamephase=BOTH, options=[]]
[20:24:24 INFO]: UUID of player TauCubed is aebeaaec-77bb-494c-852d-72ac095272a5
[20:24:24 INFO]: TauCubed joined the game
[20:24:24 INFO]: TauCubed[/127.0.0.1:60135] logged in with entity id 792 at ([world]77.39689564220804, 82.0, -29.688029953954008)
[20:24:28 INFO]: [ProtocolLib] Received TAB_COMPLETE[class=PacketPlayInTabComplete, id=6] from TauCubed:
{ a = 285088706, b = "/bu" }
[20:24:28 INFO]: [ProtocolLib] Sent TAB_COMPLETE[class=PacketPlayOutTabComplete, id=17] to TauCubed:
{ a = 285088706, b = { range = { start = 1, end = 3 }, suggestions = ("Suggestion{range=StringRange{start=1, end=3}, text='bukkit:?', tooltip='null'}", "Suggestion{range=StringRange{start=1, end=3}, text='bukkit:about', tooltip='null'}", "Suggestion{range=StringRange{start=1, end=3}, text='bukkit:help', tooltip='null'}", "Suggestion{range=StringRange{start=1, end=3}, text='bukkit:pl', tooltip='null'}", "Suggestion{range=StringRange{start=1, end=3}, text='bukkit:plugins', tooltip='null'}", "Suggestion{range=StringRange{start=1, end=3}, text='bukkit:ver', tooltip='null'}", "Suggestion{range=StringRange{start=1, end=3}, text='bukkit:version', tooltip='null'}") } }
```

**Comment by kennytv** [comment]
Players get what they have permission to get, that's all

**Comment by TauCubed** [comment]
In that case this issue is still valid as if you view the log above you'll see that a tab complete has been requested and responded to on a 1.12.2 client and 1.18.1 server using ViaBackwards.

**Comment by TauCubed** [comment]
Well that's what I'm trying to figure out.
If the server would respond to such a request without VIA or if VIA is causing different behavior.

If VIA is causing it then it would make sense for VIA to handle the appropriate events. If this is a Bukkit problem and the server would respond in such a way without VIA if the client made a TAB_COMPLETE request like this then It would be an issue with the server not VIA.

This is why I'm trying to figure out if this is a VIA issue or a Bukkit issue.
