### ISSUE TITLE
Recipe book empty on 1.12.2 client on 1.13+ server

### ISSUE THREAD

**Issue by Jo0001** [ViaVersion/ViaBackwards#443]
### '/viaversion dump' Output

https://dump.viaversion.com/430fd2f2413fcc89c250c594b866867f441f96a1953c8278ad43bc8bf382ffd6

### Bug Description

The recipe book is empty when joining a 1.13 or newer server with  1.12.2 
![2022-03-12_17 33 27](https://user-images.githubusercontent.com/47455182/158027685-a2fe9b06-bf01-453f-92bd-eb99299965a9.png)

### Steps to Reproduce

1. Create 1.13.2 or newer server (also tested with 1.16.5 and 1.18.2)
2. Unlock some recipes  (with a 1.13 or newer client)
3. Log in with 1.12.2
4. Open Recipe book -> its empty

### Expected Behavior

Recipe book shouldn't be empty
![2022-03-12_17 33 39](https://user-images.githubusercontent.com/47455182/158027811-50e8573f-c490-46e0-b202-5cfb21a74c04.png)

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [x] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--216%20%28MC%3A%201.18.1%29](https://img.shields.io/badge/Platform-git--Paper--216%20%28MC%3A%201.18.1%29-3498db?style=flat-square) </br>![ViaVersion (4.2.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.2.2--SNAPSHOT)-Even%20withmaster-brightgreen?style=flat-square) </br>![ViaRewind(2.0.3-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaRewind%20(2.0.3--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(4.2.1-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.2.1--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by kennytv** [comment]
Won't fix
