### ISSUE TITLE
Add a visual minimum version in the config

### ISSUE THREAD

**Issue by AVuTuVA** [ViaVersion/ViaBackwards#444]
### Problem Description

I propose to add a new item in the config, namely, so that we can make sure that the minimum version for entering is 1.17, and the maximum is 1.18.1.

### Solution Description

Add item in config

**Comment by Barvalg** [comment]
![Error: Invalid or missing dump](https://img.shields.io/badge/Error-Invalid/missing%20dump-red?style=flat-square) </br>

**Comment by kennytv** [comment]
Set `block-versions` to `["<1.17", ">1.18.1"]`
