### ISSUE TITLE
TabCompleteResponse start position and transactionId always 0

### ISSUE THREAD

**Issue by TauCubed** [ViaVersion/ViaBackwards#447]
### '/viaversion dump' Output

https://dump.viaversion.com/f50eed5a2836877ad0f26af0a81239b40db8b181d6189f5e19c729771f4b97c8

### Console Error

```
Put the paste.gg link or text here.
```

### Bug Description

I'm not sure if this is a Protocolize bug or a ViaBackwards bug but when reading TabCompleteResponse via Protocolize the start position and transactionId return 0 when running a version <1.13

Interestingly it does return the correct values if It's a Proxy command.

Versions 1.13 or above return the correct values leading me to believe it's a ViaBackwards bug

Paste of ViaDebug
https://pastebin.com/5eRmGD8T

### Steps to Reproduce

1. Login with client below 1.13
2. run /via debug
3. tab complete the `/msg <first letter of your playername>` command

### Expected Behavior

That the startPosition and transactionId mirror that of >1.13 clients

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: velocity%203.1.1](https://img.shields.io/badge/Platform-velocity%203.1.1-3498db?style=flat-square) </br>![ViaVersion (4.2.1): 4 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.2.1)-4%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(4.2.1): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.2.1)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by kennytv** [comment]
Not a Via issue

**Comment by TauCubed** [comment]
Oh that's interesting, for some reason the transactionId always had what appears to be a random value on BungeeCord.
Anyway, thanks for your help.

**Comment by kennytv** [comment]
Yep that's intended, Via generates some random id (which is easier than keeping track of what can be arbitrary ids the server simply mirrors anyways)

**Comment by TauCubed** [comment]
Makes sense, cheers.
