### ISSUE TITLE
Compatibility issue with LibsDisguises

### ISSUE THREAD

**Issue by mcdoeswhat** [ViaVersion/ViaBackwards#448]
### '/viaversion dump' Output

https://dump.viaversion.com/507373ebc43cbf3cf4d63036630af9683e7bad1fa72c9ef0a4f962d6989077d0

### Console Error

```
[11:16:36 WARN]: [ViaBackwards] Received invalid horse armor: Item{identifier=528, amount=1, data=0, tag=CompoundTag { {Damage=IntTag { 0 }} }

```

### Bug Description

When you disguise as a horse and wear armor in front of another player, the console will spam

### Steps to Reproduce

Install Viaversion Viabackwards And LibsDisguises
Disguise as a horse and wear armor in front of another player
The console would spam,

### Expected Behavior

Console should not spam

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Purpur--1171%20%28MC%3A%201.16.5%29](https://img.shields.io/badge/Platform-git--Purpur--1171%20%28MC%3A%201.16.5%29-3498db?style=flat-square) </br>![ViaVersion (4.2.1): 4 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.2.1)-4%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(4.2.1): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.2.1)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by kennytv** [comment]
LD still sending non-horse armor equipment data for the horse is sus, but I removed the warning anyways
