### ISSUE TITLE
Custom item use cooldowns don't work

### ISSUE THREAD

**Issue by VidTu** [ViaVersion/ViaBackwards#450]
### '/viaversion dump' Output

https://dump.viaversion.com/9f2c409337701d2716a574369ed0b64e585cbffe113b28d5e1d75305c73fbeb3

### Bug Description

Custom (`org.bukkit.Player.setCooldown(Material, int)`) item use cooldowns don't work for 1.12.2 players on the 1.18.2 server

### Steps to Reproduce

1. Setup a 1.18.2 (paper) server.
2. Join with the vanilla (1.12.2) client.
3. Use the `org.bukkit.Player.setCooldown(Material, int)` method via some plugin.
4. Notice the cooldown not displaying.

### Expected Behavior

The cooldown should display, because [its packet exists in 1.12.2](https://wiki.vg/index.php?title=Protocol&oldid=14204#Set_Cooldown)

### Additional Server Info

Test plugin code, compiled using latest (1.18.2-R0.1-SNAPSHOT) paper-api:
```java
package test;

import org.bukkit.command.Command;
import org.bukkit.command.CommandSender;
import org.bukkit.entity.Player;
import org.bukkit.plugin.java.JavaPlugin;
import org.jetbrains.annotations.NotNull;

public class TestPlugin extends JavaPlugin {
    @Override
    public boolean onCommand(@NotNull CommandSender sender, @NotNull Command command, @NotNull String label, @NotNull String[] args) {
        if (!(sender instanceof Player p)) return false;
        p.setCooldown(p.getInventory().getItemInMainHand().getType(), 200);
        return true;
    }
}
```

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--283%20%28MC%3A%201.18.2%29](https://img.shields.io/badge/Platform-git--Paper--283%20%28MC%3A%201.18.2%29-3498db?style=flat-square) </br>![ViaVersion (4.3.0-22w14a-SNAPSHOT): Even with dev](https://img.shields.io/badge/ViaVersion%20(4.3.0--22w14a--SNAPSHOT)-Even%20withdev-brightgreen?style=flat-square) </br>![ViaBackwards(4.3.0-22w14a-SNAPSHOT): Even with dev](https://img.shields.io/badge/ViaBackwards%20(4.3.0--22w14a--SNAPSHOT)-Even%20with%20dev-brightgreen?style=flat-square) </br>
