### ISSUE TITLE
Unable to transfer from Lobby of Paper1.17.1 to forge1.12.2 sub-server

### ISSUE THREAD

**Issue by FZDNSZYT** [ViaVersion/ViaBackwards#452]
### '/viaversion dump' Output

https://dump.viaversion.com/2d5a2a64bed7f927609158de04e989e9c8bdfa90098df086bbffee4602c09b52

### Console Error

```
Put the paste.gg link or text here.
```
[ViaBackwards] Ignoring plugin channel in incoming REGISTER: FML
[15:59:43 WARN]: [ViaBackwards] Ignoring plugin channel in incoming REGISTER: FORGE
[15:59:43 WARN]: [ViaBackwards] Ignoring plugin channel in incoming REGISTER: FML
[15:59:43 WARN]: [ViaBackwards] Ignoring plugin channel in incoming REGISTER: InventoryTweaks
[15:59:43 WARN]: [ViaBackwards] Ignoring plugin channel in incoming REGISTER: FML
[15:59:43 WARN]: [ViaBackwards] Ignoring plugin channel in incoming REGISTER: FORGE

 [/117.174.189.117:5449] <-> InitialHandler has connected
[15:59:42 INFO]: [FZDNSZYT|/117.174.189.117:5449] <-> ServerConnector [lobby] has connected
[15:59:48 INFO]: [FZDNSZYT|/117.174.189.117:5449] <-> ServerConnector [xiuxian] has connected
[15:59:48 INFO]: [FZDNSZYT|/117.174.189.117:5449] <-> ServerConnector [xiuxian] has disconnected

### Bug Description

![image](https://user-images.githubusercontent.com/86947716/167800408-1ad71c92-0199-4d7e-a734-a575fd7f5c23.png)
![image](https://user-images.githubusercontent.com/86947716/167800465-ddc1f189-ae5b-407f-b30d-b833f1d30d8c.png)

### Steps to Reproduce

Use the directive [server(servername)]

### Expected Behavior

Hope this bug can be fixed soon

### Additional Server Info

I use waterfall-1.18-486

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--409%20%28MC%3A%201.17.1%29](https://img.shields.io/badge/Platform-git--Paper--409%20%28MC%3A%201.17.1%29-3498db?style=flat-square) </br>![ViaVersion (4.2.1): 4 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.2.1)-4%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(4.2.1): 1 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.2.1)-1%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaRewind(2.0.2): 8 commits behind master](https://img.shields.io/badge/ViaRewind%20(2.0.2)-8%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><br>To fix console spam, use `suppress-conversion-warnings: true` and `suppress-metadata-errors: true` in the _ViaVersion config.yml_. The errors will still happen but you won't be spammed with them and the issues will be ignored.

**Comment by kennytv** [comment]
The error is not a Via issue. The warnings are harmless and can be turned off using the settings mentioned above

**Comment by FZDNSZYT** [comment]
> 错误不是 Via 问题。警告是无害的，可以使用上述设置关闭

Where is the problem of not being able to transmit, I have configured forge compatibility
