### ISSUE TITLE
Chat Types Changing Block Types

### ISSUE THREAD

**Issue by IllegalBananaz** [ViaVersion/ViaBackwards#457]
### '/viaversion dump' Output

https://dump.viaversion.com/48de539a0cd7b55338d674c8d03211d5dabc38716ac702a95e343c390837cabc

### Bug Description

Changing chat-types: in the ViaBackwards config is changing block types for players
Changing chat.type.text: <%s> to chat.type.text: %s changes the mappings of blocks for versions affected by viabackwards

### Steps to Reproduce

Running ViaBackwards 4.3.0 and ViaVersion 4.3.1 on proxy server and backend
1. Using auto generated configs run server on version affected by viabackwards to verify block mappings are correct and stop server
2. edit viabackwards config and change chat.type.text: <%s> %s to chat.type.text: %s
3. Restart and join server on viabakwards affected version

### Expected Behavior

Block mappings should not change when editing Chat-Types

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git%3ABungeeCord--Bootstrap%3A1.19--R0.1--SNAPSHOT%3Aff5727c%3A1644](https://img.shields.io/badge/Platform-git%3ABungeeCord--Bootstrap%3A1.19--R0.1--SNAPSHOT%3Aff5727c%3A1644-3498db?style=flat-square) </br>![ViaVersion (4.3.1): 6 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.3.1)-6%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(4.3.0): 5 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.3.0)-5%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaRewind(2.0.2): 8 commits behind master](https://img.shields.io/badge/ViaRewind%20(2.0.2)-8%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/)

**Comment by IllegalBananaz** [comment]
Downloaded viabackwards from https://www.spigotmc.org/resources/viabackwards.27448/ gave this issue
changing to https://ci.viaversion.com/ fixed the issue

**Comment by Kichura** [comment]
Closing this issue as you have said the CI builds of viaversion have resolved your issue even though your main comment says it otherwise.
