### ISSUE TITLE
Via Backwards changes the new 1.19 blocks

### ISSUE THREAD

**Issue by Razorxd1993** [ViaVersion/ViaBackwards#458]
### '/viaversion dump' Output

- don't work

### Console Error

As the title already describes, Via Backwards changes the new 1.19 blocks to stone or otherwise...

The server of course runs on 1.19, but you joint from a 1.18.2 lobby
Even if the lobby runs on 1.19, the same error occurs

Plugins + Bungee is all on the latest versions.
(Protocollib was also tested on different versions).
(Tested with Spigot/Paper/Purpur)

How to fix this ?

Kind regards

### Bug Description

As the title already describes, Via Backwards changes the new 1.19 blocks to stone or otherwise...

The server of course runs on 1.19, but you joint from a 1.18.2 lobby
Even if the lobby runs on 1.19, the same error occurs

Plugins + Bungee is all on the latest versions.
(Protocollib was also tested on different versions).
(Tested with Spigot/Paper/Purpur)

How to fix this ?

Kind regards

### Steps to Reproduce

none

### Expected Behavior

-

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Error: Invalid or missing dump](https://img.shields.io/badge/Error-Invalid/missing%20dump-red?style=flat-square) </br>

**Comment by Razorxd1993** [comment]
https://dump.viaversion.com/1fee3f712b85dd6755a1616c9d4e920c7513833006eb38ff086e42bd3c32d3a1

**Comment by Kichura** [comment]
ViaBackwards is not designed to give you newer blocks / items in older versions. If your server was on 1.18.2 for example then we will be replacing any newer blocks / items to stone in viaversion itself as they do not exist in the older servers; And it was vice versa then they become translated but will behave as intended in correct version.

Also take a moment to review this image for comparison:
![via-1 19-1 18](https://user-images.githubusercontent.com/68134602/173553890-b2372fc8-366c-43de-851a-d7dc4cd9b774.png)
