### ISSUE TITLE
Crashing 1.9 clients with MyPets

### ISSUE THREAD

**Issue by LinsaFTW** [ViaVersion/ViaBackwards#46]
### What is the output url of /viaversion dump?
> https://hastebin.com/vigijepenu.swift

### How/when does this error happen? login?:
> When opening /petswitch in MyPet plugin.

### Is there an error in the console? Use pastebin.com. Is there a kick message?:
> https://hastebin.com/ewuxucidaw.md

**Comment by Matsv** [comment]
Does this issue still occur for you?
