### ISSUE TITLE
1.18.2 clients send expired chat on 1.19 server.

### ISSUE THREAD

**Issue by mibby** [ViaVersion/ViaBackwards#461]
### '/viaversion dump' Output

https://dump.viaversion.com/49eb45646ee009f5155a63a0413210223dbe2209ac9ccafaeee7de84660a0e97

### Console Error

https://paste.gg/p/anonymous/45e4c9ad5f0d408b9877b587545eb6d4/files/cdf91e50408b401ab31b83fc2cf804e9/raw

The messages / commands still go through fine, it just double outputs in console. i.e.

```
[19:14:46] [Netty Epoll Server IO #3/WARN]: LightWarriorK sent expired chat: 'back'. Is the client/server system time unsynchronized?
[19:14:46] [Server thread/INFO]: LightWarriorK issued server command: /back
```
```
[19:14:59] [Netty Epoll Server IO #2/WARN]: Knaxia sent expired chat: 'making my way in the /baltop without doing much'. Is the client/server system time unsynchronized?
[19:14:59] [Async Chat Thread - #2/INFO]: <Almighty> ~Lucario: making my way in the /baltop without doing much
```

### Bug Description

1.18.2 clients seem to warn console every time they chat that their chat / command is expired. 1.19 clients on the 1.19 server do not have this problem.

### Steps to Reproduce

1. Start 1.19 server.
2. Login with 1.18.2 client.
3. Chat or use command.
4. Console complains of unsynchronized time / expired chat.

### Expected Behavior

No expired chat / warnings.

### Additional Server Info

Waterfall dev 496
Purpur dev 1668 (Paper 1.19)

All via plugins are behind the server, not proxy.

Every single person this warning outputs for, I confirmed they are using 1.18.2. No person on 1.19 has this problem. I also tried syncing the server clock to verify it wasn't the problem.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Purpur--1668%20%28MC%3A%201.19%29](https://img.shields.io/badge/Platform-git--Purpur--1668%20%28MC%3A%201.19%29-3498db?style=flat-square) </br>![ViaVersion (4.3.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.3.2--SNAPSHOT)-Even%20withmaster-brightgreen?style=flat-square) </br>![ViaBackwards(4.3.1-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.3.1--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaRewind(2.0.3-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaRewind%20(2.0.3--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by kennytv** [comment]
Not a Via issue, that's just client and server time mismatching

**Comment by mibby** [comment]
Where is the mismatch coming from though? It is every single client that is below 1.19. If the server time is synced, it seems unlikely that every other player would have a clock offset.

**Comment by kennytv** [comment]
https://bugs.mojang.com/browse/MC-251989

**Comment by mibby** [comment]
I do not believe that is related. My server is not running any ticks behind or generating chunks (profiled performance). Ntpd system time was synced, restarted, and full system rebooted to ensure it wasn't offset. Commands and chat are not being blocked, they execute fine. Nor is this happening to 1.19 clients. Likewise, that issue says it was resolved.

Another person reported the same problem using Via in the Paper discord with a screenshot so I can only assume perhaps they added some form of chat validation in 1.19 that older clients don't have, which is why it complains.

**Comment by kennytv** [comment]
The linked issue was "resolved" by simply not having the server kick the client anymore, it is still that same issue resulting in that log message, including 1.19 clients. Lag can be one cause, but isn't the only one - nonetheless, this is out of our control

**Comment by ayunami2000** [comment]
I get this as well. Is there really no way to, idk, at least suppress the warn message?
