### ISSUE TITLE
only 1.19 clients

### ISSUE THREAD

**Issue by Luka-s0** [ViaVersion/ViaBackwards#463]
### '/viaversion dump' Output

https://dump.viaversion.com/1fec704621c3910bd85c7663292ee81e8fbc8329a840c9791495f9cdb4ae5877

### Console Error

```
Put the paste.gg link or text here.
```

### Bug Description

cant join a 1.19 server with any other client that version 1.19    get error message "incomplete set of tags received from the server please contact the server operator"

### Steps to Reproduce

joining on any client on version before 1.19

### Expected Behavior

joining the server as normal

### Additional Server Info

i use the plugins:
viaversion
viabackwards
eco
ecoenchants
coreprotect
cmi
cmilib
realisticseasons
ecotalismans
TAB
TAB-Bukkit-bridge
protocollib
spartan
antialtaccount
ultimatestatistics
and filegui

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--24%20%28MC%3A%201.19%29](https://img.shields.io/badge/Platform-git--Paper--24%20%28MC%3A%201.19%29-3498db?style=flat-square) </br>![ViaVersion (4.3.1): 7 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.3.1)-7%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(4.3.0): 8 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.3.0)-8%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/)
