### ISSUE TITLE
villagers crash

### ISSUE THREAD

**Issue by JohnHeikens** [ViaVersion/ViaBackwards#465]
### '/viaversion dump' Output

https://dump.viaversion.com/a40c1d804e740f73cc1c920524652f56fbce6a6f3e71b5c6aa6ce9c2ced8bcf3

### Console Error

```
09:03:26 [WARNING] [JohnHeikens] -> UpstreamBridge - NativeIoException: readAddress(..) failed: Connection reset by peer
09:03:26 [INFO] [JohnHeikens] disconnected with: NativeIoException : readAddress(..) failed: Connection reset by peer
09:03:26 [INFO] [JohnHeikens] <-> DownstreamBridge <-> [dev] has disconnected
09:03:26 [INFO] [JohnHeikens] -> UpstreamBridge has disconnected
```

### Bug Description

Rightclicking certain villagers on a 1.17.1 server with a 1.19 client causes your client to disconnect

### Steps to Reproduce

1. Login with a 1.19 client on a 1.17.1 server (test ip: dev.axo.bar)
2. Rightclick on certain villagers
![2022-06-22_09 11 47](https://user-images.githubusercontent.com/50964021/174966727-541eec94-0702-4dce-83a5-517ed89e244d.png)
 (not all villagers work, there are some which crash you, others which don't. we named them 'crashie' if they kick you)
3. you will get kicked because of "internal exception io.netty.handler.codec.decoderexception: z: loading nbt data"
![2022-06-22_09 13 01](https://user-images.githubusercontent.com/50964021/174966920-e5c875e8-5c18-44ee-882d-15a31739bad9.png)

### Expected Behavior

when one rightclicks a villager they should see their trades open up like this:
![2022-06-22_09 19 04](https://user-images.githubusercontent.com/50964021/174968041-0e91ef9a-b54a-4e0e-af5d-f841fe6e1c77.png)

### Additional Server Info

I use the latest Bungeecord build, latest viabackwards dev build, viaversion and viarewind. there shouldn't be any plugin causing this really.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git%3ABungeeCord--Bootstrap%3A1.19--R0.1--SNAPSHOT%3Aff5727c%3A1644](https://img.shields.io/badge/Platform-git%3ABungeeCord--Bootstrap%3A1.19--R0.1--SNAPSHOT%3Aff5727c%3A1644-3498db?style=flat-square) </br>![ViaVersion (4.3.1): 7 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.3.1)-7%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaRewind(2.0.2): 8 commits behind master](https://img.shields.io/badge/ViaRewind%20(2.0.2)-8%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/)

**Comment by kennytv** [comment]
Update to ci builds
