### ISSUE TITLE
Villagers' trades are bugged

### ISSUE THREAD

**Issue by javanoah** [ViaVersion/ViaBackwards#466]
### '/viaversion dump' Output

https://dump.viaversion.com/21efa6703ac073a4f6329a1c9cb0f69901b1c8b188049a712fa12af2d7bee6d7

### Bug Description

When I trade with Villagers in 1.19 they work perfectly. But when I trade with them in the 1.18.2  they're bugged. They show andesite and I can't trade with them (Andesite and books) doesn't work

![image](https://user-images.githubusercontent.com/87227367/175497130-c646430c-abba-49f2-942b-96cb179e3d1d.png)

### Steps to Reproduce

1. login with 1.18.2 version
2. Put a lectern to a villager (I saw that the Cartography villagers are also broken)
3. See the trades

### Expected Behavior

Instead of andesite there should be books or the respective item

### Additional Server Info

I use purpur 1.19 1670
![image](https://user-images.githubusercontent.com/87227367/175497406-889422b8-6053-4a73-881d-275d0a558ed6.png)

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Purpur--1670%20%28MC%3A%201.19%29](https://img.shields.io/badge/Platform-git--Purpur--1670%20%28MC%3A%201.19%29-3498db?style=flat-square) </br>![ViaVersion (4.3.1): 7 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.3.1)-7%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(4.3.0): 8 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.3.0)-8%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/)
