### ISSUE TITLE
Scoreboard (with Teams) problem

### ISSUE THREAD

**Issue by xHyroM** [ViaVersion/ViaBackwards#467]
### '/viaversion dump' Output

https://dump.viaversion.com/56a3e162120132e400cfdc5c3fb310dc9431c68ad30b25de78ad0903f2c5478b

### Bug Description

![image](https://user-images.githubusercontent.com/56601352/177337839-260a5833-1eb3-4813-afd6-19c53596c9b1.png)
![image](https://user-images.githubusercontent.com/56601352/177339771-2b1e7fbb-b723-4c1b-9bcd-fa63c7bc6816.png) - Sometimes a different scoreboard line is shown.
_1.18- (1.17, 1.16)_ 

**Creating scoreboard:**
```java
@EventHandler
public void onJoin(PlayerJoinEvent event) throws InvocationTargetException, IllegalAccessException {
    Player p = event.getPlayer();
    Scoreboard scoreboard = Scoreboard.createScoreboard(
        "a",
        "b",
        "c",
        "",
        "d"
    );

    scoreboard.show(p);
}
```

**My scoreboard class helper:**
```java
package me.xhyrom.test;

import net.kyori.adventure.text.Component;
import net.kyori.adventure.text.minimessage.MiniMessage;
import org.bukkit.Bukkit;
import org.bukkit.ChatColor;
import org.bukkit.entity.Player;
import org.bukkit.scoreboard.DisplaySlot;
import org.bukkit.scoreboard.Objective;
import org.bukkit.scoreboard.Team;
import org.sharkurmc.utilities.java.RandomUtils;

import java.util.Arrays;
import java.util.Collections;
import java.util.List;
import java.util.stream.Collectors;

public class Scoreboard {
    public org.bukkit.scoreboard.Scoreboard originalScoreboard;
    public Objective objective;
    public String randomId;
    public Component title;
    public Scoreboard(Component title) {
        this.title = title;
        this.randomId = RandomUtils.randomString(7);
        this.originalScoreboard = Bukkit.getScoreboardManager().getNewScoreboard();

        createObjective();
    }

    public void show(Player player) {
        player.setScoreboard(this.originalScoreboard);
    }

    public void hide(Player player) {
        player.setScoreboard(Bukkit.getScoreboardManager().getMainScoreboard());
    }

    public void setLine(String line, int i) {
        setLine(MiniMessage.miniMessage().deserialize(line), i);
    }

    public void setLine(Component line, int i) {
        Team team = originalScoreboard.getTeam("scoreboard_"+randomId+"_"+i) != null ?
                originalScoreboard.getTeam("scoreboard_"+randomId+"_"+i) :
                originalScoreboard.registerNewTeam("scoreboard_"+randomId+"_"+i);
        team.prefix(line);

        String empty = scoreToName(i);
        team.addEntry(empty);

        objective.getScore(empty).setScore(i);
    }

    public void setLines(String... lines) {
        setLines(Arrays.stream(lines).map((line) -> MiniMessage.miniMessage().deserialize(line)).collect(Collectors.toList()));
    }

    public void setLines(List<Component> lines) {
        Collections.reverse(lines);

        int i = 1;
        for (Component line : lines) {
            setLine(line, i);
            i++;
        }
    }

    public static Scoreboard createScoreboard(String title, String... lines) {
        return createScoreboard(
                MiniMessage.miniMessage().deserialize(title),
                Arrays.stream(lines).map((line) -> MiniMessage.miniMessage().deserialize(line)).collect(Collectors.toList())
        );
    }

    public static Scoreboard createScoreboard(Component title, List<Component> lines) {
        Scoreboard scoreboard = new Scoreboard(title);

        scoreboard.setLines(lines);

        return scoreboard;
    }

    private static String scoreToName(int score) {
        return ChatColor.values()[score].toString();
    }

    private void createObjective() {
        objective = originalScoreboard.registerNewObjective("obj", "dummy", title);
        objective.setDisplaySlot(DisplaySlot.SIDEBAR);
    }
}

```

**PS:** I'm doing this via teams because I want to use hex colors.

### Steps to Reproduce

1. Login with 1.18- (1.17) client
2. Check scoreboard

### Expected Behavior

![image](https://user-images.githubusercontent.com/56601352/177337730-f28ae494-70c3-4a61-accc-c97b9cfdd6d9.png)
_1.18-1.19+_

All lines of the scoreboard should be visible.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Purpur--1697%20%28MC%3A%201.19%29](https://img.shields.io/badge/Platform-git--Purpur--1697%20%28MC%3A%201.19%29-3498db?style=flat-square) </br>![ViaVersion (4.4.0-1.19.1-pre2-SNAPSHOT): Even with dev](https://img.shields.io/badge/ViaVersion%20(4.4.0--1.19.1--pre2--SNAPSHOT)-Even%20withdev-brightgreen?style=flat-square) </br>![ViaBackwards(4.4.0-1.19.1-pre2-SNAPSHOT): Even with dev](https://img.shields.io/badge/ViaBackwards%20(4.4.0--1.19.1--pre2--SNAPSHOT)-Even%20with%20dev-brightgreen?style=flat-square) </br>

**Comment by xHyroM** [comment]
It's because team name is too long

**Comment by kennytv** [comment]
Can't do anything about that on Via's side, clients older than 1.18 have a hard limit of 16
