### ISSUE TITLE
strange kick when doing things

### ISSUE THREAD

**Issue by kingakis2** [ViaVersion/ViaBackwards#473]
### '/viaversion dump' Output

https://dump.viaversion.com/72d534e913a3c4e73dc7a8111ecf2e5ce7d62c4e9e1353e0e78aa759c0d44d01

### Console Error

https://paste.gg/p/anonymous/818cd4ef894e4042af9595e3c99abc60

### Bug Description

Open a cosmetic on gadgetsmenu last version plugin just kick you and that error console appears or doing random things sometimes just kick randomly too but only on old versions below 1.19 in a server base 1.19

### Steps to Reproduce

1. Join server
2. Play and do random things
3. Get kick instantly or don't get kick absolutely or if you want a kick open a cosmetic on gadgets menu and wait for the chat reward appear

### Expected Behavior

It should not kick and works normally

### Additional Server Info

Paper mc 1.19

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by Kichura** [comment]
Closing this as this issue cannot be reproduced anymore, if it happens again then please open a new issue.
