### ISSUE TITLE
[21:26:24] [Render thread/WARN]: Incomplete server tags, disconnecting. Missing: {ResourceKey[minecraft:root / minecraft:block]=[minecraft:polar_bears_spawnable_on_in_frozen_ocean]}

### ISSUE THREAD

**Issue by SlenkyDev** [ViaVersion/ViaBackwards#476]
### '/viaversion dump' Output

https://dump.viaversion.com/e89d45687bf80b1a1210349bdb16f6a385fca1a94f56856f7d0be42d493718ed

### Console Error

```
[21:26:24] [Render thread/WARN]: Incomplete server tags, disconnecting. Missing: {ResourceKey[minecraft:root / minecraft:block]=[minecraft:polar_bears_spawnable_on_in_frozen_ocean]} (client log)
```

### Bug Description

Players unable to connect to 1.19 server

### Steps to Reproduce

1. Login with a <1.19 client
2. Try to join the server
3. You are unable to join, "Incomplete set of tags recieved from server. Please contact server operator."

### Expected Behavior

Player joins the server

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: velocity%203.1.2--SNAPSHOT%20%28git--662fbc4e--b159%29](https://img.shields.io/badge/Platform-velocity%203.1.2--SNAPSHOT%20%28git--662fbc4e--b159%29-3498db?style=flat-square) </br>![ViaVersion (4.3.2-SNAPSHOT): 6 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.3.2--SNAPSHOT)-6%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaRewind(2.0.3-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaRewind%20(2.0.3--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards: Outdated](https://img.shields.io/badge/ViaBackwards%20(4.3.1-SNAPSHOT)-Outdated!-red?style=flat-square) </br><br>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/)
