### ISSUE TITLE
DUMP TEST

### ISSUE THREAD

**Issue by HowardZHY** [ViaVersion/ViaBackwards#478]
### Problem Description

https://dump.viaversion.com/5b16c0297489e134e170edbfba10decfd8302ee8084438969588a5368aab0cce

### Solution Description

https://dump.viaversion.com/5b16c0297489e134e170edbfba10decfd8302ee8084438969588a5368aab0cce

**Comment by Barvalg** [comment]
![Platform: git--Scissors--58%20%28MC%3A%201.19%29](https://img.shields.io/badge/Platform-git--Scissors--58%20%28MC%3A%201.19%29-3498db?style=flat-square) </br>![ViaVersion (4.3.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.3.2--SNAPSHOT)-Even%20withmaster-brightgreen?style=flat-square) </br>![ViaBackwards: Outdated](https://img.shields.io/badge/ViaBackwards%20(4.3.1--SNAPSHOT)-Outdated!-red?style=flat-square) </br>![ViaRewind(2.0.3-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaRewind%20(2.0.3--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br><br>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/)

**Comment by HowardZHY** [comment]
Damn, that free op server's vb is outdated. As same as I thought.
