### ISSUE TITLE
DUMP TEST2

### ISSUE THREAD

**Issue by HowardZHY** [ViaVersion/ViaBackwards#479]
### Problem Description

https://dump.viaversion.com/f51247aaddae60711c09262a06187e92aa8072993c8a58fbebf30d53c85eee44

### Solution Description

https://dump.viaversion.com/f51247aaddae60711c09262a06187e92aa8072993c8a58fbebf30d53c85eee44

**Comment by Barvalg** [comment]
![Platform: 3498--Spigot--b081915--10ba1be%20%28MC%3A%201.18.2%29](https://img.shields.io/badge/Platform-3498--Spigot--b081915--10ba1be%20%28MC%3A%201.18.2%29-3498db?style=flat-square) </br>![ViaVersion (4.3.1): 11 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.3.1)-11%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/)

**Comment by HowardZHY** [comment]
the fucking server owner forgot to add VB.

**Comment by HowardZHY** [comment]
and it seems like ad-blocking block the dump show

**Comment by kennytv** [comment]
Please don't open spam issues to test dumps
