### ISSUE TITLE
Iventory Items Teleporting Back

### ISSUE THREAD

**Issue by LinsaFTW** [ViaVersion/ViaBackwards#48]
### What is the output url of /viaversion dump?
> https://dump.viaversion.com/fe8a7b495e080020208fbc397f42bb3d8088946079b99b92027fadf593dbbf10

### How/when does this error happen? login?:
> When moving things from any inventory fast in 1.11-1.7.

### Is there an error in the console? Use pastebin.com. Is there a kick message?:
> No.

When i move items in any inventory really fast it teleports back to its place, this is really bad for PotPvP and SkyWars.

**Comment by Gerrygames** [comment]
This is related to this fix in ViaVersion:
https://github.com/MylesIsCool/ViaVersion/pull/754

**Comment by creeper123123321** [comment]
Can you test #97
