### ISSUE TITLE
Clients with 1.19 cannot join the 1.19.1 server

### ISSUE THREAD

**Issue by A1Panda** [ViaVersion/ViaBackwards#480]
### '/viaversion dump' Output

We've made a dump with useful information, report your issue and provide this url: https://dump.viaversion.com/99f5710f1610

### Console Error

```
Put the paste.gg link or text here.
```
no Error

### Bug Description

Clients with 1.19 cannot join the 1.19.1 server
![image](https://user-images.githubusercontent.com/59989747/181563128-390283cb-6efb-4c7d-9643-138424d46d0a.png)
![image](https://user-images.githubusercontent.com/59989747/181564496-d4e8ca5f-919e-4a5f-a272-42f156d4f15b.png)

### Steps to Reproduce

no

### Expected Behavior

Clients in 1.19 should be able to join 1.19.1 like 1.18

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Error: Invalid or missing dump](https://img.shields.io/badge/Error-Invalid/missing%20dump-red?style=flat-square) </br>

**Comment by kennytv** [comment]
Follow the issue template, including trying ci builds
