### ISSUE TITLE
1.19 client -> 1.19.1 server use 1.18.2 translation

### ISSUE THREAD

**Issue by Kichura** [ViaVersion/ViaBackwards#481]
### '/viaversion dump' Output

https://dump.viaversion.com/8ec77f6c6415c4103da7c645b8be001ebf9d3062f551d1028266c3601cad2347

### Console Error

*(No console errors are found)*

### Bug Description

When joining any 1.19.1 servers; all 1.19 clients will suffer from the 1.18.2 client translation instead of actually seeing things expectedly.

### Steps to Reproduce

1. Make any server that uses the 1.19.1-base,
2. Join the server using 1.19.0,
3. Expect mobs like wardens to look incorrect.

### Expected Behavior

The 1.19 client should see similar things to what 1.19.1 can see.

### Additional Server Info

While i consider this as an known issue; it is best to remind people that this may or may not be fixable if at all - Otherwise i do not have any further information here.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Purpur--1737%20%28MC%3A%201.19.1%29](https://img.shields.io/badge/Platform-git--Purpur--1737%20%28MC%3A%201.19.1%29-3498db?style=flat-square) </br>![ViaVersion (4.4.1): Even with master](https://img.shields.io/badge/ViaVersion%20(4.4.1)-Even%20withmaster-brightgreen?style=flat-square) </br>![ViaBackwards(4.4.1): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.4.1)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by kennytv** [comment]
Won't fix
