### ISSUE TITLE
Item is not visible

### ISSUE THREAD

**Issue by JunSuner** [ViaVersion/ViaBackwards#482]
### '/viaversion dump' Output

https://dump.viaversion.com/9ad031f321b59e888d58f469477aeabe10a1f48a5849f99ec2b2ca03502b0cac

### Console Error

```
Put the paste.gg link or text here.
```
This is a problem so no error is reported

### Bug Description

I can't see 1.19 items when i use 1.19 client.
On 1.19.1
![image](https://user-images.githubusercontent.com/79354637/181691992-c6ba158f-182e-41fe-9b93-3dd9061d76b6.png)

On 1.19
![image](https://user-images.githubusercontent.com/79354637/181692159-2aa6b8f1-d8f5-4909-8f9a-65fd060e9362.png)

### Steps to Reproduce

1. I log in to the 1.19.1 server using the 1.19 client.
2. I can't see 1.19 items.

### Expected Behavior

1.19 items should be displayed when the player logs in to the server using a 1.19 client.

### Additional Server Info

I used Waterfall Proxy.
Plugins (20): AdvancedBan, BungeeTabListPlus, ColoredSigns, CoreProtect, Essentials, EssentialsGeoIP, InventoryRollbackPlus, LuckPerms, Matrix, PlaceholderAPI, PlugManX (PlugMan), ProtocolLib, ServersNPC, ServerTeleport*, SkinsRestorer, TigerReports, UltimateAutoRestart, Vault, ViaBackwards, ViaVersion

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--86%20%28MC%3A%201.19.1%29](https://img.shields.io/badge/Platform-git--Paper--86%20%28MC%3A%201.19.1%29-3498db?style=flat-square) </br>![ViaVersion (4.4.1): Even with master](https://img.shields.io/badge/ViaVersion%20(4.4.1)-Even%20withmaster-brightgreen?style=flat-square) </br>![ViaBackwards(4.4.1): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.4.1)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by kennytv** [comment]
1.19 client support on 1.19.1 servers is limited and does a roundtrip from 1.19.1->1.18.2->1.19, that's expected.

**Comment by JunSuner** [comment]
thanks

**Comment by Schuwi** [comment]
Hi, can you give a reason why this will not be supported?

**Comment by tomcraft** [comment]
Technical changes between 1.19 and 1.19.1 client that cannot be translated properly. But they can be from 1.18.2.

**Comment by JunSuner** [comment]
please support it thx :)

**Comment by kennytv** [comment]
https://github.com/ViaVersion/ViaBackwards/commit/d559c7cff15243e3d55e1cc837ecb1c07b10c061
