### ISSUE TITLE
Player can't join with 1.19 on 1.19.1 server with velocity 

### ISSUE THREAD

**Issue by steveminecraft2** [ViaVersion/ViaBackwards#483]
### '/viaversion dump' Output

https://dump.viaversion.com/5adb2bb1f60fc485e00bbc9600625a5085785a66be9f1eec9952491768fa855a

### Console Error

kick on 1.19.1: lost connection: Internal Exception: com.mojang.authlib.minecraft.InsecurePublicKeyException$InvalidException: Invalid profile public key signature
kick on velocity: Unable to connect to test: disconnect.genericReason

### Bug Description

on 1.19.1 server with velocity player can't connect from version 1.19, player kick on version 1.19. (In console error I wrote what the kick is for)
when player join to server with 1.19.1, player normally enters and there is no error and does not kick him

### Steps to Reproduce

1. install 1.19.1 server and velocity (newet version for 1.19.1)
2. install viaversion and viabackwars on velocity OR 1.19.1 server 
3. set servers to offline mode 
4. block version <1.19
5. join to server with 1.19

### Expected Behavior

player will also be able to enter with 1.19

### Additional Server Info

i have 1.19.1 server and velocity. Viaversion and viabackwars i have on velocity server

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: velocity%203.1.2--SNAPSHOT%20%28git--c57fb489--bunknown%29](https://img.shields.io/badge/Platform-velocity%203.1.2--SNAPSHOT%20%28git--c57fb489--bunknown%29-3498db?style=flat-square) </br>![ViaVersion (4.4.1): Even with master](https://img.shields.io/badge/ViaVersion%20(4.4.1)-Even%20withmaster-brightgreen?style=flat-square) </br>![ViaBackwards(4.4.1): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.4.1)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by kennytv** [comment]
Update Velocity

**Comment by CS-Birb** [comment]
Also experiencing issue as described with ViaVersion, ViaBackwards and Velocity git-1a3fba42-b163.

My own dump:
https://dump.viaversion.com/c861e451d20fad26cdccf670d26b7b78fa93b4163c14bc3eb9a025b32eedb8ee

**Comment by steveminecraft2** [comment]
> 
at me also with the latest version from papermc.io velocity for 1.19.1 this happens on version 1.19, so updating velocity does not help:
https://dump.viaversion.com/04ed8400b816778a45775bb6d22190ddd674b098ccebcbb1961c43efd59cd337

**Comment by kennytv** [comment]
Copied from our Discord:
> To resolve the "Missing profile public key" issue:
> 
> 1. You need to disable enforce-secure-profile in server.properties file via 1.19.1 or later backend server(s), 
> 
> 2. If you have velocity as your proxy; ensure that force-key-authentication is disabled in the velocity.toml file,
> 
> 3. Specific client-to-server transitions may not support this capability properly and will end up persisting this issue which is something that cannot be easily solved by us. (Example: 1.19 client -> 1.19.1 server)

**Comment by steveminecraft2** [comment]
> Copied from our Discord:
> 
> > To resolve the "Missing profile public key" issue:
> > 
> > 1. You need to disable enforce-secure-profile in server.properties file via 1.19.1 or later backend server(s),
> > 2. If you have velocity as your proxy; ensure that force-key-authentication is disabled in the velocity.toml file,
> > 3. Specific client-to-server transitions may not support this capability properly and will end up persisting this issue which is something that cannot be easily solved by us. (Example: 1.19 client -> 1.19.1 server)

I set: enforce-secure-profile=false on 1.19.1 server In server.properties, in velocity.toml I have set: force-key-authentication=false
and I still have that I can't enter from 1.19

**Comment by kennytv** [comment]
You can join our Discord for more help.
