### ISSUE TITLE
The 1.19 players sees the same as 1.18 players on 1.19.1 servers.

### ISSUE THREAD

**Issue by moonEEVEEXwX** [ViaVersion/ViaBackwards#484]
### '/viaversion dump' Output

https://dump.viaversion.com/0ea554a1d203fe73ab64c0378fe1ee639741b53f16c088db490126d1af8cb791

### Bug Description

(sorry for my poor english.Chinese is my mother language.)
We try to use viabackwards on our 1.19.1 server
But when we entered the ancient city,the Sculk Vein became Glow Lichen,the Warden became an Iron Golem named"warden".
You see,We are using the 1.19 client and it should be normal to see it.but we still be sent the 1.18 packs.

### Steps to Reproduce

1.Build a 1.19.1 spigot server with viaversion & viabackwards
2.Use 1.19 Client join in
3.Teleport to the ancient city

### Expected Behavior

The ancient city should be normal

### Additional Server Info

I also use bungeecord with these plugins "luckperm bcgod"

### Checklist

- [x] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: 3558--Spigot--2183145--401f1ad%20%28MC%3A%201.19.1%29](https://img.shields.io/badge/Platform-3558--Spigot--2183145--401f1ad%20%28MC%3A%201.19.1%29-3498db?style=flat-square) </br>![ViaVersion (4.4.1): Even with master](https://img.shields.io/badge/ViaVersion%20(4.4.1)-Even%20withmaster-brightgreen?style=flat-square) </br>![ViaRewind(2.0.2): 9 commits behind master](https://img.shields.io/badge/ViaRewind%20(2.0.2)-9%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(4.4.1): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.4.1)-Even%20with%20master-brightgreen?style=flat-square) </br><br>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/)

**Comment by kennytv** [comment]
See pinned issues
