### ISSUE TITLE
[1.19.1] Wild update features, e.g. mud bricks, are stone / incorrect for 1.19 clients

### ISSUE THREAD

**Issue by ajh123** [ViaVersion/ViaBackwards#488]
### '/viaversion dump' Output

https://dump.viaversion.com/d6c6f310042e7ea66a8e2b264bc9237b911a5154f37efea3540458da4647d3a9

### Console Error

There is no error

### Bug Description

Have a 1.19.1 server with 'Wild Update' features. Make 1.19 clients join and 'Wild Update' features look like 
![bug](https://user-images.githubusercontent.com/41990982/182929096-b20de140-50ba-4de1-8d52-25191dd2cbba.PNG)
### 

Or if a 1.19 client grabs them out of creative menus, they turn to stone.

### Steps to Reproduce

I'm running a server with
```
[19:48:52 INFO]: This server is running Paper version git-Paper-109 (MC: 1.19.1) (Implementing API version 1.19.1-R0.1-SNAPSHOT) (Git: 69950d5)
You are running the latest version
Previous version: git-Paper-36 (MC: 1.19)
```
All the plugins that I use can be found in the dump.
Put features from the 'Wild update' on a 1.19.1 world/server.
Get a 1.19 client to join.
Then you get something like the screenshot above.

### Expected Behavior

![real](https://user-images.githubusercontent.com/41990982/182930033-5d77a152-a98b-4ce2-816c-a6250f3cd776.PNG)
How it looks like on 1.19.1 client.

### Additional Server Info

I also use a Waterfall proxy
```
[19:53:04 INFO]: This server is running Waterfall version git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:5b246ea:499 by md_5
```
with the plugins
```
[19:54:13 INFO]: ------------=[ ServerUtils Plugins ]=-------------
[19:54:13 INFO]:  Plugins (16): AtParty, BungeeExtras, BungeeKickListener, CancelFriendRequest, FRL, Geyser-BungeeCord, Lobbysystem, LuckPerms, NuVotifier, PAF-Block, Party-Jump, PartyAndFriends, ServerUtils, SubIslands, SubServers-Bungee and floodgate
[19:54:13 INFO]: -------------------------------------------------
```

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--109%20%28MC%3A%201.19.1%29](https://img.shields.io/badge/Platform-git--Paper--109%20%28MC%3A%201.19.1%29-3498db?style=flat-square) </br>![ViaVersion (4.4.2-SNAPSHOT): 4 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.4.2--SNAPSHOT)-4%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaRewind(2.0.3-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaRewind%20(2.0.3--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(4.4.2-SNAPSHOT): 1 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.4.2--SNAPSHOT)-1%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/)

**Comment by Kichura** [comment]
Update viaversion and viabackwards as said above.

**Comment by ajh123** [comment]
Thanks, those work! Could you send this to anyone else who complains about this issue?
