### ISSUE TITLE
Minecraft 1.19 Entities/Block Not Showing on 1.19 But Working on 1.19.1 And 1.19.2

### ISSUE THREAD

**Issue by vinderguy** [ViaVersion/ViaBackwards#491]
### '/viaversion dump' Output

https://dump.viaversion.com/1a9401d756b9412236c6428c0813d33a721d52190d30295abf0f9cc31e87aeb3

### Bug Description

I am running the server on 1.19.2 (Paper build 118). When I connect from a 1.19 client, new 1.19 blocks are replaced with blocks from older versions, and Warden is replaced by the Iron Golem. Sculk Sensors are unaffected. It doesn't make sense, since 1.19 client supports these features natively. However, when I connect from 1.19.1 or 1.19.2, everything is working correctly (blocks and warden are visible).

**1.19 client connected to 1.19.2 server (bug)**
![Minecraft Screenshot 2022 08 08 - 22 15 05 88](https://user-images.githubusercontent.com/26736457/183509501-d24d1f6b-af16-42df-bd9b-6bdf5839a944.png)

**1.19.1 client connected to 1.19.2 server (correct)**
![Minecraft Screenshot 2022 08 08 - 22 13 15 48](https://user-images.githubusercontent.com/26736457/183509657-ce351b52-da32-42ff-b8bb-d0c93fb0a50f.png)

**1.19.2 client connected to 1.19.2 server (correct)**
![Minecraft Screenshot 2022 08 08 - 22 11 20 51](https://user-images.githubusercontent.com/26736457/183509713-a6d02ee6-44e4-4fed-aa92-4c610bbdc3ad.png)

### Steps to Reproduce

1. Set up and host a 1.19.2 Paper server.
2. Install both ViaVersion and ViaBackwards plugins.
3. Connect to the server from a 1.19 client.
4. See sculk blocks (and other 1.19 blocks) being replaced with blocks from older versions.
5. Disconnect from the server.
6. Connect to the server again, but from a 1.19.1 or 1.19.2 client.
7. See that everything works correctly.

### Expected Behavior

1.19.x blocks and entities should display normally to 1.19 clients connected to a 1.19.2 server.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--118%20%28MC%3A%201.19.2%29](https://img.shields.io/badge/Platform-git--Paper--118%20%28MC%3A%201.19.2%29-3498db?style=flat-square) </br>![ViaVersion (4.4.1): 12 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.4.1)-12%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(4.4.1): 5 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.4.1)-5%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/)

**Comment by vinderguy** [comment]
Closing. This is a duplicate of: https://github.com/ViaVersion/ViaBackwards/issues/482
