### ISSUE TITLE
Low version client -> Server 1.19.1_Invalid signature for profile public key.

### ISSUE THREAD

**Issue by Gu-f** [ViaVersion/ViaBackwards#493]
### '/viaversion dump' Output

https://dump.viaversion.com/de2547dfdee0035b8e6c58328f4e694d8575dca9145c3c709dacb62fb4e70d97

### Console Error

```
Put the paste.gg link or text here.
```
No Error.

### Bug Description

My server version is `paper1.19.1`, The login method is used `authlib-injector-1.2.1.jar`. 
In `server.properties`, I set `enforce-secure-profile=true`. 
When I use the 1.19.1 HCML client, it works. However, when I use a lower version client, such as 1.18.2 and 1.19. It has an error `Invalid signature for profile public key. Try restarting your game.`

### Steps to Reproduce

1. Startup paper1.19.1 with authlib-injector-1.2.1.jar
2. load ViaBackwards-4.4.1.jar and ViaVersion-4.4.1.jar
4. Use 1.19 or 1.18.2 or lower client login

### Expected Behavior

Enter the game normally.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--110%20%28MC%3A%201.19.1%29](https://img.shields.io/badge/Platform-git--Paper--110%20%28MC%3A%201.19.1%29-3498db?style=flat-square) </br>![ViaVersion (4.4.1): 15 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.4.1)-15%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(4.4.1): 5 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.4.1)-5%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/)

**Comment by kennytv** [comment]
Old clients don't have profile keys.

**Comment by Gu-f** [comment]
So, is there any good way to avoid this?

**Comment by kennytv** [comment]
The only way to allow old clients is to set `enforce-secure-profile` to false

**Comment by Gu-f** [comment]
ok, thanks!

**Comment by TyraVex** [comment]
Is there a way to connect to 1.19+ from 1.18+ and under without negociating with a server owner for changing weird settings in it's server.properties?

I feel like it could be bypassed, by reusing a 1.19 auth mod on  1.18+ and under, but I do not have any practical ideas  to do so.

**Comment by HowardZHY** [comment]
> Is there a way to connect to 1.19+ from 1.18+ and under without negociating with a server owner for changing weird settings in it's server.properties?
> 
> I feel like it could be bypassed, by reusing a 1.19 auth mod on 1.18+ and under, but I do not have any practical ideas to do so.

that's meanless, server owners should realize turn off that is the best choice

**Comment by TyraVex** [comment]
> that's meanless, server owners should realize turn off that is the best choice

Wow, interresting

So your solution is basically : 
There is a fix, but you can't enable it by yourself and you don't have to, because it's known that all server owners have already changed an option they never heard about in their server.properties and because everyone know that's better for some reason to disable security related options.
And in the case that this option isn't modified and you can't access/negociate with the server owner, you are screwed :)

Thank you.
