### ISSUE TITLE
Wooded Mountains Biome translation issue with clients < 1.16.5

### ISSUE THREAD

**Issue by terbin** [ViaVersion/ViaBackwards#496]
### '/viaversion dump' Output

https://dump.viaversion.com/e2db4191f116ce96aac162e1a31512860be7a57eef6c570f941e5e1c026825c8

### Bug Description

Running Paper 1.18.2 with ViaVersion 4.4.2 / 4.4.3 https://ci.viaversion.com/job/ViaVersion/648/ and ViaBackwards 4.4.2
(Also reproduced with Paper 1.19.2 build 133, ViaVersion 4.4.2 and ViaBackwards 4.4.2)

There is a biome translation issue when connecting to 1.18.2 Paper server a client version < 1.16

The **Windswept Forest** biome is translated improperly to **Forest**, while it should be translated to **Wooded Mountains**
https://minecraft.fandom.com/wiki/Windswept_Hills#Windswept_Forest

### Steps to Reproduce

Start 1.18.2 Paper server with ViaVersion
connect  with a client version < 1.16
Go to a Windswept Forest biome
Check the Biome information sent to the client with F3

### Expected Behavior

The Biome **Windswept Forest** should be translated to **Wooded Mountains**

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--387%20%28MC%3A%201.18.2%29](https://img.shields.io/badge/Platform-git--Paper--387%20%28MC%3A%201.18.2%29-3498db?style=flat-square) </br>![ViaVersion (4.4.3-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.4.3--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(4.4.2): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.4.2)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by kennytv** [comment]
https://github.com/ViaVersion/ViaBackwards/commit/c55402710800c0cbefd57699d4c8979d78aa7946
