### ISSUE TITLE
Kick on chest open

### ISSUE THREAD

**Issue by SageSphinx63920** [ViaVersion/ViaBackwards#497]
### `/viaversion dump` Output

https://dump.viaversion.com/f40b33f7286bdd17c42f9d869d6e68f001716a7dcc0920f8e4c5c007934a7c8c

### Console Error

https://bin.sageee.xyz/hukuxoroka.properties

### Bug Description

I found an outpost in my world and opened the chest on the top. Then i got kicked from the proxy.

### Steps to Reproduce

Login with 1.12.2 (Optifine)
Find an outpost
Open the chest

### Expected Behavior

I should be able to open chest without getting kicked.

### Additional Server Info

Im using the latest Velocity build and my server is running on the lastest Purpur(fork ok paper) build. 

Seed: 1637782194520608074
Server Version: 

> [14:55:15 INFO]: Current: git-Purpur-1732 (MC: 1.19)*
Previous: git-Purpur-1722 (MC: 1.19)
> * You are running the latest version

Coords: -216 78 103

Velocity Version:
> Velocity 3.1.2-SNAPSHOT (git-6be344d9-b162)

I forgot this line in my hastebin:
``[15:07:44 WARN] [viaversion]: ERROR IN Protocol1_12_2To1_13 IN REMAP OF WINDOW_ITEMS (0x15)``

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: velocity%203.1.2--SNAPSHOT%20%28git--6be344d9--b162%29](https://img.shields.io/badge/Platform-velocity%203.1.2--SNAPSHOT%20%28git--6be344d9--b162%29-3498db?style=flat-square) </br>![ViaVersion: Outdated](https://img.shields.io/badge/ViaVersion%20(4.4.0--1.19.1--rc2--SNAPSHOT)-Outdated!-red?style=flat-square) </br>![ViaBackwards: Outdated](https://img.shields.io/badge/ViaBackwards%20(4.4.0--1.19.1--pre6--SNAPSHOT)-Outdated!-red?style=flat-square) </br>![ViaRewind(2.0.3-SNAPSHOT): 1 commits behind master](https://img.shields.io/badge/ViaRewind%20(2.0.3--SNAPSHOT)-1%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/)
