### ISSUE TITLE
Internal Exception: io.netty.handler.codec.DecoderException

### ISSUE THREAD

**Issue by MagM1go** [ViaVersion/ViaBackwards#498]
### `/viaversion dump` Output

https://dump.viaversion.com/21247d20b029dcc0ab0856922d00ae8f0c4c5a92b098a42a644a12f1cf18b9b9

### Console Error

```
Internal Exception: io.netty.handler.codec.DecoderException:
com.veiversion.veaversion.exception.InformationException: Please post ...
(Packet Type: DECLARE_RECIPES), Type: FlatVarIntItem Array, Data: [Pair{TypeIVarInt, 835}, Pair{TypeIString, minecraft:acaia_boat}, Pair{TypeIString, crafting_shaped}, Pair{TypeIVarInt, 3}, Pair{TypeIVarInt, 2}, Pair{TypeIString, boat}, Pair(TypeIFlatVarIntItem Array, [Lcom.viaversion.viaversion.api.minecraft.item.Item;@47a7b343}], Source 0: com.viaversion.viaversion.protocols.protocol1_13_1to1_13.packets.InventoryPackets $2 (Anonymous), Packet ID: 84}]
                               Actual Error:
```

### Bug Description

1.19 purpur
Viabackwards + viaversion 4.4.1
1.19 ok
1.12.2 not working
1.13 error on console error
Versions >1.13 ok

### Steps to Reproduce

Logged with 1.13 and take this error

### Expected Behavior

didn't do anything

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Purpur--1735%20%28MC%3A%201.19%29](https://img.shields.io/badge/Platform-git--Purpur--1735%20%28MC%3A%201.19%29-3498db?style=flat-square) </br>![ViaVersion: Outdated](https://img.shields.io/badge/ViaVersion%20(4.4.2--SNAPSHOT)-Outdated!-red?style=flat-square) </br>![ViaBackwards: Outdated](https://img.shields.io/badge/ViaBackwards%20(4.4.1)-Outdated!-red?style=flat-square) </br><br>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/)
