### ISSUE TITLE
Strange banners.

### ISSUE THREAD

**Issue by CtrelokCvobods** [ViaVersion/ViaBackwards#501]
### '/viaversion dump' Output

https://dump.viaversion.com/3f3f3ffa2cb85832dd64d0167f81d077311a528a48b76b38e177b1785fe6ea9b

### Console Error

[09:36:12 WARN]: [ViaBackwards] Custom worlds heights are NOT SUPPORTED for 1.16 players and older and may lead to errors!
[09:36:12 WARN]: [ViaBackwards] You have min/max set to -64/256

### Bug Description

The bug is similar to https://github.com/ViaVersion/ViaBackwards/pull/414.
1.12.2 some banners are painted black.
1.19.2 is displayed correctly (the server is on this version).

### Steps to Reproduce

1) Building a map.
2) Restarting the server.
- Login from client 1.12.2 to server 1.19.2.
!Bug (screenshot)!
![2022-10-20_12-53-09](https://user-images.githubusercontent.com/87975297/196917565-9c5f8d39-e448-4d79-bccf-c04f26705711.png)

- Re-login from client 1.19.2.
.Correct display.
*Logged in from clean (without Forge and others) clients.
*Banners are repainted black exactly at certain coordinates.

### Expected Behavior

Correct display on the client 1.12.2

### Additional Server Info

**Minecraft 1.19.2:
Paper:
ViaVersion-4.4.2.jar
ViaBackwards-4.4.2.jar**

And

**Minecraft 1.19.2:
Paper:
ViaVersion-4.4.3-SNAPSHOT.jar
ViaBackwards-4.4.3-SNAPSHOT.jar**

* ViaVersion-4.5.0-22w42a-SNAPSHOT.jar - Not a worker.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--215%20%28MC%3A%201.19.2%29](https://img.shields.io/badge/Platform-git--Paper--215%20%28MC%3A%201.19.2%29-3498db?style=flat-square) </br>![ViaVersion (4.4.3-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.4.3--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(4.4.3-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.4.3--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by CtrelokCvobods** [comment]
I have destroyed blocks below 0 and above 255...
There is no more error...
