### ISSUE TITLE
Sounds wrong on 1.19.3 server - 1.19.2 client

### ISSUE THREAD

**Issue by Bobcat00** [ViaVersion/ViaBackwards#505]
### '/viaversion dump' Output

https://dump.viaversion.com/5f5c3fbb86afec202ba09ca1a1d4739c49418d78db6920c28e7aeeb381d90663

### Console Error

None

### Bug Description

1.19.3 Spigot server with 1.19.2 client: The client plays the wrong sounds for many things. Chests, mobs, animals, shooting arrows, arrows hitting the ground. It's quite hilarious. Something keeps ringing a bell. No idea what that's coming from; could be cows or bees.

### Steps to Reproduce

1.19.3 server, 1.19.2 client
Open and close a chest. Listen to the sounds.

### Expected Behavior

Opening a chest should not sound like a chicken.

### Additional Server Info

Just a server. No proxy.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: 3616--Spigot--d90018e--eecb4c0%20%28MC%3A%201.19.3%29](https://img.shields.io/badge/Platform-3616--Spigot--d90018e--eecb4c0%20%28MC%3A%201.19.3%29-3498db?style=flat-square) </br>![ViaVersion (4.5.1-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.5.1--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaRewind(2.0.3-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaRewind%20(2.0.3--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(4.5.0): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.5.0)-Even%20with%20master-brightgreen?style=flat-square) </br>
