### ISSUE TITLE
blocks turned into the mapping blocks

### ISSUE THREAD

**Issue by explorer3039** [ViaVersion/ViaBackwards#506]
### '/viaversion dump' Output

https://dump.viaversion.com/e3016ea2ee1c4cdd3ecf8ffd25c6178980ee37ef8df2328a968f5e5303ffd349

### Console Error

no console errors

### Bug Description

Placing >1.9 blocks(I use 1.9.4 to connect my 1.12.2 server) and use survival mode to destory it, then open your inventory, a normal block appears instead of a viabackwards block.

### Steps to Reproduce

1. Login with a < 1.12 client
2. Place some 1.12 blocks or take them into your inventory
3.open your inv and you will see It as a normal block. (For example if you place a dropper and break it in < 1.11 client, then open your inv, a normal dropper appeared instead of a dropper with the name 1.11 Shulker Box. And its behavior is the normal dropper's not the shulker box's)

### Expected Behavior

The block should not appear as a normal block.

### Additional Server Info

I don't have any additional plugins only viaversion and viabackwards

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Akarin--%22e912498%22%20%28MC%3A%201.12.2%29](https://img.shields.io/badge/Platform-git--Akarin--%22e912498%22%20%28MC%3A%201.12.2%29-3498db?style=flat-square) </br>![ViaVersion (4.5.1): Even with master](https://img.shields.io/badge/ViaVersion%20(4.5.1)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(4.5.1): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.5.1)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaRewind(2.0.2): 17 commits behind master](https://img.shields.io/badge/ViaRewind%20(2.0.2)-17%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump
