### ISSUE TITLE
ERROR IN Protocol1_19To1_19_1 IN REMAP OF SERVER_DATA (0x42)

### ISSUE THREAD

**Issue by LcyDev** [ViaVersion/ViaBackwards#508]
### '/viaversion dump' Output

https://dump.viaversion.com/dba6148d03398a3f748ad6f492b2382e2d851b2802a50e7790f8455c4336dbde

### Console Error

https://bin.bloom.host/iperoqatuk.md

### Bug Description

Trying to use the plugin on 1.19.2 and connecting with below

### Steps to Reproduce

1. Set up 1.19.2 server
2. Try joining with client below 1.19

### Expected Behavior

You should be able to join the server, and no errors related in console should show

### Additional Server Info

https://spark.lucko.me/hahm1T6bOo

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Purpur--1858%20%28MC%3A%201.19.2%29](https://img.shields.io/badge/Platform-git--Purpur--1858%20%28MC%3A%201.19.2%29-3498db?style=flat-square) </br>![ViaVersion (4.5.1): Even with master](https://img.shields.io/badge/ViaVersion%20(4.5.1)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(4.5.1): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.5.1)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by LcyDev** [comment]
I identified the issue `FreedomChat`

**Comment by Kichura** [comment]
Have checked to see if freedomchat continues to cause the same issue without the mass amount of plugins and i cannot reproduce it that way.

**Comment by LcyDev** [comment]
Hmm, interesting

**Comment by Kichura** [comment]
I am very likely certain it is just you using an incompatible version of freedomchat then.
