### ISSUE TITLE
Warden kicks 1.19.2 clients on 1.19.3 server

### ISSUE THREAD

**Issue by Jacques2** [ViaVersion/ViaBackwards#509]
### '/viaversion dump' Output

https://dump.viaversion.com/27eda482bc84e008cfdc960686107f3a1b71b5af02aaafeb616864d3a26deed5

### Bug Description

Warden digging down action causes 1.19.2 clients to be kicked on a 1.19.3 server. (Other versions untested)

The following kick message is displayed on the client:
"Internal Exception: io.netty.handler.codec.DecoderException: java.lang.ArrayIndexOutOfBoundsException"

There are no unusual console errors/logs.

### Steps to Reproduce

Login with a 1.19.2 client on a 1.19.3 server (earlier versions untested)
Enter creative mode
Build a small platform in the sky (where no sounds will distract the warden)
Summon a warden on the platform using a spawn egg or an active sculk shrieker
Wait for the warden to burrow down. You will be kicked when this happens

### Expected Behavior

You should not be kicked from the game.

### Additional Server Info

Running Paper Server 1.19.3 build 323
ViaVersion 4.5.1 and ViaBackwards 4.5.1 are installed

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--323%20%28MC%3A%201.19.3%29](https://img.shields.io/badge/Platform-git--Paper--323%20%28MC%3A%201.19.3%29-3498db?style=flat-square) </br>![ViaVersion (4.5.1): Even with master](https://img.shields.io/badge/ViaVersion%20(4.5.1)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(4.5.1): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.5.1)-Even%20with%20master-brightgreen?style=flat-square) </br>
