### ISSUE TITLE
players using 1.18.1 and below cannot connect to server in 1.18.2

### ISSUE THREAD

**Issue by RedBeanhgd** [ViaVersion/ViaBackwards#511]
### '/viaversion dump' Output

https://dump.viaversion.com/063c278e04ff5967d143492ce1eb51c2169dac416fd408b94cee57899753f4c1

### Bug Description

I'm running a fabric server in 1.18.2 and have already installed viafabric 0.4.9 and viabackwards 4.5.2 snapshot, but players using clients in 1.18.1 and below cannot access the server, saying the version of the server is incompatible with the client. 

### Steps to Reproduce

1. Install both viafabric and viabackwards on the fabric server.
2. Start the server.

### Expected Behavior

Players using client in versions below 1.18.2 cannot connect to the server

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: 0.4.9+19--main](https://img.shields.io/badge/Platform-0.4.9+19--main-3498db?style=flat-square) </br>![ViaVersion: Outdated](https://img.shields.io/badge/ViaVersion%20(4.4.3--SNAPSHOT)-Outdated!-red?style=flat-square) </br><br>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump

**Comment by RedBeanhgd** [comment]
Sorry, but I'm using the newest version viafabric and viabackwards, so how can i change the version of viaversion?

**Comment by Kichura** [comment]
Install latest viaversion to your mods folder so that viafabric can try to communicate with it; Otherwise modify the viafabric jar itself to replace the viaversion-4.4.3 with 4.5.1/4.5.2-snapshot copy and in the fabric.mod.json - tell it to use the new viaversion jar instead of old.
