### ISSUE TITLE
Multiple kick issues

### ISSUE THREAD

**Issue by Atomosic** [ViaVersion/ViaBackwards#513]
### '/viaversion dump' Output

https://dump.viaversion.com/532a17a94ac1eaa059b16c126fbdee6476880d42c2ba6e2fe53fb6cb3aabdd1d

### Console Error

```
Put the paste.gg link or text here.
```

### Bug Description

whenever a player is below 1.19.3 is within the simulation distance of a despawning warden, they will be kicked and unable to rejoin the SMP 

whenever a player is below 1.19.3 is sleeping in a bed during a server reboot, they are unable to leave the bed once the server restarts.

### Steps to Reproduce

log in with 1.19.2 on a 1.19.3 server, wait for a warden to despawn around you and get kicked

log in with 1.19.2 on a 1.19.3 server, sleep, and reboot the server. join back 

### Expected Behavior

player should not be kicked, or unable to leave the bed

### Additional Server Info

the server is a part of a bungee cord network. players get sent back to the fallback server and get sent back and forth until the server is rebooted for the warden bug.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--338%20%28MC%3A%201.19.3%29](https://img.shields.io/badge/Platform-git--Paper--338%20%28MC%3A%201.19.3%29-3498db?style=flat-square) </br>![ViaVersion (4.5.1): 3 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.5.1)-3%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(4.5.1): 2 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.5.1)-2%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump

**Comment by Kichura** [comment]
Does that issue continue to happen with the CI builds of via* ?

**Comment by Atomosic** [comment]
> Does that issue continue to happen with the CI builds of via* ?

Yes, the warden still causes kick issues if the player is on 1.19.2

**Comment by Kichura** [comment]
> > Does that issue continue to happen with the CI builds of via* ?
> 
> Yes, the warden still causes kick issues if the player is on 1.19.2

Then it's likely caused by a third-party plugin and possibly not our issue, please check if it still happens with just via* active.
