### ISSUE TITLE
Custom block mappings

### ISSUE THREAD

**Issue by pbcairo** [ViaVersion/ViaBackwards#514]
### Problem Description

I don't like the default mappings for ViaBackwards, such as I want the cut copper block to be purpur block but it's bricks.

### Solution Description

Add custom mappings to some config file or other YML files?

### Alternatives

if I want to use custom mappings now I need to manually modify `ViaBackwards*.jar/assets/mapping-*to*.json` using 7-Zip. It does work but I need to do it every time ViaBackwards gets updated.

**Comment by buzzcoding** [comment]
You can copy the mapping file to the ViaVersion plugin config directory. Look here: [https://github.com/ViaVersion/ViaBackwards/wiki](https://github.com/ViaVersion/ViaBackwards/wiki)

**Comment by pbcairo** [comment]
are entities possible in that way? as far as I know many entities are hardcoded to squids
