### ISSUE TITLE
World empty on 1.12 (server version 1.18)

### ISSUE THREAD

**Issue by C0D3-M4513R** [ViaVersion/ViaBackwards#517]
### '/viaversion dump' Output

https://dump.viaversion.com/19aa06a914347b383a8ba1d48be92a1cb9f40e65ae5bf2fa9ea37931aa4c031a

### Console Error

```
[17:36:47 WARN]: [ViaBackwards] Ignoring incoming plugin message with channel: LagGoggles
```
get's spammed in the console when joining with LagGoggles.

https://paste.gg/p/anonymous/c543d9cd7e90434cb34d89194edb424b
When joining with FTB Stoneblock 2 v1.16.1 the above linked messages appear once on join.
Can these be suppressed via config options?

### Bug Description

With 1.12 the world is just empty. If you get tp'd via console, you just fall (but you do get tp'd).
1.18:
![1.18](https://cdn.discordapp.com/attachments/864169000345927690/1064226157324664852/image.png)
1.12:
![1.12](https://cdn.discordapp.com/attachments/864169000345927690/1064226245732225104/image.png)

### Steps to Reproduce

1. Login to the server using 1.18 (native version) and observer the server/world functioning completely fine.
2. Login to the server using 1.12 and observe a black world. I am stuck at y=-60.
World is a superflat map.

### Expected Behavior

The world should just show up.

### Additional Server Info

also tested using 
- https://ci.viaversion.com/job/ViaVersion/670/
- https://ci.viaversion.com/view/ViaBackwards/job/ViaBackwards/298/

Server runs `paper-1.18.2-388.jar`
We are running a velocity proxy, using `player-info-forwarding-mode = "legacy"` option.
Velocity runs no plugins currently.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--388%20%28MC%3A%201.18.2%29](https://img.shields.io/badge/Platform-git--Paper--388%20%28MC%3A%201.18.2%29-3498db?style=flat-square) </br>![ViaVersion: Outdated](https://img.shields.io/badge/ViaVersion%20(4.4.2)-Outdated!-red?style=flat-square) </br>![ViaBackwards: Outdated](https://img.shields.io/badge/ViaBackwards%20(4.4.2)-Outdated!-red?style=flat-square) </br><br><br>To fix console spam, use `suppress-conversion-warnings: true` and `suppress-metadata-errors: true` in the _ViaVersion config.yml_. The errors will still happen but you won't be spammed with them and the issues will be ignored.<br>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump
