### ISSUE TITLE
World doesn't show up on `1.12` (server on `1.18`)

### ISSUE THREAD

**Issue by C0D3-M4513R** [ViaVersion/ViaBackwards#519]
### '/viaversion dump' Output

https://dump.viaversion.com/4b588e9f2b4a80931adfd3775bbe4a0a66d73c12174acaaff6e45dbcace0321c

### Bug Description

With 1.12 the world is just empty. If you get tp'd via console, you just fall (but you do get tp'd).
1.18:
![1.18](https://cdn.discordapp.com/attachments/864169000345927690/1064226157324664852/image.png)
1.12:
![1.12](https://cdn.discordapp.com/attachments/864169000345927690/1064226245732225104/image.png)

### Steps to Reproduce

1. Login to the server using 1.18 (native version) and observer the server/world functioning completely fine.
2. Login to the server using 1.12 and observe a black world. I am stuck at y=-60.
World is a superflat map.

### Expected Behavior

The world should just show up.

### Additional Server Info

Also tested with https://dump.viaversion.com/19aa06a914347b383a8ba1d48be92a1cb9f40e65ae5bf2fa9ea37931aa4c031a

Server runs `paper-1.18.2-388.jar`
We are running a velocity proxy, using `player-info-forwarding-mode = "legacy"` option.
Velocity runs no plugins currently.

also tested using 
- https://ci.viaversion.com/job/ViaVersion/670/
- https://ci.viaversion.com/view/ViaBackwards/job/ViaBackwards/298/

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

Duplicate issues, trying to fiddle with the bot: #518 #517

**Comment by Barvalg** [comment]
![Platform: git--Paper--388%20%28MC%3A%201.18.2%29](https://img.shields.io/badge/Platform-git--Paper--388%20%28MC%3A%201.18.2%29-3498db?style=flat-square) </br>![ViaVersion (4.5.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.5.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(4.5.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.5.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by Jo0001** [comment]
Please stop spamming new issues!
Are below y=0?

**Comment by Jo0001** [comment]
Below y=0 is only on 1.17 and up supported. For details see https://gist.github.com/Jo0001/4fe96cf5a78c8a00560ea985f3b9eb22

**Comment by Jo0001** [comment]
Please read the linked article (https://gist.github.com/Jo0001/4fe96cf5a78c8a00560ea985f3b9eb22)

**Comment by Jo0001** [comment]
Works fine for me. Make sure you follow the steps and use the correct datapack.
