### ISSUE TITLE
Error converting hover event component.

### ISSUE THREAD

**Issue by andrewkm** [ViaVersion/ViaBackwards#520]
### '/viaversion dump' Output

https://dump.viaversion.com/c4dde53e36de3b048672cbc8cb34bf58f3e1c09a84dca39b674dd123b2d3d887

### Console Error

https://pastebin.com/YrRksuX0

### Bug Description

Console errors.

### Steps to Reproduce

Unknown.

### Expected Behavior

No errors.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [x] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--371%20%28MC%3A%201.19.3%29](https://img.shields.io/badge/Platform-git--Paper--371%20%28MC%3A%201.19.3%29-3498db?style=flat-square) </br>![ViaVersion (4.5.2-SNAPSHOT): 3 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.5.2--SNAPSHOT)-3%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(4.5.2-SNAPSHOT): 1 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.5.2--SNAPSHOT)-1%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump

**Comment by andrewkm** [comment]
Issue persists. (https://pastebin.com/M6ifzCZG)
https://dump.viaversion.com/d61bf6fd96c17f59c1b5f19253bf93ea2e72e69c2e7382769167c37b172a1170

**Comment by Barvalg** [comment]
![Platform: git--Paper--379%20%28MC%3A%201.19.3%29](https://img.shields.io/badge/Platform-git--Paper--379%20%28MC%3A%201.19.3%29-3498db?style=flat-square) </br>![ViaVersion (4.5.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.5.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(4.5.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.5.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by andrewkm** [comment]
Fixed in one of our plugins as such:
https://i.imgur.com/FqcyEKc.png

This was happening when older clients would create auctions with our auction system.

**Comment by kennytv** [comment]
Thanks for the extra info, I made VB catch and ignore bad tags in item hovers, also suppressing those errors in general if the suppress option is enabled
