### ISSUE TITLE
1.16.5 user on a 1.19 world loading a custom mob

### ISSUE THREAD

**Issue by MrJoshuaT** [ViaVersion/ViaBackwards#521]
### '/viaversion dump' Output

https://dump.viaversion.com/d5b7e82f53f595582e32ec49d6651b6c0dcc6b67503471b3b74244dd1a323b79

### Console Error

```
[Put the paste.gg link or text here.](https://paste.gg/p/anonymous/d5945b8d492f4f9f87ab8e4b513b88a1)
```

### Bug Description

User in 1.16.5 user connecting to a 1.19 server, flying into a specific region. Which seems to have a "Copper Golem" (custom mob) in the region from this mod https://www.curseforge.com/minecraft/mc-mods/copper-golem-for-fabric. In normal vanilla this mob reverts to a pig if the client hasn't got it installed

### Steps to Reproduce

I believe the issue is with the Copper Golem mod, so if thats the case.

1. install https://www.curseforge.com/minecraft/mc-mods/copper-golem-for-fabric on a 1.19 server
2. with a 1.19 client spawn the copper golem mob
3. join the world with 1.16.5, notice the crash message

### Expected Behavior

The copper golem reverts back to a pig, the same way vanilla does it if the entity is unknown

### Additional Server Info

![image](https://user-images.githubusercontent.com/1721365/213015048-ce855742-3e10-4cfe-8d41-1039ac465575.png)

This is the error shown to the user

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: 0.4.9+19--main](https://img.shields.io/badge/Platform-0.4.9+19--main-3498db?style=flat-square) </br>![ViaVersion: Outdated](https://img.shields.io/badge/ViaVersion%20(4.4.3--SNAPSHOT)-Outdated!-red?style=flat-square) </br>![ViaBackwards: Outdated](https://img.shields.io/badge/ViaBackwards%20(4.4.2)-Outdated!-red?style=flat-square) </br><br>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump
