### ISSUE TITLE
1.16-1.18 clients can't join 1.19.2 server when using ViaBackwards in Velocity

### ISSUE THREAD

**Issue by XiaoHuiHui233** [ViaVersion/ViaBackwards#522]
### '/viaversion dump' Output

https://dump.viaversion.com/e9815ad97ac08eb1d0ad1a2d78e4b9168cc5b22cbaec1a0a989145248fb6006e

### Console Error

No Console Error

### Bug Description

The players using 1.16-1.18 clients will be kicked from the server when connecting to 1.19.2 server. The prompt message when kicking out is as follows:
```
Registry remapping failed: Received ID map for minecraft:mob_effect contains IDs unknown to the receiver!
                                       - minecraft.darkness
```

Some players report that they can join the 1.19 server normally through 1.16-1.18 at certain times, but the reports of not being able to join normally occur too frequently.
Based on this information, I can't figure out where the problem is. If you have a solution or steps for further analysis, please let me know. Thank you very much.

### Steps to Reproduce

1. Login in with 1.16.5 or 1.18.2 client
2. Join a 1.19.2 server

### Expected Behavior

You can join the 1.19.2 server instead of being kicked.

### Additional Server Info

Velocity 3.1.2-SNAPSHOT-195 for proxy with the following plugins:
- Geyser-Velocity
- LuckPerms 5.4.54
- ViaVersion 4.5.1
- ViaBackwards 4.5.1
The 1.19.2 server is using fabric 0.14.9 with the following mods:
- appleskin 2.4.1
- architectury 6.2.46
- carpet-extra 1.4.83
- carpet-tis-addition 1.40.0
- Chunky 1.3.38
- clean-logs 1.1.0
- fabric-api 0.60.0
- fabric-carpet 1.4.83+v220727
- fabric-language-kotlin 1.8.4+kotlin.1.7.20
- FabricProxy-Lite 2.3.0
- krypton 0.2.1
- lazydfu 0.1.3
- lithium 0.8.3
- magiclib 0.6.191+b8dbc1a-beta
- more-statistics 2.1.0
- NoChatReports 1.10.1
- plusls-carpet-addition 0.2.5-beta+380683d
- RoughlyEnoughItems 9.1.550
- servux 0.1.0
- spark 1.9.40

Although there are so many mods installed here, most of them do not modify the vanilla features. The only thing I think might be relevant to this question is FabricProxy-Lite, which is used to create a modern proxy between fabric and velocity.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: velocity%203.1.2--SNAPSHOT%20%28git--9cbaeb7b--b195%29](https://img.shields.io/badge/Platform-velocity%203.1.2--SNAPSHOT%20%28git--9cbaeb7b--b195%29-3498db?style=flat-square) </br>![ViaVersion (4.5.1): 7 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.5.1)-7%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(4.5.1): 3 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.5.1)-3%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump

**Comment by XiaoHuiHui233** [comment]
new dump:
https://dump.viaversion.com/a3828a0d79180791659ed7d929e9fc7c3e1f21553539b2ac46111db65818c2e4

**Comment by Barvalg** [comment]
![Platform: velocity%203.1.2--SNAPSHOT%20%28git--9cbaeb7b--b195%29](https://img.shields.io/badge/Platform-velocity%203.1.2--SNAPSHOT%20%28git--9cbaeb7b--b195%29-3498db?style=flat-square) </br>![ViaVersion (4.5.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.5.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(4.5.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.5.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by XiaoHuiHui233** [comment]
Confirm its caused by Xaero World Map. Closed this.
