### ISSUE TITLE
Comparators in 1.12.2 are backwards

### ISSUE THREAD

**Issue by MasterDash5** [ViaVersion/ViaBackwards#524]
### '/viaversion dump' Output

https://dump.viaversion.com/12a0227269c8f46c5180aa17d4e53dfb60042e8ba0eae13d03d8fe0425232fb6

### Console Error

N/A

### Bug Description

Comparators in 1.9-1.12.2 appear backwards when placed. This occurs with all 4 rotations of the comparator.

1.12.2:
![2023-01-25_17 29 39](https://user-images.githubusercontent.com/24374253/214730744-bd87e188-4e47-4e02-aa13-b4e6c23e4524.png)

1.13:
![2023-01-25_17 30 41](https://user-images.githubusercontent.com/24374253/214730797-98ed70a5-494f-4e2c-9101-fbb37ef8d122.png)

### Steps to Reproduce

1. Login with a 1.12.2 client.
2. Place a comparator.

### Expected Behavior

Comparators should face the other direction.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--384%20%28MC%3A%201.19.3%29](https://img.shields.io/badge/Platform-git--Paper--384%20%28MC%3A%201.19.3%29-3498db?style=flat-square) </br>![ViaVersion (4.5.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.5.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(4.5.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.5.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by Jo0001** [comment]
Can reproduce
![img](https://user-images.githubusercontent.com/47455182/214927135-d7303f5d-83a4-42ba-b00d-43e2dcd75f68.png)
