### ISSUE TITLE
1.18.1 client can't see entity name on 1.19.3 server

### ISSUE THREAD

**Issue by BredyAK** [ViaVersion/ViaBackwards#527]
### '/viaversion dump' Output

https://dump.viaversion.com/dccc7fbde79c075bb3d5c7fdfff5fe0f0a1216d9243b6b28aef823f153605eb9

### Console Error

no errors.

### Bug Description

for example, when you join game with 1.18.1 client, and you will see 1.19 frog entity as rabbit, with no name on it, even if you have set `always-show-original-mob-name` to `true`. if you install mod to forcely see entity's custom name, you will see it has a default name "Rabbit", it looks like the entity doesn't have a custom name set by the mapping file.
![](https://i.imgur.com/PEzDF9E.jpeg)

### Steps to Reproduce

1. join a 1.19.3 server with 1.18.1 client
2. spawn a frog entity
3. you will see it has no name

### Expected Behavior

fix the issue please, make the mapped entity name displayed as expacted.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git%3ABungeeCord--Bootstrap%3A1.19--R0.1--SNAPSHOT%3A19424ab%3A1678](https://img.shields.io/badge/Platform-git%3ABungeeCord--Bootstrap%3A1.19--R0.1--SNAPSHOT%3A19424ab%3A1678-3498db?style=flat-square) </br>![ViaVersion (4.6.0-23w05a-SNAPSHOT): Even with dev](https://img.shields.io/badge/ViaVersion%20(4.6.0--23w05a--SNAPSHOT)-Even%20with%20dev-brightgreen?style=flat-square) </br>![ViaBackwards(4.6.0-23w05a-SNAPSHOT): Even with dev](https://img.shields.io/badge/ViaBackwards%20(4.6.0--23w05a--SNAPSHOT)-Even%20with%20dev-brightgreen?style=flat-square) </br>
