### ISSUE TITLE
Ghost block destroy permission glitch on 1.18.2 client

### ISSUE THREAD

**Issue by 7wOv6ySCjo** [ViaVersion/ViaBackwards#529]
### `/viaversion dump` Output

https://dump.viaversion.com/fd3ccaf1f969b2543a9288f0844ddd81ad8da1691375a400aee1215a3a8c4e25

### Console Error

N/A

### Bug Description

Clients not using server version 1.19.3 causes blocks to disappear when breaking and reappear with a re-join. This happens with any protection plugin like PlotSquared or ProtectionStones. The error does not happen if I use the 1.19.3 client only with older versions. 

All plugins are updated to their latest dev version.

Youtube video: https://youtu.be/yukaO-5o-dU

### Steps to Reproduce

log into a paper 1.19.3 server with the plotsquared plugin installed fresh and 1.18.2 client and try to break a block on an unprotected plot. The bug appears.

### Expected Behavior

N/A

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--420%20%28MC%3A%201.19.3%29](https://img.shields.io/badge/Platform-git--Paper--420%20%28MC%3A%201.19.3%29-3498db?style=flat-square) </br>![ViaVersion (4.6.0-1.19.4-pre1-SNAPSHOT): 1 commits behind dev](https://img.shields.io/badge/ViaVersion%20(4.6.0--1.19.4--pre1--SNAPSHOT)-1%20commit(s)%20behind%20dev-yellow?style=flat-square) </br>![ViaBackwards(4.6.0-1.19.4-pre1-SNAPSHOT): Even with dev](https://img.shields.io/badge/ViaBackwards%20(4.6.0--1.19.4--pre1--SNAPSHOT)-Even%20with%20dev-brightgreen?style=flat-square) </br><br>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump

**Comment by 7wOv6ySCjo** [comment]
the problem persists.

**Comment by Kichura** [comment]
Cannot reproduce anymore in dev builds of via*, assuming it as fixed - if this somehow persists there too then make a reply and it will be reopened.

**Comment by 7wOv6ySCjo** [comment]
> After more investigation: It will remain unfixed for vanilla's spawn-protection, as it would require caching the entire player world state, which is quite expensive, and there don't seem to be any Paper events to use here. The same applies to plugins using the PlayerInteractEvent to cancel block breaks - WG and ProtectionStones properly use the BlockBreakEvent for that, so those shouldn't be the cause here. Otherwise, we unfortunately don't easily have access to the block to reset it manually.
> 
> This is a result from 1.19 block ack changes, where the server no longer resends the block on cancelled breaks, and instead just tells the client to revert the action itself

Do you think it would be a good idea to ask the Paper team to try to incorporate this event into the API? I see it as extremely necessary to try to fix this dreadful visual bug, as it happens even on a vanilla/paper server. Without plugins. With ViaVersion alone, they should be able to get this resolved.
