### ISSUE TITLE
[Feature Request] Add support for 'mob heads on note blocks interaction sound' to client versions lower than 1.19.3

### ISSUE THREAD

**Issue by Pantera07** [ViaVersion/ViaBackwards#534]
### Problem Description

In clients with versions lower than 1.19.3, the 'mob heads on note blocks interaction' sound from 1.19.3 and 1.19.4 servers cannot be heard. As it is scheduled to be officially added in 1.20, it would be great if players could hear the mob sound in versions lower than 1.19.3.

### Solution Description

Even if the client version is lower than 1.19.3, it has the mob sound resource, so it should be possible to enable players to hear it.

### Additional Info

![1](https://user-images.githubusercontent.com/89838384/226103805-ddaec26d-f31c-4fe5-9355-6c406c27fa81.png)

**Comment by kennytv** [comment]
See https://github.com/ViaVersion/ViaBackwards/issues/326
