### ISSUE TITLE
Where is 4.6.1 jar file?

### ISSUE THREAD

**Issue by Anduin2017** [ViaVersion/ViaBackwards#535]
### '/viaversion dump' Output

https://github.com/ViaVersion/ViaBackwards/releases

### Console Error

```
Put the paste.gg link or text here.
```

### Bug Description

https://github.com/ViaVersion/ViaBackwards/releases

Where is the jar file? 

![image](https://user-images.githubusercontent.com/19531547/226325860-ef4af0fb-9b24-4775-83bb-f9483f723788.png)

### Steps to Reproduce

Open GitHub Release page.

### Expected Behavior

I wrote an automatic script to download latest jar file to all my servers. But currently all servers are crashing...

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Error: Invalid or missing dump](https://img.shields.io/badge/Error-Invalid/missing%20dump-red?style=flat-square) </br>

**Comment by kennytv** [comment]
Uploaded it
