### ISSUE TITLE
ViaBackwards fail to load

### ISSUE THREAD

**Issue by Ibotmealot** [ViaVersion/ViaBackwards#540]
### '/viaversion dump' Output

https://dump.viaversion.com/937711a2877ffec066229c6b16067dfece8f203f03894cb38cbe8c8e85b5be6e

### Console Error

https://paste.gg/p/anonymous/973b5d66283d4f279d8ff2d3e34e923c

### Bug Description

The plugin fails to load on startup

### Steps to Reproduce

1. Use Purpur 1.19.3
2. Install ViaVersion and ViaBackwards
3. Start the server
4. ViaVersion loads, ViaBackwards does not. 

### Expected Behavior

ViaBackwards loads

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Purpur--1917%20%28MC%3A%201.19.3%29](https://img.shields.io/badge/Platform-git--Purpur--1917%20%28MC%3A%201.19.3%29-3498db?style=flat-square) </br>![ViaVersion (4.6.2): 2 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.6.2)-2%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump</h3>

**Comment by Kichura** [comment]
Update via*, otherwise bad config or bad third party plugin.
