### ISSUE TITLE
Selection of versions

### ISSUE THREAD

**Issue by games4681** [ViaVersion/ViaBackwards#542]
### Problem Description

The problem: when I install the plugin it allows players to connect to my server from all versions even from too old versions: 1.8 or 1.9 are very old versions and not suitable if my server is 1.19.3 and I want to allow only 1.18.2 the players will see the blocks completely different in 1.8 and also the mobs and it doesn't fit.

### Solution Description

The solution: In the config, allow the server administrator to choose which versions to allow in the plugin and the versions he does not register will not work to avoid the problem I listed above

**Comment by kennytv** [comment]
See block versions int the ViaVersion config

**Comment by games4681** [comment]
Thank you very much!
