### ISSUE TITLE
Can't Join 1.16.5 On 1.8.9 

### ISSUE THREAD

**Issue by NeilPazon** [ViaVersion/ViaBackwards#545]
### '/viaversion dump' Output

https://dump.viaversion.com/a7a4e4585358fdd9ddba0245f4e67ffa9d547a1071d43055c4cd7984ddc50751

### Console Error

```
Put the paste.gg link or text here.
```

### Bug Description

I Can't Join The 1.16.5 Server It Has Via Backwards And Via Version Why

### Steps to Reproduce

1.Login 1.8.9
2.Cant Join

### Expected Behavior

I Will Able To Join 1.16.5 With 1.8.9 By Via Backwards 

### Additional Server Info

I Use World Edit And Using The Paper Software

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--794%20%28MC%3A%201.16.5%29](https://img.shields.io/badge/Platform-git--Paper--794%20%28MC%3A%201.16.5%29-3498db?style=flat-square) </br>![ViaVersion (4.6.2): 6 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.6.2)-6%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(4.6.1): 9 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.6.1)-9%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump</h3>

**Comment by Kichura** [comment]
Install ViaRewind to your server as it is resposible for 1.8.9 support.
