### ISSUE TITLE
Can't connect with 1.19.2 to 1.19.4 server

### ISSUE THREAD

**Issue by Dandraghas** [ViaVersion/ViaBackwards#546]
### '/viaversion dump' Output

https://dump.viaversion.com/e3bbc5a2b73a71ec0f19282a13f39fe9449913ebd4c9068133069ec26bc370c4

### Console Error

Note: its not a console error but a client error:

this error gives vannilla 1.19.2 client
```
io.netty.handler.codec.DecoderException: java.lang.NullPointerException: Cannot invoke "qusa.alint, qx)" because the return value of "java.util.Map.get(Object)" is null.
```

this error gives modified(quilt) 1.19.2 client:
```
io.netty.handler.codec.DecoderException: java.lang.NullPointerException: Cannot invoke "net.minecraft.class_2539$class_4532.method_22310(int, net.minecraft.class_2540)" because the return value of "java.util.Map.get(Object)" is null
```

### Bug Description

I Can't connect to my paper 1.19.4 server using viabackwards

before i get 'Disconnected' and then error

also every other version like 1.18.* work except 1.19.2

and i tried viaversion 4.6.1 and 4.6.2 but i get same error

### Steps to Reproduce

1. Try to connect with 1.19.2 client
2. See error

### Expected Behavior

Connection with 1.19.2 to 1.19.4 server is working normarly

### Additional Server Info

I use Velocity, but all viabackwards and viaversions is placed on backend servers.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--538%20%28MC%3A%201.19.4%29](https://img.shields.io/badge/Platform-git--Paper--538%20%28MC%3A%201.19.4%29-3498db?style=flat-square) </br>![ViaVersion: Outdated](https://img.shields.io/badge/ViaVersion%20(4.6.1)-Outdated!-red?style=flat-square) </br>![ViaBackwards(4.6.1): 9 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.6.1)-9%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump and the issue will be reopened</h3>

**Comment by Dandraghas** [comment]
https://dump.viaversion.com/78ef99be4c61458bb2950bca94f060e00f909b6a8af66c368a1c5a4d2a801313

**Comment by Barvalg** [comment]
![Platform: git--Paper--538%20%28MC%3A%201.19.4%29](https://img.shields.io/badge/Platform-git--Paper--538%20%28MC%3A%201.19.4%29-3498db?style=flat-square) </br>![ViaVersion (4.6.3-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.6.3--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(4.6.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.6.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>
