### ISSUE TITLE
Can't join a specific 1.19.4 server from 1.8.8 client using viabackward

### ISSUE THREAD

**Issue by Mollomm1** [ViaVersion/ViaBackwards#548]
### '/viaversion dump' Output

https://dump.viaversion.com/cbfa84a995cfa9bb8a5c4538ebc531f92df1fa8ca7063fd2fde7809cd760f1a1

### Console Error

https://paste.gg/p/anonymous/64bed366d2c248a0adcd1df673859056

### Bug Description

ViaBackward works fine for others 1.19.4 Servers, but not for this one.

i am using [ViaProxy](https://github.com/RaphiMC/ViaProxy), but it still a ViaBackward related issue.

### Steps to Reproduce

1. launch the [ViaProxy](https://github.com/RaphiMC/ViaProxy)  and **survive.mineinabyss.com** as server with **1.19.4** as version with a **valid online account**.
2. try to join the proxied server using a 1.8.8 client.
3. it disconnect immediately

### Expected Behavior

load the server without major problems (if we forget about texture packs)

### Additional Server Info

i am using [ViaProxy](https://github.com/RaphiMC/ViaProxy) to join the server **survive.mineinabyss.com**

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: 2.2.4](https://img.shields.io/badge/Platform-2.2.4-3498db?style=flat-square) </br>![ViaVersion (4.7.0-23w17a-SNAPSHOT): Even with dev](https://img.shields.io/badge/ViaVersion%20(4.7.0--23w17a--SNAPSHOT)-Even%20with%20dev-brightgreen?style=flat-square) </br>![ViaBackwards(4.7.0-1.20-pre5-SNAPSHOT): Even with dev](https://img.shields.io/badge/ViaBackwards%20(4.7.0--1.20--pre5--SNAPSHOT)-Even%20with%20dev-brightgreen?style=flat-square) </br>
