### ISSUE TITLE
1.13 support.

### ISSUE THREAD

**Issue by TheIntelloBox** [ViaVersion/ViaBackwards#55]
Hey,

Could you update ViaBackwards for 1.13 ?

**Comment by TheIntelloBox** [comment]
@Matsv

**Comment by FrozenBeard** [comment]
Is this going to happen?

**Comment by Tiippex** [comment]
I think there are already a few forked 1.13 versions.

**Comment by FrozenBeard** [comment]
@Tiippex link me!

**Comment by Tiippex** [comment]
https://github.com/ForceUpdate1/ViaBackwards/commits/master
From @ForceUpdate1

**Comment by ForceUpdate1** [comment]
https://ci.viaversion.com/view/ViaBackwards/job/ViaBackwards-DEV/

**Comment by Rand404** [comment]
> https://github.com/ForceUpdate1/ViaBackwards/commits/master
> From @ForceUpdate1

How would I go about compiling this?



> https://ci.viaversion.com/view/ViaBackwards/job/ViaBackwards-DEV/

This doesn't seem to work correctly for allowing someone on 1.12 to connect to a server running 1.13.2

**Comment by successed** [comment]
PLEASE UPDATE 1.13.2

**Comment by Disorbs** [comment]
more like update to 1.14.3 lol

**Comment by Patbox** [comment]
> more like update to 1.14.3 lol

https://github.com/ViaVersion/ViaBackwards/pull/109
They work on a update. https://jenkins.krusic22.com/job/ViaBackwards-ForceUpdate1-1.14/
