### ISSUE TITLE
No NBT for 1.20 items

### ISSUE THREAD

**Issue by bangetto** [ViaVersion/ViaBackwards#551]
### '/viaversion dump' Output

https://dump.viaversion.com/f68577e22996904f11e2e9567835c7d62a78f5241e2ade63e12d10f20588cef1

### Console Error

there's no error but here you go
https://paste.gg/p/anonymous/5ac27441f03f46b4acf58ad47d2e8f51

### Bug Description

the items that have been added in 1.20 has no NBT

### Steps to Reproduce

give yourself an 1.20 item in a version prior to it.

### Expected Behavior

the item should have an NBT [name and protocols]

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: 3777--Spigot--723951c--f3b2b22%20%28MC%3A%201.20%29](https://img.shields.io/badge/Platform-3777--Spigot--723951c--f3b2b22%20%28MC%3A%201.20%29-3498db?style=flat-square) </br>![ViaVersion (4.7.0): 1 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.7.0)-1%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(4.7.0): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.7.0)-Even%20with%20master-brightgreen?style=flat-square) </br><br><h3>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump</h3>

**Comment by abhisantos** [comment]
Just tested with the new version and the issue persists.
Dump: https://dump.viaversion.com/788635cdf70ae4a679f90525252268e8c397aed2dc3338d42db0e31c714ce7df

This is happening in spigot/paper 1.19.4 and 1.19.3

**Comment by Barvalg** [comment]
![Platform: git--Paper--445%20%28MC%3A%201.19.3%29](https://img.shields.io/badge/Platform-git--Paper--445%20%28MC%3A%201.19.3%29-3498db?style=flat-square) </br>![ViaVersion (4.7.1-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.7.1--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaRewind(2.0.3): 4 commits behind master](https://img.shields.io/badge/ViaRewind%20(2.0.3)-4%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(4.7.0): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.7.0)-Even%20with%20master-brightgreen?style=flat-square) </br><br><h3>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump</h3>

**Comment by abhisantos** [comment]
This bug persists in the latest update today...

**Comment by bangetto** [comment]
Yeah, and quite annoying because I make a pack where I backport the items from newer versions and this is the only thing stopping me.
