### ISSUE TITLE
Broken new trim pattern texture

### ISSUE THREAD

**Issue by Pantera07** [ViaVersion/ViaBackwards#554]
### '/viaversion dump' Output

https://dump.viaversion.com/45f86bbf95ad2422a4a09e913e29e4c6fe116938eb25df9cd6750d0b7bebff88

### Bug Description

1.20 new trim pattern texture is broken on 1.19.4 client.

### Steps to Reproduce

https://youtu.be/ah8gPhUQqsA

### Expected Behavior

I was expecting the 1.20 new trim pattern texture to look fine on the 1.19.4 client, or replaced with the trim pattern supported by 1.19.4.

### Additional Server Info

Server: 1.20
Client: 1.19.4

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--17%20%28MC%3A%201.20%29](https://img.shields.io/badge/Platform-git--Paper--17%20%28MC%3A%201.20%29-3498db?style=flat-square) </br>![ViaVersion (4.7.1-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.7.1--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(4.7.1-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.7.1--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by Barvalg** [comment]
![Platform: git--Paper--176%20%28MC%3A%201.20.1%29](https://img.shields.io/badge/Platform-git--Paper--176%20%28MC%3A%201.20.1%29-3498db?style=flat-square) </br>![ViaVersion (4.8.0-1.20.2-pre2-SNAPSHOT): Even with dev](https://img.shields.io/badge/ViaVersion%20(4.8.0--1.20.2--pre2--SNAPSHOT)-Even%20with%20dev-brightgreen?style=flat-square) </br>
