### ISSUE TITLE
Error when joining 1.20 server with 1.19.2 client

### ISSUE THREAD

**Issue by RaphiMC** [ViaVersion/ViaBackwards#556]
### '/viaversion dump' Output

https://dump.viaversion.com/da2cea1ddd366e949d25166cc44215c40d369706d885dde1e75308fe030d315e

### Console Error

https://mclo.gs/ZmuUjJP

### Bug Description

Connect to mc.vanillasquad.com:25565 (1.20) with a 1.19.2 client and the client will be disconnected immediately

### Steps to Reproduce

Connect to mc.vanillasquad.com:25565 (1.20) with a 1.19.2 client

### Expected Behavior

No disconnect

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: 2.2.7--SNAPSHOT](https://img.shields.io/badge/Platform-2.2.7--SNAPSHOT-3498db?style=flat-square) </br>![ViaVersion (4.7.1-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.7.1--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(4.7.1-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.7.1--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>
