### ISSUE TITLE
1.18(.1) does not work on 1.20/1.20.1 servers

### ISSUE THREAD

**Issue by Kichura** [ViaVersion/ViaBackwards#558]
### '/viaversion dump' Output

https://dump.viaversion.com/87e6e039affadf6c2cd4a90beb191cf61bd29f9c2f714a2ae02b85845f7cc8e6

### Console Error

*(No console errors have been discovered)*

### Bug Description

Joining any 1.20/1.20.1 server results in 1.18.1 and older clients getting booted from the server entirely for the following message:

```
Incomplete set of tags received from server.
Please contact server operator.
```

### Steps to Reproduce

1. Create a test server that runs on 1.20/1.20.1 of either Paper or Purpur,
2. Create a test client that runs on either 1.18.1 or older,
3. Start the server and tell the client to try and connect to it on post-boot,
4. Expect the error to occur from there.

### Expected Behavior

1.18.1 and older clients are able to connect properly without errors.

### Additional Server Info

1. This setup did not use any proxies,
2. Purpur 1.20.1 - Build 1992,
3. ViaVersion and ViaBackwards. (Both are on 4.7.1-SNAPSHOT)

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Purpur--1992%20%28MC%3A%201.20.1%29](https://img.shields.io/badge/Platform-git--Purpur--1992%20%28MC%3A%201.20.1%29-3498db?style=flat-square) </br>![ViaVersion (4.7.1-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.7.1--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(4.7.1-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.7.1--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by Kichura** [comment]
As for client's end, Managed to discover this:

![mc](https://github.com/ViaVersion/ViaBackwards/assets/68134602/a33abd86-41c6-45e0-a4e0-33a5e1aefbbb)

**Comment by hasankayra04** [comment]
Hoping it will get fixed soon.
(Wanted to receive updates in my mail, so made this comment. Sorry if it's found to be disturbing.)

**Comment by kennytv** [comment]
Easy workaround: Use 1.18.2 instead

**Comment by hasankayra04** [comment]
Is this change rolled back out or not out to stable yet?
