### ISSUE TITLE
Add a config where players could set their own mappings.

### ISSUE THREAD

**Issue by paj1s** [ViaVersion/ViaBackwards#559]
### Problem Description

I think the title is pretty self explanatory. Right now it's incredibly complicated to change a single thing for client. And i don't don't know about other people but i would be so happy if i could set my own substitutes.

### Solution Description

Well i don't exactly how to implement this internaly. But why not make it so people could just paste the contents of the diff folder from the "Mappings", edit it, via would check these files upon start aand if they're different from it's own and valid it will use them.

**Comment by Camotoy** [comment]
https://github.com/ViaVersion/ViaBackwards/wiki does this help?

**Comment by paj1s** [comment]
I think im being misunderstood i want to (as per wiki) "Changing block/item/sound id mappings".

**Comment by FlorianMichael** [comment]
You should provide a more detailed description about what you want to do and what you tried to get it, also consider joining our discord server for support, will close the issue for now as we don't have any plans to change the mapping system at the moment.
