### ISSUE TITLE
"itemnames" mappings aren't implemented when ViaFabric is used by the client to connect to a vanilla 1.20.1 server

### ISSUE THREAD

**Issue by FrostBird347** [ViaVersion/ViaBackwards#560]
### '/viaversion dump' Output

https://dump.viaversion.com/fb4dd03cc0aaffd52b5863dfad4200ee708270bdb1f20cf54d3b245a45786ef6

### Bug Description

"itemnames" mappings aren't applied to the client when viafabric and viabackwards is used to connect to a vanilla 1.20.1 server from a 1.19.4 client.
This results in new 1.20.1 items (e.g `minecraft:pitcher_pod` and `minecraft:sniffer_egg`) being impossible to differentiate from the older mapped block without the use of commands, which require operator permissions and thus are not usually a viable solution.
new 1.20.1 blocks are also not autocompleted in the command list, nor do new advancements have mapped text in the achievements menu or the achievement toast.

Video: https://youtu.be/MYgPE48EmZ8

### Steps to Reproduce

1. Login to a vanilla 1.20.1 server with a fabric 1.19.4 client that has ViaFabric and ViaBackwards installed
2. Make sure you are in survival with operator permissions, nor with any 1.20 advancements unlocked
3. Type in `/give @s pitcher_pod` and take note of the lack of autocomplete
4. Take note of the "lilac" that is impossible to tell apart from a real lilac without commands
5. Place the pitcher pod (lilac) on some farmland and take note of the advancement toast text
6. Verify that the advancement text is missing through the advancements menu

### Expected Behavior

- The command to spawn in the pitcher pod should have autocompletion
- The advancement for planting the pitcher pod should be named
- The pitcher pod should be called "1.20 Pitcher Pod", as shown here: https://github.com/ViaVersion/Mappings/blob/8ae0d4985b56c2133ab6e9d8ac21fe68be85ee8c/mappings/diff/mapping-1.20to1.19.4.json#LL495C21-L495C37

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [ ] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: 0.4.10+39--main](https://img.shields.io/badge/Platform-0.4.10+39--main-3498db?style=flat-square) </br>![ViaVersion (4.7.0): 9 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.7.0)-9%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(4.7.0): 6 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.7.0)-6%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump</h3>

**Comment by kennytv** [comment]
Updating ViaBackwards to a ci build should fix the issue. With ViaFabric, you can do that by simply moving a jar from https://ci.viaversion.com/view/ViaBackwards/job/ViaBackwards/ into the mods directory as well

**Comment by FrostBird347** [comment]
I have verified that the item names are fixed in the latest CI version, however the command completion and advancement name issues are still present
