### ISSUE TITLE
Smithing Table not opening on 1.20 Paper Server with 1.16 Client (<1.20)

### ISSUE THREAD

**Issue by kforbro** [ViaVersion/ViaBackwards#561]
### '/viaversion dump' Output

https://dump.viaversion.com/26f092dd0043728616b1aaf765f0a54aebed757fcd50667c89202ff375f4e6ba

### Console Error

```
Put the paste.gg link or text here.
```

### Bug Description

Smithing Table does not open for Java players (1.16) on 1.20 paper server.

### Steps to Reproduce

Start a paper server using the latest 1.20 version.

Join on a 1.16.5 java Client.
Place or locate a smithing table.
Interact by right clicking.
Nothing happens.

### Expected Behavior

Should open up GUI for the Smithing Table.  (maybe custom?)

### Additional Server Info

Paper 1.20.1

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--32%20%28MC%3A%201.20.1%29](https://img.shields.io/badge/Platform-git--Paper--32%20%28MC%3A%201.20.1%29-3498db?style=flat-square) </br>![ViaVersion (4.7.1-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.7.1--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(4.7.1-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.7.1--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by SLeSToR** [comment]
When will you fix it approximately?

**Comment by Leahcimkrob** [comment]
We have the same issue.

**Comment by Kichura** [comment]
> When will you fix it approximately?

There is no ETA to when issues are fixed, but since this is a low priority issue - it shouldn't come off as a "fix asap" scenario.

**Comment by kennytv** [comment]
VB does not add new features to old clients. This may or may not be done in the future but in general is not a target
