### ISSUE TITLE
Via backwards is using wrong biome mappings

### ISSUE THREAD

**Issue by paj1s** [ViaVersion/ViaBackwards#565]
### '/viaversion dump' Output

https://dump.viaversion.com/0a959ec8af33562bc1b42c55a2e64c7f4dc8f12eb42916ccc1679ba4b5823794

### Bug Description

I tested versions 1.16.2, 1.16.3, 1.16.4 and 1.16.5 and it's using wrong (new) biomes which weren't a thing when these versions came out, biomes such as "windswept_hills".
When i open a singleplayer world it's using the old biomes this version is suposed to  such as "mountains".
This makes havoc with mods such as world downloaders. Some will just crash, others will download the world and upon opening it every biome in the world will turn plains.
There is also a weird thing in version 1.16.1. There the biomes are utterly berserk, they are at random places and sizes, just broken.

### Steps to Reproduce

Make a server with version 1.20.1 (I tested 1.19.4, 1.20 and 1.20.1) with plugins viaversion and viabackwards. Connect with any 1.16.x client to the server and look at the biomes with f3.

### Expected Behavior

The biomes should corespond to vanilla.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--32%20%28MC%3A%201.20.1%29](https://img.shields.io/badge/Platform-git--Paper--32%20%28MC%3A%201.20.1%29-3498db?style=flat-square) </br>![ViaVersion (4.7.0): 14 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.7.0)-14%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(4.7.0): 6 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.7.0)-6%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump</h3>

**Comment by paj1s** [comment]
I tried the new version ofc and the issue persists and it wont let me create another dump rn.

**Comment by kennytv** [comment]
Biomes have been almost entirely data-driven since 1.16.2, so this is an issue with world downloader, not Via

**Comment by paj1s** [comment]
How could this be a problem with a world downloader? The biomes are just incorrect, when i generate the same world by the same seed and go to same mountain, in the singleplayer the biome would be named "mountains" and on the server the name would be "windswept_hills" which according to official minecraft wiki was renamed to this in the 1.18.  An i don't even have the world downloader installed. So you tell me how is it changing the biome name.

**Comment by kennytv** [comment]
They aren't incorrect, that's the point. The *server* determines which biomes exist and what their properties are and then sends this data to the client on join, the exact same could happen on a 1.16.2 server. If mods don't handle custom biome definitions correctly, that's on them

**Comment by paj1s** [comment]
Ok, i get it. Can i make it so the server will tell the client other names? Just to make the mod work?

**Comment by kennytv** [comment]
Probably only with a server datapack that keeps the same data/ids as vanilla but replaces the name

**Comment by paj1s** [comment]
Anyways thanks
