### ISSUE TITLE
Otherside has no NBT

### ISSUE THREAD

**Issue by bangetto** [ViaVersion/ViaBackwards#568]
### '/viaversion dump' Output

https://dump.viaversion.com/fca43e46825d6b731f4cdb4412311c0c36df498315790b0e4f1a8438f112bf81

### Console Error

no error

### Bug Description

the other side music disc don't have an NBT

I think this is similar issue as  #551  

### Steps to Reproduce

- create a 1.18+ server
- join with an older version
- give yourself the otherside disc

### Expected Behavior

otherside should have an NBT [name & protocols] like disc 5 and any other item

### Additional Server Info

1.20.1 paper server, 1.16.5 client

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.

**Comment by Barvalg** [comment]
![Platform: git--Paper--68%20%28MC%3A%201.20.1%29](https://img.shields.io/badge/Platform-git--Paper--68%20%28MC%3A%201.20.1%29-3498db?style=flat-square) </br>![ViaVersion (4.7.1-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.7.1--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(4.7.1-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.7.1--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>
