### ISSUE TITLE
Flat world doesn´t load

### ISSUE THREAD

**Issue by SansonDN7** [ViaVersion/ViaBackwards#569]
### '/viaversion dump' Output

https://dump.viaversion.com/676ac84f0fad93d632570b505db74041f15a369ad71eef142eaf4d3240e349ca

### Console Error

```
Put the paste.gg link or text here.
```
No console Error

### Bug Description

Flat world doesn´t load in a server in 1.20.1 with a launcher in 1.14 minecraft java 

### Steps to Reproduce

Enter in a minecraft server in version 1.20.1 with multiverse. Your minecraft is in versión 1.14. Try to enter in a flat world. All the world except for the entities is black and you can´t move.

### Expected Behavior

You can see the world and move

### Additional Server Info

Use multiversecore to create the flat world. use viaversion and via backwards. 

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: 3835--Spigot--3374045--5daeb50%20%28MC%3A%201.20.1%29](https://img.shields.io/badge/Platform-3835--Spigot--3374045--5daeb50%20%28MC%3A%201.20.1%29-3498db?style=flat-square) </br>![ViaVersion (4.7.0): 19 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.7.0)-19%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(4.7.0): 8 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.7.0)-8%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump</h3>

**Comment by SansonDN7** [comment]
Still persists
