### ISSUE TITLE
Armor with trims appears as texture blocks

### ISSUE THREAD

**Issue by CDX-1** [ViaVersion/ViaBackwards#570]
### '/viaversion dump' Output

https://dump.viaversion.com/4e331a11d17f30daf909752754da46825774927753528576d3f20df691b3bfda

### Console Error

N/A

### Bug Description

Viewing armor with trims on either a player or armor stand displays a texture block (only tested on 1.19.4).
![image_2023-07-31_222326576](https://github.com/ViaVersion/ViaBackwards/assets/80155611/7001e52f-d985-4600-96a9-344a2c084e24)
![image_2023-07-31_222332103](https://github.com/ViaVersion/ViaBackwards/assets/80155611/ea274a87-8fcd-4102-979a-1778f71ede26)

### Steps to Reproduce

1. Produce an armor with armor trims on a 1.20.1 server
2. Place the armor on an armor stand or have a friend wear the armor
3. Login on 1.19.4 and you will see texture blocks in the place of the armor

### Expected Behavior

The armor should appear as some substitute armor or the base armor without trims. For example, a golden chestplate with a netherite trim should just appear as a gold chestplate on 1.19.4.

### Additional Server Info

Paper 1.20.1 with following plugins: Citizens, CoreProtect, DecentHolograms, DiscordSRV, FastAsyncWorldEdit, goBrush, goPaint, InventoryRollbackPlus, ItemEdit, ItemTag, LiteBans, LuckPerms, Multiverse-Core, MythicCrucible, MythicMobs, OpenInv, PlaceholderAPI, PlayerParticles, PlugManX, Shopkeepers, SkBee, skript-reflect, TAB, ViaBackwards, ViaRewind, ViaVersion, VoidGen, VoxelSniper, Vulcan, WorldGuard

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--97%20%28MC%3A%201.20.1%29](https://img.shields.io/badge/Platform-git--Paper--97%20%28MC%3A%201.20.1%29-3498db?style=flat-square) </br>![ViaVersion (4.7.0): 20 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.7.0)-20%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(4.7.0): 10 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.7.0)-10%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaRewind(2.0.3): 17 commits behind master](https://img.shields.io/badge/ViaRewind%20(2.0.3)-17%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump</h3>

**Comment by Barvalg** [comment]
![Platform: git--Paper--97%20%28MC%3A%201.20.1%29](https://img.shields.io/badge/Platform-git--Paper--97%20%28MC%3A%201.20.1%29-3498db?style=flat-square) </br>![ViaVersion (4.7.1-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.7.1--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(4.7.1-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.7.1--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaRewind(2.0.4-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaRewind%20(2.0.4--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>
