### ISSUE TITLE
Hover event doesn't work prior 1.16.4

### ISSUE THREAD

**Issue by iTzVirtual00** [ViaVersion/ViaBackwards#572]
### '/viaversion dump' Output

https://dump.viaversion.com/88dbb1eed35f5536d40f3253f571049b9d766c2965dfd9d26c5fa6c46a74f1a8

### Console Error

```
Nothing
```

### Bug Description

I'm creating books with text with hover events using the Adventure API. The hover event doesn't show on version prior 1.16.4. Note that using the old md_5 text api it shows correctly. (I'm using 1.14.4)

These are the NBT json of the generated book.

Generated by Adventure API:
```json
{
  "pages": [
    {"hoverEvent":{"action":"show_text","contents":{"text":"Some text"}},"text":"Adventure api"}
  ]
  "author":"",
  "title":""
}
```

![immagine](https://github.com/ViaVersion/ViaBackwards/assets/58611844/31a1ff8f-ca30-4b96-9772-46a46e916050)

Generated by md_5 API
```json
{
  "pages": [
    {"hoverEvent":{"action":"show_text","value":[{"text":"Some text"}]},"text":"md_5 apii"}
  ]
  "author":"",
  "title":""
}
```
![immagine](https://github.com/ViaVersion/ViaBackwards/assets/58611844/d0eb74cb-9ad0-4443-8bab-8b8bb684b996)

### Steps to Reproduce

```java 
ItemStack itemStack = new ItemStack(Material.WRITTEN_BOOK);
BookMeta bookMeta = (BookMeta) itemStack.getItemMeta();
Component testComponent = Component.text("Adventure api").hoverEvent(HoverEvent.showText(Component.text("Some text")));
bookMeta.author(Component.text(""));
bookMeta.title(Component.text(""));
bookMeta.addPages(testComponent);
itemStack.setItemMeta(bookMeta);
player.getInventory().addItem(itemStack);
```
execute this code to create a book with hoverable text and give it to the player

the player doesn't see the text when hovering (prior 1.16)

### Expected Behavior

The text should display on every version

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--18%20%28MC%3A%201.20.1%29](https://img.shields.io/badge/Platform-git--Paper--18%20%28MC%3A%201.20.1%29-3498db?style=flat-square) </br>![ViaVersion (4.7.0): 20 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.7.0)-20%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(4.7.0): 10 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.7.0)-10%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaRewind(2.0.3): 17 commits behind master](https://img.shields.io/badge/ViaRewind%20(2.0.3)-17%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump</h3>

**Comment by iTzVirtual00** [comment]
https://dump.viaversion.com/b8bdad6293126325fac77f006329bbececaf5e155c381aed8ea9a2b227e14d2c

**Comment by Barvalg** [comment]
![Platform: git--Paper--18%20%28MC%3A%201.20.1%29](https://img.shields.io/badge/Platform-git--Paper--18%20%28MC%3A%201.20.1%29-3498db?style=flat-square) </br>![ViaVersion (4.8.0-23w31a-SNAPSHOT): Even with dev](https://img.shields.io/badge/ViaVersion%20(4.8.0--23w31a--SNAPSHOT)-Even%20with%20dev-brightgreen?style=flat-square) </br>![ViaRewind(2.0.4-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaRewind%20(2.0.4--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(4.8.0-23w31a-SNAPSHOT): Even with dev](https://img.shields.io/badge/ViaBackwards%20(4.8.0--23w31a--SNAPSHOT)-Even%20with%20dev-brightgreen?style=flat-square) </br>

**Comment by kennytv** [comment]
Thanks for the detailed report, fixed in https://github.com/ViaVersion/ViaBackwards/commit/83636ecf517f2e5e2d5e51f05552238dba3cc3a1
