### ISSUE TITLE
Publish to Modrinth

### ISSUE THREAD

**Issue by RaptaG** [ViaVersion/ViaBackwards#573]
### Problem Description

This mod is only accessible through CurseForge, limiting [Modrinth](https://modrinth.com) users.

### Solution Description

Upload the mod to Modrinth:

- ViaFabric, ViaForge and ViaFabricPlus are already there.
- Creator payouts
- Friendly and helpful community and moderators
- Open-source
- Has its own launcher and is supported by all the major launchers.

**Comment by 4drian3d** [comment]
https://modrinth.com/mod/viabackwards
