### ISSUE TITLE
Error joining 1.20.1 server with 1.19.2 client

### ISSUE THREAD

**Issue by RaphiMC** [ViaVersion/ViaBackwards#577]
### '/viaversion dump' Output

https://dump.viaversion.com/c5bed1b872d4d059f206e0c0c0e17adc7bf91a21e5f9c2f390315c4e95c6203a

### Console Error

https://mclo.gs/aOOCDts

### Bug Description

Connect to play.sinussmp.ru:25565 (1.20.1) with a 1.19.2 client over ViaProxy

### Steps to Reproduce

Connect to play.sinussmp.ru:25565 (1.20.1) with a 1.19.2 client over ViaProxy

### Expected Behavior

No disconnect

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: 2.2.7](https://img.shields.io/badge/Platform-2.2.7-3498db?style=flat-square) </br>![ViaVersion (4.7.1-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.7.1--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(4.7.1-SNAPSHOT): 1 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.7.1--SNAPSHOT)-1%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump</h3>

**Comment by RaphiMC** [comment]
The ViaBackwards is up to date. That 1 commit only changed the GH actions files
