### ISSUE TITLE
Smithing Table GUI not opening on 1.20.1 server with a 1.19.3 client and older client versions.

### ISSUE THREAD

**Issue by TBYT** [ViaVersion/ViaBackwards#582]
### '/viaversion dump' Output

https://dump.viaversion.com/0caa70991993ab4fe340c908a8d61f54a0a5703580c02c36e8b3ea62e9bc04b2

### Console Error

```
Put the paste.gg link or text here.
```

### Bug Description

GUI, Opening Smithing Table on 1.19.3 client does not work. Although It does work on a 1.19.4 client. 

### Steps to Reproduce

1. Using the Essential client (custom fabric client). (optional hopefully)
2. Use minecraft version 1.19.3.
2. Join  a 1.20.1 paper server running viabackwards and try to click the smithing table hoping to open the gui.

### Expected Behavior

I should be prompted the 1.20 smithing table gui, just like I am when I join with a 1.19.4 client.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by kennytv** [comment]
VB doesn't add new features. The smithing table changed and doesn't exist like that in 1.19.3

**Comment by TBYT** [comment]
> VB doesn't reimplement new server inventories. The smithing table changed and doesn't exist like that in 1.19.3

true but @FlorianMichael wanted me to make the issue so I did, I thought he would say something about it. Anyway this doesn't affect me much because I can go to 1.19.4 or 1.20 client on java, but reported it none of the less.

**Comment by TBYT** [comment]
> https://www.spigotmc.org/resources/axsmithing-viaversion-addon.112793/ https://github.com/Artillex-Studios/AxSmithing

this works great
