### ISSUE TITLE
Scoreboard title and team suffix are translated but cut off

### ISSUE THREAD

**Issue by SplotyCode** [ViaVersion/ViaBackwards#585]
### '/viaversion dump' Output

https://dump.viaversion.com/16346237d260a22877e72ad0cc2d3563c2bcb067ec81f98f888561e89ba1dc76

### Bug Description

Scoreboard title and team suffix are translated but cut off. I can imagine that color codes are translated to the closest 1.12 color codes. For gradients almost every char has than 2 chars of color codes. This will result in long strings witch are than cut off. Example `§bH§be§bl§bl§bo §bW§bo§br§bl§bd` will be cut off to `§bH§be§bl§bl§bo` while a better translation would be `§bHello World `

### Steps to Reproduce

Join for exmaple play.timolia.de and compare the scoreboard on 1.8 and 1.20 clients. You see that not only the color differs (as expected) but also the text is cut off
![image](https://github.com/ViaVersion/ViaBackwards/assets/31861387/975a486e-621f-4ebe-b5cd-3e8fcd078bc7)
![image](https://github.com/ViaVersion/ViaBackwards/assets/31861387/ceee5e87-61a1-40e7-9601-34b357276259)

### Expected Behavior

Scoreboard title and team suffix should not be cut off the the common case described above

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--169%20%28MC%3A%201.20.1%29](https://img.shields.io/badge/Platform-git--Paper--169%20%28MC%3A%201.20.1%29-3498db?style=flat-square) </br>![ViaVersion (4.7.1-SNAPSHOT): 7 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.7.1--SNAPSHOT)-7%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(4.7.1-SNAPSHOT): 6 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.7.1--SNAPSHOT)-6%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaRewind(2.0.4-SNAPSHOT): 7 commits behind master](https://img.shields.io/badge/ViaRewind%20(2.0.4--SNAPSHOT)-7%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump</h3>

**Comment by l3nnartt** [comment]
https://dump.viaversion.com/936cdcb725cb967e35c06db7380c0079adbff845d106ba2d6054f6d459e14fa3

**Comment by Barvalg** [comment]
![Platform: git--Paper--134%20%28MC%3A%201.20.1%29](https://img.shields.io/badge/Platform-git--Paper--134%20%28MC%3A%201.20.1%29-3498db?style=flat-square) </br>![ViaVersion (4.7.1-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.7.1--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaRewind(2.0.4-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaRewind%20(2.0.4--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(4.7.1-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.7.1--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>
