### ISSUE TITLE
Recovery Compass

### ISSUE THREAD

**Issue by JoyousCreeper1059** [ViaVersion/ViaBackwards#589]
### Problem Description

Recovery compasses don't work on <1.19 client

### Solution Description

Replace the recovery compass with a lodestone compass with its position set to the death position

### Additional Info

Affects any client 1.18 or lower

**Comment by Barvalg** [comment]
![Error: Invalid or missing dump](https://img.shields.io/badge/Error-Invalid/missing%20dump-red?style=flat-square) </br>

**Comment by JoyousCreeper1059** [comment]
> ![Error: Invalid or missing dump](https://camo.githubusercontent.com/d52699b4f8c5e7e91cb92ecd59b5aa5ed2f9eb37e741b87aa9334b5e364c0512/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f4572726f722d496e76616c69642f6d697373696e6725323064756d702d7265643f7374796c653d666c61742d737175617265)

I don't think I need to dump to make a feature request

**Comment by FlorianMichael** [comment]
No you don't need a dump for feature requests, I implemented your idea via https://github.com/ViaVersion/ViaBackwards/pull/770. Thank you for suggesting.
