### ISSUE TITLE
Server kick while joining on 1.9

### ISSUE THREAD

**Issue by Disorbs** [ViaVersion/ViaBackwards#59]
### What is the output url of /viaversion dump?
> https://dump.viaversion.com/62114aaf81491ae3a00eb66568ab0944b8f5ec22f8255108c32e40f6e92095a4

### How/when does this error happen? login?:
> when i log into my server on 1.9 not sure if on others as well

### Is there an error in the console? Use pastebin.com. Is there a kick message?:
> kick message only `Internal Exception: io.netty.handler.codec.decoderexception:
com.google.gson.jsonsyntax exception:
com.google.gson.stream.malformedjsonexception: use
jsonreader.setlenien(tru) to accept malformed json at line 1 column 1`

### ViaVersion config:
> https://hastebin.com/ohocezifif.shell

**Comment by KennyTV** [comment]
Since the hastebin expired and this is quite old of an issue, I'm just going to close this. If this ever happened/happens again on the latest versions, feel free to open a new issue
