### ISSUE TITLE
Help with changing legacy block mappings

### ISSUE THREAD

**Issue by SladeHazard** [ViaVersion/ViaBackwards#591]
### Problem Description

hey, I'm unable to change a certain material id block in viabackwards' legacy mappings

```
{
  "1.12": {
    "251": {
      "id": 98,
      "data": 0,
      "name": "1.12 %vb_color% Concrete",
      "block": true
    },
```

I only want to modify the block for 251:0, but the above config does it for all the material ids... 251:1, 251:2 ect and there is no data option

### Solution Description

Add support for newer blocks with their ids in the legacy mapping

### Alternatives

simply changing the 251 to 251:0 doesnt work either, Caused by: java.lang.NumberFormatException: For input string: "251:0"

### Additional Info

Server version: 1.12.2, java 11

**Comment by kennytv** [comment]
Join the Discord for help https://discord.gg/viaversion
