### ISSUE TITLE
Error REMAP OF BLOCK_ENTITY_DATA

### ISSUE THREAD

**Issue by UnperishedDev** [ViaVersion/ViaBackwards#596]
### '/viaversion dump' Output

https://dump.viaversion.com/b811440075da2e8d3c397a70caee909fb0bc5af13ff9d3921757f3395435e358

### Console Error

```
https://paste.gg/p/anonymous/3a0c89de061b4794bc5630c98e940527
```

### Bug Description

Joining the 1.20.2 server on Minecraft 1.20.1 disconnects players from the server.

### Steps to Reproduce

1. Join with 1.20.1 with server version 1.20.2 and Viabackwards/viaversion version 4.8.0.
2. Receive the error

### Expected Behavior

I expected players to be able to log in on earlier versions with ViaBackwards.

### Additional Server Info

I use PaperMC 1.20.1 build 210 and other survival-oriented plugins.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--210%20%28MC%3A%201.20.2%29](https://img.shields.io/badge/Platform-git--Paper--210%20%28MC%3A%201.20.2%29-3498db?style=flat-square) </br>![ViaVersion: Outdated](https://img.shields.io/badge/ViaVersion%20(4.8.0)-Outdated!-red?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump and the issue will be reopened</h3>

**Comment by UnperishedDev** [comment]
ViaVersion/ViaBackwards have been updated to 4.8.1, problem still persists. 
https://dump.viaversion.com/b19c19b4f4190465710e3010bcf804fafc764ad8a219ca9550d14609ebdab67a

**Comment by Barvalg** [comment]
![Platform: git--Paper--210%20%28MC%3A%201.20.2%29](https://img.shields.io/badge/Platform-git--Paper--210%20%28MC%3A%201.20.2%29-3498db?style=flat-square) </br>![ViaVersion (4.8.1): Even with master](https://img.shields.io/badge/ViaVersion%20(4.8.1)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(4.8.1): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.8.1)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by Kichura** [comment]
Update ProtocolLib to add 1.20.2 support for the other plugins, otherwise it's likely to be caused by another third-party plugin that breaks viaversion.

**Comment by UnperishedDev** [comment]
Still an issue with the latest commit of ProtocolLib. I’ll test other plugins, but this hasn’t been an observed issue since mid-June.
