### ISSUE TITLE
Text display entities are incorrectly translated to nameless armor stands when joining 1.20.2 server from 1.18.2

### ISSUE THREAD

**Issue by Misat11** [ViaVersion/ViaBackwards#597]
### '/viaversion dump' Output

https://dump.viaversion.com/6c96aa88b1614d7e56280160f4de4ac79175485c56b5de67b8bff9de83f06e10

### Bug Description

When joining 1.20.2 server from 1.18.2 client (possibly from any pre-1.19.4 client), the text display entities are wrongly translated, resulting in the original text not being visible.

### Steps to Reproduce

1. Join with 1.20.2 and place a text display entity using /summon command (for example `/summon minecraft:text_display ~ ~ ~ {billboard:center,text:"{\"text\":\"Hello World!\"}"}`) 
2. Reconnect with 1.18.2 to observe there's no text.
3. Switch to spectator gamemode, this will reveal that the armor stand is in fact there, however has no name or the name is not visible.

### Expected Behavior

Text display entities should be translated to invisible armor stands with their name visible and set to the original text.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--213%20%28MC%3A%201.20.2%29](https://img.shields.io/badge/Platform-git--Paper--213%20%28MC%3A%201.20.2%29-3498db?style=flat-square) </br>![ViaVersion (4.8.1): Even with master](https://img.shields.io/badge/ViaVersion%20(4.8.1)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(4.8.1): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.8.1)-Even%20with%20master-brightgreen?style=flat-square) </br>
