### ISSUE TITLE
Entities got changed in 1.19.2, 1.8.x clients crash on packet 0/14 (fk)

### ISSUE THREAD

**Issue by CamperSamu** [ViaVersion/ViaBackwards#606]
**Describe the bug, provide any errors**
There are no errors on the Velocity side (where I run Via) outside of the world height warning and the custom biome error, but the client reports a netty exception
![image](https://user-images.githubusercontent.com/32773961/188925189-0f441e77-fc36-4b00-9473-899712a1d4e7.png)

In 1.19.2 something must've changed with entitiy packets and from the looks of it there's no mitigation for this in ViaRewind.
Wiki.vg 1.8.x packet: https://wiki.vg/index.php?title=Protocol&oldid=7368#Entity

**How can we reproduce it?**
1. Login on a 1.19.2 server with a 1.8.x client (I use custom biomes too)
2. Get the netty exception

**Expected behaviour**
You should be able to join without issues (or minor issues)

**Screenshots**
See above.

**ViaVersion Dump:**
https://dump.viaversion.com/4a943465d9288ed081921f13e69fe2f420338d68e9db8a1832f5f1deb6811374

**Additional server info**
I use a Velocity proxy with 2 Paper, 1 Purpur and 1 Quilt backend servers (hub uses Paper)

**Checklist** (mark with [X] to check)
- [x] I have included a ViaVersion dump
- [x] If applicable, I have included a paste (not a screenshot) of the error
- [x] I have tried a build from https://ci.viaversion.com/ and the issue still persists
- [x] I have looked at https://www.spigotmc.org/resources/viarewind-legacy-support.52924/ and it does not offer a fix for my problem

**IMPORTANT: Follow the Checklist or we can't reproduce your issue and your issue will be closed**

**Comment by Barvalg** [comment]
![Platform: velocity%203.1.2--SNAPSHOT%20%28git--8a63df2a--b168%29](https://img.shields.io/badge/Platform-velocity%203.1.2--SNAPSHOT%20%28git--8a63df2a--b168%29-3498db?style=flat-square) </br>![Proxy is 97 builds behind](https://img.shields.io/badge/Your%20proxy%20is%2097%20build(s)%20behind.%20Please%20update%20to%20the%20latest%20version-orange?style=flat-square) </br>![ViaVersion: Outdated](https://img.shields.io/badge/ViaVersion%20(4.4.3--SNAPSHOT)-Outdated!-red?style=flat-square) </br>![ViaRewind: Outdated](https://img.shields.io/badge/ViaRewind%20(2.0.3--SNAPSHOT)-Outdated!-red?style=flat-square) </br>![ViaBackwards: Outdated](https://img.shields.io/badge/ViaBackwards%20(4.4.2)-Outdated!-red?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump and the issue will be reopened</h3>
