### ISSUE TITLE
Clean install, can´t join with older than 1.20.2 versions

### ISSUE THREAD

**Issue by mercadanteus** [ViaVersion/ViaBackwards#607]
### '/viaversion dump' Output

https://dump.viaversion.com/5b388d0897697f62bea0a6d25f00111e6ef1d2d6b9e1aeb902da426a3aaebd68
### Console Error

```
----In console:
[10.10 09:26:59] [Server] [INFO] UUID of player JF4b10 is 9d549133-3a85-303c-b142-43f43af1fbff
[10.10 09:26:59] [Disconnect] com.mojang.authlib.GameProfile@4e3ef1[id=9d549133-3a85-303c-b142-43f43af1fbff,name=JF4b10,properties={}] has disconnected, reasonDisconnected
```

----In the player app, appeaRs this error:
Internal exception; io.netty.handler.codec.decoderexception: java.lang.indexoutofboundsexception: index 64 out of bounds for length 5

### Bug Description

Server running Purpur version git-Purpur-2077 (MC: 1.20.2)
Using a clean install, no plugins other than viaversion and viabackwars
Cannot join if using any older than 1.20.2 version

### Steps to Reproduce

1. Run server with  Purpur version git-Purpur-2077 (MC: 1.20.2)
2. Only plugins present are viaversion-4.9.0-23w40a-snapshot.jar and viabackwards-4.9.0-23w40a-snapshot.jar
3. No resource pack
4. Join server using client with 1.17.1
5. Fail

### Expected Behavior

Yo can join with 1.17.1 client and even older

### Additional Server Info

1. Run server with  Purpur version git-Purpur-2077 (MC: 1.20.2)
2. Only plugins present are viaversion-4.9.0-23w40a-snapshot.jar and viabackwards-4.9.0-23w40a-snapshot.jar
3. No resource pack

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Purpur--2077%20%28MC%3A%201.20.2%29](https://img.shields.io/badge/Platform-git--Purpur--2077%20%28MC%3A%201.20.2%29-3498db?style=flat-square) </br>![ViaVersion (4.8.1): Even with master](https://img.shields.io/badge/ViaVersion%20(4.8.1)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(4.8.1): 1 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.8.1)-1%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump</h3>

**Comment by mercadanteus** [comment]
![Captura](https://github.com/ViaVersion/ViaBackwards/assets/24380156/57ee8735-f46b-4f14-b842-d5e21ba8a3e6)

**Comment by Barvalg** [comment]
![Platform: git--Purpur--2077%20%28MC%3A%201.20.2%29](https://img.shields.io/badge/Platform-git--Purpur--2077%20%28MC%3A%201.20.2%29-3498db?style=flat-square) </br>![ViaVersion (4.9.0-23w40a-SNAPSHOT): 1 commits behind dev](https://img.shields.io/badge/ViaVersion%20(4.9.0--23w40a--SNAPSHOT)-1%20commit(s)%20behind%20dev-yellow?style=flat-square) </br><br><h3>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump</h3>

**Comment by mercadanteus** [comment]
All viabackward and viaversion updated now to the latest, please dont ignore

**Comment by kennytv** [comment]
Are you using Bungee?

**Comment by mercadanteus** [comment]
> Are you using Bungee?

No, is a single server hosted in meloncube

**Comment by kennytv** [comment]
Can't reproduce - can you try with a Paper server instead?

**Comment by mercadanteus** [comment]
Alredy did, and had the same result... actually downgraded server

**Comment by Kichura** [comment]
Cannot reproduce with latest purpur on test server, i wonder if it's a bad world save or something?

**Comment by hugovdev** [comment]
Same happening here with clean install ad latest update of viaversion, viabackwards and paper, as extra data: We do have a resource pack on the server.properties file

**Comment by Kichura** [comment]
Update to dev builds of via* as 4.8.1 has broken compatibility in terms of resource packs.

**Comment by hugovdev** [comment]
> Update to dev builds of via* as 4.8.1 has broken compatibility in terms of resource packs.

![image](https://github.com/ViaVersion/ViaBackwards/assets/23460704/88214fb5-d47c-4982-873c-4aee949fca24)

Dev builds crash on start

**Comment by Kichura** [comment]
> > Update to dev builds of via* as 4.8.1 has broken compatibility in terms of resource packs.
> 
> ![image](https://user-images.githubusercontent.com/23460704/277138651-88214fb5-d47c-4982-873c-4aee949fca24.png)
> 
> Dev builds crash on start

Update viabackwards and viarewind.

**Comment by hugovdev** [comment]
> > > Update to dev builds of via* as 4.8.1 has broken compatibility in terms of resource packs.
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/23460704/277138651-88214fb5-d47c-4982-873c-4aee949fca24.png)
> > Dev builds crash on start
> 
> Update viabackwards and viarewind.

I'm running the latest build of viabackwards too

**Comment by Kichura** [comment]
> > > > Update to dev builds of via* as 4.8.1 has broken compatibility in terms of resource packs.
> > > 
> > > 
> > > ![image](https://user-images.githubusercontent.com/23460704/277138651-88214fb5-d47c-4982-873c-4aee949fca24.png)
> > > Dev builds crash on start
> > 
> > 
> > Update viabackwards and viarewind.
> 
> I'm running the latest build of viabackwards too, latest viabackwards didnt even build

It says 4.8.1 in server logs meaning not latest.

**Comment by hugovdev** [comment]
> > > > > Update to dev builds of via* as 4.8.1 has broken compatibility in terms of resource packs.
> > > > 
> > > > 
> > > > ![image](https://user-images.githubusercontent.com/23460704/277138651-88214fb5-d47c-4982-873c-4aee949fca24.png)
> > > > Dev builds crash on start
> > > 
> > > 
> > > Update viabackwards and viarewind.
> > 
> > 
> > I'm running the latest build of viabackwards too, latest viabackwards didnt even build
> 
> It says 4.8.1 in server logs meaning not latest.

You're right, I followed some link that said dev builds but it was normal builds.
New error on startup though
![image](https://github.com/ViaVersion/ViaBackwards/assets/23460704/fd3cd34d-dcfd-4550-8ad7-426e54ef6d17)

**Comment by Kichura** [comment]
> > > > > > Update to dev builds of via* as 4.8.1 has broken compatibility in terms of resource packs.
> > > > > 
> > > > > 
> > > > > ![image](https://user-images.githubusercontent.com/23460704/277138651-88214fb5-d47c-4982-873c-4aee949fca24.png)
> > > > > Dev builds crash on start
> > > > 
> > > > 
> > > > Update viabackwards and viarewind.
> > > 
> > > 
> > > I'm running the latest build of viabackwards too, latest viabackwards didnt even build
> > 
> > 
> > It says 4.8.1 in server logs meaning not latest.
> 
> You're right, I followed some link that said dev builds but it was normal builds. New error on startup though ![image](https://user-images.githubusercontent.com/23460704/277138753-fd3cd34d-dcfd-4550-8ad7-426e54ef6d17.png)

Seems like slimeworldmanager is screwing up viaversion entirely, attempt to update it or report it to the devs to see what's happening.
