### ISSUE TITLE
The shield does not protect against mobs projectiles when joining with 1.20.1 on 1.20.2 server

### ISSUE THREAD

**Issue by Amitexing** [ViaVersion/ViaBackwards#612]
### '/viaversion dump' Output

https://dump.viaversion.com/0fe6fee0670523987e7a5de916d003afecdac156a7496e4d7e0b57a82f6e9330

### Console Error

```
Put the paste.gg link or text here.
```

### Bug Description

The damage is randomly large and the shield does not protect against mobs projectiles when joining with 1.20.1 on 1.20.2 server

### Steps to Reproduce

1. Log in to 1.20.2 server with 1.20.1
2. Take the shield and find the skeleton/blaze The damage from it will be very large, and the shield will not protect against it

### Expected Behavior

The shield should reflect projectiles, and the damage should be considered normal

### Additional Server Info

Purpur 1.20.2
Latest viaversions & viabackwards

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Purpur--2078%20%28MC%3A%201.20.2%29](https://img.shields.io/badge/Platform-git--Purpur--2078%20%28MC%3A%201.20.2%29-3498db?style=flat-square) </br>![ViaVersion (4.8.1): Even with master](https://img.shields.io/badge/ViaVersion%20(4.8.1)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(4.8.1): 1 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.8.1)-1%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump</h3>

**Comment by Amitexing** [comment]
https://dump.viaversion.com/f7a76266c3323b3b9c10c02224dfed7b5f1eceb7f5abe6c3683b0b5b0bdf8527

**Comment by Barvalg** [comment]
![Platform: git--Purpur--2078%20%28MC%3A%201.20.2%29](https://img.shields.io/badge/Platform-git--Purpur--2078%20%28MC%3A%201.20.2%29-3498db?style=flat-square) </br>![ViaVersion (4.9.0-23w41a-SNAPSHOT): Even with dev](https://img.shields.io/badge/ViaVersion%20(4.9.0--23w41a--SNAPSHOT)-Even%20with%20dev-brightgreen?style=flat-square) </br>![ViaBackwards(4.9.0-23w41a-SNAPSHOT): Even with dev](https://img.shields.io/badge/ViaBackwards%20(4.9.0--23w41a--SNAPSHOT)-Even%20with%20dev-brightgreen?style=flat-square) </br>

**Comment by Amitexing** [comment]
After update still works

**Comment by kennytv** [comment]
Works fine for me. Please try without other plugins
