### ISSUE TITLE
Player cannot join the server

### ISSUE THREAD

**Issue by Kennyyan66** [ViaVersion/ViaBackwards#613]
### '/viaversion dump' Output

https://dump.viaversion.com/138251e117317f252e4b928bf36029db68f25134b751a407eb949b50f8452e88

### Console Error

```
https://paste.gg/p/anonymous/b683a9258b314f92b2439163fdd88eaf
```

### Bug Description

I installed viaversion and viabackwards on bungeecord
Today I updated viaversion and viabackwards to 4.8.1 in order to support 1.20.2 players entering my server
My subserver is on spigot 1.18.2. I use 1.20.2 client and tried to enter, but the server kicked me out

### Steps to Reproduce

1. install ProtocolLib on subserver
2. install viaversion and viabackwards on bungeecord, not on the subserver
3. configure bungeecord and subserver, so that it can join subserver through bungeecord
4. start the two servers
5. join the server

### Expected Behavior

I should normally join the server

### Additional Server Info

I use bungeecord and spigot 1.18.2
bungeecord: viaversion, viabackwards, pistonmotd; both viaversion and viabackwards are 4.8.1
subserver: authme, commandNPC, citizens, chestcommands, placeholderapi, protocollib, skinsrestorer
there's also have a screenshot, shows what happen when I join the server: https://sm.ms/image/I1BbDrwxGmFjEVP

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git%3ABungeeCord--Bootstrap%3A1.20--R0.2--SNAPSHOT%3Aa7cd79e%3A1731](https://img.shields.io/badge/Platform-git%3ABungeeCord--Bootstrap%3A1.20--R0.2--SNAPSHOT%3Aa7cd79e%3A1731-3498db?style=flat-square) </br>![Proxy is 26 builds behind](https://img.shields.io/badge/Your%20proxy%20is%2026%20build(s)%20behind.%20Please%20update%20to%20the%20latest%20version-orange?style=flat-square) </br>![ViaVersion (4.8.1): Even with master](https://img.shields.io/badge/ViaVersion%20(4.8.1)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(4.8.1): 1 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.8.1)-1%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump</h3>

**Comment by Kennyyan66** [comment]
> ![Platform: git%3ABungeeCord--Bootstrap%3A1.20--R0.2--SNAPSHOT%3Aa7cd79e%3A1731](https://camo.githubusercontent.com/2fd04dad1346b9d97b48b5c1e59a49b23b24beb3477ba377641dbadb1acd1397/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f506c6174666f726d2d67697425334142756e676565436f72642d2d426f6f747374726170253341312e32302d2d52302e322d2d534e415053484f5425334161376364373965253341313733312d3334393864623f7374796c653d666c61742d737175617265) ![Proxy is 26 builds behind](https://camo.githubusercontent.com/ba71bea51479c4127428b75717a2fba6890f3c1d39238dea94aa96022fae1bd5/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f596f757225323070726f7879253230697325323032362532306275696c64287329253230626568696e642e253230506c65617365253230757064617465253230746f2532307468652532306c617465737425323076657273696f6e2d6f72616e67653f7374796c653d666c61742d737175617265) ![ViaVersion (4.8.1): Even with master](https://camo.githubusercontent.com/50a7e23c01641dd8c52b9e8c95ea6e571296f51c8a57a34dac1600ee536e0e53/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f56696156657273696f6e25323028342e382e31292d4576656e253230776974682532306d61737465722d627269676874677265656e3f7374796c653d666c61742d737175617265) ![ViaBackwards(4.8.1): 1 commits behind master](https://camo.githubusercontent.com/e1c1d13306f525d38faa76f130b78bb2cc9ba6511f3c49be66432b99e5cc16e1/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f5669614261636b776172647325323028342e382e31292d31253230636f6d6d6974287329253230626568696e642532306d61737465722d79656c6c6f773f7374796c653d666c61742d737175617265)
> 
> ### Please try the **latest** build(s) from https://ci.viaversion.com/. In case the issue still persists send the new dump

the problem still exists, here's the new dump: https://dump.viaversion.com/faf68ff6a0674aefc0845606602de8db7e35d32ee05f1ebfc902294ced9032de

**Comment by Barvalg** [comment]
![Platform: git%3ABungeeCord--Bootstrap%3A1.20--R0.2--SNAPSHOT%3Aa7cd79e%3A1731](https://img.shields.io/badge/Platform-git%3ABungeeCord--Bootstrap%3A1.20--R0.2--SNAPSHOT%3Aa7cd79e%3A1731-3498db?style=flat-square) </br>![Proxy is 26 builds behind](https://img.shields.io/badge/Your%20proxy%20is%2026%20build(s)%20behind.%20Please%20update%20to%20the%20latest%20version-orange?style=flat-square) </br>![ViaVersion (4.9.0-23w41a-SNAPSHOT): Even with dev](https://img.shields.io/badge/ViaVersion%20(4.9.0--23w41a--SNAPSHOT)-Even%20with%20dev-brightgreen?style=flat-square) </br>![ViaBackwards(4.9.0-23w41a-SNAPSHOT): Even with dev](https://img.shields.io/badge/ViaBackwards%20(4.9.0--23w41a--SNAPSHOT)-Even%20with%20dev-brightgreen?style=flat-square) </br>

**Comment by kennytv** [comment]
That looks like something sending bad chat packets, or the outdated Bungee

**Comment by Kennyyan66** [comment]
> That looks like something sending bad chat packets, or the outdated Bungee (although note that Bungee doesn't properly support 1.20.2 yet and ViaVersion in general doesn't work well if placed on Bungee)

I tried updating bungeecord and added viaversion and viabackwards to the subserver, and now it works normally. Thanks
