### ISSUE TITLE
1.20.2 Server Does Not Allowed >1.20.2 To Join With Resource Pack

### ISSUE THREAD

**Issue by 0bviouslee** [ViaVersion/ViaBackwards#615]
### '/viaversion dump' Output

https://dump.viaversion.com/e88d127e6c2b88c77b1db2fb716a497ea08df1ca413ab12c35f49b1ba1326894

### Console Error

From Proxy's Console:
https://paste.gg/p/anonymous/21935e2904f84c7ea5f8f8af24dcbf12

### Bug Description

When a resource pack is added to the server inside of server.properities, it is impossible to join the server on versions lower than 1.20.2 but you can join without being kicked on 1.20.2. When removing the resource pack link from server.properties, this issue goes away and any version can join.

### Steps to Reproduce

1. Put a link in the "resource-pack" config key of the "server.properties" file
2. Add the latest development builds of ViaVersion and ViaBackwards
3. Join the server on 1.20.1, it will kick you for the shown error
4. Join the server on 1.20.2, it will let you join normally

### Expected Behavior

Older versions should be possible to connect even with a resource pack on the server.

### Additional Server Info

I used Waterfall as my proxy software and Paper as my Spigot software. I use various plugins though I have tried removing all of them and using a freshly installed server and with a resource pack assigned it does not work still.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--234%20%28MC%3A%201.20.2%29](https://img.shields.io/badge/Platform-git--Paper--234%20%28MC%3A%201.20.2%29-3498db?style=flat-square) </br>![ViaVersion (4.9.0-23w41a-SNAPSHOT): Even with dev](https://img.shields.io/badge/ViaVersion%20(4.9.0--23w41a--SNAPSHOT)-Even%20with%20dev-brightgreen?style=flat-square) </br>![ViaBackwards(4.9.0-23w41a-SNAPSHOT): Even with dev](https://img.shields.io/badge/ViaBackwards%20(4.9.0--23w41a--SNAPSHOT)-Even%20with%20dev-brightgreen?style=flat-square) </br>

**Comment by kennytv** [comment]
Fixed in dev builds
