### ISSUE TITLE
Advancements display abnormally on the 1.20.2 server

### ISSUE THREAD

**Issue by MSCMDD** [ViaVersion/ViaBackwards#616]
### '/viaversion dump' Output

https://dump.viaversion.com/6c7046a1e64ea52b52778b63b93d21bb68a906edfd2b77607183bad94b33ccb0

### Console Error

```
Put the paste.gg link or text here.
```

### Bug Description

The old version of Minecraft achieved abnormal results when accessing the 1.20.2 server through ViaBackwards
Advancements not displaying properly

### Steps to Reproduce

Log in to the 1.20.2 server using a 1.20.1 client or earlier version

### Expected Behavior

Older versions of clients logging into 1.20.2 servers should display Advancements correctly

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--238%20%28MC%3A%201.20.2%29](https://img.shields.io/badge/Platform-git--Paper--238%20%28MC%3A%201.20.2%29-3498db?style=flat-square) </br>![ViaVersion (4.8.1): Even with master](https://img.shields.io/badge/ViaVersion%20(4.8.1)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(4.8.1): 1 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.8.1)-1%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump</h3>

**Comment by MSCMDD** [comment]
https://dump.viaversion.com/9a4014b5c03d5243106b9ae6ddbd90a4021cb57e290bc37a9a9e17d3d45c767d

**Comment by Barvalg** [comment]
![Platform: git--Paper--238%20%28MC%3A%201.20.2%29](https://img.shields.io/badge/Platform-git--Paper--238%20%28MC%3A%201.20.2%29-3498db?style=flat-square) </br>![ViaVersion (4.9.0-23w41a-SNAPSHOT): Even with dev](https://img.shields.io/badge/ViaVersion%20(4.9.0--23w41a--SNAPSHOT)-Even%20with%20dev-brightgreen?style=flat-square) </br>![ViaBackwards(4.9.0-23w41a-SNAPSHOT): Even with dev](https://img.shields.io/badge/ViaBackwards%20(4.9.0--23w41a--SNAPSHOT)-Even%20with%20dev-brightgreen?style=flat-square) </br>

**Comment by MSCMDD** [comment]
https://dump.viaversion.com/9a4014b5c03d5243106b9ae6ddbd90a4021cb57e290bc37a9a9e17d3d45c767d

**Comment by Barvalg** [comment]
![Platform: git--Paper--238%20%28MC%3A%201.20.2%29](https://img.shields.io/badge/Platform-git--Paper--238%20%28MC%3A%201.20.2%29-3498db?style=flat-square) </br>![ViaVersion (4.9.0-23w41a-SNAPSHOT): Even with dev](https://img.shields.io/badge/ViaVersion%20(4.9.0--23w41a--SNAPSHOT)-Even%20with%20dev-brightgreen?style=flat-square) </br>![ViaBackwards(4.9.0-23w41a-SNAPSHOT): Even with dev](https://img.shields.io/badge/ViaBackwards%20(4.9.0--23w41a--SNAPSHOT)-Even%20with%20dev-brightgreen?style=flat-square) </br>

**Comment by kennytv** [comment]
Display them correctly where? What exactly does "abnormally" mean?

**Comment by MSCMDD** [comment]
For example, when I enter “advancement grant User everything” in the server console, I can see the normal feedback through the 1.20.2 client.
![image](https://github.com/ViaVersion/ViaBackwards/assets/128666602/0874d75a-f49e-46e0-93b7-93fef11ca686)
![image](https://github.com/ViaVersion/ViaBackwards/assets/128666602/8cc5d5ef-5c31-4b4e-9696-7d7be92769d3)
However, when I use the 1.20.1 version of the client or any lower version, I cannot see the advancement progress being completed.
![image](https://github.com/ViaVersion/ViaBackwards/assets/128666602/34886449-df58-420b-b786-1ba8519df721)

**Comment by MSCMDD** [comment]
How should I configure them to enable lower version clients to display advancements correctly, or is there an error causing the issue? Could it be due to using a new version of the Paper server (Paper build explorer: #231, 5509610 Fix UnsafeValues#loadAdvancement (#9753))?
emmmmmm
However, even when using a previous version of the Paper server, I still cannot display advancements correctly on lower versions of clients.

**Comment by Barvalg** [comment]
![Platform: git--Paper--246%20%28MC%3A%201.20.2%29](https://img.shields.io/badge/Platform-git--Paper--246%20%28MC%3A%201.20.2%29-3498db?style=flat-square) </br>![ViaVersion (4.9.0-23w43a-SNAPSHOT): Even with dev](https://img.shields.io/badge/ViaVersion%20(4.9.0--23w43a--SNAPSHOT)-Even%20with%20dev-brightgreen?style=flat-square) </br>![ViaBackwards(4.9.0-23w43a-SNAPSHOT): Even with dev](https://img.shields.io/badge/ViaBackwards%20(4.9.0--23w43a--SNAPSHOT)-Even%20with%20dev-brightgreen?style=flat-square) </br>

**Comment by Dreeam-qwq** [comment]
Same problem, but if using 1.12.2 or even lower version client, the advancements screen will show "There doesn't seem to be anything here"

**Comment by Saharo4eks** [comment]
Same problem

**Comment by DinoFengz** [comment]
Same problem for latest dev build

**Comment by wd4q5dy** [comment]
same problem

**Comment by jajader** [comment]
same problem

**Comment by Barvalg** [comment]
![Platform: git--Paper--246%20%28MC%3A%201.20.2%29](https://img.shields.io/badge/Platform-git--Paper--246%20%28MC%3A%201.20.2%29-3498db?style=flat-square) </br>![ViaVersion (4.9.0-23w43a-SNAPSHOT): 17 commits behind dev](https://img.shields.io/badge/ViaVersion%20(4.9.0--23w43a--SNAPSHOT)-17%20commit(s)%20behind%20dev-yellow?style=flat-square) </br>![ViaBackwards(4.9.0-23w43a-SNAPSHOT): 7 commits behind dev](https://img.shields.io/badge/ViaBackwards%20(4.9.0--23w43a--SNAPSHOT)-7%20commit(s)%20behind%20dev-yellow?style=flat-square) </br><br><h3>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump</h3>

**Comment by wd4q5dy** [comment]
https://dump.viaversion.com/13469c25d1fc98fe8c7082d660a5fba928c152b5b186648578994e59f03e052b
[dump.txt](https://github.com/ViaVersion/ViaBackwards/files/13343446/dump.txt)

**Comment by Barvalg** [comment]
![Platform: git--Paper--262%20%28MC%3A%201.20.2%29](https://img.shields.io/badge/Platform-git--Paper--262%20%28MC%3A%201.20.2%29-3498db?style=flat-square) </br>![ViaVersion (4.9.0-23w42a-SNAPSHOT): 28 commits behind dev](https://img.shields.io/badge/ViaVersion%20(4.9.0--23w42a--SNAPSHOT)-28%20commit(s)%20behind%20dev-yellow?style=flat-square) </br>![ViaBackwards(4.9.0-23w45a-SNAPSHOT): Even with dev](https://img.shields.io/badge/ViaBackwards%20(4.9.0--23w45a--SNAPSHOT)-Even%20with%20dev-brightgreen?style=flat-square) </br><br><h3>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump</h3>

**Comment by wd4q5dy** [comment]
https://dump.viaversion.com/6b0edd8a5ce779fdd1425d42d616a1570651597240758b20b7554252667b590e

**Comment by Barvalg** [comment]
![Platform: git--Paper--262%20%28MC%3A%201.20.2%29](https://img.shields.io/badge/Platform-git--Paper--262%20%28MC%3A%201.20.2%29-3498db?style=flat-square) </br>![ViaVersion (4.9.0-23w42a-SNAPSHOT): 37 commits behind dev](https://img.shields.io/badge/ViaVersion%20(4.9.0--23w42a--SNAPSHOT)-37%20commit(s)%20behind%20dev-yellow?style=flat-square) </br>![ViaBackwards(4.9.0-1.20.3-pre1-SNAPSHOT): Even with dev](https://img.shields.io/badge/ViaBackwards%20(4.9.0--1.20.3--pre1--SNAPSHOT)-Even%20with%20dev-brightgreen?style=flat-square) </br><br><h3>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump</h3>

**Comment by RICE0707** [comment]
> ![Platform: git--Paper--262%20%28MC%3A%201.20.2%29](https://camo.githubusercontent.com/83fbbb1f0977c8cee0bf1db626ceb9f88ffb50e5de8a1996ab9e83a064ec76c0/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f506c6174666f726d2d6769742d2d50617065722d2d3236322532302532384d43253341253230312e32302e322532392d3334393864623f7374796c653d666c61742d737175617265) ![ViaVersion (4.9.0-23w42a-SNAPSHOT): 37 commits behind dev](https://camo.githubusercontent.com/c0253be93ed510f8e3aac66c62acbde23b55304c93c9baf8133b1bfa1a6211ec/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f56696156657273696f6e25323028342e392e302d2d3233773432612d2d534e415053484f54292d3337253230636f6d6d6974287329253230626568696e642532306465762d79656c6c6f773f7374796c653d666c61742d737175617265) ![ViaBackwards(4.9.0-1.20.3-pre1-SNAPSHOT): Even with dev](https://camo.githubusercontent.com/8a957b6c507335fa937d1ce2de97e76fb220c32508aa9490c763e14c2d37cd4d/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f5669614261636b776172647325323028342e392e302d2d312e32302e332d2d707265312d2d534e415053484f54292d4576656e253230776974682532306465762d627269676874677265656e3f7374796c653d666c61742d737175617265)
> 
> ### Please try the **latest** build(s) from https://ci.viaversion.com/. In case the issue still persists send the new dump

https://dump.viaversion.com/a178ef326c3a6bfbe11f8ec6995abf5a846d189deacbc1f0ee12f34eb8222db2

**Comment by Barvalg** [comment]
![Platform: git--Purpur--2092%20%28MC%3A%201.20.2%29](https://img.shields.io/badge/Platform-git--Purpur--2092%20%28MC%3A%201.20.2%29-3498db?style=flat-square) </br>![ViaVersion (4.9.2): Even with master](https://img.shields.io/badge/ViaVersion%20(4.9.2)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(4.9.1): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.9.1)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by RICE0707** [comment]
> > ![平台：git--論文--262%20%28MC%3A%201.20.2%29](https://camo.githubusercontent.com/83fbbb1f0977c8cee0bf1db626ceb9f88ffb50e5de8a1996ab9e83a064ec76c0/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f506c6174666f726d2d6769742d2d50617065722d2d3236322532302532384d43253341253230312e32302e322532392d3334393864623f7374796c653d666c61742d737175617265) ![ViaVersion (4.9.0-23w42a-SNAPSHOT)：落後開發者 37 次提交](https://camo.githubusercontent.com/c0253be93ed510f8e3aac66c62acbde23b55304c93c9baf8133b1bfa1a6211ec/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f56696156657273696f6e25323028342e392e302d2d3233773432612d2d534e415053484f54292d3337253230636f6d6d6974287329253230626568696e642532306465762d79656c6c6f773f7374796c653d666c61742d737175617265) ![ViaBackwards(4.9.0-1.20.3-pre1-SNAPSHOT)：即使使用開發](https://camo.githubusercontent.com/8a957b6c507335fa937d1ce2de97e76fb220c32508aa9490c763e14c2d37cd4d/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f5669614261636b776172647325323028342e392e302d2d312e32302e332d2d707265312d2d534e415053484f54292d4576656e253230776974682532306465762d627269676874677265656e3f7374796c653d666c61742d737175617265)
> > ### 請嘗試[https://ci.viaversion.com/中的](https://ci.viaversion.com/)**最新**版本。如果問題仍然存在，請發送新的轉儲[](https://ci.viaversion.com/)
> 
> https://dump.viaversion.com/a178ef326c3a6bfbe11f8ec6995abf5a846d189deacbc1f0ee12f34eb8222db2

1.20.4
![image](https://github.com/ViaVersion/ViaBackwards/assets/68499464/a51034ec-60d2-4ac1-9dce-8c90a2e68310)

1.20.3
![image](https://github.com/ViaVersion/ViaBackwards/assets/68499464/84690b4e-c0b4-4d1e-b4de-b8872642f9f4)

1.20.2
![image](https://github.com/ViaVersion/ViaBackwards/assets/68499464/d84196a1-ec2f-407d-b566-c400aa022998)

1.20.1
![image](https://github.com/ViaVersion/ViaBackwards/assets/68499464/69f3a051-f460-457b-a6fc-7eff89c0f5dd)

1.20
![image](https://github.com/ViaVersion/ViaBackwards/assets/68499464/f07e00a8-126c-4716-8cb6-060b161f8f38)

**Comment by RICE0707** [comment]
> ![Platform: git--Purpur--2092%20%28MC%3A%201.20.2%29](https://camo.githubusercontent.com/b1a6b2274c33aeed9b089305ffb70387f0152fb354dda18790166c74601a97f0/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f506c6174666f726d2d6769742d2d5075727075722d2d323039322532302532384d43253341253230312e32302e322532392d3334393864623f7374796c653d666c61742d737175617265) ![ViaVersion (4.9.2): Even with master](https://camo.githubusercontent.com/32f7a1018f7b4920eeabe3b21d1c056d50de3c22979d72677f768640b81847e1/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f56696156657273696f6e25323028342e392e32292d4576656e253230776974682532306d61737465722d627269676874677265656e3f7374796c653d666c61742d737175617265) ![ViaBackwards(4.9.1): 2 commits behind master](https://camo.githubusercontent.com/68d6f966610b3396d3b92ac0187b43aca57a7bdca8e6bd7de370ea3fbfbb5e1a/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f5669614261636b776172647325323028342e392e31292d32253230636f6d6d6974287329253230626568696e642532306d61737465722d79656c6c6f773f7374796c653d666c61742d737175617265)
> 
> ### Please try the **latest** build(s) from https://ci.viaversion.com/. In case the issue still persists send the new dump

https://dump.viaversion.com/4c11679206556024f63d2d7770f970b2a16521b17c6b1e4f555e96123a786a42

**Comment by Dreeam-qwq** [comment]
Any progress of this advancement display issue?

**Comment by DinoFengz** [comment]
Any progress?

**Comment by UnitedCraft** [comment]
Is that problem fixed?

**Comment by Krakenied** [comment]
https://gist.github.com/Krakenied/bfb18952b5ea60a766ad4a70448b6b89

Just in case anyone wants to use this only on a Bukkit-based server

**Comment by Dreeam-qwq** [comment]
This issue seems is fixed.

Plugins: [ViaBackwards](https://ci.viaversion.com/view/ViaBackwards/job/ViaBackwards-DEV/583/), [ViaVersion](https://ci.viaversion.com/job/ViaVersion-DEV/1052/), [ViaRewind](https://ci.viaversion.com/view/ViaRewind/job/ViaRewind-DEV/94/)
Tested on `git-Paper-318 (MC: 1.20.2)` with 1.20.1 vanilla client. And also tested on `git-Paper-450 (MC: 1.20.4)` with some major versions between 1.13 ~ 1.20.4. After granting all advancements, The advancement screen displays normally.

But using 1.8.9 or 1.12.2 vanilla client, it still has issues.
1.8.9: https://imgur.com/yvdd66W
1.12.2: https://imgur.com/5APqMZI

**Comment by kennytv** [comment]
> https://gist.github.com/Krakenied/bfb18952b5ea60a766ad4a70448b6b89
> 
> Just in case anyone wants to use this only on a Bukkit-based server

I'll get back to this once 1.20.5 is dealt with, thanks 😎
