### ISSUE TITLE
com.viaversion.viabackwards.protocol.protocol1_15_2to1_16.packets.EntityPackets1_16$5

### ISSUE THREAD

**Issue by Cerealistic** [ViaVersion/ViaBackwards#617]
### '/viaversion dump' Output

https://dump.viaversion.com/e875211748d5af37306743daaec263333756d9dcac23c64201d12f91e6747caa

### Console Error

[Paste.gg](https://paste.gg/p/anonymous/3585b9b4e47044fe83637331428d4936)

### Bug Description

Randomly, the server is running fine and then this error happens. Users start not being able to join until I kick the user who is mentioned to have the faulty playerdata.

![image](https://github.com/ViaVersion/ViaBackwards/assets/117193440/d1d0e600-4019-4175-9572-43027aba11e3)
This is an example of the error, but with a different player.

### Steps to Reproduce

Reproduction Steps:

1. Join the server with a 1.8.x client.
2. On connection to the backend, you will be kicked on join with this error.

### Expected Behavior

The player should be able to connect to the server.

### Additional Server Info

I have Waterfall running with AuthMeBungee, LuckPermsBungee, EaglercraftXBungee, ServerListPlus, HubMagic, Spark, and BanManager.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Purpur--1428%20%28MC%3A%201.17.1%29](https://img.shields.io/badge/Platform-git--Purpur--1428%20%28MC%3A%201.17.1%29-3498db?style=flat-square) </br>![ViaVersion (4.9.0-23w41a-SNAPSHOT): Even with dev](https://img.shields.io/badge/ViaVersion%20(4.9.0--23w41a--SNAPSHOT)-Even%20with%20dev-brightgreen?style=flat-square) </br>![ViaBackwards(4.9.0-23w41a-SNAPSHOT): 1 commits behind dev](https://img.shields.io/badge/ViaBackwards%20(4.9.0--23w41a--SNAPSHOT)-1%20commit(s)%20behind%20dev-yellow?style=flat-square) </br>![ViaRewind(3.0.3-SNAPSHOT): 5 commits behind dev](https://img.shields.io/badge/ViaRewind%20(3.0.3--SNAPSHOT)-5%20commit(s)%20behind%20dev-yellow?style=flat-square) </br><br><h3>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump</h3>

**Comment by Cerealistic** [comment]
https://dump.viaversion.com/f9319cd678a330abb8d08c87f38aab1ec1cebffb618dee3ba45600a8be7b2dd9

**Comment by Barvalg** [comment]
![Platform: git--Purpur--1428%20%28MC%3A%201.17.1%29](https://img.shields.io/badge/Platform-git--Purpur--1428%20%28MC%3A%201.17.1%29-3498db?style=flat-square) </br>![ViaVersion (4.9.0-23w41a-SNAPSHOT): Even with dev](https://img.shields.io/badge/ViaVersion%20(4.9.0--23w41a--SNAPSHOT)-Even%20with%20dev-brightgreen?style=flat-square) </br>![ViaBackwards(4.9.0-23w41a-SNAPSHOT): Even with dev](https://img.shields.io/badge/ViaBackwards%20(4.9.0--23w41a--SNAPSHOT)-Even%20with%20dev-brightgreen?style=flat-square) </br>![ViaRewind(3.0.3-SNAPSHOT): Even with dev](https://img.shields.io/badge/ViaRewind%20(3.0.3--SNAPSHOT)-Even%20with%20dev-brightgreen?style=flat-square) </br>

**Comment by Kichura** [comment]
This seems to be caused by a third-party plugin causing viaversion to fail, please perform a binary search to see which one is causing it.
