### ISSUE TITLE
The sculk catalyst does not break

### ISSUE THREAD

**Issue by Freemandns** [ViaVersion/ViaBackwards#618]
### '/viaversion dump' Output

https://dump.viaversion.com/ad20476f2b518414107010af6383db5b4901169e6ab4686d2368e00a42972b47

### Bug Description

My server has version 1.19. Players who have client version 1.9 through 1.18.2 cannot break "sculk_shrieker". Perhaps it's because it shows up as "end_portal_frame".

### Steps to Reproduce

1. I enter the server from the client 1.18.2;
2. I find the block "sculk_shrieker", which looks like "end_portal_frame";
3. I try to break it with my hand;
4. After a minute, the block still hasn't broken.

### Expected Behavior

1. I am logged in from version 1.9 to 1.18.2;
2. I find the block "sculk_shrieker", which looks like "end_portal_frame";
3. I start breaking it, for example, with my hand;
4. It breaks after 4.5 seconds (this is the time it takes to break the block with my hand).

### Additional Server Info

The project has no proxy server, and everything else you can see here: https://dump.viaversion.com/ad20476f2b518414107010af6383db5b4901169e6ab4686d2368e00a42972b47.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: 3553--Bukkit--ef09464%20%28MC%3A%201.19%29](https://img.shields.io/badge/Platform-3553--Bukkit--ef09464%20%28MC%3A%201.19%29-3498db?style=flat-square) </br>![ViaVersion (4.8.1): Even with master](https://img.shields.io/badge/ViaVersion%20(4.8.1)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(4.8.1): 1 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.8.1)-1%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump</h3>

**Comment by Freemandns** [comment]
https://dump.viaversion.com/7645af67a5aec0fca246a91d708007f0dd640cb0ad59e8c6af3e266f77c004dd

**Comment by Barvalg** [comment]
![Platform: 3553--Bukkit--ef09464%20%28MC%3A%201.19%29](https://img.shields.io/badge/Platform-3553--Bukkit--ef09464%20%28MC%3A%201.19%29-3498db?style=flat-square) </br>![ViaVersion (4.8.1): Even with master](https://img.shields.io/badge/ViaVersion%20(4.8.1)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(4.8.1): 1 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.8.1)-1%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump</h3>

**Comment by SyedOmarNoor** [comment]
is that not the latest build?
