### ISSUE TITLE
ERROR IN Protocol1_19To1_19_1 IN REMAP OF SYSTEM_CHAT (0x62)

### ISSUE THREAD

**Issue by Overwrite987** [ViaVersion/ViaBackwards#619]
### '/viaversion dump' Output

https://dump.viaversion.com/11de0114ad39db4dfea9a204dda562ef71d33333e67bd46227aaae19d4cae6cf

### Console Error

```
Put the paste.gg link or text here.
```
https://paste.gg/p/anonymous/d68049b954204a28a0a3b63c76c1c283

### Bug Description

when trying to log in to the server version 1.20.1 from version 1.16.5 with the last installed dev build viaver and viaback, the following error occurs and player gets kicked

### Steps to Reproduce

1) Start the 1.20.1 server with latest viaver + viaback dev build installed
2) Join via 1.16.5
3) Here we are

### Expected Behavior

The error should not occur and player should not be kicked

### Additional Server Info

none

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--196%20%28MC%3A%201.20.1%29](https://img.shields.io/badge/Platform-git--Paper--196%20%28MC%3A%201.20.1%29-3498db?style=flat-square) </br>![ViaVersion (4.9.0-23w41a-SNAPSHOT): Even with dev](https://img.shields.io/badge/ViaVersion%20(4.9.0--23w41a--SNAPSHOT)-Even%20with%20dev-brightgreen?style=flat-square) </br>![ViaBackwards(4.9.0-23w41a-SNAPSHOT): Even with dev](https://img.shields.io/badge/ViaBackwards%20(4.9.0--23w41a--SNAPSHOT)-Even%20with%20dev-brightgreen?style=flat-square) </br>

**Comment by kennytv** [comment]
Fixed once the latest ViaVersion build finished
