### ISSUE TITLE
Getting disconnected when player gets near

### ISSUE THREAD

**Issue by GabiRP** [ViaVersion/ViaBackwards#620]
### '/viaversion dump' Output

Can't using ViaForge

### Console Error

[https://mclo.gs/Y0IKjPR](https://mclo.gs/Y0IKjPR)

### Bug Description

Using ViaForge to join a 1.20.2 server using 1.12.2 and a player gets near you, you get kicked from the server with an error saying
`java.io.IOException: Packet 0/64 (SPacketSetExperience) was larger than I expected, found 1 bytes extra whilst reading packet 64`

### Steps to Reproduce

1. Use ViaForge to get into a 1.20.2 server using 1.12.2
2. Have a player approach you
3. Once the player gets within 20-30 blocks away from you, you get kicked from the server

### Expected Behavior

When a player approaches you, you shouldn't get kicked.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Error: Invalid or missing dump](https://img.shields.io/badge/Error-Invalid/missing%20dump-red?style=flat-square) </br>

**Comment by kennytv** [comment]
That error is not from the latest ViaVersion build
