### ISSUE TITLE
It is not possible to connect from 1.20.1 to a 1.20.2 server that's using server-resourcepack

### ISSUE THREAD

**Issue by LocalMachineOnLinux** [ViaVersion/ViaBackwards#627]
### '/viaversion dump' Output

https://dump.viaversion.com/c75f264b53f661ceb8206579d5b13479c8cc8d37e9ef6497ca23d3fb9b05113b

### Bug Description

No one can connect to server if there is the server resourcepack.

### Steps to Reproduce

1. Login with a 1.20.1 or 1.20 client and get an error: "Failed to connect to the server. Internal Exception: io.netty.handler.codex.DecoderException:
java.lang.IndexOutOfBoundsException: Index 64 out of bounds for length 5"
![problem](https://github.com/ViaVersion/ViaBackwards/assets/75432821/eeee37dc-51c6-42aa-9ef8-c7dd826f2219)

### Expected Behavior

I think anyone should be able to connect, regardless of whether there is a server resource pack or not

### Additional Server Info

No, I don't use BungeeCord or anything like that.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--241%20%28MC%3A%201.20.2%29](https://img.shields.io/badge/Platform-git--Paper--241%20%28MC%3A%201.20.2%29-3498db?style=flat-square) </br>![ViaVersion (4.8.1): Even with master](https://img.shields.io/badge/ViaVersion%20(4.8.1)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(4.8.1): 2 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.8.1)-2%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump</h3>

**Comment by kennytv** [comment]
Update to ci dev builds
