### ISSUE TITLE
Trade rebalance's filled maps cause permanent kicks

### ISSUE THREAD

**Issue by Kichura** [ViaVersion/ViaBackwards#629]
### '/viaversion dump' Output

https://dump.viaversion.com/231e94ab40b025911cdaf43d5e8bfceecb1ff481bc4b5bb8435e7bf73ab47c39

### Console Error

*(Console reports no errors)*

### Bug Description

When buying any filled maps that are from the villager trade rebalance datapack which is included in 1.20.2, it will cause permanent kicks to occur once it is placed into the inventory - the maps are also untranslated which adds extra concerns.

### Steps to Reproduce

1. Create any Spigot/Paper server that contains no world data,
2. Enable the trade rebalance datapack using `initial-enabled-packs` via server properties file,
3. Spawn a cartographer villager and unlock the filled maps,
4. Attempt to buy one map and place it into the inventory,
5. You should get instantly kicked until your inventory is modified to not have it.

### Expected Behavior

The filled maps in the datapack are translated and can be bought without getting thrown out permanently.

### Additional Server Info

1. This setup did not use any proxy software,
2. Purpur *(Build 2088)* with latest dev builds of ViaVersion + ViaBackwards from the CI website and Spark as it is shipped with Purpur by default.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Purpur--2088%20%28MC%3A%201.20.2%29](https://img.shields.io/badge/Platform-git--Purpur--2088%20%28MC%3A%201.20.2%29-3498db?style=flat-square) </br>![ViaVersion (4.9.0-23w44a-SNAPSHOT): Even with dev](https://img.shields.io/badge/ViaVersion%20(4.9.0--23w44a--SNAPSHOT)-Even%20with%20dev-brightgreen?style=flat-square) </br>![ViaBackwards(4.9.0-23w44a-SNAPSHOT): Even with dev](https://img.shields.io/badge/ViaBackwards%20(4.9.0--23w44a--SNAPSHOT)-Even%20with%20dev-brightgreen?style=flat-square) </br>

**Comment by kennytv** [comment]
What kick message? What client version?
