### ISSUE TITLE
Slim and MagmaCube size are 1 hitbox can't match when client version below 1.19.3

### ISSUE THREAD

**Issue by Happy-FZM** [ViaVersion/ViaBackwards#634]
### '/viaversion dump' Output

https://dump.viaversion.com/b66851f94e3e013d8ac7332088fa457c62bcdb9c9af4a8c92531190410c92a5e

### Bug Description

Slim and MagmaCube size are 1 hitbox can't match when client version below 1.19.3.

### Steps to Reproduce

1. Login with a clent version below 1.19.3

### Expected Behavior

Slim and MagmaCube size are 1 hitbox can't match

![1 18 2](https://github.com/ViaVersion/ViaBackwards/assets/8757536/871259df-d2dc-432d-b8e5-89a830e236ee)
![1 19 2](https://github.com/ViaVersion/ViaBackwards/assets/8757536/9c37b309-68ea-489e-a163-694b5730368d)
![1 19 3](https://github.com/ViaVersion/ViaBackwards/assets/8757536/769272e3-2707-4339-9dc9-9cd6887b5569)

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--299%20%28MC%3A%201.20.2%29](https://img.shields.io/badge/Platform-git--Paper--299%20%28MC%3A%201.20.2%29-3498db?style=flat-square) </br>![ViaVersion (4.8.1): 2 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.8.1)-2%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(4.8.1): 2 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.8.1)-2%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump</h3>

**Comment by Happy-FZM** [comment]
https://dump.viaversion.com/118b746aa4c2115c88c6cde74cad633bdf1d9c83b1e3286541cda01cd69d1334

**Comment by Barvalg** [comment]
![Platform: git--Paper--299%20%28MC%3A%201.20.2%29](https://img.shields.io/badge/Platform-git--Paper--299%20%28MC%3A%201.20.2%29-3498db?style=flat-square) </br>![ViaVersion (4.9.0-1.20.3-pre2-SNAPSHOT): Even with dev](https://img.shields.io/badge/ViaVersion%20(4.9.0--1.20.3--pre2--SNAPSHOT)-Even%20with%20dev-brightgreen?style=flat-square) </br>![ViaBackwards(4.9.0-1.20.3-pre1-SNAPSHOT): Even with dev](https://img.shields.io/badge/ViaBackwards%20(4.9.0--1.20.3--pre1--SNAPSHOT)-Even%20with%20dev-brightgreen?style=flat-square) </br>

**Comment by kennytv** [comment]
There have been a few client bugs with slime hitboxes in the past, this is likely one of them, in that case there'd be nothing we can do about it
