### ISSUE TITLE
Holograms not showing for players on older versions

### ISSUE THREAD

**Issue by qrawless** [ViaVersion/ViaBackwards#637]
### Problem Description

I am running a Minecraft server with the version 1.20.2 (Purpur). I would like to use the holograms that were added in this version. However, when I do, holograms are not shown to players who join my server on older versions.

I would like to request a feature that would allow me to show holograms to players on older versions in the old style, instead of the new method.

Steps to reproduce:
  1. Create a Minecraft server with the version 1.20.2 (Purpur).
  2. Install a plugin that allows you to create holograms.
  3. Create a hologram (new method).
  4. Join the server with a client that is running an older version of Minecraft.
  5. The hologram should not be visible.

**Expected behavior:**
The hologram should be visible to players on all versions of Minecraft.

### Solution Description

A possible solution would be to show a new style hologram with the old hologram style to players logged in with the lower version.

**Comment by kennytv** [comment]
Wrong issue template; you probably just need to update to -dev builds on https://ci.viaversion.com/

**Comment by qrawless** [comment]
![image](https://github.com/ViaVersion/ViaBackwards/assets/37976051/f1ad4bf4-d800-4e2a-affe-32068d287ae6)
![image](https://github.com/ViaVersion/ViaBackwards/assets/37976051/85913aed-b60a-4b72-9494-103828d1560a)

I updated to the latest alpha version. as you said, the hologram is there, but it only shows one line. is there any way to fix it?
