### ISSUE TITLE
Invisible display entities

### ISSUE THREAD

**Issue by h14turkiye** [ViaVersion/ViaBackwards#638]
### '/viaversion dump' Output

https://dump.viaversion.com/1ee41b5bb44bc706e36ef0c249da7814770865cf53c9f2aabf785605d3cf4e91

### Bug Description

Invisible displays in lower versions.

### Steps to Reproduce

Base server is 1.20.2
Login with 1.20.1
Summon a display entity
display entity is not visible

### Expected Behavior

display entity is visible

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--309%20%28MC%3A%201.20.2%29](https://img.shields.io/badge/Platform-git--Paper--309%20%28MC%3A%201.20.2%29-3498db?style=flat-square) </br>![ViaVersion (4.8.1): 2 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.8.1)-2%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(4.8.1): 2 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.8.1)-2%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump</h3>

**Comment by kennytv** [comment]
Update to -dev builds from the ci
