### ISSUE TITLE
NoSuchFieldError: RESOURCE_PACK_PUSH - can't start fabric 1.20.2 server with latest OR snapshot viafabackwards + viafabric + fabricAPI

### ISSUE THREAD

**Issue by RealKomander** [ViaVersion/ViaBackwards#644]
### '/viaversion dump' Output

the server doesn't load

### Console Error

https://paste.gg/p/anonymous/2ddd5662e0d044a6bce8471e42b3561c

### Bug Description

Server doesn't load up and outputs this error

### Steps to Reproduce

To replicate, just install latest  viafabackwards + viafabric + fabricAPI or their latest snapshots on a fabric 1.20.2 server

### Expected Behavior

Loading up

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Error: Invalid or missing dump](https://img.shields.io/badge/Error-Invalid/missing%20dump-red?style=flat-square) </br>

**Comment by wrotin** [comment]
@RealKomander  зайди в гс олух

**Comment by Kichura** [comment]
Install viaversion 4.9.2 and viabackwards 4.9.1 onto your fabric server's mods folder.

**Comment by RealKomander** [comment]
How am I supposed to install viaversion on a fabric server? Did you mean viafabric? Which version do I need to install then?

**Comment by RealKomander** [comment]
I'm still getting the same error with any viafabric build I try

**Comment by Kichura** [comment]
You instal latest CI build of viaversion and viabackwards jars onto mods folder and use latest viafabric build from modrinth as the loader.

**Comment by RealKomander** [comment]
How on earth do you use a mod as a loader? Sorry for me being dumb, but I genuinely don't understand and can't find any information online

**Comment by RealKomander** [comment]
And what is a CI build? Is it just the latest compatible build or something?

**Comment by HowardZHY** [comment]
> And what is a CI build? Is it just the latest compatible build or something?

Just download Latest (Alpha) of all 3 mod and plugins ViaFabric, ViaVersion and ViaBackwards from Modrinth
