### ISSUE TITLE
Error related to the map in the frame at negative height | ERROR IN Protocol1_16_4To1_17 IN REMAP OF MAP_DATA (0x27)

### ISSUE THREAD

**Issue by Overwrite987** [ViaVersion/ViaBackwards#646]
### '/viaversion dump' Output

https://dump.viaversion.com/e25b0de94c6d6010ab2f1f5320580818c73827fef411a2e86c420e66af6995a8

### Console Error

```
https://paste.gg/p/anonymous/f8f9f5d03ff8413cb6573d977d8d6fc3
```

### Bug Description

When a player logs into a server with version 1.16.5 or lower - he gets this error and gets kicked. If he logs in with 1.17 and above - there is no error.
This happens only when there is a frame in which the map is installed (and maybe not only the map) and it is located at a minus height

### Steps to Reproduce

1) Start 1.20.2 server and join with 1.20.2 or any version that support negative Y coords
2) go to the negative Y coordinate
3) Place a frame and put a map into that frame (or a glowing frame, no matters)
4) join with 1.16.5
5) Error 

### Expected Behavior

there should not be this error

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Error: Invalid or missing dump](https://img.shields.io/badge/Error-Invalid/missing%20dump-red?style=flat-square) </br>

**Comment by Overwrite987** [comment]
> ![Error: Invalid or missing dump](https://camo.githubusercontent.com/d52699b4f8c5e7e91cb92ecd59b5aa5ed2f9eb37e741b87aa9334b5e364c0512/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f4572726f722d496e76616c69642f6d697373696e6725323064756d702d7265643f7374796c653d666c61742d737175617265)

it is not...
