### ISSUE TITLE
Joining with lower versions on proxy does not work

### ISSUE THREAD

**Issue by RealBauHD** [ViaVersion/ViaBackwards#647]
### '/viaversion dump' Output

https://dump.viaversion.com/5ce10993b100c702ed7db51f82f1c2b63759011c5897c4233c3fb45549883c5e

### Console Error

```
https://paste.gg/p/anonymous/3716258a79254e2392953955208c742d
```

### Bug Description

When you join a network with 1.20.2 backend servers with an < 1.20.2 Client you cann't connect.

### Steps to Reproduce

1. Make a proxy with Via* plugins
2. Make a 1.20.2 backend server
3. Try to join with an < 1.20.2 Client

### Expected Behavior

ViaBackwards should make it happen that you can join a 1.20.2 with older versions.

### Additional Server Info

Tested with Velocity and Waterfall, if the Plugins are on a backend paper server it works.

![image](https://github.com/ViaVersion/ViaBackwards/assets/71191102/b43d55f0-6d17-45f2-982f-9162f0651aad)
Error when joining with an 1.19.4 Client through Waterfall

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: velocity%203.2.0--SNAPSHOT%20%28git--07a525be--b296%29](https://img.shields.io/badge/Platform-velocity%203.2.0--SNAPSHOT%20%28git--07a525be--b296%29-3498db?style=flat-square) </br>![Proxy is 5 builds behind](https://img.shields.io/badge/Your%20proxy%20is%205%20build(s)%20behind.%20Please%20update%20to%20the%20latest%20version-orange?style=flat-square) </br>![ViaVersion (4.9.2): 9 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.9.2)-9%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaRewind(3.0.5): Even with master](https://img.shields.io/badge/ViaRewind%20(3.0.5)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(4.9.1): 7 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.9.1)-7%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump</h3>

**Comment by RealBauHD** [comment]
https://dump.viaversion.com/713d3826785e738b81371e6ab3ebc2f456e79d81be55be9766c227cfef86e395

**Comment by Barvalg** [comment]
![Platform: velocity%203.2.0--SNAPSHOT%20%28git--07a525be--b296%29](https://img.shields.io/badge/Platform-velocity%203.2.0--SNAPSHOT%20%28git--07a525be--b296%29-3498db?style=flat-square) </br>![Proxy is 5 builds behind](https://img.shields.io/badge/Your%20proxy%20is%205%20build(s)%20behind.%20Please%20update%20to%20the%20latest%20version-orange?style=flat-square) </br>![ViaVersion (4.9.3-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.9.3--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaRewind(3.0.5): Even with master](https://img.shields.io/badge/ViaRewind%20(3.0.5)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(4.9.1): 7 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.9.1)-7%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump</h3>

**Comment by RealBauHD** [comment]
https://dump.viaversion.com/39e52d2cba9f963b4ccf0a0e2c29ba08dc0ee32907357b6d60b956ddbcc756c6

**Comment by Barvalg** [comment]
![Platform: velocity%203.3.0--SNAPSHOT%20%28git--b270206d--b301%29](https://img.shields.io/badge/Platform-velocity%203.3.0--SNAPSHOT%20%28git--b270206d--b301%29-3498db?style=flat-square) </br>![ViaVersion (4.9.3-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.9.3--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaRewind(3.0.5): Even with master](https://img.shields.io/badge/ViaRewind%20(3.0.5)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(4.9.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.9.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by RealBauHD** [comment]
Could not reproduce on latest versions.
