### ISSUE TITLE
Tab completion before 1.13.1 is borked on 1.20.4 server

### ISSUE THREAD

**Issue by BadAimWeeb** [ViaVersion/ViaBackwards#648]
### '/viaversion dump' Output

https://dump.viaversion.com/14a1654f255e96032b37993d9ac0c311d707d1df6ff98fc0f13e5a18653c6445

### Console Error

https://paste.gg/p/anonymous/44a9d22a80d5405498d2ec9622fa9978

### Bug Description

Trying to type commands will result in connection getting disconnected.

### Steps to Reproduce

1. Run a 1.20.4 server and connect using client version lower than 1.13.1
2. Try to write command and let it auto-complete
3. Connection crash

### Expected Behavior

Tab completion should work flawlessly.

### Additional Server Info

Velocity is used (3.2.0-SNAPSHOT git-7774e993), Velocity/1150 enabling 1.20.3/4 proxy (should not affect anything).

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--324%20%28MC%3A%201.20.4%29](https://img.shields.io/badge/Platform-git--Paper--324%20%28MC%3A%201.20.4%29-3498db?style=flat-square) </br>![ViaVersion (4.9.3-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.9.3--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaRewind(3.0.5): Even with master](https://img.shields.io/badge/ViaRewind%20(3.0.5)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(4.9.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.9.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>
