### ISSUE TITLE
lower 1.20.1 versions cannot join to the server of fabric 1.20.2+

### ISSUE THREAD

**Issue by 404XiaoTuHao** [ViaVersion/ViaBackwards#649]
### '/viaversion dump' Output

https://dump.viaversion.com/3cbcb0427c118e0f3f19cff433fb0c0a767fe384b5577563ffadab8768ce8fd4

### Bug Description

<=1.20.1 can join to the server of paper 1.20.2, but cannot join to the server of >=fabric 1.20.2. The fabric server mods only has the fabric API and fabric proxy

### Steps to Reproduce

1、velocity Install latest viabackwards and viaversion，via are only running on velocity
2、Use 1.20.1 and lower client versions Connect server of fabric 1.20.2+
3、Tip: You are already trying to connect to a server
![(T@~$V%)NVQDSE3%~E$ B{Q](https://github.com/ViaVersion/ViaBackwards/assets/82070627/3570646c-9c41-4f26-a6df-66f3976f2adf)

1、via  are only running on fabric server
2、fabric 1.20.2 server only capable of install viafabric-0.4.11+44-dev、ViaBackwards-4.8.1、ViaVersion-4.8.1，then can it startup
![MPX{7}$32D(SKVCB3MA8P9L](https://github.com/ViaVersion/ViaBackwards/assets/82070627/4f030b35-6f02-4df0-9c31-0c655bb8ac27)

### Expected Behavior

Use 1.20.1 and lower client versions normal to connect server of fabric 1.20.2+

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: velocity%203.2.0--SNAPSHOT%20%28git--07a525be--b296%29](https://img.shields.io/badge/Platform-velocity%203.2.0--SNAPSHOT%20%28git--07a525be--b296%29-3498db?style=flat-square) </br>![Proxy is 7 builds behind](https://img.shields.io/badge/Your%20proxy%20is%207%20build(s)%20behind.%20Please%20update%20to%20the%20latest%20version-orange?style=flat-square) </br>![ViaVersion (4.9.3-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.9.3--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(4.9.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.9.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by ifacify** [comment]
Only reproducible with velocity + fabric server, standalone fabric server works just fine with vb. The issue also affects velocity + fabric server when vb is installed on the velocity proxy.

**Comment by Kichura** [comment]
Remove via* from velocity, also viafabric in fabric server is currently busted as of #642.
