### ISSUE TITLE
Tab information is broken for client below 1.17.1 on 1.20.4 server

### ISSUE THREAD

**Issue by BadAimWeeb** [ViaVersion/ViaBackwards#650]
### '/viaversion dump' Output

https://dump.viaversion.com/2c5d8a86153870d5712f2e48aa8cb28441104d8dbaac021a5268a56ab094fa14

### Console Error

https://paste.gg/p/anonymous/bc2a94c82d084517b8402f463ded979c

### Bug Description

After installing [TAB](https://github.com/NEZNAMY/TAB) 4.1.2, client below 1.17.1 (in this case, 1.16.1) got disconnected because of scoreboard/tab update.

### Steps to Reproduce

1. Install [TAB](https://github.com/NEZNAMY/TAB) 4.1.2
2. Join with client below 1.17.1
3. Get kicked out

### Expected Behavior

Client should not get kicked out.

### Additional Server Info

Server is running on Paper 1.20.4 with 1.21 feature enabled.
Velocity is used (3.2.0-SNAPSHOT git-7774e993), Velocity/1150 enabling 1.20.3/4 proxy (should not affect anything).

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--324%20%28MC%3A%201.20.4%29](https://img.shields.io/badge/Platform-git--Paper--324%20%28MC%3A%201.20.4%29-3498db?style=flat-square) </br>![ViaVersion (4.9.3-SNAPSHOT): 1 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.9.3--SNAPSHOT)-1%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaRewind(3.0.5): Even with master](https://img.shields.io/badge/ViaRewind%20(3.0.5)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(4.9.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.9.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br><br><h3>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump</h3>

**Comment by BadAimWeeb** [comment]
https://dump.viaversion.com/fe84c86d054542e3c6e9918e5c53e6479df52a91962f880b240a9771906d973d

**Comment by Barvalg** [comment]
![Platform: git--Paper--328%20%28MC%3A%201.20.4%29](https://img.shields.io/badge/Platform-git--Paper--328%20%28MC%3A%201.20.4%29-3498db?style=flat-square) </br>![ViaVersion (4.9.3-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.9.3--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaRewind(3.0.5): Even with master](https://img.shields.io/badge/ViaRewind%20(3.0.5)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(4.9.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.9.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>
