### ISSUE TITLE
1.20.2 client cannot join 1.20.1 server

### ISSUE THREAD

**Issue by JeffHD** [ViaVersion/ViaBackwards#651]
### '/viaversion dump' Output

https://dump.viaversion.com/6028a398991b86be497cc14ecbdedb7da301aeb4b3172b82e68617499ec45492

### Console Error

```
Outdated server! I'm still on 1.20.1
```

### Bug Description

I want to join my 1.20.1 server with 1.20.2 client and  cannot join

### Steps to Reproduce

PaperServer on 1.20.1 + latest BungeeCord + latest ViaVersion/ViaBackwards
Join with 1.20.2 Client
Get Kicked

### Expected Behavior

Join the server normally

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git%3ABungeeCord--Bootstrap%3A1.20--R0.2--SNAPSHOT%3A1a80773%3A1779](https://img.shields.io/badge/Platform-git%3ABungeeCord--Bootstrap%3A1.20--R0.2--SNAPSHOT%3A1a80773%3A1779-3498db?style=flat-square) </br>![ViaVersion (4.9.3-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.9.3--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(4.9.2-SNAPSHOT): Even with dev](https://img.shields.io/badge/ViaBackwards%20(4.9.2--SNAPSHOT)-Even%20with%20dev-brightgreen?style=flat-square) </br>

**Comment by Kichura** [comment]
Have you tried running via* on thr spigot/paper servers instead of bungee?

**Comment by JeffHD** [comment]
Yes i tried. Client error: Internal Exception: io.netty.handler.codec.DecoderException: java.io.IOException: Packet play/24 (class_2658) was larger than I expected, found 239 bytes extra whilst reading packet 24
No error in server console

**Comment by Kichura** [comment]
Then it's either f3name or another third-party plugin is causing the play packet to get overflowed.

**Comment by JeffHD** [comment]
yes it was f3name. but with via on server instead on bungee the plugin BungeeTabListPlus cannot function correctly causing my tablist to break. Plus the setup should remain that via is on bungee since all my servers are setup to work with exactly with this configuration

**Comment by Kichura** [comment]
Well this would be a problem since:

A: It's very easy for viaversion to break since it has essentially no clue what's on the spigot/paper servers if running on proxy, *(causing it to try and guess everything by itself)*
and B: If it's about tab, you could use tab plugin on backend server instead with the setup you need.

**Comment by JeffHD** [comment]
But ViaVersion knows every Serverversion and is completly right about them as seen in the dump...
The tab runs on proxy and backend since they comunicate
And running via on proxy IS a feature. If the feature is not working correctly its still a bug and not completed....
