### ISSUE TITLE
Getting kicked from backend to proxxy

### ISSUE THREAD

**Issue by HiMyNameIsBoxxy** [ViaVersion/ViaBackwards#652]
### '/viaversion dump' Output

https://dump.viaversion.com/a56cd4e1e248b221bc7f96916117da715f796990ef02984d7e0b94b58c7d292c

### Console Error

<html>
<body>

[10:15:00 ERROR]: [connected player] HiMyNameIsBoxxy (/**.**.**.**:61849): unable to connect to server lifesteal
--
2 | io.netty.handler.codec.DecoderException: com.viaversion.viaversion.exception.InformativeException: Please report this on the Via support Discord or open an issue on the relevant GitHub repository
3 | Source 0: com.viaversion.viaversion.protocols.base.BaseProtocol1_7$$Lambda$1881/0x00007f9015afd530
4 | at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:98) ~[velocity-3.3.0-SNAPSHOT-303.jar:3.3.0-SNAPSHOT (git-a6d90105-b303)]
5 | at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[velocity-3.3.0-SNAPSHOT-303.jar:3.3.0-SNAPSHOT (git-a6d90105-b303)]
6 | at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity-3.3.0-SNAPSHOT-303.jar:3.3.0-SNAPSHOT (git-a6d90105-b303)]
7 | at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[velocity-3.3.0-SNAPSHOT-303.jar:3.3.0-SNAPSHOT (git-a6d90105-b303)]
8 | at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[velocity-3.3.0-SNAPSHOT-303.jar:3.3.0-SNAPSHOT (git-a6d90105-b303)]
9 | at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[velocity-3.3.0-SNAPSHOT-303.jar:3.3.0-SNAPSHOT (git-a6d90105-b303)]
10 | at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity-3.3.0-SNAPSHOT-303.jar:3.3.0-SNAPSHOT (git-a6d90105-b303)]
11 | at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[velocity-3.3.0-SNAPSHOT-303.jar:3.3.0-SNAPSHOT (git-a6d90105-b303)]
12 | at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[velocity-3.3.0-SNAPSHOT-303.jar:3.3.0-SNAPSHOT (git-a6d90105-b303)]
13 | at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) ~[velocity-3.3.0-SNAPSHOT-303.jar:3.3.0-SNAPSHOT (git-a6d90105-b303)]
14 | at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity-3.3.0-SNAPSHOT-303.jar:3.3.0-SNAPSHOT (git-a6d90105-b303)]
15 | at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[velocity-3.3.0-SNAPSHOT-303.jar:3.3.0-SNAPSHOT (git-a6d90105-b303)]
16 | at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346) ~[velocity-3.3.0-SNAPSHOT-303.jar:3.3.0-SNAPSHOT (git-a6d90105-b303)]
17 | at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318) ~[velocity-3.3.0-SNAPSHOT-303.jar:3.3.0-SNAPSHOT (git-a6d90105-b303)]
18 | at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[velocity-3.3.0-SNAPSHOT-303.jar:3.3.0-SNAPSHOT (git-a6d90105-b303)]
19 | at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity-3.3.0-SNAPSHOT-303.jar:3.3.0-SNAPSHOT (git-a6d90105-b303)]
20 | at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[velocity-3.3.0-SNAPSHOT-303.jar:3.3.0-SNAPSHOT (git-a6d90105-b303)]
21 | at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[velocity-3.3.0-SNAPSHOT-303.jar:3.3.0-SNAPSHOT (git-a6d90105-b303)]
22 | at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440) ~[velocity-3.3.0-SNAPSHOT-303.jar:3.3.0-SNAPSHOT (git-a6d90105-b303)]
23 | at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity-3.3.0-SNAPSHOT-303.jar:3.3.0-SNAPSHOT (git-a6d90105-b303)]
24 | at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[velocity-3.3.0-SNAPSHOT-303.jar:3.3.0-SNAPSHOT (git-a6d90105-b303)]
25 | at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800) ~[velocity-3.3.0-SNAPSHOT-303.jar:3.3.0-SNAPSHOT (git-a6d90105-b303)]
26 | at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:509) ~[velocity-3.3.0-SNAPSHOT-303.jar:3.3.0-SNAPSHOT (git-a6d90105-b303)]
27 | at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:407) ~[velocity-3.3.0-SNAPSHOT-303.jar:3.3.0-SNAPSHOT (git-a6d90105-b303)]
28 | at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[velocity-3.3.0-SNAPSHOT-303.jar:3.3.0-SNAPSHOT (git-a6d90105-b303)]
29 | at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[velocity-3.3.0-SNAPSHOT-303.jar:3.3.0-SNAPSHOT (git-a6d90105-b303)]
30 | at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[velocity-3.3.0-SNAPSHOT-303.jar:3.3.0-SNAPSHOT (git-a6d90105-b303)]
31 | at java.lang.Thread.run(Thread.java:840) [?:?]
32 | Caused by: com.viaversion.viaversion.exception.InformativeException: Please report this on the Via support Discord or open an issue on the relevant GitHub repository
33 | Source 0: com.viaversion.viaversion.protocols.base.BaseProtocol1_7$$Lambda$1881/0x00007f9015afd530
34 | Caused by: java.lang.IllegalArgumentException: UUID string too large
35 | at java.util.UUID.fromString1(UUID.java:264) ~[?:?]
36 | at java.util.UUID.fromString(UUID.java:258) ~[?:?]
37 | at com.viaversion.viaversion.protocols.base.BaseProtocol1_7.passthroughLoginUUID(BaseProtocol1_7.java:192) ~[?:?]
38 | at com.viaversion.viaversion.protocols.base.BaseProtocol1_7.lambda$registerPackets$0(BaseProtocol1_7.java:126) ~[?:?]
39 | at com.viaversion.viaversion.api.protocol.AbstractProtocol.transform(AbstractProtocol.java:392) ~[?:?]
40 | at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:423) ~[?:?]
41 | at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:407) ~[?:?]
42 | at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:46) ~[?:?]
43 | at com.viaversion.viaversion.protocol.ProtocolPipelineImpl.transform(ProtocolPipelineImpl.java:115) ~[?:?]
44 | at com.viaversion.viaversion.connection.UserConnectionImpl.transform(UserConnectionImpl.java:330) ~[?:?]
45 | at com.viaversion.viaversion.connection.UserConnectionImpl.transformClientbound(UserConnectionImpl.java:308) ~[?:?]
46 | at com.viaversion.viaversion.api.connection.UserConnection.transformIncoming(UserConnection.java:248) ~[?:?]
47 | at com.viaversion.viaversion.velocity.handlers.VelocityDecodeHandler.decode(VelocityDecodeHandler.java:48) ~[?:?]
48 | at com.viaversion.viaversion.velocity.handlers.VelocityDecodeHandler.decode(VelocityDecodeHandler.java:30) ~[?:?]
49 | at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:88) ~[velocity-3.3.0-SNAPSHOT-303.jar:3.3.0-SNAPSHOT (git-a6d90105-b303)]

</body>
</html>

### Bug Description

Latest Velocity
Joining with 1.20.4 client
1.20.1 backend
Cannot join.a

### Steps to Reproduce

Running latest Velocity
Joining with 1.20.4 client to
1.20.1 backend
Getting kicked.

### Expected Behavior

Running latest Velocity
Joining with 1.20.4 client to
1.20.1 backend
Getting kicked.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: velocity%203.3.0--SNAPSHOT%20%28git--a6d90105--b303%29](https://img.shields.io/badge/Platform-velocity%203.3.0--SNAPSHOT%20%28git--a6d90105--b303%29-3498db?style=flat-square) </br>![ViaVersion (4.9.2): 12 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.9.2)-12%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(4.9.1): 9 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.9.1)-9%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump</h3>

**Comment by HiMyNameIsBoxxy** [comment]
Tried the latest build. Still getting the same error.

**Comment by Kichura** [comment]
This is not the latest build of via* you are using unfortunately nor is your velocity proxy on latest build either, if updating does not work then something on the backend server is causing unexpected failures.

**Comment by Jo0001** [comment]
Works fine for me
![grafik](https://github.com/ViaVersion/ViaBackwards/assets/47455182/8399a590-0b10-429d-ae82-00ed51b4cbd2)
