### ISSUE TITLE
server keep crashed

### ISSUE THREAD

**Issue by Ecilpse** [ViaVersion/ViaBackwards#653]
### '/viaversion dump' Output

##secure

### Console Error

```
Put the paste.gg link or text here.
https://paste.gg/p/anonymous/03a6fcfab552424ba164c071e91794c7
```

### Bug Description

server keep crashed after this console messages.

### Steps to Reproduce

 can't reproduce the crash by myself, this is happening with about over 50 players running for more than 10 hours.

### Expected Behavior

I don't know the cause of the crash, but it seems to be an interaction problem with the entity.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--318%20%28MC%3A%201.20.2%29](https://img.shields.io/badge/Platform-git--Paper--318%20%28MC%3A%201.20.2%29-3498db?style=flat-square) </br>![ViaVersion (4.9.3-SNAPSHOT): 1 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.9.3--SNAPSHOT)-1%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(4.9.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.9.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br><br><h3>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump</h3>

**Comment by HowardZHY** [comment]
This seems likely caused by HuskSync, try to remove it

**Comment by Ecilpse** [comment]
> ![Platform: git--Paper--318%20%28MC%3A%201.20.2%29](https://camo.githubusercontent.com/c3a3d7e56cbf477b618a57cfefad757542e5bd394642928b1ce8c95eceb85363/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f506c6174666f726d2d6769742d2d50617065722d2d3331382532302532384d43253341253230312e32302e322532392d3334393864623f7374796c653d666c61742d737175617265) ![ViaVersion (4.9.3-SNAPSHOT): 1 commits behind master](https://camo.githubusercontent.com/4e2686883fb0223e45e1c4a96903d45860a5e2fea9aa68ef67a592f3265aaa83/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f56696156657273696f6e25323028342e392e332d2d534e415053484f54292d31253230636f6d6d6974287329253230626568696e642532306d61737465722d79656c6c6f773f7374796c653d666c61742d737175617265) ![ViaBackwards(4.9.2-SNAPSHOT): Even with master](https://camo.githubusercontent.com/e249728faae3678f22bfa399091007c8afe8c947632a0529fcc8bb718651a888/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f5669614261636b776172647325323028342e392e322d2d534e415053484f54292d4576656e253230776974682532306d61737465722d627269676874677265656e3f7374796c653d666c61742d737175617265)
> 
> ### Please try the **latest** build(s) from https://ci.viaversion.com/. In case the issue still persists send the new dump

https://dump.viaversion.com/d1e247b8367cdc9984acbdeb344580e65905e81dba0f0496941e02d95622925a
still same.

**Comment by Barvalg** [comment]
![Platform: git--Paper--318%20%28MC%3A%201.20.2%29](https://img.shields.io/badge/Platform-git--Paper--318%20%28MC%3A%201.20.2%29-3498db?style=flat-square) </br>![ViaVersion (4.9.3-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.9.3--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(4.9.2-SNAPSHOT): 1 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.9.2--SNAPSHOT)-1%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump</h3>

**Comment by Ecilpse** [comment]
> ![Platform: git--Paper--318%20%28MC%3A%201.20.2%29](https://camo.githubusercontent.com/c3a3d7e56cbf477b618a57cfefad757542e5bd394642928b1ce8c95eceb85363/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f506c6174666f726d2d6769742d2d50617065722d2d3331382532302532384d43253341253230312e32302e322532392d3334393864623f7374796c653d666c61742d737175617265) ![ViaVersion (4.9.3-SNAPSHOT): Even with master](https://camo.githubusercontent.com/12502a11c2d6968b04dd6cf8c39fe18e7bb6395979811e9ec691bff84e9c0f7e/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f56696156657273696f6e25323028342e392e332d2d534e415053484f54292d4576656e253230776974682532306d61737465722d627269676874677265656e3f7374796c653d666c61742d737175617265) ![ViaBackwards(4.9.2-SNAPSHOT): 1 commits behind master](https://camo.githubusercontent.com/e36b25f5e69dc1c8cfcc2e3d435fe695f2f614cf4e42de5ec92afcb205281bfa/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f5669614261636b776172647325323028342e392e322d2d534e415053484f54292d31253230636f6d6d6974287329253230626568696e642532306d61737465722d79656c6c6f773f7374796c653d666c61742d737175617265)
> 
> ### Please try the **latest** build(s) from https://ci.viaversion.com/. In case the issue still persists send the new dump

i already tested today with dev version

**Comment by Kichura** [comment]
Caused by third-party plugins that are sending packets that causes both server and viaversion to fail, Please perform a binary search to see which ones are it. *(known ones i can find; itemsadder, mythicmobs, modelengine, and probably others)*
