### ISSUE TITLE
1.13/1.13.1 clients cannot join velocity->paper 1.20.4

### ISSUE THREAD

**Issue by Kichura** [ViaVersion/ViaBackwards#663]
### '/viaversion dump' Output

https://dump.viaversion.com/e69757425c33e0584c6b39d69ae7350ddedae20293b6a8fa5037ab081ba1dc09

### Console Error

*(No console errors but client kick was found [here](https://i.imgur.com/HDf551Q.png))*

### Bug Description

When attempting to a velocity proxy that is paired with an Paper 1.20.4 server running via* plugins, the 1.13/1.13.1 clients instantly drop and cannot log in unless the client was on 1.13.2.

### Steps to Reproduce

1. Create a velocity proxy regardless of forwarding modes,
2. Create a Paper 1.20.4 server with the via* plugins on it,
3. Try to connect to server with an 1.13/1.13.1 client,
4. Get kicked out.

### Expected Behavior

1.13/1.13.1 clients can log in properly without issues.

### Additional Server Info

1. Yes - This setup is using Velocity, *(Build 316)*
2. Paper 1.20.4 as backend server,
3. ViaVersion *(4.9.3-SNAPSHOT)*, ViaBackwards *(4.9.2-SNAPSHOT)* and ViaRewind *(3.0.6-SNAPSHOT)*.

*EDIT: This not only affects velocity proxies but bungee itself as a whole.*

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--381%20%28MC%3A%201.20.4%29](https://img.shields.io/badge/Platform-git--Paper--381%20%28MC%3A%201.20.4%29-3498db?style=flat-square) </br>![ViaVersion (4.9.3-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.9.3--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaRewind(3.0.6-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaRewind%20(3.0.6--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(4.9.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.9.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by Jo0001** [comment]
Works fine now
