### ISSUE TITLE
Cant join 1.20.1 server(waterfall→paper) by any client

### ISSUE THREAD

**Issue by wksdjfhgfrejwksld** [ViaVersion/ViaBackwards#665]
### '/viaversion dump' Output

https://dump.viaversion.com/fcaa51c59ed691fa0349a446e862061c24a143895049b4051a2e5d2dccc50cdc

### Console Error

[22:03:14 INFO]: [/180.106.165.89:60336] <-> InitialHandler has pinged
[22:03:15 INFO]: [/180.106.165.89:60339] <-> InitialHandler has connected
[22:03:16 INFO]: [darkshabby|/180.106.165.89:60339] <-> ServerConnector [lobby] has connected
[22:03:16 INFO]: [darkshabby] disconnected with: Kicked whilst connecting to lobby: Outdated client! Please use 1.20.1
[22:03:16 INFO]: [/180.106.165.89:60339|darkshabby] -> UpstreamBridge has disconnected

### Bug Description

cant join 1.20.1 server with ViaBackwards by any client(tried 1.20.1 and 1.19.4)

### Steps to Reproduce

1.join the server with ViaBackwards(i was kicked because "Outdated client! Please use 1.20.1")
2.remove ViaBackwards(i can join now)
3.install lasted waterfall ViaBackwards viaversion but doesnt work

### Expected Behavior

join my server

### Additional Server Info

i use bungeecord

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git%3AWaterfall--Bootstrap%3A1.20--R0.2--SNAPSHOT%3A92b5149%3A562](https://img.shields.io/badge/Platform-git%3AWaterfall--Bootstrap%3A1.20--R0.2--SNAPSHOT%3A92b5149%3A562-3498db?style=flat-square) </br>![ViaVersion (4.9.3-SNAPSHOT): 3 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.9.3--SNAPSHOT)-3%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(4.9.1): 19 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.9.1)-19%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump and the issue will be reopened</h3>
