### ISSUE TITLE
Clients 1.19.2 cannot connect to server 1.20.4

### ISSUE THREAD

**Issue by lucasfrederico** [ViaVersion/ViaBackwards#667]
### '/viaversion dump' Output

https://dump.viaversion.com/e4839bdde8503ee5d734b90e5737236b03fa64985297b55a38481f429c9d4bbb

### Console Error

```
Put the paste.gg link or text here.
```

### Bug Description

Trying to enter version 1.19.2 on a 1.20.4 server, it says "Outdated client!" message.

### Steps to Reproduce

1. Login with 1.19.2
2. Join in 1.20.4 server

### Expected Behavior

Hopefully the player will be able to connect.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--SlimeWorldManager--25%20%28MC%3A%201.20.4%29](https://img.shields.io/badge/Platform-git--SlimeWorldManager--25%20%28MC%3A%201.20.4%29-3498db?style=flat-square) </br>![ViaVersion (4.9.3-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.9.3--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by Kichura** [comment]
Your viabackwards copy is not compatible with viaversion 4.9.3-snapshot, Please update viaversion to the dev build or downgrade viabackwards to 4.9.2-snapshot.

**Comment by lucasfrederico** [comment]
I updated and it still doesn't work.
https://dump.viaversion.com/9d17a2001877337bf71c77d38db6d1de39dd76f4a2f1bca27a5257244a278020

**Comment by Barvalg** [comment]
![Platform: git--SlimeWorldManager--25%20%28MC%3A%201.20.4%29](https://img.shields.io/badge/Platform-git--SlimeWorldManager--25%20%28MC%3A%201.20.4%29-3498db?style=flat-square) </br>![ViaVersion (4.10.0-24w03b-SNAPSHOT): Even with dev](https://img.shields.io/badge/ViaVersion%20(4.10.0--24w03b--SNAPSHOT)-Even%20with%20dev-brightgreen?style=flat-square) </br>![ViaBackwards(4.10.0-23w51b-SNAPSHOT): 13 commits behind dev](https://img.shields.io/badge/ViaBackwards%20(4.10.0--23w51b--SNAPSHOT)-13%20commit(s)%20behind%20dev-yellow?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump and the issue will be reopened</h3>

**Comment by lucasfrederico** [comment]
Okay, I updated the viabackwards, but...
![image](https://github.com/ViaVersion/ViaBackwards/assets/55282018/3ca29417-4ca2-4a25-9e0d-e8fde2e93e09)
I got this issue
https://dump.viaversion.com/9487f77e37d4a7e9dc583791bb9137c6fb9582099d64d465f282a8d3374986d4

**Comment by Barvalg** [comment]
![Platform: git--SlimeWorldManager--25%20%28MC%3A%201.20.4%29](https://img.shields.io/badge/Platform-git--SlimeWorldManager--25%20%28MC%3A%201.20.4%29-3498db?style=flat-square) </br>![ViaVersion (4.10.0-24w03b-SNAPSHOT): Even with dev](https://img.shields.io/badge/ViaVersion%20(4.10.0--24w03b--SNAPSHOT)-Even%20with%20dev-brightgreen?style=flat-square) </br>![ViaBackwards(4.10.0-24w03a-SNAPSHOT): Even with dev](https://img.shields.io/badge/ViaBackwards%20(4.10.0--24w03a--SNAPSHOT)-Even%20with%20dev-brightgreen?style=flat-square) </br>

**Comment by Kichura** [comment]
Caused by a third-party plugin sending bad player info packets to the server, please perform a binary search to see what's causing viabackwards to complain about it.
