### ISSUE TITLE
can't connect to 1.20.4

### ISSUE THREAD

**Issue by GetSlained** [ViaVersion/ViaBackwards#668]
### '/viaversion dump' Output

https://dump.viaversion.com/ce7b84c1d65a1976de3229d3434d7a1f20c07774c77017a9f28f66571eb13c31

### Bug Description

i've updated my server to 1.20.4 since geyser wont work otherwise. I cannot login to my server from earlier versions even tho i have viaversion installed. I know the latest version doesnt say it supports 1.20.4.

I've tried downloading latest snapshots but nothing seems to work. Is there something i can do?

### Steps to Reproduce

1. Login with a version below 1.20.4
2. Connection lost
 Internal Exception: io.netty.handler.codec.DecoderException: java.lang.IndexOutOfBoundsException: readerIndex(1) + lenght (8) exceeds writerIndex(5): PooledUnsafeDirectByteBuf(ridx:1, widx:5, cap: 5)

### Expected Behavior

Join the server with a version below 1.20.4

### Additional Server Info

i use bunjeecord with geyser, luckperms, votifier and my commands

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: 4021--Spigot--864e4ac--fb97348%20%28MC%3A%201.20.4%29](https://img.shields.io/badge/Platform-4021--Spigot--864e4ac--fb97348%20%28MC%3A%201.20.4%29-3498db?style=flat-square) </br>![ViaVersion (4.9.3-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.9.3--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(4.9.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.9.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by GetSlained** [comment]
i have fixed the problem only for the hub, i think my anticheat was causing some trouble and i fixed it by just updating it to the latest version.

**Comment by GetSlained** [comment]
fixed it myself
