### ISSUE TITLE
Itemswapper Incompatibility

### ISSUE THREAD

**Issue by Daniel99j2** [ViaVersion/ViaBackwards#669]
### '/viaversion dump' Output

Unable to obtain

### Console Error

```
[link](https://mclo.gs/h2OtYQN)
```

### Bug Description

Loading game with [itemswapper](https://modrinth.com/plugin/itemswapper) crashes on startup

### Steps to Reproduce

1. Load game with [itemswapper](https://modrinth.com/plugin/itemswapper) and viafabricbackwards
2. Crash

### Expected Behavior

[Itemswapper](https://modrinth.com/plugin/itemswapper should be compatible

### Additional Server Info

Fabric, viafabricplus, viafabricbackwards, [itemswapper](https://modrinth.com/plugin/itemswapper)

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Error: Invalid or missing dump](https://img.shields.io/badge/Error-Invalid/missing%20dump-red?style=flat-square) </br>

**Comment by Daniel99j2** [comment]
Oops it was something else
