### ISSUE TITLE
Add a fake bedrock/barrier layer at y=0 in 1.17-

### ISSUE THREAD

**Issue by explorer3039** [ViaVersion/ViaBackwards#670]
### Problem Description

Since minecraft 1.18 was updated, I noticed that if I use a <1.17 mc client to join the server, players will stuck at y=0 and can't get out.

### Solution Description

To avoid this, add a fake bedrock/barrier layer at y=0 in 1.17-

**Comment by FlorianMichael** [comment]
It's an idea to fix the issue, but this would case y=0 blocks to not be rendered for <1.17 clients even though they could. In addition to that players would get flagged by vanilla and other anticheat plugins for flying in case y=-1 or y=0 doesn't have blocks.

**Comment by bangetto** [comment]
what if instead of making possibility to legally fly, teleport back players to the block they jumped from and send them a message about the limitations?

**Comment by explorer3039** [comment]
maybe we can add this as an unsupported setting

**Comment by FlorianMichael** [comment]
@explorer3039 done
