### ISSUE TITLE
1.20.4 blockstate bug?

### ISSUE THREAD

**Issue by Potothingi** [ViaVersion/ViaBackwards#672]
### Problem Description

I get error messages. (1.20.4 Server, Latest Snapshots ViaVersion&ViaBackwards)
This error continued to occur after updating my server from 1.20.2 to 1.20.4.

ViaBackwards] Missing 1.20 blockstate for 1.20.2 blockstate 24751
ViaBackwards] Missing 1.20 blockstate for 1.20.2 blockstate 24755
ViaBackwards] Missing 1.20 blockstate for 1.20.2 blockstate 24759
ViaBackwards] Missing 1.20 blockstate for 1.20.2 blockstate 24763
ViaBackwards] Missing 1.20 blockstate for 1.20.2 blockstate 24767

### Solution Description

I would like to know if I can ignore this error message, and if not, I would like it to be fixed.

### Additional Info

I don't know how to reproduce. I found this out through logs.

**Comment by kennytv** [comment]
Wrong issue template
