### ISSUE TITLE
Cant join my 1.20.2 server with anything below 1.19.

### ISSUE THREAD

**Issue by buzznation** [ViaVersion/ViaBackwards#673]
### '/viaversion dump' Output

https://dump.viaversion.com/f1d2377d7471ea6d997e3d0262a65bed0044fd439807de62af95e918bdd2b25d

### Console Error

No error

### Bug Description

Since i have updated my purpur server from 1.20.1 to 1.20.2, it kind of stopped working for everyone who wants to join on an older version than 1.19.

Versions im using:
• ViaBackwards-4.9.2-SNAPSHOT.jar
• ViaVersion-4.9.3-SNAPSHOT.jar

### Steps to Reproduce

• Players on clients below 1.19, get stuck on loading screen.
• Game crashes after a while

### Expected Behavior

Player should be able to login without issues

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by Kichura** [comment]
ModelEngine *(for example)* is not supported, Although please perform a binary search to see what causes unexpected game crashes to happen.
