### ISSUE TITLE
Note Particles Lose their color

### ISSUE THREAD

**Issue by feliscatusmeows** [ViaVersion/ViaBackwards#679]
### '/viaversion dump' Output

https://dump.viaversion.com/e31a5f84bb3cba4d8df8b910547dd50aef24212a5f53730fa4160d4bfe6df094

### Console Error

[https://mclo.gs/KnTT169](https://mclo.gs/KnTT169)

### Bug Description

Note particles lose their color when connecting from 1.12.2 to 1.13.2. 

### Steps to Reproduce

![image](https://github.com/ViaVersion/ViaBackwards/assets/29553771/f23da124-0ea8-438d-9ce6-c9ec1b9b1aa0)
Step 1. Start a 1.13.2 Lan server
Step 2. Connect using 1.12.2 via viaproxy

Step 3. Place a noteblock
Step 4. right click the noteblock
Step 5. notice that all the colors for the note particle are the same

### Expected Behavior

The note particles should have been the correct color. 

### Additional Server Info

I used vanilla minecraft 1.13.2 for the lan server, vanilla minecraft 1.12.2 for the client, and viaproxy 3.1.1-SNAPSHOT

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: 2.2.13--SNAPSHOT](https://img.shields.io/badge/Platform-2.2.13--SNAPSHOT-3498db?style=flat-square) </br>![ViaVersion (4.10.0-24w05a-SNAPSHOT): 2 commits behind dev](https://img.shields.io/badge/ViaVersion%20(4.10.0--24w05a--SNAPSHOT)-2%20commit(s)%20behind%20dev-yellow?style=flat-square) </br>![ViaBackwards(4.10.0-24w05a-SNAPSHOT): 3 commits behind dev](https://img.shields.io/badge/ViaBackwards%20(4.10.0--24w05a--SNAPSHOT)-3%20commit(s)%20behind%20dev-yellow?style=flat-square) </br>![ViaRewind(3.0.6-SNAPSHOT): Even with dev](https://img.shields.io/badge/ViaRewind%20(3.0.6--SNAPSHOT)-Even%20with%20dev-brightgreen?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump and the issue will be reopened</h3>

**Comment by feliscatusmeows** [comment]
![image](https://github.com/ViaVersion/ViaBackwards/assets/29553771/6a09a420-5f41-4eb7-8ddf-ebe1676f38ff)
https://dump.viaversion.com/de9907b47c27f23b071c1e165b0ea954e8252c722c70f4eb8345840a89b5b27b
I hope I set it up correct.

**Comment by Barvalg** [comment]
![Platform: velocity%203.3.0--SNAPSHOT%20%28git--38558783--b345%29](https://img.shields.io/badge/Platform-velocity%203.3.0--SNAPSHOT%20%28git--38558783--b345%29-3498db?style=flat-square) </br>![ViaVersion (4.10.0-24w05a-SNAPSHOT): Even with dev](https://img.shields.io/badge/ViaVersion%20(4.10.0--24w05a--SNAPSHOT)-Even%20with%20dev-brightgreen?style=flat-square) </br>![ViaBackwards(4.10.0-24w05a-SNAPSHOT): Even with dev](https://img.shields.io/badge/ViaBackwards%20(4.10.0--24w05a--SNAPSHOT)-Even%20with%20dev-brightgreen?style=flat-square) </br>

**Comment by feliscatusmeows** [comment]
I'm not sure if this is helpful, but I found this:
https://www.reddit.com/r/Minecraft/comments/3mgfa5/image_tutorial_how_to_create_particles_of_a/
It said something about dx or xd?
