### ISSUE TITLE
Transaction packets are confirmed instantaneous on < 1.17

### ISSUE THREAD

**Issue by micartey** [ViaVersion/ViaBackwards#681]
### ViaVersion Dump

https://dump.viaversion.com/7e744e6ee57116e5fa5008cf20e894a39f50f56d556f7a90bf2db7df342d8250

### Bug Description

It seems like there is an issue with the “Transaction” Packets in lower versions.

When using server versions > 1.17 the `ServerPing` packet is used, but it appears that the packets are confirmed instantaneous for players <1.17 that use the `WindowConfirmation` packet. 

When joining with >= 1.17 the `ServerPing` packet is used, and it works as expected. 

The server is running on 1.20, so the issue actually appears to be due to the packet translation to versions lower than 1.17

### Steps to Reproduce

1. Setup a server (e.g. 1.20.4)
2. Add ViaVersion and ViaBackwards
3. Join with a version lower than 1.17 (e.g. 1.12)
4. Use a plugin that uses transaction packets to calculate the ping (Plugin should be for 1.17+)
5. The ping will be 0

### Expected Behavior

The transaction packets should not be confirmed instantaneous

### Additional Server Info

I used Paper and Spigot

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--408%20%28MC%3A%201.20.4%29](https://img.shields.io/badge/Platform-git--Paper--408%20%28MC%3A%201.20.4%29-3498db?style=flat-square) </br>![ViaVersion (4.10.0-24w05a-SNAPSHOT): 3 commits behind dev](https://img.shields.io/badge/ViaVersion%20(4.10.0--24w05a--SNAPSHOT)-3%20commit(s)%20behind%20dev-yellow?style=flat-square) </br>![ViaBackwards(4.10.0-24w05a-SNAPSHOT): 4 commits behind dev](https://img.shields.io/badge/ViaBackwards%20(4.10.0--24w05a--SNAPSHOT)-4%20commit(s)%20behind%20dev-yellow?style=flat-square) </br>![ViaRewind(3.0.6-SNAPSHOT): Even with dev](https://img.shields.io/badge/ViaRewind%20(3.0.6--SNAPSHOT)-Even%20with%20dev-brightgreen?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump and the issue will be reopened</h3>

**Comment by micartey** [comment]
https://dump.viaversion.com/9eb30e6be1967caa946eae1951e9b7d55c72cc0675540e27e9384eb563119e0e

**Comment by Barvalg** [comment]
![Platform: git--Paper--408%20%28MC%3A%201.20.4%29](https://img.shields.io/badge/Platform-git--Paper--408%20%28MC%3A%201.20.4%29-3498db?style=flat-square) </br>![ViaVersion (4.10.0-24w05b-SNAPSHOT): Even with dev](https://img.shields.io/badge/ViaVersion%20(4.10.0--24w05b--SNAPSHOT)-Even%20with%20dev-brightgreen?style=flat-square) </br>![ViaBackwards(4.10.0-24w05b-SNAPSHOT): Even with dev](https://img.shields.io/badge/ViaBackwards%20(4.10.0--24w05b--SNAPSHOT)-Even%20with%20dev-brightgreen?style=flat-square) </br>![ViaRewind(3.0.6-SNAPSHOT): Even with dev](https://img.shields.io/badge/ViaRewind%20(3.0.6--SNAPSHOT)-Even%20with%20dev-brightgreen?style=flat-square) </br>

**Comment by kennytv** [comment]
Enable `handle-pings-as-inv-acknowledgements` in the config or set the `com.viaversion.handlePingsAsInvAcknowledgements` system property
