### ISSUE TITLE
Friend cannot join on 1.9: Gets kicked

### ISSUE THREAD

**Issue by Marko2155** [ViaVersion/ViaBackwards#682]
### '/viaversion dump' Output

https://dump.viaversion.com/9ac86fe71e64e1a8011a7600f236c35cf02e01dc5985ef4b13e6a5a556cc4f5e

### Console Error

```
https://paste.gg/p/anonymous/3576a462ddd04b43a42a456ec72a12e6
```

### Bug Description

So my friend plays on 1.9, (cause he has a Mid-2011 MacBook Air and cannot run any newer games without them crashing or being really laggy) and I play on 1.20.4 so I decided to set up a Paper server with ViaVersion and ViaBackwards to play with him. Fast forward hours after I setup the server. It's been going really well, until now. Now, when he joins, he spawns in the void and after a few seconds, gets kicked out with the error message above.

### Steps to Reproduce

1: Download ViaVersion + ViaBackwards 4.9.1
2: Login with a 1.9 client (any)

### Expected Behavior

Should be able to join and play just fine

### Additional Server Info

Also, I tried to use a build of ViaVersion from https://ci.viaversion.com and it made older versions not able to join at all.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--409%20%28MC%3A%201.20.4%29](https://img.shields.io/badge/Platform-git--Paper--409%20%28MC%3A%201.20.4%29-3498db?style=flat-square) </br>![ViaVersion (4.9.2): 46 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.9.2)-46%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaRewind(3.0.6-SNAPSHOT): Even with dev](https://img.shields.io/badge/ViaRewind%20(3.0.6--SNAPSHOT)-Even%20with%20dev-brightgreen?style=flat-square) </br>![ViaBackwards(4.9.1): 28 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.9.1)-28%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump and the issue will be reopened</h3>

**Comment by Marko2155** [comment]
https://dump.viaversion.com/cdf856cb646f49c78e50e8dc2557e60fa89b6a0861fd7928d25c468142fe6c6e

**Comment by Barvalg** [comment]
![Platform: git--Paper--409%20%28MC%3A%201.20.4%29](https://img.shields.io/badge/Platform-git--Paper--409%20%28MC%3A%201.20.4%29-3498db?style=flat-square) </br>![ViaVersion (4.9.3-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.9.3--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(4.9.1): 28 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.9.1)-28%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump and the issue will be reopened</h3>

**Comment by Marko2155** [comment]
https://dump.viaversion.com/9ed275fc85ed6d72306a2dcc68e1a9d5f0ac8b41f2e40daac9378dddce059dd0

**Comment by Barvalg** [comment]
![Platform: git--Paper--409%20%28MC%3A%201.20.4%29](https://img.shields.io/badge/Platform-git--Paper--409%20%28MC%3A%201.20.4%29-3498db?style=flat-square) </br>![ViaVersion (4.9.3-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.9.3--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(4.9.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.9.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by Marko2155** [comment]
No, I did test the updated version and it still didn't work

**Comment by kennytv** [comment]
Then send the new stacktrace. Also note that y<0 and y>255 are not supported for old players, as noted in the console

**Comment by Marko2155** [comment]
https://dump.viaversion.com/18d4380661ac840cdae27b115cf947dde9c09ce237381dd462adae930423a5f5

**Comment by Barvalg** [comment]
![Platform: git--Paper--409%20%28MC%3A%201.20.4%29](https://img.shields.io/badge/Platform-git--Paper--409%20%28MC%3A%201.20.4%29-3498db?style=flat-square) </br>![ViaVersion (4.9.3-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.9.3--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(4.9.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.9.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by Marko2155** [comment]
+ Even after clearing all configs, it still doesn't work. Well, now I can fly, but it doesn't load anything in the world.

**Comment by kennytv** [comment]
I'd suggest joining our Discord for help, that can be better diagnosed there, but presumably it's down to something else in the setup

**Comment by Marko2155** [comment]
Ok, will do
