### ISSUE TITLE
Maps are corrupted (or not loading at all) on ViaFabric 1.16.5->1.17

### ISSUE THREAD

**Issue by skidunion** [ViaVersion/ViaBackwards#687]
### '/viaversion dump' Output

https://dump.viaversion.com/4bd9d79376b3b299e4d1286554606e6c00cbb25c8d2ec0fe983ea6e13a3bf1a0

### Console Error

```
>> [19:13:55] [main/INFO]: Connecting to mc.funtime.su, 25565
>> [19:13:55] [Netty Client IO #14/INFO]: Auto-detected 1.16.4/5 (754) for mc.funtime.su/89.33.12.3:25565
>> [19:13:56] [main/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
>> [19:13:56] [main/FATAL]: Error executing task on Client
>> java.lang.NullPointerException: null
>> [19:13:56] [main/FATAL]: Error executing task on Client
>> java.lang.NullPointerException: null
>> [19:13:56] [main/FATAL]: Error executing task on Client
>> java.lang.NullPointerException: null
>> [19:13:56] [main/FATAL]: Error executing task on Client
>> java.lang.NullPointerException: null
>> [19:13:56] [main/FATAL]: Error executing task on Client
>> java.lang.NullPointerException: null
>> [19:13:56] [main/FATAL]: Error executing task on Client
>> java.lang.NullPointerException: null
>> [19:13:56] [main/INFO]: [CHAT] BotFilter >> Введите номер с картинки в чат
```

### Bug Description

Map images are not loading correctly on a 1.16.5 client with 1.17 protocol.

### Steps to Reproduce

1. Enable client-side in ViaFabric and select version 1.17
2. Login to `mc.funtime.su` (cracked)
3. The CAPTCHA image (maps in item frames) in front of the player won't be loaded correctly

### Expected Behavior

The images should be loaded correctly as in 1.16.5.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by kennytv** [comment]
https://github.com/ViaVersion/ViaBackwards/commit/a0d063d93eeef2c4ebab394cedffe180aa1760fd
