### ISSUE TITLE
Problem with connection 1.9.4 on server Minecraft Paper 1.20.4

### ISSUE THREAD

**Issue by Adrian5063** [ViaVersion/ViaBackwards#692]
### '/viaversion dump' Output

https://dump.viaversion.com/17dbc81d2acf02e348efd76731bff87d23a90be51934180fd2b1dcde9be7eb6e

### Console Error

[12:38:34] [User Authenticator #1/INFO]: UUID of player sk89q is be75b756-f30f-3f49-87b0-01f7bcb29709
[12:38:35] [Netty Epoll Server IO #3/WARN]: [ViaBackwards] Custom worlds heights are NOT SUPPORTED for 1.16 players and older and may lead to errors!
[12:38:35] [Netty Epoll Server IO #3/WARN]: [ViaBackwards] You have min/max set to -64/256
[12:38:35] [Server thread/INFO]: sk89q[/46.205.204.228:6293] logged in with entity id 462 at ([PvP]2600.5, 30.0, 2600.5)
[12:38:36] [Server thread/INFO]: sk89q lost connection: Disconnected

### Bug Description

When try to join on Minecraft version 1.9.4 to server on software Paper 1.20.4 error caused connection problem
No any errors in the server console/logs, only error in the client Minecraft 1.9.4
When i'm try with version something like 1.17.1 this work correct, but with 1.9.4 cannot join to the server
![error](https://github.com/ViaVersion/ViaBackwards/assets/161377580/b10ebca5-e5d1-41ad-8933-2d1fb9552360)

### Steps to Reproduce

1. Launch Minecraft version 1.9.4
2. Try connect to server Paper 1.20.4 with installed ViaVersion and ViaBackwards (IP: playnopay.pl)
3. You cannot join when error appear and nothing about this in console/logs

### Expected Behavior

I'm try to working join with the Minecraft 1.9.4 to server Paper 1.20.4

### Additional Server Info

Paper 1.20.4 build 435

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--435%20%28MC%3A%201.20.4%29](https://img.shields.io/badge/Platform-git--Paper--435%20%28MC%3A%201.20.4%29-3498db?style=flat-square) </br>![ViaVersion (4.9.2): 51 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.9.2)-51%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(4.9.1): 32 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.9.1)-32%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump and the issue will be reopened</h3>
