### ISSUE TITLE
Update Needed for 1.20.4

### ISSUE THREAD

**Issue by GlitchUser001** [ViaVersion/ViaBackwards#696]
### Problem Description

I have made a server but It _can't Allow older version player_ because the **via backwards** works till **1.20** and my server is **1.20.4** also We need other mods to run the server. hence, please Reply

### Solution Description

Please Make an _Update_ For **1.20.4**

### Alternatives

there is _no other suggestion_ because All the Players Need an **Update**

**Comment by Kichura** [comment]
Either you did not update viaversion and viabackwards properly to latest CI builds or a mod is breaking our plugins, therefore this is not a feature request.
