### ISSUE TITLE
ERROR IN BaseProtocol1_16 IN REMAP OF LOGIN 0x02->0x02

### ISSUE THREAD

**Issue by MrPibbly** [ViaVersion/ViaBackwards#697]
### '/viaversion dump' Output

https://dump.viaversion.com/406a5484a5eb754926fb816b3254f702a0932bdaa6696ae4b7cf798036c9bd19

### Console Error

(https://mclo.gs/UzdfOpi)

### Bug Description

Any client 1.20.1 or below cannot connect to the proxy and get an Internal Error. Randomly players will also get disconnected with the same error.

### Steps to Reproduce

Login to 1.20.1 and it will kick you with an Internal Error.

### Expected Behavior

Should allow all clients to join

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: velocity%203.3.0--SNAPSHOT%20%28git--af09677f--b365%29](https://img.shields.io/badge/Platform-velocity%203.3.0--SNAPSHOT%20%28git--af09677f--b365%29-3498db?style=flat-square) </br>![Proxy is 2 builds behind](https://img.shields.io/badge/Your%20proxy%20is%202%20build(s)%20behind.%20Please%20update%20to%20the%20latest%20version-orange?style=flat-square) </br>![ViaVersion (4.9.3-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.9.3--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(4.9.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.9.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br><br><details><summary></summary>proxy_limbo</details>

**Comment by HowardZHY** [comment]
Does it happen with proxy and Via* updated?

**Comment by Kichura** [comment]
Ignore my previous comment as it was wrong but; Limbo is not supported, Please move via* to spigot/paper servers or remove limbo.
