### ISSUE TITLE
Ressouce pack isn't load with ViaBackwards with 1.20.2 server and 1.20.1 client.

### ISSUE THREAD

**Issue by HydrolienF** [ViaVersion/ViaBackwards#698]
### '/viaversion dump' Output

https://dump.viaversion.com/1d3e5ee3b689521caee2603601addeb3cc8c1130068ba0be333080195d38aeb8

### Console Error

No error in console

### Bug Description

Ressouce pack isn't load with ViaBackwards with 1.20.2 server and 1.20.1 or 1.20 client. (might affect lower version to)
It's working with 1.20.2 and 1.20.4.
I'm using last velocity version (3.3.0-SNAPSHOT-370) and last ViaVersion version (4.9.3) and last ViaBackwards version (4.9.2).
I have tried with last ViaBackwards  build (#390 (2024-mar-09 12:10:09)) without success.

### Steps to Reproduce

Login to mc.mvndicraft.net in 1.20.1
Login to the same server in 1.20.2
See the difference.

Or configure a 1.20.2 paper server and a velocity proxy.
Install forceresourcepacks and configure a resources pack.
Login in 1.20.1
Login in 1.20.2
See the difference.

### Expected Behavior

Ressource pack should be download with 1.20 and 1.20.1

### Additional Server Info

Server ressource pack is send to the user with forceresourcepacks plugin.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: velocity%203.3.0--SNAPSHOT%20%28git--8891faa5--b370%29](https://img.shields.io/badge/Platform-velocity%203.3.0--SNAPSHOT%20%28git--8891faa5--b370%29-3498db?style=flat-square) </br>![ViaVersion (4.9.3): 5 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.9.3)-5%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(4.9.2): 2 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.9.2)-2%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump and the issue will be reopened</h3>

**Comment by HydrolienF** [comment]
I have tried with the 2 last version without success.
https://dump.viaversion.com/1935e2d5da4bea7d053fbbaaea475e822bd30af1d721a04b2be08db5a22dc937

**Comment by Barvalg** [comment]
![Platform: velocity%203.3.0--SNAPSHOT%20%28git--8891faa5--b370%29](https://img.shields.io/badge/Platform-velocity%203.3.0--SNAPSHOT%20%28git--8891faa5--b370%29-3498db?style=flat-square) </br>![ViaVersion (4.9.4-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.9.4--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(4.9.3-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.9.3--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by Jo0001** [comment]
I can't reproduce the issue using a 1.20.2 pack. Make sure your packs is valid and has a correct pack format see https://minecraft.wiki/w/Pack_format

**Comment by HydrolienF** [comment]
It is a valid resource pack, it work in solo or in 1.20.2 on the server. Cf https://github.com/HydrolienF/MvndiPack/releases/latest/download/MvndiCraftResourcePack.zip
I think it might be because I'm using Velocity and Forceresourcepacks to provide a resource pack to the user, and one of them isn't compatible with ViaBackwards.
Or because resource pack is compressed. Some unziper can't read it, but Minecraft can.

**Comment by Jo0001** [comment]
I also used Velocity, either your pack is incompatible or the Forceresourcepacks plugin (which is not really needed as vanilla has the option to require-resource-pack=true)

**Comment by HydrolienF** [comment]
I will try to force resource pack with velocity without Forceresourcepacks plugin. Thanks.
