### ISSUE TITLE
Older version can't join the server when disconnecting with combat plugins

### ISSUE THREAD

**Issue by msmanui** [ViaVersion/ViaBackwards#708]
### '/viaversion dump' Output

https://dump.viaversion.com/2cef209376d18ff28419c644f6e6ef249ac41b6b1c1499e954af5a9a3f317a66

### Console Error

	Line  711: [21:39:12] [Server thread/INFO]: Take085 lost connection: Disconnected
	Line  712: [21:39:12] [Server thread/INFO]: [PvPManager] Take085 tried to escape combat and died!
	Line  713: [21:39:12] [Server thread/INFO]: Combat Take085 died
	Line  722: [21:39:19] [User Authenticator #1/INFO]: UUID of player Take085 is 94d3567e-b2ff-3069-9906-71b370a3cb7c
	Line  724: [21:39:19] [Server thread/INFO]: Take085[/ip:57890] logged in with entity id 1140 at ([pracsandboxffa]31.943478185090406, 39.56722100089407, -45.07503365495197)

### Bug Description

Using paper 1.20.4
You must be using version 1.18.2 of Minecraft. What you need to do is engage in combat with either the DeluxCombat or PvPManager plugin. Then, while in combat, disconnect. This will cause your inventory to drop and also kill you. When you try to log back in, you'll encounter the loading screen and won't be able to enter.

I personally tried to reproduce it and couldn't. However, what I notice is that if you disconnect during combat, when you log back in, you'll see the respawn screen.

To fix it, the only way is to log in with version 1.20.4, and you'll respawn without any issues. I must reiterate, I tried to test this myself and couldn't replicate it, but it happens to other users.

### Steps to Reproduce

1. Enter in combat with 1.18.2 client (With either plugin deluxecombat or pvp manager)
2.  Disconnect while being tag
3. If you try to rejoin it will appear loading screen
Note: This does not happen to everyone, i tested myself i couldnt reproduce

### Expected Behavior

Enter the server normally

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--450%20%28MC%3A%201.20.4%29](https://img.shields.io/badge/Platform-git--Paper--450%20%28MC%3A%201.20.4%29-3498db?style=flat-square) </br>![ViaVersion (4.9.4-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.9.4--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaRewind(3.0.7-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaRewind%20(3.0.7--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(4.9.3-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.9.3--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by kennytv** [comment]
Most likely due to Paper and Sodium having conflicts in expected behavior, try telling players to remove client mods
