### ISSUE TITLE
Players get kicked when running /back after going to a different world

### ISSUE THREAD

**Issue by SkyLyfe** [ViaVersion/ViaBackwards#711]
### '/viaversion dump' Output

https://dump.viaversion.com/03ee46312d7b1f865c142381f3fdf42517c2924b6addb0804cc1b2452621ef5e

### Console Error

https://mclo.gs/OeYJBxn

### Bug Description

Players get kicked when running /back after going to a different world

### Steps to Reproduce

1. Travel to the nether
2. (I use CMI) Do /back (teleports you to previous location)
3. You get kicked instead

### Expected Behavior

Shouldn't kick you

### Additional Server Info

I use velocity, but viaversion is on all the backend paper servers only

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--431%20%28MC%3A%201.20.4%29](https://img.shields.io/badge/Platform-git--Paper--431%20%28MC%3A%201.20.4%29-3498db?style=flat-square) </br>![ViaVersion (4.10.0-24w07a-SNAPSHOT): 38 commits behind dev](https://img.shields.io/badge/ViaVersion%20(4.10.0--24w07a--SNAPSHOT)-38%20commit(s)%20behind%20dev-yellow?style=flat-square) </br>![ViaBackwards(4.10.0-24w07a-SNAPSHOT): 29 commits behind dev](https://img.shields.io/badge/ViaBackwards%20(4.10.0--24w07a--SNAPSHOT)-29%20commit(s)%20behind%20dev-yellow?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump and the issue will be reopened</h3>
