### ISSUE TITLE
Server kicks if you enter nether portals some times in a row

### ISSUE THREAD

**Issue by Skrayti** [ViaVersion/ViaBackwards#712]
### '/viaversion dump' Output

https://dump.viaversion.com/9ad78d061b0dc17edd48989cf7632102f6fdb48327e1de1e6a476d84a4a68ab6

### Console Error

```
Put the mclo.gs link or text here.
```
https://mclo.gs/UWhJH1T

### Bug Description

Receiving diconnection or java error on my screen while entering nether portal some times

### Steps to Reproduce

1. Login with 1.20.1 client
2. Enter portals 2-4 times.

### Expected Behavior

You shouldn't be kicked. 

### Additional Server Info

List of plugins: AdminMode, AuthMe, Chatty, Chunky, ChunkyBorder, ClearLag, CoreProtect, CoreProtectTNT, DebugStickCraftingInSurvival, DiscordSRV, EasyWhitelist, emotecraft, EnchantsSquared, GSit, LetMeDespawn, LiteBans, LuckPerms, MiniMOTD, OpenInv, PL-Hide, PlasmoVoice, ProtocolLib, RealisticSeasons, Simple-Drugs, SkinsRestorer, spark, SuperVanish, TAB, Terra, Vault, VaultChatFormatter, ViaBackwards, ViaVersion
Server is running on Purpur 1.20.2

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Purpur--2095%20%28MC%3A%201.20.2%29](https://img.shields.io/badge/Platform-git--Purpur--2095%20%28MC%3A%201.20.2%29-3498db?style=flat-square) </br>![ViaVersion (4.9.4-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.9.4--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(4.9.3-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.9.3--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by FlorianMichael** [comment]
Try to perform a binary search on your plugins list:
1. Remove half of the existing plugins and put them aside for now,
2. Run the server again,
3. Is it still creating errors from there?

(If yes; Repeat from step 1 with current items)
(If not; Swap out the current plugins with the ones set aside and repeat from step 1)

4. Repeat process until problematic plugin/s are found.

**Comment by Skrayti** [comment]
Tried to do the same with 1.20.2 client and it's working properly
