### ISSUE TITLE
Getting Internal Exception: io.netty.handler.codec.EncoderException

### ISSUE THREAD

**Issue by LennartSBR** [ViaVersion/ViaBackwards#729]
### '/viaversion dump' Output

https://dump.viaversion.com/b635345d8ca547e833c9ef89c5322b72a4cf4853970ed07a7dad389177858bda

### Console Error

https://mclo.gs/ii6sUtI
Internal Exception: io.netty.handler.codec.EncoderException: com.viaversion.viaversion.exception.InformativeException: Please report this on the Via support Discord or open an issue on the relevant GitHub repository
Source 0: com.viaversion.viaversion.rewriter.ItemRewriter$2 (Anonymous)

### Bug Description

When joining with MC (Badlion in my Case idk) 1.20.4 on a Spigot 1.20.5 Server some Players get following Error (picture). We have 2 Players on the Server where IT doesn't Work they both have Numbers in their Name. Our other members do Not have Numbers in their Name and can Join. There is No Problem when joining with 1.20.5
![IMG-20240427-WA0017](https://github.com/ViaVersion/ViaBackwards/assets/82516983/8094f2d4-74e1-41f6-8184-bc6aa846f440)
![IMG-20240427-WA0017](https://github.com/ViaVersion/ViaBackwards/assets/82516983/79be66f1-daa4-4ef5-9ae7-b207d03515ef)

Also If joining in another Version, If you Type you get kicked with "Chat validation Error".

### Steps to Reproduce

Login in into the Server with 1.20.5 to get kicked 

### Expected Behavior

Don't get kicked when you Join or Type a message

### Additional Server Info

I use spigot 1.20.5 on an Aternos Server, and IT happend after we Upgraded to 1.20.5, i already tried reinstalling etc. We don't use a proxy

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: 4129--Spigot--b698b49--7ddb482%20%28MC%3A%201.20.5%29](https://img.shields.io/badge/Platform-4129--Spigot--b698b49--7ddb482%20%28MC%3A%201.20.5%29-3498db?style=flat-square) </br>![ViaVersion (4.10.1-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.10.1--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(4.10.0): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.10.0)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by LennartSBR** [comment]
btw sorry for my english, im speaking an another languege and and my Auto correct sucks

**Comment by andy01745** [comment]
I am getting the same problem 
![image](https://github.com/ViaVersion/ViaBackwards/assets/84942293/78fad1dc-36ea-449b-9fab-abe19ce6e24a)

**Comment by Kichura** [comment]
Can you test this with just via* plugins active to see if problems continue to happen + And also paper 1.20.4 as second server for testing?

**Comment by LukeyWookey** [comment]
I am getting a similar issue on a 1.21 server with viabackwards, when any player with trimed armor (any trims, not just 1.21 trims), I get kicked with a similar error. I play in 1.20.2

**Comment by kennytv** [comment]
The original issue shouldn't happen on the latest release, everything below that would be different issues
