### ISSUE TITLE
LecternInteractListener appears to register on 1.8.x servers

### ISSUE THREAD

**Issue by calcastor** [ViaVersion/ViaBackwards#730]
### '/viaversion dump' Output

https://dump.viaversion.com/addd3aafdd77b55abda66f7d4ba52cbce2ffde882e20612c91466b1043efa7ed

### Console Error

https://mclo.gs/3ZeONyi

### Bug Description

LecternInteractListener appears to register on 1.8.x servers

### Steps to Reproduce

1. Launch a 1.8.x Paper based server with latest ViaVersion, ViaBackwards, ViaRewind
2. Log on with 1.20.4 or potentially other client versions
3. Open a container, like a chest or otherwise and observe error in console

### Expected Behavior

LecternInteractListener should not be registered on a 1.8.x server.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--SportPaper--c03663e--P.2081566--SP.aff24bb--CB.e1ebe52%20%28MC%3A%201.8.8%29](https://img.shields.io/badge/Platform-git--SportPaper--c03663e--P.2081566--SP.aff24bb--CB.e1ebe52%20%28MC%3A%201.8.8%29-3498db?style=flat-square) </br>![ViaVersion (4.10.1-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.10.1--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(4.10.1-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.10.1--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaRewind(3.1.1-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaRewind%20(3.1.1--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>
