### ISSUE TITLE
1.16 error with texturepack

### ISSUE THREAD

**Issue by SliderKP** [ViaVersion/ViaBackwards#736]
### '/viaversion dump' Output

https://dump.viaversion.com/1c7301c91d8732b3d3593e3f5fa985f7e9b6ba9125d6245289fca9b22d7637c7

### Console Error

no errors

### Bug Description

when i try to join with 1.16.x version users cant join with this screen:
![image](https://github.com/ViaVersion/ViaBackwards/assets/6493041/d4f7d9d1-306e-449a-904b-f765cee347ba)

### Steps to Reproduce

join with 1.16 version to a server with itemsadder texturepack

### Expected Behavior

join to the server

### Additional Server Info

velocity and pufferfish, itemsadder.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Pufferfish--49%20%28MC%3A%201.20.4%29](https://img.shields.io/badge/Platform-git--Pufferfish--49%20%28MC%3A%201.20.4%29-3498db?style=flat-square) </br>![ViaVersion (4.10.1-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.10.1--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(4.10.1-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.10.1--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by kennytv** [comment]
You need to server resource packs per version depending on major changes some of them have
