### ISSUE TITLE
Skull textures not loading on older 1.20 versions (1.20.6)

### ISSUE THREAD

**Issue by Teelair** [ViaVersion/ViaBackwards#741]
### '/viaversion dump' Output

https://dump.viaversion.com/77d480d3d6f38bfdc61cb02123a7134ea113923c8a2b3669f100f001d69ac514

### Bug Description

1.20.6 placed player skulls are shown as Steve skins on previous 1.20 versions. 

There are also a few more weird test cases:
- If a 1.20.2 player receives the skull from a command block, then places it, the 1.20.2 player can see the skull until they relog. The 1.20.6 player cannot see it.
- If a 1.20.6 player receives the skull from a command block, then places it, the 1.20.2 player can't ever see it.
- If a 1.20.6 player receives the skull from a command block, tosses it to the 1.20.2 player, and then that player places it, both accounts can see the proper skin when placed in the world, but after a relog, 1.20.2 can't see it anymore.

The 1.20.2 player can never see it in their inventory, only when in world under these specific conditions.

### Steps to Reproduce

1) Using a 1.20.6 paper jar, log in with a 1.20.6 instance and 1.20.2 instance.
2) Put this command into a command block: 
```
/give @p player_head[profile={name:"Notch",id:[I;110787060,1156138790,-1514210135,238594805],properties:[{name:"textures",value:"ewogICJ0aW1lc3RhbXAiIDogMTcxNTI2NTg0OTQxMywKICAicHJvZmlsZUlkIiA6ICIwNjlhNzlmNDQ0ZTk0NzI2YTViZWZjYTkwZTM4YWFmNSIsCiAgInByb2ZpbGVOYW1lIiA6ICJOb3RjaCIsCiAgInRleHR1cmVzIiA6IHsKICAgICJTS0lOIiA6IHsKICAgICAgInVybCIgOiAiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS8yOTIwMDlhNDkyNWI1OGYwMmM3N2RhZGMzZWNlZjA3ZWE0Yzc0NzJmNjRlMGZkYzMyY2U1NTIyNDg5MzYyNjgwIgogICAgfQogIH0KfQ=="}]}] 1
```
3) Make both accounts obtain the skull by each using the command block
4) Place the skull from each version. Notice that 1.20.2 can only see the 1.20.2 placed skull, and 1.20.6 can see both.
Optionally, you can relog here to see further weird behavior, but I think you get the point =)

### Expected Behavior

Skulls placed on any 1.20 version should be visible from any other 1.20 version.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--53%20%28MC%3A%201.20.6%29](https://img.shields.io/badge/Platform-git--Paper--53%20%28MC%3A%201.20.6%29-3498db?style=flat-square) </br>![ViaVersion (4.10.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.10.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(4.10.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.10.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by Teelair** [comment]
@kennytv Thanks for the quick work! It works great for vanilla heads, but unfortunately when I try to import a head from somewhere like minecraft-heads.com with the give command, the same issue arises.

Here's the command I'm using:
```
/give @p minecraft:player_head[minecraft:custom_name='{"text":"Present (red, opened)","color":"gold","underlined":true,"bold":true,"italic":false}',minecraft:lore=['{"text":"Custom Head ID: 4313","color":"gray","italic":false}','{"text":"www.minecraft-heads.com","color":"blue","italic":false}'],profile={id:[I;-203203141,-1723839055,-1934448592,1834573286],properties:[{name:"textures",value:"eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMmVhODdhNjY0MWIyMWRiYjMxYjA0YWQ1ZmVhZDVlM2UwMzNiYjkxZmJlODMyYjdjNzEyYTg4NjE4OTQ0In19fQ=="}]}] 1
```

Source is https://minecraft-heads.com/custom-heads/head/4313-present-red-opened

Happy to open a new issue if that's preferred.

**Comment by kennytv** [comment]
Should be all fixed now
