### ISSUE TITLE
Unable to use "Pick Block"

### ISSUE THREAD

**Issue by Velosofy** [ViaVersion/ViaBackwards#752]
### `/viaversion dump` Output

Can't provide

### Bug Description

"Pick Block" is not working in <=1.20.4 clients.
This work just fine if I login with 1.20.5/6 clients.

I'm not really sure what cause this, or even how to troubleshoot.

I also unable to provide `/viaversion dump` output since it doesn't actually work (nothing happen, even after several minutes)

Video of me clicking the "Pick Block" keybind:
https://github.com/ViaVersion/ViaFabric/assets/61261357/1cf5bc59-ad14-4693-b03c-244cd0c147a1

### Steps to Reproduce

1. Setup Fabric 1.20.6 server with Via* installed
2. Login with 1.20.4 client
3. Try "Pick Block"

### Expected Behavior

"Pick Block" should work as expected

### Additional Server Info

Client Info:
Vanilla 1.20.4 with 0 mods

Server Info:
Fabric 1.20.6 (Loader 0.15.11 - Installer 1.0.1) with 4 mods

Server Mods:
- fabric-api-0.97.8+1.20.6.jar
- ViaFabric-0.4.14+576-dev.jar
- ViaBackwards-5.0.0-SNAPSHOT.jar
- ViaVersion-5.0.0-SNAPSHOT.jar

### Checklist

- [ ] I have checked if this is specific to ViaFabric platform, and doesn't happen when running it on other platforms (Paper/Sponge/Velocity/Waterfall).
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Error: Invalid or missing dump](https://img.shields.io/badge/Error-Invalid/missing%20dump-red?style=flat-square) </br>

**Comment by Barvalg** [comment]
![Platform: 1.20.6--81--5a9afbe%20%28MC%3A%201.20.6%29](https://img.shields.io/badge/Platform-1.20.6--81--5a9afbe%20%28MC%3A%201.20.6%29-3498db?style=flat-square) </br>![ViaVersion (5.0.0-SNAPSHOT): Even with dev](https://img.shields.io/badge/ViaVersion%20(5.0.0--SNAPSHOT)-Even%20with%20dev-brightgreen?style=flat-square) </br>![ViaBackwards(5.0.0-SNAPSHOT): Even with dev](https://img.shields.io/badge/ViaBackwards%20(5.0.0--SNAPSHOT)-Even%20with%20dev-brightgreen?style=flat-square) </br>
