### ISSUE TITLE
Horse/Llama can't equip armor/carpet

### ISSUE THREAD

**Issue by Velosofy** [ViaVersion/ViaBackwards#754]
### '/viaversion dump' Output

Unable to generate, doesn't output anything

### Bug Description

Horse can't equip armor, doing so will result in game crash
Same goes with Llama, trying to equip carpet into it will also result in game crash.
The item goes back to your inventory.

[latest.log](https://mclo.gs/8lVuw0k)
[crash-reports.txt](https://mclo.gs/8lVuw0k)

[Video Demonstration](https://youtu.be/1ORt5S0rOh0)

I'm assuming due to 1.20.5 [change log](https://minecraft.wiki/w/Java_Edition_1.20.5#:~:text=rolled%20up%20state.-,Horse,Replaced%20%C2%A0DecorItem%20with%20%C2%A0body_armor_item.,-Shulkers)
![image](https://github.com/ViaVersion/ViaBackwards/assets/61261357/dfeb79c1-6bf4-4532-8f34-8646ee25f7d1)

### Steps to Reproduce

1. Setup Fabric 1.20.6 server with Via* installed
2. Login with 1.20.4 client
3. Equip horse armor or carpet onto llama

### Expected Behavior

Game should not crash, and apply the item into the entity.

### Additional Server Info

Client Info:
Vanilla 1.20.4

Server Info:
Fabric 1.20.6 (Loader 0.15.11 - Installer 1.0.1) with 4 mods

Server Mods:

fabric-api-0.97.8+1.20.6.jar
ViaFabric-0.4.14+576-dev.jar
ViaBackwards-5.0.0-SNAPSHOT.jar
ViaVersion-5.0.0-SNAPSHOT.jar

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Error: Invalid or missing dump](https://img.shields.io/badge/Error-Invalid/missing%20dump-red?style=flat-square) </br>

**Comment by Barvalg** [comment]
![Platform: 1.20.6--81--5a9afbe%20%28MC%3A%201.20.6%29](https://img.shields.io/badge/Platform-1.20.6--81--5a9afbe%20%28MC%3A%201.20.6%29-3498db?style=flat-square) </br>![ViaVersion (5.0.0-SNAPSHOT): Even with dev](https://img.shields.io/badge/ViaVersion%20(5.0.0--SNAPSHOT)-Even%20with%20dev-brightgreen?style=flat-square) </br>![ViaBackwards(5.0.0-SNAPSHOT): Even with dev](https://img.shields.io/badge/ViaBackwards%20(5.0.0--SNAPSHOT)-Even%20with%20dev-brightgreen?style=flat-square) </br>

**Comment by kennytv** [comment]
Slot updates still aren't always there, but the crash/error is fixed
