### ISSUE TITLE
Sniffers digging cause 1.12.2 players to crash

### ISSUE THREAD

**Issue by cosmunn** [ViaVersion/ViaBackwards#757]
### '/viaversion dump' Output

https://dump.viaversion.com/ce2207aad71a322966a5b6cf802d0b19b07a6ae444b0837d3e366c42cdc12e58

### Console Error

```
There is no error message on the console, this is the crash log from the client.
https://mclo.gs/ATNKd9r
```

### Bug Description

Consistently, whenever a sniffer enters the digging action, players using 1.12.2 (have not tested any other version, as it's the earliest my server supports) crashes. It is reproduceable every single time.

Video showcasing the issue:
https://www.youtube.com/watch?v=THKHzvMTrI4

In the video, I spawn a sniffer with a 1.20.6 client and have both that and a 1.12.2 client connected at the same time. When the sniffer digs, the 1.12.2 client crashes and cannot reconnect without instantly crashing until I kill the sniffer. As soon as I do that, I am able to reconnect. I then spawn another sniffer and recreate the same scenario exactly, showing it can be consistently recreated. The crash report both times show the entity being ticked at the time of crash as a minecraft:cow, with the name Ravager, however its name in-game shows as Sniffer. Both the Ravager and the Sniffer render as a cow to 1.12.2 players, so it could be related. The crash report is linked above, in the Console Error field.

### Steps to Reproduce

1. Log in with a 1.12.2 client on a server version 1.20 or higher.
2. Spawn a sniffer
3. Wait for it to enter the digging action

### Expected Behavior

1.12.2 players should theoretically not see anything happen as they only see a cow, however the entire client crashes.

### Additional Server Info

I believe everything of note is on the dump.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Purpur--2176%20%28MC%3A%201.20.4%29](https://img.shields.io/badge/Platform-git--Purpur--2176%20%28MC%3A%201.20.4%29-3498db?style=flat-square) </br>![ViaVersion (4.10.2): 2 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.10.2)-2%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(4.10.2): 2 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.10.2)-2%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/).In case the issue still persists send the new dump and the issue will be reopened</h3>

**Comment by cosmunn** [comment]
https://dump.viaversion.com/9c7099ff9a2a5d317078138be17b5b413c9bdb3b8d045f7e6bfb1de3724cf14e

**Comment by Barvalg** [comment]
![Platform: git--Purpur--2176%20%28MC%3A%201.20.4%29](https://img.shields.io/badge/Platform-git--Purpur--2176%20%28MC%3A%201.20.4%29-3498db?style=flat-square) </br>![ViaVersion (5.0.0-SNAPSHOT): Even with dev](https://img.shields.io/badge/ViaVersion%20(5.0.0--SNAPSHOT)-Even%20with%20dev-brightgreen?style=flat-square) </br>![ViaBackwards(5.0.0-SNAPSHOT): Even with dev](https://img.shields.io/badge/ViaBackwards%20(5.0.0--SNAPSHOT)-Even%20with%20dev-brightgreen?style=flat-square) </br>

**Comment by kennytv** [comment]
Cannot reproduce
