### ISSUE TITLE
1.20.4 client on 1.20.6 server: When trying to get a defined painting in creative mode out of the creative inventory the player is kicked

### ISSUE THREAD

**Issue by Brokkonaut** [ViaVersion/ViaBackwards#758]
### '/viaversion dump' Output

https://dump.viaversion.com/2259d648711f974ae943f2f88217c8d112e9fd8d0b935fd37d8ffe997c823673

### Console Error

[08:59:24 INFO]: Brokkonaut lost connection: Internal Exception: io.netty.handler.codec.DecoderException: Failed to decode packet 'serverbound/minecraft:set_creative_mode_slot'

### Bug Description

When a client with minecraft 1.20.4 is trying to get a defined painting in creative mode out of the creative inventory the player is kicked. (Server version 1.20.6)

### Steps to Reproduce

1. use 1.20.4 client on a 1.20.6 server
2. gamemode creative
3. click on a painting with a defined picture int the creative inventory
4. try to place it in your inventory
5. lost connection

### Expected Behavior

i think i should get the painting

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: 1.20.6--DEV--0ad09de%20%28MC%3A%201.20.6%29](https://img.shields.io/badge/Platform-1.20.6--DEV--0ad09de%20%28MC%3A%201.20.6%29-3498db?style=flat-square) </br>![ViaVersion (4.10.2): 2 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.10.2)-2%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(4.10.3-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.10.3--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/).In case the issue still persists send the new dump and the issue will be reopened</h3>

**Comment by Brokkonaut** [comment]
https://dump.viaversion.com/f4f05b9cc7e9fc4bd8a31c95b0e5ae91d39510c7c29bf91fe1853665a355f884

**Comment by Barvalg** [comment]
![Platform: 1.20.6--DEV--0ad09de%20%28MC%3A%201.20.6%29](https://img.shields.io/badge/Platform-1.20.6--DEV--0ad09de%20%28MC%3A%201.20.6%29-3498db?style=flat-square) </br>![ViaVersion (4.10.3-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.10.3--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(4.10.3-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.10.3--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by kennytv** [comment]
Fixed in https://github.com/ViaVersion/ViaVersion/commit/94e853e5cfe5bfa1628c9ecced9093447ac38464
