### ISSUE TITLE
Clients older than 1.17 are stuck in a void.

### ISSUE THREAD

**Issue by Clyde-Timonera** [ViaVersion/ViaBackwards#759]
### '/viaversion dump' Output

https://dump.viaversion.com/3370ac566bf1601f18cb5b452ec2a2c3947edfe6e273dcd8faa66fc8a00ba3ce

### Console Error

[09:26:18 WARN] [viabackwards]: Increased world height is NOT SUPPORTED for 1.16 players and below. They will see a void below y 0 and above 256

### Bug Description

Players are stuck in void unless they fly but only some structures and entities are visible.
![Screenshot from 2024-05-26 09-28-47](https://github.com/ViaVersion/ViaBackwards/assets/78290310/1ea621b6-3668-4d29-a8f1-f940a2a7e692)
![Screenshot from 2024-05-26 09-31-58](https://github.com/ViaVersion/ViaBackwards/assets/78290310/4cf1c5ed-5340-42da-b038-8e5bbff17369)

### Steps to Reproduce

1. Login on a client older than 1.17
2. After going thru the lobby (which is invisible due to this bug) you see that you are now either connected to an empty survival or creative server.

### Expected Behavior

Players are able to roam around freely.

### Additional Server Info

I use Paper & Velocity with the following plugins.
Chunky
CMILib
CoreProtect
CrazyEnchantments
FAWE
Floodgate (On Velocity)
FreedomChat
Hibernate
IronElevators
Placeholder API
SetSpawn
WorldGuard
JustPlayerTPA
LuckPerms (On Velocity)
GeyserMod (On Velocity)
LimboAPI (On Velocity)
LimboReconnect (On Velocity)

### Checklist

- [x] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: velocity%203.3.0--SNAPSHOT%20%28git--71bb0246--b392%29](https://img.shields.io/badge/Platform-velocity%203.3.0--SNAPSHOT%20%28git--71bb0246--b392%29-3498db?style=flat-square) </br>![ViaVersion (4.10.2): 2 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.10.2)-2%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(4.10.2): 2 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.10.2)-2%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/).In case the issue still persists send the new dump and the issue will be reopened</h3>

**Comment by Clyde-Timonera** [comment]
Issue still persists.

**Comment by Clyde-Timonera** [comment]
https://dump.viaversion.com/3370ac566bf1601f18cb5b452ec2a2c3947edfe6e273dcd8faa66fc8a00ba3ce

**Comment by Barvalg** [comment]
![Platform: velocity%203.3.0--SNAPSHOT%20%28git--71bb0246--b392%29](https://img.shields.io/badge/Platform-velocity%203.3.0--SNAPSHOT%20%28git--71bb0246--b392%29-3498db?style=flat-square) </br>![ViaVersion (4.10.3-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.10.3--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(4.10.3-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.10.3--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by Clyde-Timonera** [comment]
Issue persists after updating.

**Comment by Jo0001** [comment]
See https://gist.github.com/Jo0001/4fe96cf5a78c8a00560ea985f3b9eb22

**Comment by Clyde-Timonera** [comment]
![image](https://github.com/ViaVersion/ViaBackwards/assets/78290310/7d041700-ba6a-4822-aa99-607d49667e50)
I now die from falling into the void infinitely and NO entities and structures are visible.

**Comment by Clyde-Timonera** [comment]
Nevermind. seems to be a world issue.
