### ISSUE TITLE
Wrong tooltip for Shulker box

### ISSUE THREAD

**Issue by Nippaku-Zanmu** [ViaVersion/ViaBackwards#763]
### '/viaversion dump' Output

https://dump.viaversion.com/57b5847bf44a187543efe3293375049bc41ff1c49022227f62131cf5a805c19a

### Console Error

```
Put the mclo.gs link or text here.
```

### Bug Description

Use the lower version to enter the higher version server that uses this plug-in
The Tooltip of the Shulker box does not display properly

### Steps to Reproduce

1. Use the client in 1.20.1 to enter the game
2. Place the mouse pointer over a shulker box
3. The Tooltip of the shulker box does not display properly

### Expected Behavior

The tooltip of the shulker box should display normally as shown in Figure 1

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: 1.20.6--115--9d6f2cc%20%28MC%3A%201.20.6%29](https://img.shields.io/badge/Platform-1.20.6--115--9d6f2cc%20%28MC%3A%201.20.6%29-3498db?style=flat-square) </br>![ViaVersion (4.10.2): 2 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.10.2)-2%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(4.10.2): 2 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.10.2)-2%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/).In case the issue still persists send the new dump and the issue will be reopened</h3>

**Comment by Nippaku-Zanmu** [comment]
on server image 
As shown in the figure, tooltip does not display properly on an advanced version server
<img width="345" alt="servet nbt 1" src="https://github.com/ViaVersion/ViaBackwards/assets/120476813/29b54199-1bb0-410c-9ca8-428257569f70">
<img width="297" alt="setver tooltip 1" src="https://github.com/ViaVersion/ViaBackwards/assets/120476813/3bfade28-cbcc-4ce7-87ac-5759029e8f5d">

**Comment by Nippaku-Zanmu** [comment]
This is the shulker box on the local server in 1.20.1
Like the one before, it contains some steps
<img width="329" alt="1201server nbt 1" src="https://github.com/ViaVersion/ViaBackwards/assets/120476813/2fdb24aa-0302-473b-8e97-5f6b6b73fe06">
<img width="293" alt="1201server tooltip 1" src="https://github.com/ViaVersion/ViaBackwards/assets/120476813/5083ff65-dced-46f3-a14a-1527f50fc0a1">

**Comment by Nippaku-Zanmu** [comment]
The obvious reason for the error is that BlockEntity was omitted during the nbt conversion
Note: I used the machine to turn over my English is not good

**Comment by Nippaku-Zanmu** [comment]
> ![Platform: 1.20.6--115--9d6f2cc%20%28MC%3A%201.20.6%29](https://camo.githubusercontent.com/b216550e3d38f85e6b05ac800efa35d510ff709f0adfd536955ff4cd65b36760/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f506c6174666f726d2d312e32302e362d2d3131352d2d396436663263632532302532384d43253341253230312e32302e362532392d3334393864623f7374796c653d666c61742d737175617265) ![ViaVersion (4.10.2): 2 commits behind master](https://camo.githubusercontent.com/6b51e5b20e72343e53da96daa0ec7993fc76faef81e779647ce9d6a60fa4f2f6/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f56696156657273696f6e25323028342e31302e32292d32253230636f6d6d6974287329253230626568696e642532306d61737465722d79656c6c6f773f7374796c653d666c61742d737175617265) ![ViaBackwards(4.10.2): 2 commits behind master](https://camo.githubusercontent.com/3a6d079832dc00de2bbe3b4314ddb1f428e5c7932484e8e6dda7b7f09a9f49f4/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f5669614261636b776172647325323028342e31302e32292d32253230636f6d6d6974287329253230626568696e642532306d61737465722d79656c6c6f773f7374796c653d666c61742d737175617265)
> 
> ### Please update **all** Via* plugins from https://ci.viaversion.com/.In case the issue still persists send the new dump and the issue will be reopened

https://dump.viaversion.com/7fc1e9f01261ca206273e373e31811488d069d8ba4e1483cbcefb23998d614ba

This is the latest dump
As shown in the figure
nbt's BlockEntityTag is still not fixed but tooltip shows no problem
This will affect mods like tweakroo that have a shulker box preview
<img width="331" alt="javaw_vJHO2xWWXs" src="https://github.com/ViaVersion/ViaBackwards/assets/120476813/415f36fd-4950-4deb-8e30-453a57b0fa51">

**Comment by Barvalg** [comment]
![Platform: 1.20.6--115--9d6f2cc%20%28MC%3A%201.20.6%29](https://img.shields.io/badge/Platform-1.20.6--115--9d6f2cc%20%28MC%3A%201.20.6%29-3498db?style=flat-square) </br>![ViaVersion (5.0.0-SNAPSHOT): Even with dev](https://img.shields.io/badge/ViaVersion%20(5.0.0--SNAPSHOT)-Even%20with%20dev-brightgreen?style=flat-square) </br>![ViaRewind(4.0.0-SNAPSHOT): Even with dev](https://img.shields.io/badge/ViaRewind%20(4.0.0--SNAPSHOT)-Even%20with%20dev-brightgreen?style=flat-square) </br>![ViaBackwards(5.0.0-SNAPSHOT): Even with dev](https://img.shields.io/badge/ViaBackwards%20(5.0.0--SNAPSHOT)-Even%20with%20dev-brightgreen?style=flat-square) </br>
