### ISSUE TITLE
[1.20.5->1.20.3] show_item tag is not handled

### ISSUE THREAD

**Issue by Pantera07** [ViaVersion/ViaBackwards#771]
### '/viaversion dump' Output

https://dump.viaversion.com/a1201c889f00d83362dc8894a03f5b943a8be2d8b1e84fa5982254fa9983fc29

### Console Error

```
none
```

### Bug Description

show_item tag is not handled

### Steps to Reproduce

```
/tellraw @p {"hoverEvent":{"action":"show_item","contents":{"components":{"minecraft:container":[{"item":{"components":{"minecraft:fireworks":{"explosions":[],"flight_duration":2}},"count":1,"id":"minecraft:firework_rocket"},"slot":0},{"item":{"components":{"minecraft:fireworks":{"explosions":[],"flight_duration":3}},"count":1,"id":"minecraft:firework_rocket"},"slot":26}]},"count":1,"id":"minecraft:shulker_box"}},"text":"Test"}
```
```
/tellraw @p {"hoverEvent":{"action":"show_item","contents":{"components":{"minecraft:fireworks":{"explosions":[],"flight_duration":2}},"count":1,"id":"minecraft:firework_rocket"}},"text":"Test"}
```

### Expected Behavior

show_item tag should not disappear.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: 1.20.6--130--5d8e53d%20%28MC%3A%201.20.6%29](https://img.shields.io/badge/Platform-1.20.6--130--5d8e53d%20%28MC%3A%201.20.6%29-3498db?style=flat-square) </br>![ViaVersion (5.0.0-SNAPSHOT): Even with dev](https://img.shields.io/badge/ViaVersion%20(5.0.0--SNAPSHOT)-Even%20with%20dev-brightgreen?style=flat-square) </br>![ViaBackwards(5.0.0-SNAPSHOT): Even with dev](https://img.shields.io/badge/ViaBackwards%20(5.0.0--SNAPSHOT)-Even%20with%20dev-brightgreen?style=flat-square) </br>

**Comment by FlorianMichael** [comment]
Already known, I still didn't came arround to write the needed conversions, but it's on my TODO

**Comment by kennytv** [comment]
Tracking this here instead https://github.com/ViaVersion/ViaBackwards/issues/788
