### ISSUE TITLE
Cant log into 1.20+ gamemodes only lobby 

### ISSUE THREAD

**Issue by pegasusgohan** [ViaVersion/ViaBackwards#777]
### '/viaversion dump' Output

https://dump.viaversion.com/32d5fba1851b1e007daa65fdded29fb9df357a3d3a55ff6dcadd7efc0c5fc69d

### Console Error

https://mclo.gs/IOKtUsX

https://mclo.gs/Mm2TJWt

### Bug Description

Using the viaproxy from 1.12 client to 1.20.5/.6, it only allows me to enter the lobby of the server, and when i try to enter gamemodes it gives me error. After a couple tries, i end up getting stuck in the ground.

![8adaa95a8bddd221c3e4478aa6734ce7](https://github.com/ViaVersion/ViaBackwards/assets/171844387/5f06cb58-b676-4deb-a32e-fb3eb3869814)
![8e2d87accd45c5a71227b751885ebec3](https://github.com/ViaVersion/ViaBackwards/assets/171844387/f2c54da1-dd00-491b-b5e2-dedd7d76794c)
![98bce58eace11f92f8994d074bd87c91](https://github.com/ViaVersion/ViaBackwards/assets/171844387/c7b55f3f-4441-42ed-922f-5bf997c36d4e)
![739d3c22e22c416b8819cd9c19f26563](https://github.com/ViaVersion/ViaBackwards/assets/171844387/33d2edd3-297c-49d3-b838-611e10335430)

### Steps to Reproduce

1: run Viaproxy latest build + java 8 version
2: login to play.hcfrevival.net
3: Attempt to join gamemode

### Expected Behavior

To enter the gamemode similar to how i would if i were on the same version.

### Additional Server Info

https://discord.gg/XvWQXFaE, this is the offical discord server where the admin shares their github updates

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: 3.0.0--SNAPSHOT](https://img.shields.io/badge/Platform-3.0.0--SNAPSHOT-3498db?style=flat-square) </br>![ViaVersion (5.0.0-SNAPSHOT): Even with dev](https://img.shields.io/badge/ViaVersion%20(5.0.0--SNAPSHOT)-Even%20with%20dev-brightgreen?style=flat-square) </br>![ViaRewind(4.0.0-SNAPSHOT): Even with dev](https://img.shields.io/badge/ViaRewind%20(4.0.0--SNAPSHOT)-Even%20with%20dev-brightgreen?style=flat-square) </br>![ViaBackwards(5.0.0-SNAPSHOT): 1 commits behind dev](https://img.shields.io/badge/ViaBackwards%20(5.0.0--SNAPSHOT)-1%20commit(s)%20behind%20dev-yellow?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/).<b>Put the jars into config/viafabricplus/jars.<br>In case the issue still persists send the new dump and the issue will be reopened</h3>

**Comment by pegasusgohan** [comment]
https://mclo.gs/8wi8oQA

https://dump.viaversion.com/80f7d6a6db1073e69c76e89d1995518b11c6b9dd768c95abc6391a83a1681f12

**Comment by Barvalg** [comment]
![Platform: 3.0.0--SNAPSHOT](https://img.shields.io/badge/Platform-3.0.0--SNAPSHOT-3498db?style=flat-square) </br>![ViaVersion (5.0.0-SNAPSHOT): 2 commits behind dev](https://img.shields.io/badge/ViaVersion%20(5.0.0--SNAPSHOT)-2%20commit(s)%20behind%20dev-yellow?style=flat-square) </br>![ViaRewind(4.0.0-SNAPSHOT): 3 commits behind dev](https://img.shields.io/badge/ViaRewind%20(4.0.0--SNAPSHOT)-3%20commit(s)%20behind%20dev-yellow?style=flat-square) </br>![ViaBackwards(5.0.0-SNAPSHOT): 3 commits behind dev](https://img.shields.io/badge/ViaBackwards%20(5.0.0--SNAPSHOT)-3%20commit(s)%20behind%20dev-yellow?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/).<b>Put the jars into config/viafabricplus/jars.<br>In case the issue still persists send the new dump and the issue will be reopened</h3>

**Comment by kennytv** [comment]
The server is not 1.20.6, you need to select a (more) correct target version since the server is already running ViaVersion. https://github.com/ViaVersion/ViaBackwards/pull/778 is going to fix that particular console error, but in order to not run into other issues, you need to change the target version

**Comment by pegasusgohan** [comment]
Thanks for helping me with this. 

Ive tried all the other versions. 
Only 1.20.1 and 1.20.5/6 seem to be working. 

1.20.5/6 is my desired goal to enter the gamemode.

After a couple disconnects, I was able to login to the gamemode, however I was stuck on the ground upon spawnning in.


https://mclo.gs/bb35dKz

https://dump.viaversion.com/2630ac2e072102d8be26f788e5ad837b27a103b1e54f5cb024f7956e66d9dfa5


recording: https://gyazo.com/803393227cfbea87177981e12f7b352e

https://github.com/ViaVersion/ViaBackwards/assets/171844387/cd4b6bbb-63a6-4f3a-89b2-24f09cfd2274

**Comment by Barvalg** [comment]
![Platform: 3.0.0--SNAPSHOT](https://img.shields.io/badge/Platform-3.0.0--SNAPSHOT-3498db?style=flat-square) </br>![ViaVersion (5.0.0-SNAPSHOT): 2 commits behind dev](https://img.shields.io/badge/ViaVersion%20(5.0.0--SNAPSHOT)-2%20commit(s)%20behind%20dev-yellow?style=flat-square) </br>![ViaRewind(4.0.0-SNAPSHOT): Even with dev](https://img.shields.io/badge/ViaRewind%20(4.0.0--SNAPSHOT)-Even%20with%20dev-brightgreen?style=flat-square) </br>![ViaBackwards(5.0.0-SNAPSHOT): 1 commits behind dev](https://img.shields.io/badge/ViaBackwards%20(5.0.0--SNAPSHOT)-1%20commit(s)%20behind%20dev-yellow?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/).<b>Put the jars into config/viafabricplus/jars.<br>In case the issue still persists send the new dump and the issue will be reopened</h3>

**Comment by pegasusgohan** [comment]
https://mclo.gs/bb35dKz

https://dump.viaversion.com/2630ac2e072102d8be26f788e5ad837b27a103b1e54f5cb024f7956e66d9dfa5

**Comment by Barvalg** [comment]
![Platform: 3.0.0--SNAPSHOT](https://img.shields.io/badge/Platform-3.0.0--SNAPSHOT-3498db?style=flat-square) </br>![ViaVersion (5.0.0-SNAPSHOT): 2 commits behind dev](https://img.shields.io/badge/ViaVersion%20(5.0.0--SNAPSHOT)-2%20commit(s)%20behind%20dev-yellow?style=flat-square) </br>![ViaRewind(4.0.0-SNAPSHOT): Even with dev](https://img.shields.io/badge/ViaRewind%20(4.0.0--SNAPSHOT)-Even%20with%20dev-brightgreen?style=flat-square) </br>![ViaBackwards(5.0.0-SNAPSHOT): 1 commits behind dev](https://img.shields.io/badge/ViaBackwards%20(5.0.0--SNAPSHOT)-1%20commit(s)%20behind%20dev-yellow?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/).<b>Put the jars into config/viafabricplus/jars.<br>In case the issue still persists send the new dump and the issue will be reopened</h3>

**Comment by pegasusgohan** [comment]
So for 1.20.1 I can log in only to the 1.20.1 gamemode, but the speed 2 potion effects does not work 

https://mclo.gs/XLPgsoT

https://dump.viaversion.com/240f7b660f23fc7ef9fdd5e5bcf551480dd447baa4477b9428e6b65be7ba6c92 

https://github.com/ViaVersion/ViaBackwards/assets/171844387/c167b92c-8382-4996-a390-9265f1d254a9

**Comment by Barvalg** [comment]
![Platform: 3.0.0--SNAPSHOT](https://img.shields.io/badge/Platform-3.0.0--SNAPSHOT-3498db?style=flat-square) </br>![ViaVersion (5.0.0-SNAPSHOT): 4 commits behind dev](https://img.shields.io/badge/ViaVersion%20(5.0.0--SNAPSHOT)-4%20commit(s)%20behind%20dev-yellow?style=flat-square) </br>![ViaRewind(4.0.0-SNAPSHOT): Even with dev](https://img.shields.io/badge/ViaRewind%20(4.0.0--SNAPSHOT)-Even%20with%20dev-brightgreen?style=flat-square) </br>![ViaBackwards(5.0.0-SNAPSHOT): 1 commits behind dev](https://img.shields.io/badge/ViaBackwards%20(5.0.0--SNAPSHOT)-1%20commit(s)%20behind%20dev-yellow?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/).<b>Put the jars into config/viafabricplus/jars.<br>In case the issue still persists send the new dump and the issue will be reopened</h3>

**Comment by pegasusgohan** [comment]
Recently tried the new viaproxy update with 1.21 and aswell with the 1.20.6

However, i got the outdated message using 1.21 and the same errors as previously posted witn 1.20-1.20.5/6+ 

![8e58eae78d7b6109904ed067354028bb](https://github.com/ViaVersion/ViaBackwards/assets/171844387/f77c29db-2dce-41ec-b3eb-c16877b18ef1)


https://mclo.gs/7zzaNhm

https://dump.viaversion.com/fc641b05b8590f68b98f81c839ea508c6207381af3a846fe95d6ea4dde852b18

**Comment by Barvalg** [comment]
![Platform: 3.0.0](https://img.shields.io/badge/Platform-3.0.0-3498db?style=flat-square) </br>![ViaVersion (5.0.0): 10 commits behind master](https://img.shields.io/badge/ViaVersion%20(5.0.0)-10%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(5.0.0): 7 commits behind master](https://img.shields.io/badge/ViaBackwards%20(5.0.0)-7%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaRewind(4.0.0): Even with master](https://img.shields.io/badge/ViaRewind%20(4.0.0)-Even%20with%20master-brightgreen?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/).<b>Put the jars into config/viafabricplus/jars.<br>In case the issue still persists send the new dump and the issue will be reopened</h3>
