### ISSUE TITLE
Client disconnects when adding armor to horse.

### ISSUE THREAD

**Issue by Mitch0S** [ViaVersion/ViaBackwards#785]
### '/viaversion dump' Output

https://dump.viaversion.com/6bc2d410f59a1c0b25468043e8a702b0a817acaecdd2b1ffae2fada413151865

### Console Error

```
The game crashed whilst container click
Error: java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
```

### Bug Description

Server Version: 1.20.6 (Purpur)
Client Version" 1.20.4 (Vanilla)

### Steps to Reproduce

1. Have a tamed horse ready to go
2. Mount the horse
3. Equip saddle if not already equipped on horse.
4. Equip armor

### Expected Behavior

After step 4, the game is expected to crash.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: velocity%203.3.0--SNAPSHOT%20%28git--2d015cdf--b397%29](https://img.shields.io/badge/Platform-velocity%203.3.0--SNAPSHOT%20%28git--2d015cdf--b397%29-3498db?style=flat-square) </br>![Proxy is 1 builds behind](https://img.shields.io/badge/Your%20proxy%20is%201%20build(s)%20behind.%20Please%20update%20to%20the%20latest%20version-orange?style=flat-square) </br>![ViaVersion (4.10.2): 2 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.10.2)-2%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(4.10.2): 2 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.10.2)-2%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/).In case the issue still persists send the new dump and the issue will be reopened</h3>
