### ISSUE TITLE
Buying trial chamber map on 1.20.5/6 server permanently kicks player

### ISSUE THREAD

**Issue by Kichura** [ViaVersion/ViaBackwards#789]
### '/viaversion dump' Output

https://dump.viaversion.com/46cad9c45030b019313f831fa6ccb946c9349eeac0efc2b4809202c48a088f74

### Console Error

Only player disconnected is seen in console but 1.20.4 client shows [this](https://i.imgur.com/ANlp24R.png).

### Bug Description

When buying a trial chamber map from a cartography villager and placing it into inventory, the player is permanently kicked until their inventory data is cleared or they switch to same version as server.

### Steps to Reproduce

1. Create a 1.20.5/6 server with viaversion and viabackwards on it,
2. Create a vanilla 1.20.4 client instance,
3. Join the server then summon a villager,
4. Mark the villager as a cartography-based one,
5. Keep buying from villager until trial chamber map is unlocked,
6. Buy the map and place it into inventory.

### Expected Behavior

The player is not kicked for having the broken map.

### Additional Server Info

1. This test server did not use any proxies,
2. Paper 1.20.6, *(Commit build: fe7043e)*
3. ViaVersion 5.0.1-SNAPSHOT with ViaBackwards 5.0.0.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. Velocity), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: 1.20.6--145--fe7043e%20%28MC%3A%201.20.6%29](https://img.shields.io/badge/Platform-1.20.6--145--fe7043e%20%28MC%3A%201.20.6%29-3498db?style=flat-square) </br>![ViaVersion (5.0.1-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(5.0.1--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(5.0.0): Even with master](https://img.shields.io/badge/ViaBackwards%20(5.0.0)-Even%20with%20master-brightgreen?style=flat-square) </br>
