### ISSUE TITLE
1.21 features are disabled on 1.20.4 clients

### ISSUE THREAD

**Issue by Kichura** [ViaVersion/ViaBackwards#790]
### '/viaversion dump' Output

https://dump.viaversion.com/082c5cf42a567c56a13d392e6b2b43654279c298dda73366b7a8abd5ea46159d

### Console Error

For the breeze one, It reports in client: `Skipping Entity with id entity.minecraft.breeze` as warning.

### Bug Description

When playing on a 1.21 server using 1.20.4 client that has both viafabric and viabackwards installed, the client cannot use any 1.21 features on it unless the server was on 1.20.5/6 instead.

Screenshot of both sides can be observed [here](https://i.imgur.com/nJWgUkN.png).

### Steps to Reproduce

1. Create a new 1.21 server,
2. Make a modded 1.20.4 client that has viafabric and viabackwards on it,
3. Make another instance but vanilla 1.21 for control,
4. Join the two accounts to same server,
5. On the vanilla 1.21 profile - Summon the breeze,
6. Notice breeze is not visible at all on 1.20.4's view.

### Expected Behavior

1.21 features properly work on older clients.

### Additional Server Info

1. This test server does not use any proxies,
2. Vanilla 1.21 for the server, Fabric 1.20.4 with ViaFabric 0.4.14+73-main *(ViaVersion 5.0.1-SNAPSHOT as override included)* with ViaBackwards 5.0.0,
3. No plugins on server as vanilla does not support any.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. Velocity), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: 0.4.14+73--main](https://img.shields.io/badge/Platform-0.4.14+73--main-3498db?style=flat-square) </br>![ViaVersion (5.0.1-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(5.0.1--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(5.0.0): Even with master](https://img.shields.io/badge/ViaBackwards%20(5.0.0)-Even%20with%20master-brightgreen?style=flat-square) </br>
