### ISSUE TITLE
Metadata for untracked entity causing log spam.

### ISSUE THREAD

**Issue by andrewkm** [ViaVersion/ViaBackwards#793]
### '/viaversion dump' Output

https://dump.viaversion.com/157ef72a78ee0c632ebbdae7ba5465ea938538e8cf7cd7cce3d618e97abcdf53

### Console Error

https://mclo.gs/B5obe6h

### Bug Description

A player using a 1.20.1 client is causing the above seen log spam.

### Steps to Reproduce

Unsure completely which plugin is causing this.

### Expected Behavior

N/A

### Additional Server Info

On request.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. Velocity), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: 1.20.6--145--fe7043e%20%28MC%3A%201.20.6%29](https://img.shields.io/badge/Platform-1.20.6--145--fe7043e%20%28MC%3A%201.20.6%29-3498db?style=flat-square) </br>![ViaVersion (5.0.1-SNAPSHOT): 5 commits behind master](https://img.shields.io/badge/ViaVersion%20(5.0.1--SNAPSHOT)-5%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(5.0.0): 7 commits behind master](https://img.shields.io/badge/ViaBackwards%20(5.0.0)-7%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaRewind(4.0.0): Even with master](https://img.shields.io/badge/ViaRewind%20(4.0.0)-Even%20with%20master-brightgreen?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/).In case the issue still persists send the new dump and the issue will be reopened</h3>

**Comment by andrewkm** [comment]
https://dump.viaversion.com/7de57558e0d59408bbd53bb671cf04152af247384de93da03214c0e02c0c26f7

**Comment by Barvalg** [comment]
![Platform: 1.20.6--145--fe7043e%20%28MC%3A%201.20.6%29](https://img.shields.io/badge/Platform-1.20.6--145--fe7043e%20%28MC%3A%201.20.6%29-3498db?style=flat-square) </br>![ViaVersion (5.0.0): 9 commits behind master](https://img.shields.io/badge/ViaVersion%20(5.0.0)-9%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(5.0.0): 7 commits behind master](https://img.shields.io/badge/ViaBackwards%20(5.0.0)-7%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaRewind(4.0.0): Even with master](https://img.shields.io/badge/ViaRewind%20(4.0.0)-Even%20with%20master-brightgreen?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/).In case the issue still persists send the new dump and the issue will be reopened</h3>

**Comment by andrewkm** [comment]
https://dump.viaversion.com/b808d584501fd183298328921ba756c2dcc1be50d09a26632fd5507eac5ad1c7

**Comment by Barvalg** [comment]
![Platform: 1.20.6--145--fe7043e%20%28MC%3A%201.20.6%29](https://img.shields.io/badge/Platform-1.20.6--145--fe7043e%20%28MC%3A%201.20.6%29-3498db?style=flat-square) </br>![ViaVersion (5.0.1-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(5.0.1--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(5.0.1-SNAPSHOT): 1 commits behind master](https://img.shields.io/badge/ViaBackwards%20(5.0.1--SNAPSHOT)-1%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaRewind(4.0.0): Even with master](https://img.shields.io/badge/ViaRewind%20(4.0.0)-Even%20with%20master-brightgreen?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/).In case the issue still persists send the new dump and the issue will be reopened</h3>

**Comment by andrewkm** [comment]
Kind of hard when latest VB doesn't compile. Sigh, I tried.

**Comment by MrPowerGamerBR** [comment]
I'm also having a similar issue, but mine is also happening with tracked entities: https://mclo.gs/ydruqt0

https://dump.viaversion.com/b3f90ba815f4e411a795673bd232f93f1ec06d3f112e5bff9a7e33042830c830

**Comment by MrPowerGamerBR** [comment]
> I'm also having a similar issue, but mine is also happening with tracked entities on 1.21: https://mclo.gs/ydruqt0
> 
> https://dump.viaversion.com/b3f90ba815f4e411a795673bd232f93f1ec06d3f112e5bff9a7e33042830c830

My issue seems to have been fixed in https://github.com/ViaVersion/ViaBackwards/commit/13a74f43ef9f9be215851ae47167575e63e6fbce (yay!)

**Comment by Barvalg** [comment]
![Platform: 1.21--DEV--e1c5e17%20%28MC%3A%201.21%29](https://img.shields.io/badge/Platform-1.21--DEV--e1c5e17%20%28MC%3A%201.21%29-3498db?style=flat-square) </br>![ViaVersion (5.0.1-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(5.0.1--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(5.0.1-SNAPSHOT): 1 commits behind master](https://img.shields.io/badge/ViaBackwards%20(5.0.1--SNAPSHOT)-1%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/).In case the issue still persists send the new dump </h3>

**Comment by andrewkm** [comment]
Thanks Kenny! :)

**Comment by andrewkm** [comment]
Ignore me just using the services of Barvalg to check something lmao:
https://dump.viaversion.com/94d3ed3504128517af06396a0683218547a87bc7f215aa2e5d707c81dab05c26

**Comment by Barvalg** [comment]
![Platform: 1.20.6--147--e41d44f%20%28MC%3A%201.20.6%29](https://img.shields.io/badge/Platform-1.20.6--147--e41d44f%20%28MC%3A%201.20.6%29-3498db?style=flat-square) </br>![ViaVersion (5.0.1-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(5.0.1--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaRewind(4.0.0): Even with master](https://img.shields.io/badge/ViaRewind%20(4.0.0)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(5.0.1-SNAPSHOT): 1 commits behind master](https://img.shields.io/badge/ViaBackwards%20(5.0.1--SNAPSHOT)-1%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/).In case the issue still persists send the new dump and the issue will be reopened</h3>
