### ISSUE TITLE
"Incomplete set of tags received from the server" when joining a 1.21 server with 1.20.5/1.20.6 (`minecraft:axolotl_tempt_items` & other tag related issues)

### ISSUE THREAD

**Issue by MrPowerGamerBR** [ViaVersion/ViaBackwards#794]
### '/viaversion dump' Output

https://dump.viaversion.com/98310e4e70de8a0101001ba051f3dccee4dbb0ac9d5dc213d692e4d0be65efde

### Console Error

*no errors*

### Bug Description

The title says it all I think, just try joining a 1.21 server with 1.16.5/1.17.1

### Steps to Reproduce

1. Login into a 1.21 server with a 1.16.5/1.17.1 client

### Expected Behavior

It works:tm:

### Additional Server Info

**Client error:**
![client-error](https://github.com/ViaVersion/ViaBackwards/assets/9496359/338024f7-1e1f-4fa8-8900-f7a70f262d27)

**Error in the launcher log:**
![client-error-log](https://github.com/ViaVersion/ViaBackwards/assets/9496359/147bff5b-51ac-4145-bbbe-acb3c93ca5d4)

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. Velocity), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: 1.21--DEV--67e8464%20%28MC%3A%201.21%29](https://img.shields.io/badge/Platform-1.21--DEV--67e8464%20%28MC%3A%201.21%29-3498db?style=flat-square) </br>![ViaVersion (5.0.1-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(5.0.1--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(5.0.1-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(5.0.1--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by Kichura** [comment]
Reopening this issue as this is still causing issues but with `Incomplete server tags, disconnecting. Missing: {ResourceKey[minecraft:root / minecraft:item]=[minecraft:axolotl_tempt_items]}` instead, 1.20.5/6 servers are affected.
