### ISSUE TITLE
Enchants are incorrectly remapped when connecting with a pre-1.21 client on a 1.21 server

### ISSUE THREAD

**Issue by MrPowerGamerBR** [ViaVersion/ViaBackwards#795]
### '/viaversion dump' Output

https://dump.viaversion.com/24f698e31c09a6b1acb4bef851bab32c9d128accf0d9ae4f02ad601968fd6bab

### Console Error

*no errors*

### Bug Description

It seems that ViaBackwards is not remapping enchantments correctly (Unbreakable is missing) and some enchantments are incorrectly remapped (Mending... 3?)

**1.21:**
<img width="246" alt="javaw_cmwGoI6RM8" src="https://github.com/ViaVersion/ViaBackwards/assets/9496359/7e348c35-671f-4624-b6cc-063e3a9936a7">

**1.20.6:**
<img width="244" alt="javaw_nx5bm9wcF2" src="https://github.com/ViaVersion/ViaBackwards/assets/9496359/813fccab-1fb1-4aab-b06f-7ef6c3bd596a">

### Steps to Reproduce

Just enchant an item with enchantments

### Expected Behavior

The enchants are correctly remapped on pre-1.21 versions

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. Velocity), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: 1.21--DEV--e1c5e17%20%28MC%3A%201.21%29](https://img.shields.io/badge/Platform-1.21--DEV--e1c5e17%20%28MC%3A%201.21%29-3498db?style=flat-square) </br>![ViaVersion (5.0.1-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(5.0.1--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(5.0.1-SNAPSHOT): 1 commits behind master](https://img.shields.io/badge/ViaBackwards%20(5.0.1--SNAPSHOT)-1%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/).In case the issue still persists send the new dump and the issue will be reopened</h3>

**Comment by Billybobertjoe** [comment]
still incorrectly remapped in enchantment tables

**Comment by fr1g** [comment]
so as the smith template, the texture and the description appeared different from the template used.
I'm just a player and not sure about the version of plugin.
But, only since the version with component (1.20.6) able to show the forged-shape data/info properly.
