### ISSUE TITLE
infinite potion effect for 1.19.3- give flash

### ISSUE THREAD

**Issue by emanondev** [ViaVersion/ViaBackwards#796]
### '/viaversion dump' Output

https://dump.viaversion.com/e84df5f8e04afc6ad87e81774282378fa44ae58020c18004a1fe7046450179ab

### Bug Description

Giving infinite potion effect (duration as -1 for 1.19.4+) is displayed as 0:00 on older clients, while this isn't a big issue for most of effects, night vision give bothering flashing color transitions for background and would be much better if displayed as a very long duration instead of 0:00 duration

https://i.imgur.com/VJ9Asqj.mp4

An user (server owner) reported this issue to me, thinking my plugin was doing the error, after a fast test from the user it was clear the issue was client version related, so forgive me if i hadn't test if with build from https://ci.viaversion.com/ the issue still persists

### Steps to Reproduce

start a server on 1.20.4
connect with a 1.18 client
obtain infinite effect of night vision with minecraft command or with any other plugin

### Expected Behavior

No flashing screen

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. Velocity), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [x] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Pufferfish--51%20%28MC%3A%201.20.4%29](https://img.shields.io/badge/Platform-git--Pufferfish--51%20%28MC%3A%201.20.4%29-3498db?style=flat-square) </br>![ViaVersion (5.0.0): 10 commits behind master](https://img.shields.io/badge/ViaVersion%20(5.0.0)-10%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(5.0.0): 10 commits behind master](https://img.shields.io/badge/ViaBackwards%20(5.0.0)-10%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/).In case the issue still persists send the new dump and the issue will be reopened</h3>
