### ISSUE TITLE
ToolComponent new 1.21 tool rules

### ISSUE THREAD

**Issue by vermulst** [ViaVersion/ViaBackwards#797]
### '/viaversion dump' Output

https://dump.viaversion.com/63313780884d36288e073f1d8a0c619314285f9ba93da348005c09bd43240a6e

### Console Error

```
not applicable
```

### Bug Description

I am trying to use custom breaking speeds using the new 1.21 feature, however these don't properly work yet for -1.20. 

### Steps to Reproduce

Login with a 1.21 client on a 1.21 server, apply a custom toolrule on a tool by executing:
/give @p diamond_shovel[tool={default_mining_speed:1,damage_per_block:1,rules:[{speed:0.2,correct_for_drops:true,blocks:"sand"}]}] 1

Test the given custom rule on a sand block
Login with a 1.20.4 client, or probably any client below 1.21.
Compare both versions.

### Expected Behavior

1.20.4 does not have a custom breaking speed, but it does break after the expected time after breaking the block.
Not sure if this is fixable.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. Velocity), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: 1.21--6--126f6d7%20%28MC%3A%201.21%29](https://img.shields.io/badge/Platform-1.21--6--126f6d7%20%28MC%3A%201.21%29-3498db?style=flat-square) </br>![ViaVersion (5.0.1-SNAPSHOT): 4 commits behind master](https://img.shields.io/badge/ViaVersion%20(5.0.1--SNAPSHOT)-4%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(5.0.0): 13 commits behind master](https://img.shields.io/badge/ViaBackwards%20(5.0.0)-13%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/).In case the issue still persists send the new dump and the issue will be reopened</h3>

**Comment by kennytv** [comment]
ViaBackwards does not (and in this case cannot) reimplement newer client features
