### ISSUE TITLE
[1.20.3->1.20.2] Falling Pointed Dripstone bug

### ISSUE THREAD

**Issue by Pantera07** [ViaVersion/ViaBackwards#799]
### '/viaversion dump' Output

https://dump.viaversion.com/0ec4c2cd81fa40b72479ec17665f3896873c189febec184a5bfa9f31ea61eb9d

### Console Error

```
[16:04:46 WARN]: [ViaBackwards] Missing 1.20 blockstate for 1.20.2 blockstate 24755
[16:04:50 WARN]: [ViaBackwards] Missing 1.20 blockstate for 1.20.2 blockstate 24755
[16:04:56 WARN]: [ViaBackwards] Missing 1.20 blockstate for 1.20.2 blockstate 24755
[16:06:17 WARN]: [ViaBackwards] Missing 1.20 blockstate for 1.20.2 blockstate 24759
[16:06:17 WARN]: [ViaBackwards] Missing 1.20 blockstate for 1.20.2 blockstate 24755
```

### Bug Description

1.20.1 and below: Falling Pointed Dripstone displays an error message and is not visible.
1.20.2: Falling Pointed Dripstone is not visible.

### Steps to Reproduce

1. Open 1.20.4 ~ 1.21 Server
2. Login 1.20.1 or 1.20.2 Client
3. Place Pointed Dripstone
4. Drop Pointed Dripstone

### Expected Behavior

Falling Pointed Dripstone should be visible and not output an error message.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. Velocity), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: 1.20.6--147--e41d44f%20%28MC%3A%201.20.6%29](https://img.shields.io/badge/Platform-1.20.6--147--e41d44f%20%28MC%3A%201.20.6%29-3498db?style=flat-square) </br>![ViaVersion (5.0.1): Even with master](https://img.shields.io/badge/ViaVersion%20(5.0.1)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(5.0.1): Even with master](https://img.shields.io/badge/ViaBackwards%20(5.0.1)-Even%20with%20master-brightgreen?style=flat-square) </br>
