### ISSUE TITLE
1.20.1 client shows incomplete shulker box tooltip on 1.21 server

### ISSUE THREAD

**Issue by Dreeam-qwq** [ViaVersion/ViaBackwards#803]
### '/viaversion dump' Output

https://dump.viaversion.com/910c16cec2ac1a3723fcda536f86a7a53700329d91faf5b3ec4d2495b8c7931b

### Console Error

No error

### Bug Description

![1 20 1](https://github.com/ViaVersion/ViaBackwards/assets/61569423/bc2cd57a-e820-48d9-92d7-a2705358745d)

### Steps to Reproduce

1. 1.21 Paper server
2. Join with 1.20.1 vanilla client
3. Use blocks or items fill shulker box
4. See incomplete tooltip hover

### Expected Behavior

![1 21](https://github.com/ViaVersion/ViaBackwards/assets/61569423/83b38460-1272-41d6-816a-75f3fa6bba91)

### Additional Server Info

Server: Paper version 1.21-38-master@1f5db50 (2024-06-27T20:15:58Z)
Plugins: ViaBackwards, ViaVersion

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. Velocity), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: 1.21--38--1f5db50%20%28MC%3A%201.21%29](https://img.shields.io/badge/Platform-1.21--38--1f5db50%20%28MC%3A%201.21%29-3498db?style=flat-square) </br>![ViaVersion (5.0.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(5.0.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(5.0.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(5.0.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>
