### ISSUE TITLE
[1.20.4 client, 1.21 server] Unable to put down boat or water/lava bucket

### ISSUE THREAD

**Issue by ImGGAAVVIINN** [ViaVersion/ViaBackwards#808]
### '/viaversion dump' Output

https://dump.viaversion.com/76b152a5b23f1d11dc9de072d6a47a7efabca082ed3389162fb30633eb8f3a1f

### Console Error

```
Put the mclo.gs link or text here.
```

### Bug Description

when placing down boat, nothing happened
When placing down water or lava with a bucket, the liquid appears for a split second and disappear. The bucket will be empty.

### Steps to Reproduce

1. Login with a 1.20.4 client
2. Place down boat anywhere (on water or on land)
3. boat is still in player's hand and nothing happened
4. place down water/lava
5. water/lava appear for a split second and disappear
6. bucket is empty

### Expected Behavior

Placing water/and lava down with a bucket should allow them to stay and flow naturally
Placing down boat should make the appear

### Additional Server Info

Server: Spigot 1.21 (also occur on paper experimental 1.21)
Plugins (28): RemoveJoinLeaveMessage, Lobbys, Skript, Chunky, PlaceholderAPI, PerWorldPlugins, CompatNoCheatPlus, Multiverse-Core, Multiverse-SignPortals, Multiverse-Inventories, DeluxeMenus, NoChatReports, ViaVersion, Multiverse-TeleportFilter, Multiverse-Portals, NexEngine, floodgate, UltimateHomes, ViaBackwards, ViaRewind, LuckPerms, ViaRewind-Legacy-Support, ProtocolLib, SkinsRestorer, Geyser-Spigot, Multiverse-NetherPortals, ItemJoin, LPC

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. Velocity), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: 4226--Spigot--146439e--2889b3a%20%28MC%3A%201.21%29](https://img.shields.io/badge/Platform-4226--Spigot--146439e--2889b3a%20%28MC%3A%201.21%29-3498db?style=flat-square) </br>![ViaVersion: Outdated](https://img.shields.io/badge/ViaVersion%20(5.0.0)-Outdated!-red?style=flat-square) </br>![ViaBackwards: Outdated](https://img.shields.io/badge/ViaBackwards%20(5.0.0)-Outdated!-red?style=flat-square) </br>![ViaRewind: Outdated](https://img.shields.io/badge/ViaRewind%20(4.0.0)-Outdated!-red?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/).In case the issue still persists send the new dump and the issue will be reopened</h3>

**Comment by JackerAcid** [comment]
you probably should have added this only happens when the client places those type of item more than 4.5 blocks (so every version except 1.20.6 and 1.21 so far as I tested)
