### ISSUE TITLE
 Could not pass event PlayerJoinEvent to PocketGames

### ISSUE THREAD

**Issue by a000a498** [ViaVersion/ViaBackwards#809]
### '/viaversion dump' Output

https://dump.viaversion.com/d11938bb7b64dc2959d566d4525b403458bb368c5dccddbdcfcbfebea55156bc

### Console Error

https://mclo.gs/2GxrZDn

### Bug Description

I only know that this problem started to occur when I upgraded vivaersion from 4.10.2 to 5.0.0 and 5.0.1. This problem did not occur when I used 4.10.2

### Steps to Reproduce

I only know that this problem started to occur when I upgraded vivaersion from 4.10.2 to 5.0.0 and 5.0.1. This problem did not occur when I used 4.10.2

### Expected Behavior

This error should not occur

### Additional Server Info

![image](https://github.com/ViaVersion/ViaBackwards/assets/33992911/21366b83-6afb-45e8-9ff0-ee2a3928cb59)

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. Velocity), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: 3763--Spigot--7d7b241--5a5e43e%20%28MC%3A%201.19.4%29](https://img.shields.io/badge/Platform-3763--Spigot--7d7b241--5a5e43e%20%28MC%3A%201.19.4%29-3498db?style=flat-square) </br>![ViaVersion (5.0.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(5.0.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by kennytv** [comment]
Report it to PocketGames
