### ISSUE TITLE
Unable to join under 1.17

### ISSUE THREAD

**Issue by mrunningmasterc** [ViaVersion/ViaBackwards#817]
### '/viaversion dump' Output

https://dump.viaversion.com/6d4c9b052287760d5fd808d6aeb6832ed3eaf18d31080cb271ca11bf140966b5

### Console Error

```
https://hastebin.com/share/xilohigiro.markdown
```

### Bug Description

<img width="774" alt="Screen Shot 2024-07-11 at 10 28 41 AM" src="https://github.com/ViaVersion/ViaBackwards/assets/63335629/82452831-3868-4b1e-b477-fb31b525ca91">

### Steps to Reproduce

Joined a 1.20.4 purpur server with a 1.16.5 client or lower and said what it said in bug desc pic. I removed all plugins and just kept the via's in and a few other support plugins but still said that message

### Expected Behavior

Joined a 1.20.4 purpur server with a 1.16.5 client or lower and said what it said in bug desc pic. 

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. Velocity), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Purpur--2176%20%28MC%3A%201.20.4%29](https://img.shields.io/badge/Platform-git--Purpur--2176%20%28MC%3A%201.20.4%29-3498db?style=flat-square) </br>![ViaVersion (5.0.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(5.0.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(5.0.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(5.0.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaRewind(4.0.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaRewind%20(4.0.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by FlorianMichael** [comment]
Hi.
Tested with both Spigot and Paper 1.20.4 and I can join with a Vanilla 1.16.5, also the error log you provided is cursed and I would say this is either an issue of your server software (Purpur) or you have some plugin installed doing cursed stuff.

**Comment by mrunningmasterc** [comment]
I am joining through a 1.21 flamecord proxy. I forgot to mention that. 

> Hi. Tested with both Spigot and Paper 1.20.4 and I can join with a Vanilla 1.16.5, also the error log you provided is cursed and I would say this is either an issue of your server software (Purpur) or you have some plugin installed doing cursed stuff.

**Comment by FlorianMichael** [comment]
Then this is a Issue of your proxy, please try to update or migrate to Velocity.

**Comment by mrunningmasterc** [comment]
> Then this is a Issue of your proxy, please try to update or migrate to Velocity.

I got it figured out. It was the oddest problem. I went into my main world file and deleted scoreboard.dat and problem is completely fine now. I guess there might have been some scoreboard character limit thing that had more than what 1.16.5 or lower could handle

**Comment by FlorianMichael** [comment]
Weird but glad you were able to sollve this issue, will close then.

**Comment by linsaftw** [comment]
Yes, heard a lot of these before. Thank you for commenting it was the scoreboard. Now I have a clue where this is coming from. This sometimes happens when installing weird scoreboard and nametags plugins.
