### ISSUE TITLE
Some of the text output in the chatbox is not displaying correctly.

### ISSUE THREAD

**Issue by PoetryWindy** [ViaVersion/ViaBackwards#819]
### '/viaversion dump' Output

https://dump.viaversion.com/bc42a28aae24aeca46d53ecf4d0ad12a636cb34ebd468a940eaf6abca958da71

### Console Error

nothing

### Bug Description

Some of the text output in the chatbox is not displaying correctly.

### Steps to Reproduce

1. Use the 1.15.2 version of the client to connect to the 1.20.1 version of the server.
2. 2. Enter any plugin command and observe the text display.

### Expected Behavior

The text should display correctly.

### Additional Server Info

![image](https://github.com/user-attachments/assets/4f6efc7d-157d-4b89-8f65-750ec8ad29d2)
![image](https://github.com/user-attachments/assets/53385556-0e38-4c1e-9feb-a7d7c57340c4)

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. Velocity), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: 0.4.14+74--main](https://img.shields.io/badge/Platform-0.4.14+74--main-3498db?style=flat-square) </br>![ViaVersion (5.0.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(5.0.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(5.0.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(5.0.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaRewind(4.0.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaRewind%20(4.0.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>
