### ISSUE TITLE
[1.20.6->1.20.4] can_break -> CanBreak isn't translated properly

### ISSUE THREAD

**Issue by wd4q5dy** [ViaVersion/ViaBackwards#824]
### '/viaversion dump' Output

https://dump.viaversion.com/16dbeffd7a6355a07a6b425f032218e695231e1ea338f143944d17897dc36251

### Console Error

```
```

### Bug Description

e.g. `/give @a stick[can_break={blocks:"dirt"}]` on a 1.20.6 server gives a stick that can break **dirt** with a 1.20.6 client, but a 1.20.4 client sees it as a stick that can break **deepslate**

**Dirt** becomes **Deepslate**
**Grass Block** becomes **Cobbled Deepslate**
**Deepslate** becomes **missingno**

### Steps to Reproduce

`/give @a stick[can_break={blocks:"dirt"}]` on a 1.20.6 server with a 1.20.4 client and check the lore of the item

### Expected Behavior

the 1.20.4 client should see the item as able to break the correct blocks

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. Velocity), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: 1.20.6--135--79c1ce1%20%28MC%3A%201.20.6%29](https://img.shields.io/badge/Platform-1.20.6--135--79c1ce1%20%28MC%3A%201.20.6%29-3498db?style=flat-square) </br>![ViaVersion (5.0.1): 29 commits behind master](https://img.shields.io/badge/ViaVersion%20(5.0.1)-29%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(5.0.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(5.0.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/).In case the issue still persists send the new dump and the issue will be reopened</h3>

**Comment by wd4q5dy** [comment]
https://dump.viaversion.com/36527cdf44d4191c280677e568ec06442657706500e23a95dd972fefdee99e19

**Comment by Barvalg** [comment]
![Platform: 1.20.6--148--20f5165%20%28MC%3A%201.20.6%29](https://img.shields.io/badge/Platform-1.20.6--148--20f5165%20%28MC%3A%201.20.6%29-3498db?style=flat-square) </br>![ViaVersion (5.0.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(5.0.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(5.0.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(5.0.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by wd4q5dy** [comment]
![Screenshot 2024-07-18 at 9 53 06 AM](https://github.com/user-attachments/assets/ac42bddc-3cbd-43e9-9255-6fa37a1a89cb)
![Screenshot 2024-07-18 at 9 53 15 AM](https://github.com/user-attachments/assets/1b281996-f68f-456d-8e6c-f102a0dbd977)

**Comment by FlorianMichael** [comment]
Thanks for reporting, fixed in dev builds from https://ci.viaversion.com/
