### ISSUE TITLE
Incorrect Armor Trims Displayed

### ISSUE THREAD

**Issue by Coswics** [ViaVersion/ViaBackwards#847]
### '/viaversion dump' Output

https://dump.viaversion.com/8afa7132720d84a7d9afaf1cfad7cd890c7454ef46df0da092cb28e603127eb3

### Console Error

```
No Console Error.
```

### Bug Description

Custom Armor Trims (provided by a datapack & resourcepack) Don't Display Correctly, if at all on lower client versions.
![image](https://github.com/user-attachments/assets/59d4a6d0-79a0-4cd4-a19e-399d2b3e01f6)
![2024-07-31_23 37 16](https://github.com/user-attachments/assets/10d29586-1ef9-485e-980b-dedad551ba08)

### Steps to Reproduce

1. Create New Server (Paper was tested, in this instance)
2. Install a Data Pack that provides custom armor trim textures/models, such as [Laser's Armor Trims Plus](https://www.planetminecraft.com/data-pack/banner-pattern-armor-trims/); modified to have the new trim materials substituted for older items
3. Login to the server with one player on a version between 1.20.5 and 1.21, and the other on any version on between 1.19.4 and 1.20.4 
4. Give yourself one of the custom trims via a command or via the smithing table
5. Wear or display the armor on an armor stand
6. Observe

### Expected Behavior

Armor Trim Displays Properly, as the custom trim material and pattern; regardless of version (due to both the datapack and texture pack formatting not really changing, tested on 1.20.4 and both 1.21 the packs work by themselves and function as intended)
could be an issue with trim formatting possibly? Additionally; for servers on newer versions; the armor trim materials arent translated to older equivalents; this error is gotten when a player tries to join a 1.21 server on 1.20.4 or below client
![2024-08-01_00 00 35](https://github.com/user-attachments/assets/524abd18-d7bb-4f2a-b35a-428b199c4d6c)

### Additional Server Info

Nothing but viaversion, viabackwards, and the datapack are installed

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. Velocity), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: 1.21--123--0a1be9a%20%28MC%3A%201.21%29](https://img.shields.io/badge/Platform-1.21--123--0a1be9a%20%28MC%3A%201.21%29-3498db?style=flat-square) </br>![ViaVersion (5.0.2): Even with master](https://img.shields.io/badge/ViaVersion%20(5.0.2)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(5.0.2): 4 commits behind master](https://img.shields.io/badge/ViaBackwards%20(5.0.2)-4%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/).In case the issue still persists send the new dump and the issue will be reopened</h3>

**Comment by Coswics** [comment]
https://dump.viaversion.com/adb53a4e000980f36588537389e72eed28f4801cd86e2c5f6b084973f1a75af2

**Comment by Barvalg** [comment]
![Platform: 1.21--123--0a1be9a%20%28MC%3A%201.21%29](https://img.shields.io/badge/Platform-1.21--123--0a1be9a%20%28MC%3A%201.21%29-3498db?style=flat-square) </br>![ViaVersion (5.0.2): Even with master](https://img.shields.io/badge/ViaVersion%20(5.0.2)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(5.0.3-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(5.0.3--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by Coswics** [comment]
Additionally, here's the exact dp we used and the resource pack
![2024-08-01_14 30 11](https://github.com/user-attachments/assets/21c26c89-1d5f-4e44-a41d-e67e116e8049)
![2024-08-01_14 30 25](https://github.com/user-attachments/assets/60c43e38-6a6d-4356-a538-aa70268766d9)
[Lasers Pack (Modified).zip](https://github.com/user-attachments/files/16460625/Lasers.Pack.Modified.zip)
[New Trim DP3.zip](https://github.com/user-attachments/files/16460626/New.Trim.DP3.zip)
