### ISSUE TITLE
[1.21->1.20.3] Armor trim display bug

### ISSUE THREAD

**Issue by Pantera07** [ViaVersion/ViaBackwards#850]
### '/viaversion dump' Output

https://dump.viaversion.com/de19aa8217684e83f420114e4d0eb5990332fa11595e0837c6eec9faf6a6da4e

### Console Error

```
none
```

### Bug Description

1.21 Server & 1.21 Client:
![2024-08-03_11 06 28](https://github.com/user-attachments/assets/162a8d39-48ae-4ff2-8a0a-ba1be3ed3069)
![image](https://github.com/user-attachments/assets/efb76d18-6616-4ddc-9517-6f015cc37607)

1.21 Server & 1.20.4 Client:
![2024-08-03_11 09 48](https://github.com/user-attachments/assets/afeea59a-d88e-4dc3-bc7e-aaa61b265394)
![image](https://github.com/user-attachments/assets/41267cec-5f8a-4081-895b-1012a9c40e57)

### Steps to Reproduce

1. Open 1.21 server
2. Check armor trim (~1.20.4 Client)

### Expected Behavior

Armor trim should appear normal.

### Additional Server Info

In this case this bug does not occur:
1.20.6 Server & 1.20.4 Client
1.21 Server & 1.20.6 Client

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. Velocity), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: 1.21--124--df3b654%20%28MC%3A%201.21%29](https://img.shields.io/badge/Platform-1.21--124--df3b654%20%28MC%3A%201.21%29-3498db?style=flat-square) </br>![ViaVersion (5.0.3-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(5.0.3--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(5.0.3-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(5.0.3--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>
