### ISSUE TITLE
1.20.1 Kicks because of dog armor

### ISSUE THREAD

**Issue by enels0n** [ViaVersion/ViaBackwards#852]
### '/viaversion dump' Output

https://dump.viaversion.com/2a7789b01a5bb30f73d370d38e21fdd63a58c14f70ba954a3883e84b01d91f5c

### Bug Description

When a wolf with armor comes into view, the client on version 1.20.1 is thrown from the server with the error "index 6 out of bounds for length 6".

### Steps to Reproduce

1. Paper 1.20.6 latest build
2. Client 1.20.1
3. Wolf + wolf armor

### Expected Behavior

Nothing

### Additional Server Info

![image](https://github.com/user-attachments/assets/8c041e70-e57e-4295-8ba2-5410a0629fdb)

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. Velocity), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: 1.20.6--148--20f5165%20%28MC%3A%201.20.6%29](https://img.shields.io/badge/Platform-1.20.6--148--20f5165%20%28MC%3A%201.20.6%29-3498db?style=flat-square) </br>![ViaVersion (5.0.2): 7 commits behind master](https://img.shields.io/badge/ViaVersion%20(5.0.2)-7%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(5.0.2): 7 commits behind master](https://img.shields.io/badge/ViaBackwards%20(5.0.2)-7%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/).In case the issue still persists send the new dump and the issue will be reopened</h3>
