### ISSUE TITLE
blast protection prevents wind charges from working

### ISSUE THREAD

**Issue by Shelper24** [ViaVersion/ViaBackwards#856]
### '/viaversion dump' Output

https://dump.viaversion.com/0ca99d87d011be761d79abb041a340d78eb432e7f02f02072fe42a55fa075683

### Console Error

```

```

### Bug Description

The repulsive force from explosions depends on the blast-protection, on versions below 1.21, wind charge works as an explosion, which is why having blast-protection on armor does not allow wind charges to push the player away

https://github.com/user-attachments/assets/0fabe1f8-9a9e-4dad-9705-b8e08a71a6b3 
(nethertie boots & leggings enchanted blast protection IV)

(The video fragment uses a resource pack that replaces the snowball with a wind charge)

### Steps to Reproduce

log in with version below 1.21 -> put on armor with enchantment **blast protection** ->use wind charge on yourself

### Expected Behavior

the player must push off upward

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. Velocity), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: 1.21--126--7e44684%20%28MC%3A%201.21%29](https://img.shields.io/badge/Platform-1.21--126--7e44684%20%28MC%3A%201.21%29-3498db?style=flat-square) </br>![ViaVersion (5.0.2): 8 commits behind master](https://img.shields.io/badge/ViaVersion%20(5.0.2)-8%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(5.0.3-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(5.0.3--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/).In case the issue still persists send the new dump and the issue will be reopened</h3>

**Comment by kennytv** [comment]
Not a Via issue https://bugs.mojang.com/browse/MC-272483
