### ISSUE TITLE
"Chat message validation failure" on Client Version 1.20 - 1.20.4

### ISSUE THREAD

**Issue by TwiceBit** [ViaVersion/ViaBackwards#859]
### '/viaversion dump' Output

https://dump.viaversion.com/fcc9765f2256cc4e05299efba8cb7702ddd5ff202f086de2bae3485d180041d0

### Console Error

https://mclo.gs/BrGsszD

### Bug Description

On 1.20 - 1.20.4 you will be kicked if you sending chat messages and execute commands.

### Steps to Reproduce

1. Setup Paper 1.21 server
2. Login with Client 1.20 - 1.20.4
3. Execute some commands and Chat

mayby you will be kicked after you try to run an invalid command and chat

### Expected Behavior

The client should'nt kicked

### Additional Server Info

My tests:
```
1.20.1 kicked
1.20.4 kicked
1.20.5 works
1.20.6 works
```

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. Velocity), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: 1.21--127--4e6a2a1%20%28MC%3A%201.21%29](https://img.shields.io/badge/Platform-1.21--127--4e6a2a1%20%28MC%3A%201.21%29-3498db?style=flat-square) </br>![ViaVersion (5.0.3): Even with master](https://img.shields.io/badge/ViaVersion%20(5.0.3)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(5.0.3): Even with master](https://img.shields.io/badge/ViaBackwards%20(5.0.3)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by Kichura** [comment]
Does this continue when disabling `enforce-secure-profile` in server properties?

**Comment by TwiceBit** [comment]
Thanks, it works with the freedomchat plugin. I never head about this plugin.

**Comment by kennytv** [comment]
It should be fixed properly now, without having to use freedomchat
