### ISSUE TITLE
1.21 -> 1.20

### ISSUE THREAD

**Issue by xProMDFKx** [ViaVersion/ViaBackwards#861]
### '/viaversion dump' Output

https://dump.viaversion.com/7bf691fc14c362655cf2fec3b1ef0fbca51ca23e580033fdb167f074184e38c1

### Console Error

```
Put the mclo.gs link or text here.
```
No errors

### Bug Description

Basically, on the new 1.21 i was able to edit the durability for the armors with ExecutableItems, so i've set a custom durability on the Leather Armor (600), but with ViaBackwards if you join wiht 1.20 that armor has the default durability and the player cand go with the armor on a negative durability but it will still not break 

### Steps to Reproduce

1. Make a 1.21 server and make a item with a custom durability
2. Use Viabackwards and join with 1.20

### Expected Behavior

The armor should have the same durability as the player see on 1.21

### Additional Server Info

There is a screenshot:

https://dump.viaversion.com/7bf691fc14c362655cf2fec3b1ef0fbca51ca23e580033fdb167f074184e38c1

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. Velocity), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: 1.21--DEV--64094d4%20%28MC%3A%201.21%29](https://img.shields.io/badge/Platform-1.21--DEV--64094d4%20%28MC%3A%201.21%29-3498db?style=flat-square) </br>![ViaVersion (5.0.3): 1 commits behind master](https://img.shields.io/badge/ViaVersion%20(5.0.3)-1%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(5.0.3): 1 commits behind master](https://img.shields.io/badge/ViaBackwards%20(5.0.3)-1%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/).In case the issue still persists send the new dump and the issue will be reopened</h3>

**Comment by xProMDFKx** [comment]
The versions are updated...

Same dump: https://dump.viaversion.com/483840ca39aab4a180c42604860b8fb9f3458c6cb6009a6b3cda5aaa488dcf70

**Comment by Barvalg** [comment]
![Platform: 1.21--DEV--64094d4%20%28MC%3A%201.21%29](https://img.shields.io/badge/Platform-1.21--DEV--64094d4%20%28MC%3A%201.21%29-3498db?style=flat-square) </br>![ViaVersion (5.0.3): 1 commits behind master](https://img.shields.io/badge/ViaVersion%20(5.0.3)-1%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(5.0.3): 1 commits behind master](https://img.shields.io/badge/ViaBackwards%20(5.0.3)-1%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/).In case the issue still persists send the new dump and the issue will be reopened</h3>

**Comment by xProMDFKx** [comment]
https://dump.viaversion.com/483840ca39aab4a180c42604860b8fb9f3458c6cb6009a6b3cda5aaa488dcf70

**Comment by Barvalg** [comment]
![Platform: 1.21--DEV--64094d4%20%28MC%3A%201.21%29](https://img.shields.io/badge/Platform-1.21--DEV--64094d4%20%28MC%3A%201.21%29-3498db?style=flat-square) </br>![ViaVersion (5.0.3): 1 commits behind master](https://img.shields.io/badge/ViaVersion%20(5.0.3)-1%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(5.0.3): 1 commits behind master](https://img.shields.io/badge/ViaBackwards%20(5.0.3)-1%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/).In case the issue still persists send the new dump and the issue will be reopened</h3>

**Comment by xProMDFKx** [comment]
> This is visual only. Duplicate of #830

Yes, i know that, but is there any way to make it visually to be the same?

**Comment by xProMDFKx** [comment]
> This is visual only. Duplicate of #830 And please stop spamming the issue

Sorry for the spam, but it's not okay to already close that.. is still a issue.. the players don't know that is just visual
