### ISSUE TITLE
Phoenix Lobby Index 6 out of bounds for lenght 6

### ISSUE THREAD

**Issue by KalviPL** [ViaVersion/ViaBackwards#862]
### '/viaversion dump' Output

https://dump.viaversion.com/8592b71b227096fcef621c6d4da868d7f60497d4317a91ca2041eba377ec00db

### Console Error

None

### Bug Description

I use plugin Phoenix Lobby

This error pops up when placing an NPC
A Model to Huge Items
I can't re-enter the server
The console displays nothing

I received a reply from Phoenix Lobby that the fault lies with the ViaBackwards plugin

![image](https://github.com/user-attachments/assets/6ff84c19-515c-472e-aff8-37c8d24abb14)

### Steps to Reproduce

1. I put NPC
2. Changing the model to HugeItem

### Expected Behavior

Not getting kicked off the server

### Additional Server Info

Server Version: 1.21

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. Velocity), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: 1.21--126--7e44684%20%28MC%3A%201.21%29](https://img.shields.io/badge/Platform-1.21--126--7e44684%20%28MC%3A%201.21%29-3498db?style=flat-square) </br>![ViaVersion: Outdated](https://img.shields.io/badge/ViaVersion%20(5.0.2)-Outdated!-red?style=flat-square) </br>![ViaRewind(4.0.2): 4 commits behind master](https://img.shields.io/badge/ViaRewind%20(4.0.2)-4%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards: Outdated](https://img.shields.io/badge/ViaBackwards%20(5.0.2)-Outdated!-red?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/).In case the issue still persists send the new dump and the issue will be reopened</h3>

**Comment by RaphiMC** [comment]
Still happens with latest dev builds: https://dump.viaversion.com/e563442bddade953ebe5954c05225d68de9dc35e97d9b5176ac6b11b5bb35862

https://discord.com/channels/316206679014244363/1112837970844721342/1284814294503915552

**Comment by Barvalg** [comment]
![Platform: 3.0.3--SNAPSHOT](https://img.shields.io/badge/Platform-3.0.3--SNAPSHOT-3498db?style=flat-square) </br>![ViaVersion (5.0.4-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(5.0.4--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaRewind(4.0.3-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaRewind%20(4.0.3--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(5.0.4-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(5.0.4--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by RaphiMC** [comment]
Game debug log: https://mclo.gs/Y45pLCH
