### ISSUE TITLE
Loading terrain for 30 seconds then player is bugged

### ISSUE THREAD

**Issue by boggymc** [ViaVersion/ViaBackwards#864]
### '/viaversion dump' Output

https://dump.viaversion.com/08d6f28b56e5b1a8f21d265f25f2188a384eab7039a05b7a072ac7314ec393ac

### Console Error

No console error

### Bug Description

Upon joining my folia 1.20.6 server on my 1.20.4 client, I occasionally get stuck on the "Loading Terrain" screen for around 30 seconds - this almost always happens when I join for the first time after a restart. Once I eventually log in, I cannot break blocks or place blocks, my second layer of my skin isn't visible and some entities seem to be invisible. When watching my account from a second account, my main does not move server side. If I disconnect and relog, the issue almost always goes away, although sometimes it persists and I need to relog multiple times. I have tested my same scenario but on a paper server, with just viaversion and viabackwards and the issue does not occur. The issue also doesn't occur when I join using a different version other than 1.20.4. I have also found that killing myself through console while I am in the loading terrain screen brings me out of it and allows me to play normally, without the issue. Attached below is a video showing the issue:
https://youtu.be/TfMxsD7noas

### Steps to Reproduce

1. Start a 1.20.6 folia server with ViaVersion + ViaBackwards
2. Connect using 1.20.4

### Expected Behavior

Loading screen will stay for around 30 seconds, and then blocks won't be able to be broken or placed. Many other things such as dropping items are messed up.

### Additional Server Info

No proxy

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. Velocity), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: 1.20.6--DEV--d797082%20%28MC%3A%201.20.6%29](https://img.shields.io/badge/Platform-1.20.6--DEV--d797082%20%28MC%3A%201.20.6%29-3498db?style=flat-square) </br>![ViaVersion (5.0.4-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(5.0.4--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(5.0.3): Even with master](https://img.shields.io/badge/ViaBackwards%20(5.0.3)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by kennytv** [comment]
Try without client mods, often Sodium causes this in combination with Paper servers (if not, we'll reopen)
