### ISSUE TITLE
Wind Charge has Gravity

### ISSUE THREAD

**Issue by HerobaneNair** [ViaVersion/ViaBackwards#868]
### '/viaversion dump' Output

https://dump.viaversion.com/797007bf9676d85f9956cc2fb556d4fe32844620de43f87230b4d8a2a90cc266

### Console Error

Please ignore the console error and viaversion dump, I just took one from my server. It doesn't have much related to the bug.

### Bug Description

Viabackward’s wind charge turns into a llama spit and would be cool except the llama spit has gravity while the wind charge doesn’t. Could you make it so the clients that are previous to 1.21 have the llama spit have a no gravity tag as true. 

Why would this be needed
For PvP reasons. I made a pack using cem that changes the llama spit to a wind charge so I can better see it, but the wind charge still has gravity even though it shouldn’t. 

https://youtu.be/pExUj9hdIKg

If youtube link isn't working:
https://discord.com/channels/316206679014244363/316218802155028482/1273536577561301014

### Steps to Reproduce

1. Log on with a client with 1.20.1 on a server that is 1.21
2. Use a wind charge
3. Observe Llama Spit (wind charge replacement) fall then teleport back up

### Expected Behavior

Wind charge should fly straight rather than going down

### Additional Server Info

Happens on all servers with via backwards updated to 1.21

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. Velocity), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: 1.21--DEV--a62044c%20%28MC%3A%201.21%29](https://img.shields.io/badge/Platform-1.21--DEV--a62044c%20%28MC%3A%201.21%29-3498db?style=flat-square) </br>![ViaVersion: Outdated](https://img.shields.io/badge/ViaVersion%20(5.0.1)-Outdated!-red?style=flat-square) </br>![ViaBackwards: Outdated](https://img.shields.io/badge/ViaBackwards%20(5.0.1)-Outdated!-red?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/).In case the issue still persists send the new dump and the issue will be reopened</h3>
