### ISSUE TITLE
Not block Tab-Complete - 1.12.2 and lower client

### ISSUE THREAD

**Issue by Guest1131** [ViaVersion/ViaBackwards#87]
Hi, I noticed that there is a problem, it does not block the tab-complete, I disabled in spigot.yml the tab-complete, but it works the same on client 1.12.2 and lower.

And locked only with the 1.13x client

What about a blockrewards problem?

I use server 1.13.2

**Comment by KennyTV** [comment]
Pretty sure that this is down to how the 1.13 server handles tabcompletes (and that even a modified 1.13 client can get the list by sending a request packet)... An extra plugin listening for/cancelling the tabcomplete event should do the trick
