### ISSUE TITLE
Failed to decode packet 'clientbound/minecraft:player_combat_kill

### ISSUE THREAD

**Issue by clivet268** [ViaVersion/ViaBackwards#870]
### '/viaversion dump' Output

https://dump.viaversion.com/2eaac1f1a108a1058a4a50849c9675eb477a920040bb09dfaede97a790af5ec7

### Bug Description

On versions 1.20.5 and 1.20.6 when the player is killed by an entity wielding a named item that also has an attribbute modiffier not found until the 1.21 update the player will be kicked with the message: 
Internal Exception: io.netty.handler.codec.DecoderException: Failed to decode packet 'clientbound/minecraft:player_combat_kill'

### Steps to Reproduce

1. Summon a mob that has the specified weapon (You will need a command block since the command is long) 
For example: /summon skeleton ~ ~ ~ {HandItems:[{id:netherite_sword,components:{custom_name:'["",{"text":"NamedItem","italic":false}]',attribute_modifiers:{modifiers:[{type:"generic.oxygen_bonus",amount:4,operation:add_value,id:1723900671949}]}},count:1}],HandDropChances:[0f]}
2. Be killed by that mob
3. Get kicked from server with the above message

### Expected Behavior

You should die, the difference in attributes between version should get handled and you don't get kicked

### Additional Server Info

I am running purpur-1.21.1-2287.jar, ViaVersion-5.0.3.jar, and ViaBackwards-5.0.3.jar

After trying out the latest dev build (ViaVersion-5.0.4-SNAPSHOT.jar, and ViaBackwards-5.0.4-SNAPSHOT.jar) the issue persists

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. Velocity), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: 1.21.1--2287--07979c3%20%28MC%3A%201.21.1%29](https://img.shields.io/badge/Platform-1.21.1--2287--07979c3%20%28MC%3A%201.21.1%29-3498db?style=flat-square) </br>![ViaVersion (5.0.4-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(5.0.4--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(5.0.4-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(5.0.4--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by kennytv** [comment]
Fixed in https://github.com/ViaVersion/ViaBackwards/commit/a5d0e4baff02aad696cd5ee724d3d042263df073
