### ISSUE TITLE
Raw custom enchantment name in lore (1.20.6 and below) (using EcoEnchants)

### ISSUE THREAD

**Issue by alexcastro1919** [ViaVersion/ViaBackwards#875]
### '/viaversion dump' Output

https://dump.viaversion.com/6fbc356418daa1394f8aef8562655bbd2a4ab28d2b790f998ce5f3a7f6c65ad5

### Bug Description

If client on 1.20.6 or lower, the lore of a custom enchantment shows the raw enchantment name.
![image](https://github.com/user-attachments/assets/822fdb9e-033b-4b02-8db3-1246bdc9184f)

If client on 1.21 or higher, the lore shows fine.
![image](https://github.com/user-attachments/assets/73260490-214f-4d63-9db9-9843e74201c8)

### Steps to Reproduce

1. Create a custom enchantment (I tried with EcoEnchants)
2. Login with 1.20.6 or lower.
3. Check the lore of an item with the custom enhantment.

### Expected Behavior

This lore:
![image](https://github.com/user-attachments/assets/2ad185f3-6b81-4470-80bd-3f139a9354ad)

### Additional Server Info

I use pufferfish 1.21.1 (it also happens with paper 1.21)

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. Velocity), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: 1.21.1--11--9a82b86%20%28MC%3A%201.21.1%29](https://img.shields.io/badge/Platform-1.21.1--11--9a82b86%20%28MC%3A%201.21.1%29-3498db?style=flat-square) </br>![ViaVersion (5.0.4-SNAPSHOT): 2 commits behind master](https://img.shields.io/badge/ViaVersion%20(5.0.4--SNAPSHOT)-2%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(5.0.4-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(5.0.4--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/).In case the issue still persists send the new dump and the issue will be reopened</h3>

**Comment by alexcastro1919** [comment]
I'm using the last dev build (from 13 minutes ago)

**Comment by LumineStd** [comment]
This is still a problem, running with the latest version of Vias
