### ISSUE TITLE
EcoEnchants - Raw custom enchantment name in lore (1.20.6 and below)

### ISSUE THREAD

**Issue by LumineStd** [ViaVersion/ViaBackwards#877]
### '/viaversion dump' Output

https://dump.viaversion.com/d7ae075556c16f04ba7063d06ea370e9efc35fce2ff405cfaed128fa5aaccea0

### Console Error

_No error_

### Bug Description

This problem had already been reported previously and the fix did not fix it, even in the latest version the problem continues.

If client on 1.20.6 or lower, the lore of a custom enchantment shows the raw enchantment name.
![image](https://github.com/user-attachments/assets/afd66eae-b4fb-4cb0-b3dc-872dc82a5e4a)

If client on 1.21 or higher, the lore shows fine.
![image](https://github.com/user-attachments/assets/b9325611-0719-4251-a51d-dc559f7c3265)

### Steps to Reproduce

Create a custom enchantment (I tried with EcoEnchants)
Login with 1.20.6 or lower.
Check the lore of an item with the custom enhantment.

### Expected Behavior

This lore in versions lower than 1.21 where the problem is:
![image](https://github.com/user-attachments/assets/a82ba8ef-cbf4-4f43-acb5-c3e516b33820)

### Additional Server Info

Pufferfish 1.21

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. Velocity), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: 1.21--6--bdb56f1%20%28MC%3A%201.21%29](https://img.shields.io/badge/Platform-1.21--6--bdb56f1%20%28MC%3A%201.21%29-3498db?style=flat-square) </br>![ViaVersion (5.0.4-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(5.0.4--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(5.0.4-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(5.0.4--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>
