### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by Envarad** [ViaVersion/ViaBackwards#880]
### '/viaversion dump' Output

https://dump.viaversion.com/

### Console Error

```
Put the mclo.gs link or text here.
```
https://mclo.gs/IPHoKHZ

### Bug Description

connecting to a 1.21 server did not work and bugged out my mc

### Steps to Reproduce

login with client, try to connect to hoplite

### Expected Behavior

Should be able to connect

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. Velocity), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Error: Invalid or missing dump](https://img.shields.io/badge/Error-Invalid/missing%20dump-red?style=flat-square) </br>
