### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by Eneskanmaz** [ViaVersion/ViaBackwards#881]
### '/viaversion dump' Output

https://dump.viaversion.com/30943f1837c40dce3624d5cdadf2a234b543001b6178ea0abb3b7fb12f6d2c01

### Console Error

https://mclo.gs/URzRStU

### Bug Description

when i join a match in mccisland it gives me an error

### Steps to Reproduce

1. Login with 1.16.5 forge
2. go to play.mccisland.net
3. join a match like sky battles

### Expected Behavior

when you join the match it gives a error like this
![2024-09-08_01-04-56](https://github.com/user-attachments/assets/f2854793-2056-4394-889d-178ae0c8779f)

### Additional Server Info

i dont use any vpn or anything i use viaproxy

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. Velocity), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: 3.0.3--SNAPSHOT](https://img.shields.io/badge/Platform-3.0.3--SNAPSHOT-3498db?style=flat-square) </br>![ViaVersion (5.0.4-SNAPSHOT): 2 commits behind master](https://img.shields.io/badge/ViaVersion%20(5.0.4--SNAPSHOT)-2%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaRewind(4.0.3-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaRewind%20(4.0.3--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(5.0.4-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(5.0.4--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/).<b>Put the jars into config/viafabricplus/jars.<br>In case the issue still persists send the new dump and the issue will be reopened</h3>

**Comment by Eneskanmaz** [comment]
oh also i made 1.21-1.21.1 to join mccisland

**Comment by Eneskanmaz** [comment]
i reported the issue to viaversion discord and they told me to its viabackwards issue they said to me to report here and issue persists
