### ISSUE TITLE
MC 1.21

### ISSUE THREAD

**Issue by Saulencijus10** [ViaVersion/ViaBackwards#894]
### '/viaversion dump' Output

its not an error or a big dumb it doesnt whow there

### Console Error

```
Put the mclo.gs link or text here.
```
no error

### Bug Description

So its nothing bad but `"max-level": 1,` when enchancement put on item returns `Enchancement-name 1`

### Steps to Reproduce

login intoserver with 1.20.4 and check custom enchancements from 1.21with max level 1

### Expected Behavior

when `max-level": 1,` it shold return `Enchancement-name`

### Additional Server Info

i use paper with 1 datapack and 31 plugin:
datapack: [ce-v1.1.7.zip](https://github.com/user-attachments/files/17321714/ce-v1.1.7.zip)

plugins: Bukkit Plugins: - ArmorStandTools, AuctionHouse, AutoCraft, ChestShop, DecentHolograms, DimensionPause, Essentials, EssentialsChat, EssentialsDiscord, EssentialsDiscordLink, EssentialsSpawn, ExcellentCrates, floodgate, FreedomChat, Geyser-Spigot, GriefPrevention, *HopperPipes, LockettePro, LuckPerms, nightcore, ProtocolLib, SuperVanish, TAB, TextDisplay, UltimateAutoRestart, Vault, ViaBackwards, ViaVersion, voicechat, WorldEdit, WorldGuard

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. Velocity), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Error: Invalid or missing dump](https://img.shields.io/badge/Error-Invalid/missing%20dump-red?style=flat-square) </br>

**Comment by FlorianMichael** [comment]
Fill out the issue form correctly and provide the viaversion dump as requested
