### ISSUE TITLE
Clearing tags for items from 1.20< on 1.21 server core 

### ISSUE THREAD

**Issue by zingeer** [ViaVersion/ViaBackwards#897]
### '/viaversion dump' Output

https://dump.viaversion.com/3ce17746af8a0b174be9d5bd57dd8697308f740a2fcfe5627bb6cc15ae443993

### Console Error

```
Put the mclo.gs link or text here.
```

### Bug Description

I have 1.20 client with creative, which has in saved items item with custom not-vanilla nbt. My server on 1.21.1 with viabackwards, and when I claim item from saved menu -> it removes all custom tags (tested using /data get, means that in serverside), but expected to save them and move them to "custom_data" component. Server & client 1.20 works fine, server & client 1.21 works fine, but when client version below server version, this problem appears.

### Steps to Reproduce

1. Log in to the server with core version 1.20 and save the item with the tag in the creative. (Client version  1.20)
2. Join the 1.21 server from the 1.20 client and take an item from the saved items menu.
3. Check the item and notice that the tag has not been converted to the custom_data section.

### Expected Behavior

item contains tag

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. Velocity), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: velocity%203.4.0--SNAPSHOT%20%28git--99aaf3ce--b439%29](https://img.shields.io/badge/Platform-velocity%203.4.0--SNAPSHOT%20%28git--99aaf3ce--b439%29-3498db?style=flat-square) </br>![ViaVersion (5.0.5): Even with master](https://img.shields.io/badge/ViaVersion%20(5.0.5)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(5.0.4): Even with master](https://img.shields.io/badge/ViaBackwards%20(5.0.4)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by kennytv** [comment]
Cannot reproduce

**Comment by kennytv** [comment]
This is going to be a wont-fix I think, we cannot reasonably filter what is and isn't actually custom and data and will otherwise create a mess of an item

**Comment by zingeer** [comment]
1.21 server and 1.20 client
![image](https://github.com/user-attachments/assets/f025cd35-8aad-4604-a259-93d4070b8c06)
1.20 server and 1.20 client
![image](https://github.com/user-attachments/assets/fc32478f-339c-44e7-8d0d-ec4c8cf35bb5)
1.21 server and 1.21 client
![image](https://github.com/user-attachments/assets/dfdbd92a-12a7-4263-a5cf-02668d12e91e)

Why is it impossible to convert a complete item using conversion from mojang?
