### ISSUE TITLE
1.21.2/3 WinterDrop Issues

### ISSUE THREAD

**Issue by fantahund** [ViaVersion/ViaBackwards#904]
### '/viaversion dump' Output

https://dump.viaversion.com/f4d913c912096e678bcd2a39b8aec35b7c4610ae090e844bdb855011ccc47ec7

### Console Error

```
Issue 1 Server Log: https://mclo.gs/gT7kaFK
Issue 2 Client Log: https://mclo.gs/AHjECeI
```

### Bug Description

Issue 1: Missing blockstate mappings for palegarden blocks

Issue 2: Network Error when Creaking is Spawning

### Steps to Reproduce

1. Use 1.21.3 Server
2. enable winter_drop in server.properties
3. Join with a 1.21.0/1 Client
4. Go to a Pale Garden Biome

### Expected Behavior

Issue 1:
The Consolle spams some errors into the console that blockstats from version 1.21 -> 1.21.2 are missing. See log 1 above

Issue 2:
If a Creaking spawns you will be kicked from the server with a DIsplayEntity error from the server see log 2 above.

### Additional Server Info

I use a current paper server without a proxy server. Installed plugins are only ViaVersion and ViaBackwards in the latest version.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. Velocity), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: 1.21.3--30--1196ab5%20%28MC%3A%201.21.3%29](https://img.shields.io/badge/Platform-1.21.3--30--1196ab5%20%28MC%3A%201.21.3%29-3498db?style=flat-square) </br>![ViaVersion (5.1.1-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(5.1.1--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(5.1.1-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(5.1.1--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>
