### ISSUE TITLE
Minecarts dont move with experimental datapack on

### ISSUE THREAD

**Issue by EreoGaming** [ViaVersion/ViaBackwards#911]
### '/viaversion dump' Output

https://dump.viaversion.com/9ede23ac718bc06035a9a8ded9ccb0d63afae7747046f58c3df9d6dbac242b7a

### Console Error

```
Put the mclo.gs link or text here.
```

### Bug Description

New Minecart Improvement experiment doesn't work on older versions

### Steps to Reproduce

1. Login on a 1.21.1 Client
2. Have 1.21.3 world have minecart improvements datapack on
3. Place minecart with track and try to use it
4. hop out and your in a different area

### Expected Behavior

Minecart should visibly move.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. Velocity), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: 0.4.16+88--main](https://img.shields.io/badge/Platform-0.4.16+88--main-3498db?style=flat-square) </br>![ViaVersion (5.1.1): 8 commits behind master](https://img.shields.io/badge/ViaVersion%20(5.1.1)-8%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(5.1.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(5.1.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/).<br>Put the jars into the mod folder.<br>In case the issue still persists send the new dump and the issue will be reopened</h3>

**Comment by EreoGaming** [comment]
Why it label it wrong

**Comment by kennytv** [comment]
Known, this will likely only be implemented once this feature is closer to completion

**Comment by EreoGaming** [comment]
dang.
