### ISSUE TITLE
ItemDisplays incorrect[1.20.4 -> 1.20.1]

### ISSUE THREAD

**Issue by belnek** [ViaVersion/ViaBackwards#914]
### '/viaversion dump' Output

https://dump.viaversion.com/9e3acf8dff2a17284bdc1030c9f10531f97352f4294a6b2b221036b71561f4d6

### Bug Description

Item Displays not showing, when player join without optifine with any version

### Steps to Reproduce

1. Login a 1.20.4 Client and spawn ItemDisplay
2. ItemDisplay not showing

### Expected Behavior

ItemDisplays show on any client version, if supported

### Additional Server Info

Paper 1.20.4
ViaVersion 5.1.1
ViaBackwards 5.1.1

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. Velocity), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Purpur--%226b1ee98%22%20%28MC%3A%201.20.4%29](https://img.shields.io/badge/Platform-git--Purpur--%226b1ee98%22%20%28MC%3A%201.20.4%29-3498db?style=flat-square) </br>![ViaVersion (5.1.1): 11 commits behind master](https://img.shields.io/badge/ViaVersion%20(5.1.1)-11%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(5.1.1): 5 commits behind master](https://img.shields.io/badge/ViaBackwards%20(5.1.1)-5%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/).In case the issue still persists send the new dump and the issue will be reopened</h3>
