### ISSUE TITLE
ViaBackwards TextDisplay support.

### ISSUE THREAD

**Issue by 2how** [ViaVersion/ViaBackwards#921]
### Problem Description

When there is a TextDisplay with multiple lines (\n) In older versions, ViaBackwards display them as a 1 line hologram. Breaking them.

### Solution Description

Translate TextDisplays with multiple lines into multiple holograms. One hologram per line.

**Comment by kennytv** [comment]
Duplicate of https://github.com/ViaVersion/ViaBackwards/issues/767
