### ISSUE TITLE
Entity Teleport Packets of Other Entities Affects the Player for 1.21 Players on 1.21.3 Server

### ISSUE THREAD

**Issue by LOOHP** [ViaVersion/ViaBackwards#922]
### '/viaversion dump' Output

https://dump.viaversion.com/c759cb88f84a3ff2f6b7de7c63745d11883312c0b4597c460a114760b491f836

### Console Error

```
N/A
```

### Bug Description

Entity teleport packets on 1.21.3 **of other entities** cause the player's own velocity to be affected if they are on a 1.21 client.

### Steps to Reproduce

1. Setup a 1.21.3 server
2. Create something that constantly sends an entity teleport packet of something else. For example, a plugin constantly teleports an entity via a PacketPlayOutEntityTeleport packet.
3. Join the server on 1.21.
4. Your movement and velocity would be affected.

### Expected Behavior

Behaves in the same way as 1.21.3, players' movement should be normal.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. Velocity), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: 1.21.3--63--4190ee7%20%28MC%3A%201.21.3%29](https://img.shields.io/badge/Platform-1.21.3--63--4190ee7%20%28MC%3A%201.21.3%29-3498db?style=flat-square) </br>![ViaVersion (5.1.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(5.1.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(5.1.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(5.1.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by kennytv** [comment]
Can you provide a code example with normal (non Spigot) mappings or API?

**Comment by danieliustt** [comment]
Kenny, please fix problems with holograms freezing. https://github.com/ViaVersion/ViaBackwards/issues/916 :)

**Comment by LOOHP** [comment]
Confirm it is fixed. Thank you!

> Can you provide a code example with normal (non Spigot) mappings or API?

Just FYI, it could be reproduced like this.
```java
Bukkit.getScheduler().runTaskTimer(this, () -> {
    ClientboundTeleportEntityPacket packet = new ClientboundTeleportEntityPacket(11231231, new PositionMoveRotation(Vec3.ZERO, Vec3.ZERO, 0.0F, 0.0F), Collections.emptySet(), false);
    Iterator var1 = Bukkit.getOnlinePlayers().iterator();
    for (Player player : Bukkit.getOnlinePlayers()) {
        ((CraftPlayer) player).getHandle().f.sendPacket(packet);
    }
}, 0L, 1L);
```
