### ISSUE TITLE
Can't work on Folia 1.21.3

### ISSUE THREAD

**Issue by Leleawa** [ViaVersion/ViaBackwards#923]
### '/viaversion dump' Output

https://dump.viaversion.com/42fb5cce6112fb84548b4100bd67901a19e569251cc5a11adfde96b962d88cba

### Console Error

https://api.mclo.gs/1/raw/iJ1gTW7

### Bug Description

runTaskTimer is not supported in Folia

### Steps to Reproduce

1.Use Folia 1.21.3
2.Install ViaVersion v5.1.1 and ViaBackwards v5.1.1 plugins.
3.Start the server

### Expected Behavior

Works fine on Folia 1.21.3

### Checklist

- [x] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. Velocity), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: 1.21.3--DEV--c937c72%20%28MC%3A%201.21.3%29](https://img.shields.io/badge/Platform-1.21.3--DEV--c937c72%20%28MC%3A%201.21.3%29-3498db?style=flat-square) </br>![ViaVersion (5.1.1): 32 commits behind master](https://img.shields.io/badge/ViaVersion%20(5.1.1)-32%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(5.1.1): 17 commits behind master](https://img.shields.io/badge/ViaBackwards%20(5.1.1)-17%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/).In case the issue still persists send the new dump and the issue will be reopened</h3>

**Comment by Barvalg** [comment]
![Platform: 1.21.3--DEV--c937c72%20%28MC%3A%201.21.3%29](https://img.shields.io/badge/Platform-1.21.3--DEV--c937c72%20%28MC%3A%201.21.3%29-3498db?style=flat-square) </br>![ViaVersion (5.1.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(5.1.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(5.1.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(5.1.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>
