### ISSUE TITLE
ViaBackwards throws error when connecting to a different server through velocity proxy

### ISSUE THREAD

**Issue by defautluser0** [ViaVersion/ViaBackwards#924]
### '/viaversion dump' Output

https://dump.viaversion.com/f27014d58c94fabb384fbce719b8ec960b5aad40f3f54a0c7c056abdf709a54d

### Console Error

```
https://mclo.gs/a6mtHxE
```

### Bug Description

Connecting to a velocity proxy with viaversion and viabackwards installed and going to a different server on the proxy causes an error and going back to the default server.

### Steps to Reproduce

1. Log into the server with a version older than the survival and lobby servers
2. Run "/server survival" on the lobby
3. Get kicked back into the lobby
4. Console shows an error

### Expected Behavior

Not get kicked from the survival server

### Additional Server Info

Velocity with ViaVersion, ViaBackwards, ViaRewind, Geyser, Floodgate, UltimateAntiBot and ServerListPlus. Both the lobby and survival servers are running paper 1.21.3.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. Velocity), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: velocity%203.4.0--SNAPSHOT%20%28git--9cfcfcf2--b451%29](https://img.shields.io/badge/Platform-velocity%203.4.0--SNAPSHOT%20%28git--9cfcfcf2--b451%29-3498db?style=flat-square) </br>![Proxy is 1 builds behind](https://img.shields.io/badge/Your%20proxy%20is%201%20build(s)%20behind.%20Please%20update%20to%20the%20latest%20version-orange?style=flat-square) </br>![ViaVersion (5.1.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(5.1.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaRewind(4.0.4-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaRewind%20(4.0.4--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(5.1.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(5.1.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by defautluser0** [comment]
that did not fix the issue, i am still getting the same error

**Comment by Kichura** [comment]
Does the problem continue when moving the via* plugins from velocity -> spigot/paper instead?

*(also nice pfp lol)*

**Comment by defautluser0** [comment]
> Does the problem continue when moving the via* plugins from velocity -> spigot/paper instead?
> 
> _(also nice pfp lol)_

yeah, it keeps happening

_(thx, you too)_

**Comment by defautluser0** [comment]
wait ig this is the survival server's fault since this doesnt happen with lobby

**Comment by defautluser0** [comment]
the issue automatically fixed itself (wtf)
