### ISSUE TITLE
Network protocol error due to particle data type mismatch between 1.21.1 and 1.21.2-3

### ISSUE THREAD

**Issue by takatalvi** [ViaVersion/ViaBackwards#926]
### '/viaversion dump' Output

https://dump.viaversion.com/8f28639316af1ebf96929317739557d6d043b59c3ac173ec105aac1d92557804

### Console Error

```
this is the 1.21.3 server log: https://pastebin.com/urSErGvM
this is the 1.21.1 client log when trying to connect: https://pastebin.com/XrJWFzH6
this is the network protocol error report from the same event: https://pastebin.com/DXLza99h
```

### Bug Description

Connecting from an older client to a 1.21.3 server which uses datapacks with biome particles fails with a network protocol error due to a change in particle color data type from int list to packed int.

### Steps to Reproduce

1. Start a clean installation of a 1.21.3 server (Paper)
2. Install only ViaVersion and ViaBackwards plugins
3. Install a datapack which uses biome particles (e.g. Incendium)
4. Connect to the server using an older client (e.g. 1.21.1)
5. The connection fails with network protocol error due to a client-bound packet issue

### Expected Behavior

The connection should succeed.

### Additional Server Info

Hello, I've opened this issue after a discussion with the developer of the Stardust Labs' Incendium datapack who identified a possible issue in handling of the int list data type on a 1.21.3 server, when a connection is attempted from an older client. This datapack uses custom biomes, with one biome having environment particles (like in vanilla basalt deltas). In the biome definition, the particle has a color value as int list. When the server sends this to the client, it appears that the 1.21.1 client can't process what ViaBackwards on 1.21.3 is sending and the connection fails. I believe that if VB translated this, it could fix the issue, possibly in other places too.

I'm attaching the info I received (with catter's permission):

> ok, here's what's going on. the actual issue is here - the client is looking for a list of ints, instead of just a single int. at face value, this looks clearly like a datapack issue. however, it's a bit more complicated
![1](https://github.com/user-attachments/assets/1f9d2606-41f7-4281-bc2c-875a531d3992)
![2](https://github.com/user-attachments/assets/293cd890-5ac0-46ff-8ddb-aa81eab71f3e)
> if you look at Incendium's code for that biome, it is clearly a list of ints. so why is it saying there's an int?
![3](https://github.com/user-attachments/assets/1fa5766e-770e-455b-9b51-38dc475965d4)
> in 1.21.2, there was a change made to a couple of particles. before, it accepted **only** a list of ints. but now it accepts the list or the compacted int
![4](https://github.com/user-attachments/assets/25590afd-fdab-44f3-b2f9-3da50f73900b)
> so, here's my theory. I do not know for sure, but my guess is that when Mojang made that change in 1.21.2, it was internally changed to deal with the compacted int. Accepting a list of ints was just the legacy option, so people weren't forced to change all their particle commands.
> Your server is in 1.21.3. that means it has this change, and if my theory is correct, it translates that list into a compacted int for it to use. However, your client is on 1.21.1, where the compacted int is not an option. so when VB sends the data to the client about the biome, it doesn't know what to do with the compacted int, so it throws a fit and disconnects.
> The other possibility is that it isn't Mojang storing the data as a compacted int; instead VV/VB. but it actually doesn't matter who is "at fault". If my theory is correct, VV/VB needs to be the one to unpack the int back into a list when sending the data to older clients.
> This is vanilla behavior, but it never gets noticed in vanilla or most other worldgen datapacks. that's because it's uncommon to make use of biome particles (vanilla only really uses them in basalt deltas, and maybe a couple other places im forgetting), and even less common to use specifically the dust particle (or the other that have the same issue). so it is a niche issue
> Normally this is not an issue - viaversion is well aware of these changes. but most of the changes viaversion doesnt even have to worry about, since they're dealt with on the server only. the client couldnt care less about recipes. but in this specific scenario, the client does need to know what color particle to display in the biome. the color format changed, and viaversion is sending the old client the new format

For after removing the biome particle color values from the datapack, the connection works, so it really looks like the data type mismatch is causing this. Thank you for your time reading this!

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. Velocity), **not on both**.
- [X] I have included a ViaVersion dump.
- [x] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: 1.21.3--81--da71382%20%28MC%3A%201.21.3%29](https://img.shields.io/badge/Platform-1.21.3--81--da71382%20%28MC%3A%201.21.3%29-3498db?style=flat-square) </br>![ViaVersion (5.1.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(5.1.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(5.1.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(5.1.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by cupang-afk** [comment]
upvote on this

i try on fresh 1.21.3 server which has Terralith datapack version [2.5.7](https://modrinth.com/datapack/terralith/version/2.5.7)

have ViaVersion 5.1.1 and ViaBackwards 5.1.1 on the server as well

```log
> pl
[20:54:30 INFO]: Paper Plugins: (0):
[20:54:30 INFO]: Bukkit Plugins: (2):
[20:54:30 INFO]:  - ViaBackwards, ViaVersion
```

i try different version of vanilla client from 1.21.3 until 1.19.4 to login to the server

version 1.21.1, 1.21, 1.20.6, 1.20.5 got this Network protocol error

here is the client log
1.21.1 https://mclo.gs/5OvQtbT
1.21 https://mclo.gs/Fxvsht4
1.20.6 https://mclo.gs/0emgdPT
1.20.5 https://mclo.gs/CAfqQnM

the rest login just fine

here is the `/viaversion dump` 
https://dump.viaversion.com/15f60f16a33af6b4038154735fa0f0dfad6fae148883d76bc57e206153634b07

also i have tried ViaVersion and ViaBackwards from https://ci.viaversion.com/ problem still there

**Comment by Barvalg** [comment]
![Platform: 1.21.3--2355--de20ba9%20%28MC%3A%201.21.3%29](https://img.shields.io/badge/Platform-1.21.3--2355--de20ba9%20%28MC%3A%201.21.3%29-3498db?style=flat-square) </br>![ViaVersion (5.1.1): 34 commits behind master](https://img.shields.io/badge/ViaVersion%20(5.1.1)-34%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(5.1.1): 17 commits behind master](https://img.shields.io/badge/ViaBackwards%20(5.1.1)-17%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/).In case the issue still persists send the new dump </h3>

**Comment by takatalvi** [comment]
Thank you for the quick fix and for all your great work!

**Comment by kennytv** [comment]
Thank you for the detailed report 😎
