### ISSUE TITLE
A client using debug stick will disconnect older clients

### ISSUE THREAD

**Issue by Athar42** [ViaVersion/ViaBackwards#927]
### '/viaversion dump' Output

https://dump.viaversion.com/f3c097ee0cdb8495640af019ad49b8813cf9220ae847aa70b880ea6504bedb65

### Console Error

```
No error in server log
```

### Bug Description

On a PaperMC server, version 1.21.3, if you take in your hand a debug stick, any client lower or above than 1.21.2/3 will be forced disconnected :
If other connected clients are 1.21/.1 or 1.21.4 : 
![image](https://github.com/user-attachments/assets/c780e3a0-cd57-46c4-a603-7f0252b90e1d)

Now, if you try to connect to the account with the debug stick in its inventory, it will drop the connection a few second after the server is joined : 
![image](https://github.com/user-attachments/assets/09d18760-8d62-48d3-b503-dd6fd39e82ed)

### Steps to Reproduce

- Use a PaperMC server version 1.21.3
- Connect with a first client in 1.21.2/3 and give yourself a debug stick
- Connect a second client in 1.21/.1/.4 and if will be disconnected if near enough of the player that have the debug stick in hand.

For the second part of the test, just disconnected the initial client and use a lower or upper version with the account that hold the debug stick, connection will be dropped.

### Expected Behavior

Client shouldn't be disconnected and debug stick would work normaly.

### Additional Server Info

Those Paper servers are behind a velocity proxy (3.4.0-SNAPSHOT-454, but Via* are only on backends side).

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. Velocity), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: 1.21.3--80--c2294d7%20%28MC%3A%201.21.3%29](https://img.shields.io/badge/Platform-1.21.3--80--c2294d7%20%28MC%3A%201.21.3%29-3498db?style=flat-square) </br>![ViaVersion (5.2.0): 3 commits behind master](https://img.shields.io/badge/ViaVersion%20(5.2.0)-3%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(5.2.0): Even with master](https://img.shields.io/badge/ViaBackwards%20(5.2.0)-Even%20with%20master-brightgreen?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/).In case the issue still persists send the new dump and the issue will be reopened</h3>

**Comment by Athar42** [comment]
Persist with latest dev build : 
https://dump.viaversion.com/f3c097ee0cdb8495640af019ad49b8813cf9220ae847aa70b880ea6504bedb65

**Comment by Barvalg** [comment]
![Platform: 1.21.3--80--c2294d7%20%28MC%3A%201.21.3%29](https://img.shields.io/badge/Platform-1.21.3--80--c2294d7%20%28MC%3A%201.21.3%29-3498db?style=flat-square) </br>![ViaVersion (5.2.1-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(5.2.1--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(5.2.0): Even with master](https://img.shields.io/badge/ViaBackwards%20(5.2.0)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by kennytv** [comment]
This definitely does not happen by just giving yourself a debug stick, presumably you specifically have a block state from a creaking heart in there

**Comment by kennytv** [comment]
This definitely does not happen by just giving yourself a debug stick, presumably you specifically have a block state of a creaking heart stored on there

**Comment by Athar42** [comment]
Hum... indeed, I just redo the test on our lobby server, no disconnection.

As the server is still in 1.21.3, there shouldn't be any creaking/pale stuff, don't know how I'll tackle this down, but thanks for the info (I think we can close this so).
