### ISSUE TITLE
New items in registry causing disconnect 1.21.3 (Server) to 1.21.1 (Client)

### ISSUE THREAD

**Issue by nicolube** [ViaVersion/ViaBackwards#928]
### '/viaversion dump' Output

https://dump.viaversion.com/b1fe15cf53441b061b34c7ca6d24318a40195d585c3f2ede47266caaae59f9a9

### Console Error

Not an console error but a client error
```
https://mclo.gs/UhM81g7
```

### Bug Description

When joining a server with custom enchants, the client dissconnects with `Network Protocol Error`

We have custom enchants, created as descriped in:
https://docs.papermc.io/paper/dev/registries

Worked just fine with 1.21.1 (Ser ver) -> 1.21.3 (Client)
But now we want to go to 1.21.3 and backward translation seems not to work quite corrently.
1.21.3 -> 1.21.3 also works just fine.

### Steps to Reproduce

1. Setup 2 1.21.3 Server with an velocity proxy in front of it. (Lobby no plugins other Server with custom enchants)
2. Add ViaVersions / Viabackwards to all client-servers (not velcoity)
3. Join Lobby with 1.21.1 and switch to server with custom enchants

### Expected Behavior

Well. that the client does not disconnct....

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. Velocity), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: 1.21.3--81--da71382%20%28MC%3A%201.21.3%29](https://img.shields.io/badge/Platform-1.21.3--81--da71382%20%28MC%3A%201.21.3%29-3498db?style=flat-square) </br>![ViaVersion (5.2.1-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(5.2.1--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(5.2.0): Even with master](https://img.shields.io/badge/ViaBackwards%20(5.2.0)-Even%20with%20master-brightgreen?style=flat-square) </br>
