### ISSUE TITLE
When I enter PaperMC of 1.21.3 with ScreamingBedwars 0.2.36 with 1.19.2 or lower version, I get an error when starting Bedwars.

### ISSUE THREAD

**Issue by YOMA8338** [ViaVersion/ViaBackwards#929]
### '/viaversion dump' Output

https://dump.viaversion.com/338a25e8bd8368ab218cd4b5526c5a7485cf362376e4fc8abecda5482f6c0b8a

### Console Error

```
[Put the mclo.gs link or text here.](https://mclo.gs/PMtHJlr)
```

### Bug Description

It could be a problem with ScreamingBedwarsPlugin, but 1.21.4~1.19.3 had no problem, so I thought it was ViaBackwards.
If I join a 1.21.3 Paper server with ScreamingBedwarsPlugin, Viaversion, Viabackwards, and ViaRewind in it, with 1.19.2 or lower versions, I get an error the moment Bedwars starts.
I have included the client side logs in the console error location.

### Steps to Reproduce

1. Start Paper1.21.3 with ScreamingBedwarsPlugin, ScreamingBedwarsAddon, ViaVersion, ViaBackwards, ViaRewind
2. Start and join Mycla with 1.19.2.
3. Join and start the Bedwars stage.
4.Internal Exception: io.netty.handler.codec.DecoderException: java.lang.IndexOutOfBoundsException: Index 120 out of bounds for length 108 error and disconnected.

### Expected Behavior

No disconnection.

### Additional Server Info

This server is running Paper version 1.21.3-81-master@da71382 (2024-12-03T14:58:13Z) (Implementing API version 1.21.3-R0.1-SNAPSHOT)
You are running the latest version
Previous version: 1.21.3-2356-03062a8 (MC: 1.21.3)

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. Velocity), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: 1.21.3--81--da71382%20%28MC%3A%201.21.3%29](https://img.shields.io/badge/Platform-1.21.3--81--da71382%20%28MC%3A%201.21.3%29-3498db?style=flat-square) </br>![ViaVersion (5.2.0): 9 commits behind master](https://img.shields.io/badge/ViaVersion%20(5.2.0)-9%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaRewind(4.0.4): Even with master](https://img.shields.io/badge/ViaRewind%20(4.0.4)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(5.2.0): Even with master](https://img.shields.io/badge/ViaBackwards%20(5.2.0)-Even%20with%20master-brightgreen?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/).In case the issue still persists send the new dump and the issue will be reopened</h3>

**Comment by YOMA8338** [comment]
https://dump.viaversion.com/3f522763d3eb930bd624723fe22c501ddfdf6e8cedec457b1965c4db8238f53c

**Comment by Barvalg** [comment]
![Platform: 1.21.3--81--da71382%20%28MC%3A%201.21.3%29](https://img.shields.io/badge/Platform-1.21.3--81--da71382%20%28MC%3A%201.21.3%29-3498db?style=flat-square) </br>![ViaVersion (5.2.1-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(5.2.1--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaRewind(4.0.4): Even with master](https://img.shields.io/badge/ViaRewind%20(4.0.4)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(5.2.0): Even with master](https://img.shields.io/badge/ViaBackwards%20(5.2.0)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by FlorianMichael** [comment]
This seems to be the bedwards (or another) plugin intentionally sending wrong data (I suppose by using Via API and having per version behaviour). Please try without said plugins and if it works, report to the developers.
