### ISSUE TITLE
CustomModelData not handled by older clients

### ISSUE THREAD

**Issue by Boy0000** [ViaVersion/ViaBackwards#939]
### '/viaversion dump' Output

https://dump.viaversion.com/286b370dcdd43ddeea8b25d00f190d5b3c6e03d39b9a90d8441ca82305ecad92

### Server/Client Error

https://mclo.gs/xF1Seea

### Bug Description

Joining a 1.21.4 server on a 1.21.1 client (prob everything below 1.21.4) doesnt show CustomModelData properly
The component is not present on items for 1.21.1 clients, likely because CMD is now a float not integer on 1.21.4
![image](https://github.com/user-attachments/assets/e996d25e-e56b-456c-89eb-dd95c80b8993)
![image](https://github.com/user-attachments/assets/abeafb66-25aa-440c-9223-c93801d2d555)

### Steps to Reproduce

1. Join a 1.21.4 server on a 1.21.1 client
2. Get item with CusotmModelData
3. Observe no CustomModelData

### Expected Behavior

CustomModelData should be converted from float to int and shown

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. Velocity), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: 1.21.4--12--c17ef64%20%28MC%3A%201.21.4%29](https://img.shields.io/badge/Platform-1.21.4--12--c17ef64%20%28MC%3A%201.21.4%29-3498db?style=flat-square) </br>![ViaVersion (5.2.1-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(5.2.1--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(5.2.1-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(5.2.1--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>
