### ISSUE TITLE
1.21.1 on 1.21.3 server - Shift-clicking the "Destroy Item" slot in the creative inventory deletes the items server-side but not client-side, causing a desync

### ISSUE THREAD

**Issue by Oublions** [ViaVersion/ViaBackwards#940]
### '/viaversion dump' Output

https://dump.viaversion.com/c9ec4ce7b79c18c65975c9865833a744fe45d395b433bc372714d599c65a1c5e

### Server/Client Error

```
https://mclo.gs/Y46pDfb
```
I do not have any error but for reference, here we go!

### Bug Description

Literally the MC-276292 bug, but only on backwards versions. On the native server versions, its working nicely.

### Steps to Reproduce

- Have a 1.21.3 PaperMC server with ViaVersion and ViaBackwards latest.
- Connect in 1.21.1.
- Get in creative.
- Try to clear your inventory with shift-clicking the "Destroy Item" slot in the creative inventory.
- and tada! the inventory is cleared in server-side. Client-side, you still have your inventory.

### Expected Behavior

It should clears inventory.

### Additional Server Info

I use latest versions of every plugins I have.

My build was from Spigot and tried out your snapshot ViaVer build, same bug. Also, an additionnal error shows.

```
[23:08:16 ERROR]: [ViaVersion] Error initializing plugin 'ViaVersion-5.2.1-SNAPSHOT.jar' in folder 'plugins' (Is it up to date?)
java.lang.NoSuchFieldError: Class com.viaversion.viaversion.api.type.types.version.Types1_21_4 does not have member field 'com.viaversion.viaversion.api.minecraft.entitydata.types.EntityDataTypes1_21 ENTITY_DATA_TYPES'
        at ViaBackwards-5.2.0.jar/com.viaversion.viabackwards.protocol.v1_21_4to1_21_2.rewriter.EntityPacketRewriter1_21_4.<init>(EntityPacketRewriter1_21_4.java:43) ~[ViaBackwards-5.2.0.jar:?]
        at ViaBackwards-5.2.0.jar/com.viaversion.viabackwards.protocol.v1_21_4to1_21_2.Protocol1_21_4To1_21_2.<init>(Protocol1_21_4To1_21_2.java:58) ~[ViaBackwards-5.2.0.jar:?]
        at ViaBackwards-5.2.0.jar/com.viaversion.viabackwards.api.ViaBackwardsPlatform.init(ViaBackwardsPlatform.java:148) ~[ViaBackwards-5.2.0.jar:?]
        at ViaBackwards-5.2.0.jar/com.viaversion.viabackwards.BukkitPlugin.lambda$new$0(BukkitPlugin.java:38) ~[ViaBackwards-5.2.0.jar:?]
        at ViaVersion-5.2.1-SNAPSHOT.jar/com.viaversion.viaversion.ViaManagerImpl.init(ViaManagerImpl.java:115) ~[ViaVersion-5.2.1-SNAPSHOT.jar:?]
        at ViaVersion-5.2.1-SNAPSHOT.jar/com.viaversion.viaversion.ViaVersionPlugin.onLoad(ViaVersionPlugin.java:88) ~[ViaVersion-5.2.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:59) ~[paper-1.21.3.jar:1.21.3-81-da71382]
        at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:18) ~[paper-1.21.3.jar:1.21.3-81-da71382]
        at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:39) ~[paper-1.21.3.jar:1.21.3-81-da71382]
        at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:40) ~[paper-1.21.3.jar:1.21.3-81-da71382]
        at org.bukkit.craftbukkit.CraftServer.loadPlugins(CraftServer.java:561) ~[paper-1.21.3.jar:1.21.3-81-da71382]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:289) ~[paper-1.21.3.jar:1.21.3-81-da71382]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1235) ~[paper-1.21.3.jar:1.21.3-81-da71382]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:340) ~[paper-1.21.3.jar:1.21.3-81-da71382]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

Clip : https://imgur.com/a/rrqbXQU

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. Velocity), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: 1.21.3--81--da71382%20%28MC%3A%201.21.3%29](https://img.shields.io/badge/Platform-1.21.3--81--da71382%20%28MC%3A%201.21.3%29-3498db?style=flat-square) </br>![ViaVersion (5.2.0): 15 commits behind master](https://img.shields.io/badge/ViaVersion%20(5.2.0)-15%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(5.2.0): 8 commits behind master](https://img.shields.io/badge/ViaBackwards%20(5.2.0)-8%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/).In case the issue still persists send the new dump and the issue will be reopened</h3>

**Comment by Oublions** [comment]
Still the same shit ^^.

**Comment by Oublions** [comment]
Oh, automated shit ? Its updated you dumb idiot

**Comment by FlorianMichael** [comment]
Don't insult our bot, he is correct. Please update to dev builds from https://ci.viaversion.com/

**Comment by FlorianMichael** [comment]
Send a new dump url then

**Comment by Oublions** [comment]
I will redownload that build then. allow me a new 2 minutes.

**Comment by Oublions** [comment]
https://dump.viaversion.com/ad83e05bd6953a2db4c7e7568dc40090a3809557cc1749e789145b67b197e1f4

**Comment by Barvalg** [comment]
![Platform: 1.21.3--81--da71382%20%28MC%3A%201.21.3%29](https://img.shields.io/badge/Platform-1.21.3--81--da71382%20%28MC%3A%201.21.3%29-3498db?style=flat-square) </br>![ViaVersion (5.2.1-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(5.2.1--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(5.2.0): 8 commits behind master](https://img.shields.io/badge/ViaBackwards%20(5.2.0)-8%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/).In case the issue still persists send the new dump and the issue will be reopened</h3>

**Comment by Oublions** [comment]
Its updated 💀

**Comment by FlorianMichael** [comment]
You need to update ViaBackwards as well

**Comment by Oublions** [comment]
there is no build at https://ci.viaversion.com/

**Comment by FlorianMichael** [comment]
https://ci.viaversion.com/view/ViaBackwards/job/ViaBackwards/

**Comment by Oublions** [comment]
Still the same bug. https://dump.viaversion.com/84c30283a5ccd23ef313abb03eedf01812e2cb2d0564d7f4a62fa3e696235b54


And they should add ViaBackwards and ViaRewind on the homepage by the way of the jenkins website lol. It could save some time.

**Comment by Barvalg** [comment]
![Platform: 1.21.3--81--da71382%20%28MC%3A%201.21.3%29](https://img.shields.io/badge/Platform-1.21.3--81--da71382%20%28MC%3A%201.21.3%29-3498db?style=flat-square) </br>![ViaVersion (5.2.1-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(5.2.1--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(5.2.1-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(5.2.1--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by FlorianMichael** [comment]
There are, you just have to read.
<img width="578" alt="image" src="https://github.com/user-attachments/assets/8fe39967-da99-47af-9966-aeb81a740d39" />

I can't reproduce your issue when using the latest ci from both ViaVersion and ViaBackwards, so you either just uploaded a new dump without doing testing again or something else in your setup is wrong.

**Comment by Oublions** [comment]
> And they should add ViaBackwards and ViaRewind on the homepage by the way of the jenkins website lol. It could save some time.
Then i am sorry, it was not really easy to read, i meant viabackwards and viarewind writed like ViaVer Dev/Java8. As I don't use this Jenkins tool too often and as there is no dark theme, my eyes get flashed everytime i access that site. I dont add dyslexia to it but you get it.


> I can't reproduce the exception issue when using the latest ci from both ViaVersion and ViaBackwards, so you either just uploaded a new dump without doing testing again or something else in your setup is wrong.
Do I still require to do this ? Cuz the same problems occurs on the last dump version.

I saw an update and gonna try back again.

**Comment by kennytv** [comment]
Inventory handling is a bit annoying to read through and handle, but I think all that it needs in ViaBackwards is sending empty inventory contents when detecting that action

**Comment by Oublions** [comment]
As far as I know, when i do my inventory cleaning by destroy item, i know that Crazy Auctions plugin syncs the inventory on /ah. Thats a workaround for me until the issue will be resolved in a near future, i hope. <3

**Comment by alzhetv** [comment]
Still the same on latest versions.
https://dump.viaversion.com/3bc07a28774b8cb50670cc93c36f7b698b92448b5a139e41ffa94c61720b87f6

**Comment by Barvalg** [comment]
![Platform: 1.21.3--81--da71382%20%28MC%3A%201.21.3%29](https://img.shields.io/badge/Platform-1.21.3--81--da71382%20%28MC%3A%201.21.3%29-3498db?style=flat-square) </br>![ViaVersion (5.2.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(5.2.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(5.2.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(5.2.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by Timokaproka** [comment]
This problem still remains. Please fix it.
