### ISSUE TITLE
Incomplete server tags when logging into server with 1.16.4 client while server is 1.21.4

### ISSUE THREAD

**Issue by alexmartz710** [ViaVersion/ViaBackwards#945]
### '/viaversion dump' Output

https://dump.viaversion.com/5c61b1df0a480fab983bbfe772afb9873a6b446e04fb36da3a587cebfb2a328f

### Bug Description

Incomplete server tags, disconnecting. Missing: {minecraft:item=[minecraft:tall_flowers, minecraft:flowers], minecraft:block=[minecraft:tall_flowers]}

### Steps to Reproduce

Login with a 1.16.4 client to a 1.21.4 paper server

### Expected Behavior

Should allow logging in but it kicks you out of the server

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. Velocity), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: 1.21.4--15--bb76819%20%28MC%3A%201.21.4%29](https://img.shields.io/badge/Platform-1.21.4--15--bb76819%20%28MC%3A%201.21.4%29-3498db?style=flat-square) </br>![ViaVersion (5.2.1-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(5.2.1--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaRewind(4.0.5-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaRewind%20(4.0.5--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(5.2.1-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(5.2.1--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>
